### ISSUE TITLE
Only some kramdown options are supported

### ISSUE THREAD

**Issue by justin808** [jekyll/jekyll#1095]
Is there any reason that only a few of the Kramdown options are passed? I'm trying to use org-mode to generate jekyll pages via octopress, and I'm trying to make this org-mode syntax work. I need to insert markdown, as the link generation of org-mode cannot be used...So it's useful to allow passing some jekyll markdown from the org-mode conversion.

Here's a full description of how I have this setup. http://octopress.dev/blog/2013/04/27/octopress-setup-with-github-and-org-mode/

The only other option  seems to be to use all absolute URLs, which is not idea.

``` org-mode
    This link
    #+begin_html
    [Some link description](/blog/2013/05/11/blog-article/)
    #+end_html
    is very good...
```

Here is a snippet from markdown.rb, line 112 (and same exact code 129). The last option shown below is not in the code base.

```
        Kramdown::Document.new(content, {
          :auto_ids      => @config['kramdown']['auto_ids'],
          :footnote_nr   => @config['kramdown']['footnote_nr'],
          :entity_output => @config['kramdown']['entity_output'],
          :toc_levels    => @config['kramdown']['toc_levels'],
          :smart_quotes  => @config['kramdown']['smart_quotes'],
          :parse_block_html  => @config['kramdown']['parse_block_html'],
```

Here's the proposed _config.yml

```
markdown: kramdown
kramdown:
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
```

It might be worthwhile to pass all kramdown options so that when a new option is added to a markdown engine, the options are simply passed through to the markdown engine.

I can look into making this change, but I need to get employer approval before contributing to any open source project, which can be a very slow process.

**Comment by HugoGiraudel** [comment]
I am sorry to comment on such an old issue but it seemed like the most appropriate place to ask my question without opening a new issue.

We are currently in the process of translating http://sass-guidelin.es in several languages. Site runs on Jekyll, hosted on GitHub Pages, Kramdown as a Markdown parser of course.

We use auto IDs (option `auto_ids`) from Kramdown. Problem is non-latin characters are stripped. It doesn't cause any trouble for most cases, but languages not using the latin alphabet such as Russian get unusable IDs because all characters are stripped, leaving nothing but dashes (e.g. `id="----"`).

Kramdown supports an option to convert non-latin characters into latin in order to preserve IDs usability: http://kramdown.gettalong.org/options.html#option-transliterated-header-ids.

I tried putting this configuration in my `_config.yml`, works fine locally but when pushing to GitHub Pages, I get a page build failure.

```yml
# Build settings
markdown: kramdown

kramdown:
    transliterated_header_ids: true
```

> The page build failed with the following error:

> Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-build-failures.

> If you have any questions please contact us at https://github.com/contact.

Any idea how to proceed perhaps?

**Comment by parkr** [comment]
Hey Hugo, no problem. For issues like this, write to support@github.com and they'll grab the error Jekyll throws. :)
