### ISSUE TITLE
Css not being passed on to posts

### ISSUE THREAD

**Issue by DanielPollitt** [jekyll/jekyll#1336]
All posts have layout "default". Post has layout "default" as well.

Css from homepage does not pass on to posts. There are no spelling errors in mm or HTML files.

Been searching forum for resolution but haven't found it yet.

Thanks,
Dan

**Comment by Schmidtfelix** [comment]
Hey guys, 
I've got the same problem. Tried around a bit but it still ain't working :/ 

I've googled "config_dev.yml" but no idea what that means, how to create one or where I should put it. 

So that's supposed to be my portfolio: 
https://github.com/Schmidtfelix/schmidtfelix.github.io

It'd be really nice if you could explain the config thing in a bit more detail, so that I can try that solution. 

Thanks! 
Felix

**Comment by envygeeks** [comment]
Hi @Schmidtfelix please use https://talk.jekyllrb.com for non-bug questions. Thanks.
