### ISSUE TITLE
Multiple _posts directories

### ISSUE THREAD

**Issue by orschiro** [jekyll/jekyll#1819]
Hello,

Currently I am rendering just one `_posts` folder into one `index.html`. However, I would like to also render another `_poems` directory into a different `poems.html`.

I created the `poems.html` with the `{% for poem in site.poems %}` in analogy to my `index.html` which contains `{% for post in site.posts %}`.

However, when accessing `poems.html` nothing is rendered. Is this feature supported by Jekyll?

```
root
 |-- index.html
 |-- _posts
 |          |-- 2012-01-12-post.textile
 |          -- 2012-03-22-post.textile
 |-- poems.html
 |-- _poems
 |          |-- 2012-01-12-poem.textile
 |          -- 2012-03-22-poem.textile
```

**Comment by potomak** [comment]
I found @parkr comment (https://github.com/jekyll/jekyll/issues/1819#issuecomment-30441840) useful, but I think that categories are described by directories at the root path of the project, instead of directories inside the `_posts` directory.

It worked for me:

```
root
 | -- index.html
 | -- poems
      | -- _posts
           | -- 2012-01-12-poem1.textile
 | -- posts
      | -- _posts
           | -- 2012-06-12-post1.textile
```

See also http://jekyllrb.com/docs/variables/#page-variables where it describes the `page.categories` variable.

**Comment by enyusu** [comment]
Here is what I do in my jekyll site
1. Create any folder in your _post directory. Since jekyll just ignore it. ex. I created /jekyll/ folder
2. Put jekyll related post into that folder.
3. Add categories(ex jekyll as category) in your front matter.
4. Use this code to add some value into jekyll folder i.e. make /jekyll/ as permalink with this code.

{% for post in site.categories.jekyll reversed %}
    <a class="panel-title" href="{{ post.url | prepend: site.baseurl }}" >{{ post.title }}</a>
     {{post.description}}
{% endfor %}

**Comment by parkr** [comment]
@enyusu Please open a new issue.
