### ISSUE TITLE
Encoding html entities?

### ISSUE THREAD

**Issue by mhulse** [jekyll/jekyll#2026]
Here's the scenario:

``` html
<meta property="og:title" content="{{ page.title }} | {{ site.title }}">
```

Using the above code, I'll run into problems if the title has double quotes.

The fix I've been using is to:

``` html
 <meta property="og:title" content="{{ page.title | markdownify | strip_html | trim }} | {{ site.title }}">
```

The above works, but it just seems a little verbose.

I tried the liquid `escape_once` filter with no results.

I've been tempted to use the XML escape filters, but this isn't XML.

How do the pros handle this?

Is there any way to automatically have all of my titles converted to entities without me having to do anything on the template level?

Thanks!

**Comment by adammichaelwood** [comment]
Is there a way to make the markdown processor convert quptes and apostrophes to the html entities:
```
&lsquo;
&rdquo;
etc.
```
I'd prefer my output text be that, rather than utf-8 encoded curly quotes, because of reasons.
I wouldn't even mind doing it my self before rendering (I have a little bash script to `sed` replace quptes with the html entities. But then the processor converts them BACK into single-chracter curly quotes. Very annoying.

**Comment by kleinfreund** [comment]
> because of reasons.

Why? There is really no need to do that unless you’re using `&` inside HTML attributes (encode it as `&amp;` then).

**Comment by penibelst** [comment]
@adammichaelwood You can replace the quotes in the HTML layout.

### `index.md`

```md
---
layout: default
---

Adam said: "I'd prefer my output text be that, because of reasons."
```

### `_layouts/default.html`

```html
{{ content | replace: "’", "&#8217;" | replace: "“", "&#8220;" | replace: "”", "&#8221;" }}
```

### `_site/index.html`

```html
<p>Adam said: &#8220;I&#8217;d prefer my output text be that, because of reasons.&#8221;</p>
```

There is no markdown processor working on HTML layouts.

**Comment by adammichaelwood** [comment]
Thanks.

Why would I want to do that?
Because content shows up in a lot of places other than the one place I put it with a proper UTF-8 declaration. Feeds, Twitters, emails, etc, etc. I see jumbled characters on things ALL THE TIME and it seems to me the easiest way to avoid it is to use the HTML ampersand codes which work pretty much everywhere without any problems.


Thanks for the info on doing the replacement inside the layout. 

I was somewhat confused by:
>There is no markdown processor working on HTML layouts.

I think my real question is - is there a way to "fix" the behavior of the markdown processor? That t converts straight quotes to curly (in UTF-8) is great and sensible. But there isn't an option to have it spit out html entities instead? And if I try to bypass that by putting html entities into my markdown content (which I don't WANT to do - it was just a thing I tried), it converts those also, instead of leaving them alone.

Well - anyway - I think I can solve my issue now. Thanks all. 
Sorry for cluttering up a gh issue thread with personal problems...

**Comment by penibelst** [comment]
Which markdown processor are you using?

**Comment by adammichaelwood** [comment]
kramdown

**Comment by penibelst** [comment]
@adammichaelwood Kramdown has an option for exactly what you need: `entity_output`. The default value is `as_char`. That’s why you get chars now. You must change it to `numeric`.

```yaml
kramdown:
  entity_output: numeric
```

Read more about available options in the excellent [documentation](http://kramdown.gettalong.org/options.html).

**Comment by adammichaelwood** [comment]
Hey that works!
Cool thanks.

Another question, if no one minds:

Is there a strong reason NOT to prefer HTML entities for this sort of thing.
My reason, as I said, was more universal compatibility, as I don't always know where my stuff will show up, and seeing goofy messed up UTF characters in feeds and so forth annoys me.
But am I now in danger of the same problem - seeing `&8221;` in weird places I shouldn't?

I ask because I don't understand why html-entitity output isn't the default for the processor. (Robust principle and all.)

**Comment by parkr** [comment]
> I don't understand why html-entitity output isn't the default for the processor.

We don't write any of the processors ourselves, so whichever one you're using, you'd have to bring this up with them. We have the escaping filters for Liquid in the case that `<` and `>` are possibly in the text (useful for making a given block of text a textnode within an XML element, for example).

**Comment by adammichaelwood** [comment]
Yes, sorry - that was more of a philosophical question, based on the reaction I got above to my desire to output html entities. @kleinfreund seemed to think it was a silly thing to want to do.

**Comment by kleinfreund** [comment]
I did not say it was particularly silly. However, I think characters like `’`, `“”`, `„“`, `–`, `—`, etc. should work everywhere without having a weird output. The only place we see something weird while encoding them would be the code. You can do either way and should be fine whatever you choose. The important thing is setting utf-8 in your HTML.

**Comment by adammichaelwood** [comment]
Thanks. (I was probably projecting. My dev skills are sketchy, so I'm a little insecure.)

Anyway --- the answer above re: output options in kramdown was exactly the answer I needed.
So thanks!
