### ISSUE TITLE
Segfault when calling 'jekyll serve' on ruby 2.0.0

### ISSUE THREAD

**Issue by Aerlinger** [jekyll/jekyll#2525]
Here's my workflow:
- 1. `gem install jekyll`
- 2. `jekyll new whatever`
- 3. cd into created project
- 4. `jekyll serve`

It happens consistently when calling the above commands. Not sure if anyone else is having this issue, but here's what I see:

```
jekyll serve                                                                                                       ⏎ [50m] ✭
Configuration file: /Users/Aerlinger/Dropbox/personal/aerlinger.com/_config.yml
            Source: /Users/Aerlinger/Dropbox/personal/aerlinger.com
       Destination: /Users/Aerlinger/Dropbox/personal/aerlinger.com/_site
      Generating...
/Users/Aerlinger/.rvm/gems/ruby-2.0.0-p247/gems/posix-spawn-0.3.8/lib/posix_spawn_ext.bundle: [BUG] Segmentation fault
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin12.3.0]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   the more detail of.

-- Control frame information -----------------------------------------------
c:0043 p:-17586701010516 s:0211 e:000210 TOP    [FINISH]
c:0042 p:---- s:0209 e:000208 CFUNC  :require


(Another few thousand lines of obscure stack trace)


  541 /Users/Aerlinger/.rvm/gems/ruby-2.0.0-p247/gems/coderay-1.1.0/lib/coderay.rb
  542 /Users/Aerlinger/.rvm/gems/ruby-2.0.0-p247/gems/kramdown-1.3.3/lib/kramdown/utils/html.rb
  543 /Users/Aerlinger/.rvm/gems/ruby-2.0.0-p247/gems/kramdown-1.3.3/lib/kramdown/converter/html.rb
  544 /Users/Aerlinger/.rvm/gems/ruby-2.0.0-p247/gems/kramdown-1.3.3/lib/kramdown/utils/ordered_hash.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

[1]    53188 abort      jekyll serve
```

**Comment by clessg** [comment]
For me, this was caused by `~/.rvm/gems/ruby-2.2.0/bin` not being the first entry in the `PATH`.

**Comment by envygeeks** [comment]
That's an RVM bug, please make your comment as bug on their repo.

**Comment by clessg** [comment]
I was posting it in case anybody else came across this issue. That particular behavior is not a bug in RVM.

**Comment by envygeeks** [comment]
Actually @clessg it is.  That kind of segfault through RVM happens when RVM does one action but does not do the other action for Gems, resulting in gems built for another ruby running on the Ruby currently in your path.  Take for example you having Ruby 2.0.0 in your path, you try to switch to 2.1.0 but it only updates the Gems to 2.1.0, but 2.0.0 is still in your path, because of the way RVM works, it will segfault on compiled gems because you are trying to use gems from another Ruby.  This doesn't happen for pure Ruby gems though.

**Comment by envygeeks** [comment]
Now, if it updated the path, but didn't put it first, that is still a bug in RVM, in one way or another.  Unless, you added another path before RVM did, however, because RVM tries to detect a path already existing, it might not add the path (unless they've updated their detection since I was last there.)

**Comment by envygeeks** [comment]
I removed my post, I'll just send a patch to RVM since it happens to me all the time too.
