### ISSUE TITLE
High CPU Usage on --watch

### ISSUE THREAD

**Issue by lucasff** [jekyll/jekyll#2570]
Hi!

Using rvm.io, ruby 2.1.2p95 and jekyll 2.1.0 on Mac OS X Mavericks (10.9.3) I got a very high CPU usage, topping around 100˚ temps.

I run from the standard terminal `jekyll serve --watch`

How can I provide more information to help you debug this issue?

**Comment by phillipadsmith** [comment]
Howdy folks, I'm currently experiencing the same / a very similar issue.

I start Jekyll with `bundle exec jekyll serve -w --config _config.yml,_config.development.yml`

At that moment, ruby shows up in the process list using 0.0% CPU.

I edit a file, and next thing ruby is taking up 99.9% or 100.1% CPU.

This is OSX 10.8.5, ruby 2.1.2p95 and:

Using RedCloth 4.2.9
Using addressable 2.3.6
Using blankslate 2.1.2.4
Using hitimes 1.2.2
Using timers 4.0.1
Using celluloid 0.16.0
Using fast-stemmer 1.0.2
Using classifier-reborn 2.0.3
Using coffee-script-source 1.8.0
Using execjs 2.2.2
Using coffee-script 2.3.0
Using colorator 0.1
Using commonjs 0.2.7
Using domainatrix 0.0.11
Using fastimage 1.6.6
Using ffi 1.9.6
Using hike 1.2.3
Using jekyll-coffeescript 1.0.1
Using jekyll-gist 1.1.0
Using jekyll-paginate 1.1.0
Using sass 3.4.10
Using jekyll-sass-converter 1.3.0
Using rb-fsevent 0.9.4
Using rb-inotify 0.9.5
Using listen 2.8.5
Using jekyll-watch 1.2.0
Using kramdown 1.5.0
Using liquid 2.6.1
Using mercenary 0.3.5
Using posix-spawn 0.3.9
Using yajl-ruby 1.1.0
Using pygments.rb 0.6.0
Using redcarpet 3.2.2
Using safe_yaml 1.0.4
Using parslet 1.5.0
Using toml 0.1.2
Using jekyll 2.5.3
Using multi_json 1.10.1
Using rack 1.6.0
Using tilt 1.4.1
Using sprockets 2.12.3
Using sprockets-helpers 1.1.0
Using sprockets-sass 1.3.1
Using jekyll-assets 0.12.1
Using less 2.6.0
Using libv8 3.16.14.7
Using ref 1.0.5
Using therubyracer 0.12.1
Using yui-compressor 0.12.0
Using bundler 1.7.0

This behaviour is new / has only started happening recently. I've been using Jekyll on this project for months, so perhaps it happened while updating Ruby or a project-specific gem?

Any pointers appreciated.

**Comment by parkr** [comment]
@phillipadsmith Did you try `LISTEN_GEM_DEBUGGING=1` and checking the output? Also, did you try `--force_polling`?

**Comment by phillipadsmith** [comment]
@parkr I did, but it wasn't clear to me what output would be useful to you? 

`--force_polling` didn't appear to change the behaviour.

**Comment by parkr** [comment]
> @parkr I did, but it wasn't clear to me what output would be useful to you?

If it was looping like crazy or something. See if you can `strace` it and figure out what it's doing? Maybe some plugins?

**Comment by e2** [comment]
@phillipadsmith - there are steps for troubleshooting issues like that. It's likely specific to your project. 

1. see: https://github.com/guard/listen/wiki/Quickfixes%2C-known-issues-and-workarounds
2. then: https://github.com/guard/listen/wiki/Troubleshooting

(@parkr - those are recommended Wiki pages - you can send people there in the future to avoid back-and-forth with debugging setup)

As a guess, I'd say you could be watching generated files (in the output directory) and performing actions on them (thus, generating files and causing everything to loop).

Or, you could be watching log files - it could be a matter of setting the right ignore/exclude rules.

So I pretty much would need to know:
1) what directory you're watching
2) where is your output directory
3) where is your source directory
4) what files you are changing
5) what are the rules triggered when changing files
6) what files in the watched directory are being changed (based on modification date)

If you want help fast, use `LISTEN_GEM_DEBUGGING=2`, trigger the error and paste the output in a gist.

**Comment by phillipadsmith** [comment]
@e2 Super helpful starting points. Many thanks.

I tried `LISTEN_GEM_DEBUGGING=2` and it was clearly some crazy recursive loop happening.

Let me do a little troubleshooting and I'll report back what I'm able to find. 

Phillip.

**Comment by phillipadsmith** [comment]
@e2 @parkr  Hmmm, I see to be having [the problem described here](https://github.com/guard/listen/wiki/Duplicate-directory-errors), but nothing that I can think of has changed with my set-up in terms of watched/ignored directories... 

The output of LISTEN_GEM_DEBUGGING=1 is [here](https://gist.github.com/phillipadsmith/6d0da5470183057069a3).

Looking at the output of the `build` command, I can't see anything in _site that would lead me to believe that something is getting included in the `watch` that should not be.

Very confused. Any pointers appreciated.

Phillip.

**Comment by phillipadsmith** [comment]
That said, I've set up a vanilla Jekyll test site and it doesn't experience the problem... 

Look like I'll need to start pulling things out of this project site until I figure out what's causing the issue.

Phillip.

**Comment by e2** [comment]
@phillipadsmith :

>  /Users/phillipadsmith/Development/bottomlines.tyeesolutions.org/_vendor/ruby/2.1.0/gems/libv8-3.16.14.7/vendor/v8/build/gyp

Avoid watching /vendor directories (add them to excludes) - it makes no sense, since you likely won't be changing anything in those directories anyway. Also that gem has some weird symlinks - so you should avoid watching that directory at all.

Also:

> Source: bottomlines.tyeesolutions.org
> Destination: bottomlines.tyeesolutions.org/_site

Ideally, the output directory (_site) should not be a subdirectory of the source dir.

Ideally the two should be separate and you should watch only the source directory, e.g.:

> Source: bottomlines.tyeesolutions.org/source
> Destination: bottomlines.tyeesolutions.org/_site

And you'd put all your source files in 'source', configure Jekyll appropriately and watch only the source directory.

@parkr - could you at least show a warning when watching directories like this? It's not the first time when watching the output directory results is really poor performance and massive CPU usage (I'm guessing most users try to "live with it"). It's ok to run "build", but watching the directory structure where the output dir is a subdir of source doesn't make any sense (I can't "ignore" things here, since the rb-fsevent driver is recursive by design - blame Apple).

**Comment by phillipadsmith** [comment]
@e2 As far as I know, any directory prefixed with an underscore is ignored automatically by Jekyll. The layout with _site in the source is how Jekyll bootstraps new projects.

**Comment by e2** [comment]
@phillipadsmith - "ignored" by jekyll does not mean ignored by `Listen`, which can't technically ignore files (events are triggered anyway). Try the changes and if the problem persists, upload a full gist with LISTEN_GEM_DEBUGGING=2 (so I can spot a potential loop).

**Comment by e2** [comment]
@phillipadsmith - it could be just that vendor dir that's causing problems. Try ignoring that dir first.

**Comment by e2** [comment]
@phillipadsmith - you can use this to check what's excluded: 

```bash
$ JEKYLL_LOG_LEVEL=debug jekyll build --watch
```

Underscored dirs are not excluded by Jekyll by default (e.g. `_vendor`), only `options[:destination]` is.

@parkr - I think having a separate source dir recommended by default would prevent people from accidentally also watching potentially large paths like: vendor, node_modules, bower_components, etc.

**Comment by phillipadsmith** [comment]
`JEKYLL_LOG_LEVEL=debug bundle exec jekyll build --watch` and `JEKYLL_LOG_LEVEL=debug bundle exec jekyll serve --watch` don't provide any additional output... 

Adding `_vendor` to the `exclude` property in the `_config.yml` doesn't appear to change anything either.

I'll capture the output from LISTEN_GEM_DEBUGGING=2 and put that in a gist. Back to you momentarily...

**Comment by phillipadsmith** [comment]
@e2 I lied... adding `_vendor` to the `exclude` property [appears to have solved the issue](https://gist.github.com/phillipadsmith/7e4ef482c8c5a3275ea5).

However, I'm still seeing this error:

```        
** ERROR: directory is already being watched! **
        Directory: /Users/phillipadsmith/Development/bottomlines.tyeesolutions.org/_vendor/ruby/2.1.0/gems/libv8-3.16.14.7/vendor/v8/build/gyp
        is already begin watched through: /Users/phillipadsmith/Development/bottomlines.tyeesolutions.org/_vendor/ruby/2.1.0/gems/libv8-3.16.14.7/vendor/gyp
```

Odd, no?

**Comment by phillipadsmith** [comment]
I should note, I started building the project again from scratch -- slowly adding in the various pieces -- and that error seems to start happening after I load the following plugins:

```
gem 'yui-compressor'
gem 'jekyll-assets'
gem 'therubyracer'
gem 'less'
```

**Comment by e2** [comment]
@phillipadsmith - the jekyll logger does provide info about what is ignored (unless you have some strange version of Jekyll). Basically, this line: https://github.com/jekyll/jekyll-watch/blob/master/lib/jekyll/watcher.rb#L86

But that doesn't matter. As I've said, the only dir ignored by default is the destination dir: https://github.com/jekyll/jekyll-watch/blob/master/lib/jekyll/watcher.rb#L65

You're still getting the error because Jekyll is watching the whole directory. This is because the source is your project root directory: https://github.com/jekyll/jekyll-watch/blob/master/lib/jekyll/watcher.rb#L28

That's why I'd highly recommend you move all your source files to a sub directory (like `src` or `source`) and set that as the `:source` option in Jekyll. That should give you the most optimum setup (less CPU, less ram, less disk thrashing, etc.).

The Jekyll default of `:source` being the current directory and containing `:destination` as a subdirectory - isn't a good default.

**Comment by phillipadsmith** [comment]
@e2 

>  "the jekyll logger does provide info about what is ignored (unless you have some strange version of Jekyll)."  

Seems that the version of Jekyll I'm using for that project (2.4.0) doesn't have that output. I tried with a newer version for testing and saw the output in question...

> But that doesn't matter. As I've said, the only dir ignored by default is the destination dir:

Wow. That was news to me (and I've been using Jekyll for a while). I bet that many folks overlook that.

> That's why I'd highly recommend you move all your source files to a sub directory (like src or source) and set that as the :source option in Jekyll. That should give you the most optimum setup (less CPU, less ram, less disk thrashing, etc.).

> The Jekyll default of :source being the current directory and containing :destination as a subdirectory - isn't a good default.

I'm curious why that's not a standard project layout? @parkr?

Many thanks for the sleuthing, @e2! :)

Phillip.

**Comment by lilchen** [comment]
Hi there,

Alas, I've run into this dreaded mistake and didn't even realize until today that it's abnormal for Jekyll/Ruby to be using 104% of my CPU memory. Woops? Been doing this for a month.

I'm not a programmer by any means, but I've been reading this thread over and over again to see if I could figure out what could be causing this issue. I've separated my source and destination folder. No dice. I've been using both "LISTEN_GEM_DEBUGGING=1" and "LISTEN_GEM_DEBUGGING=2" without luck (though I don't fully understand what I'm looking at). Most of my engineer friends aren't familiar with Jekyll, so here I am!

One moment everything is at 0%, I hit save a few times and then it leaps to 102-104%. When I use the debugging code, my Terminal freaks out and spams lines incessantly.

I have also excluded in my _config.yml.
````    
exclude: [vendor, sass]
````

[This](https://gist.github.com/lilchen/8211095ec56e8e700e65) is just __part__ of what happens after I make one or two tiny adjustments in my CSS and hit save. :(

I guess I'm at wit's end and out of my element here, any help would be super appreciated ;_;.

**Comment by e2** [comment]
@lilchen - thankyou VERY MUCH for the gist. I'll be glad to help - I'll check it out and let you know as soon as I can.

Don't hesitate to open an issue in Listen (https://github.com/guard/listen) - even if it's a problem with your project, I'd like to help prevent it or at least provide meaningful messages in the future.

**Comment by e2** [comment]
@lilchen - I'd suggest you ignore the `src/assets/_sass/vendor` directory for starters. Overall, OSX support is pretty slow (I don't have OSX, so I can't confidently optimize things there). Carefully setting things up to avoid watching too many files/directories is best (Especially on OSX, you should be watching only directories where you intend to make changes in files). Either way, ignoring the `src/assets/_sass/vendor` should help a lot.

**Comment by lilchen** [comment]
@e2 Don't thank me! I should be thanking YOU for taking the time to help me! And, I totally would open the issue in Listen if I understood how Listen operated haha.

I just added these to the excludes. It appears my caches and random files from Codekit are getting caught up in being rebuilt.
````
exclude: ['assets/_sass/vendor', 'assets/fonts', 'assets/scripts', '.sass-cache', 'config.codekit', '.codekit-cache', '.DS_Store']
````

[This](https://gist.github.com/lilchen/31d09272fc410256fb2a) is everything looks afterwards in Terminal. I'm still trying to figure out how to decipher this stuff. It appears that those things have been 'silenced', but I still see a lot of `recursive=>true`, I'm not sure if this means there is a loop in there?

**Comment by e2** [comment]
@lilchen - I've opened up https://github.com/guard/listen/issues/310 so we can track this down and fix it.

Listen is quite complex, so I really, really appreciate gists like that and you taking the time to prepare it. The .DS_Store files should be caught by the default excludes in Listen, so there's some overriding going on (probably how Jekyll works). There's something generating fsevents in multiple directories within a split second - I don't know if you saved multiple files or it that wasn't you (see the linked issue).

The OSX adapter only reports directories as a result of changes, so changing `foo/bar` results in an event `bar`, which results in scanning a directory.

**Comment by envygeeks** [comment]
You can't blame Jekyll for everything, if you have a default list of ignores and we send ignores it's on you to either ensure those ignores get merged or provide an option to include them, blaming us because your behavior alters from what you expect when you designed that behavior is a strange thing to do.

**Comment by e2** [comment]
@envygeeks - I'm not blaming (I used the word "probably" since I was unsure). I didn't dig into the code - my bad (I didn't find the issue important). But neither did you, and you're making assumptions just as I did. Either dig into the code to prove me wrong, or voice doubt yourself like I did.

Listen provides 2 options: `:ignore` (merge with defaults) and `:ignore!` (override defaults) - and I have *no* control over which one Jekyll uses (in other words, I wasn't sure what Jekyll does while you were wrong about what Listen does). 

Turns out, for example, Jekyll doesn't allow overriding the Listen defaults (e.g. you can't get Jekyll to tell Listen to *not* ignore e.g. a `log` directory). And I didn't even design the API in the first place.
Also turns out, that according to the gist, `.DS_Store` is actually properly ignored (so there's no need to exclude it).
You could've simply said something more constructive like: "In jekyll-watch, we use this: https://github.com/jekyll/jekyll-watch/blob/3b411b80677a9c0bae3e1e890f29624ecfc8471e/lib/jekyll/watcher.rb#L29 and we expect Listen to merge those values with it's defaults- does that mean there's a bug in Listen?"

If you're not ok with how I phrase my doubts or my assumptions, don't do the same.

**Comment by lilchen** [comment]
@e2 I can't shake the feeling that something tiny within my site structure is causing this. Gonna make a repo for this.

Pushed my first repository to Git ever. Here's how my file structure looks (go easy on me):
https://github.com/lilchen/lilchen.com

Even with the patch you had me add into my Gemfile, something still freaks out in debug mode. I wonder if I have an include or something in my layouts...
