### ISSUE TITLE
Template Variables for Next/Previous posts within a category

### ISSUE THREAD

**Issue by surajram** [jekyll/jekyll#260]
I separated different sections of a website using categories. But I couldnt use `{{post.next}}` and `{{post.previous}}` for chronological navigation between the posts as these kept linking to posts from all the categories. 

I came up with the following code in my template to overcome it. 

``` html
    {% for post in site.categories.photos %}
        {% if post.url == page.url %}
            {% assign post_index0 = forloop.index0 %}
            {% assign post_index1 = forloop.index %}
        {% endif %}
    {% endfor %}
    {% for post in site.categories.photos %}
        {% if post_index0 == forloop.index %}
            {% assign next_post = post.url %}
        {% endif %}
        {% if post_index1 == forloop.index0 %}
            {% assign prev_post = post.url %}
        {% endif %}
    {% endfor %}
    {% if next_post %}
        <a href="{{ next_post }}">Next Post</a> <br>
    {% endif %}
    {% if prev_post %}
        <a href="{{ prev_post }}">Previous Post</a> <br>
    {% endif %}
```

A simpler solution would be to have template variables like `{{category.CATEGORYNAME.next}}` and `{{category.CATEGORYNAME.previous}}`

**Comment by SimplGy** [comment]
Is it safe to assume that the array in `site.categories.photos` is in time order?

**Comment by parkr** [comment]
@SimplGy I can't say – try it out! Does it consistently hold true?

**Comment by SimplGy** [comment]
@parkr black box testing wouldn't really convince me (just because the ice cream consumption goes up when it's hot doesn't mean it always will). Trying to analyze it white box using the published source....

The jekyll team traverses them [in a time dependent way here](https://github.com/jekyll/jekyll/blob/c8b22a19adee0d2dfe3418349b314c35dd8c1212/site/news/releases/index.html#L8). I think it's good enough for my needs, but scanning the codebase for a few minutes I was unable to determine a firm "yes" or "no". There are [no tests](https://github.com/jekyll/jekyll/search?utf8=%E2%9C%93&q=test+categories&type=Code) verifying the time order of the posts in categories.

I don't know ruby well--**is the order of the keys in a ruby hash deterministic**? In JS it is not, but most implementations behave predictably. If the same is true of Ruby it may look like posts are in time order most of the time but not be guaranteed.

**Comment by parkr** [comment]
In my experience, the order of keys in a ruby hash is deterministic, yes.

**Comment by envygeeks** [comment]
In Ruby the spec is insertion unless you enumerate it.

**Comment by envygeeks** [comment]
To Add: Of which that specific piece of Liquid code does do, it enumerates the array/hash.

**Comment by envygeeks** [comment]
And by enumerate I mean enumerate over it in an order you wish to.

**Comment by dotnil** [comment]
```liquid
{% if page.categories %}
  {% assign category = page.categories[0] %}
  {% assign posts = site.categories[category] %}
  {% for post in posts %}
    {% if post.url == page.url %}
      {% assign post_index0 = forloop.index0 %}
      {% assign post_index1 = forloop.index %}
    {% endif %}
  {% endfor %}
  {% for post in posts %}
    {% if post_index0 == forloop.index %}
      {% assign next_post = post %}
    {% endif %}
    {% if post_index1 == forloop.index0 %}
      {% assign prev_post = post %}
    {% endif %}
  {% endfor %}
{% endif %}
```

Modified a bit to allow arbitrary categories. Also changed the type of `prev_post` and `next_post` to `Post` rather than just the url.
