### ISSUE TITLE
Fenced backtick code highlighting using GFM 

### ISSUE THREAD

**Issue by rogeralsing** [jekyll/jekyll#2709]
So I've been fighting with Jekyll for a week now to get it to render my github wiki pages in a proper way on my github pages site.

The only markdown renderer that I have successfully got to render highlighted backtick code is `redcarpet`

The `kramdown` renderer has GFM support (?) there is an `input: GFM` option, this does not seem to have any effect on the output.

So what renderer am I supposed to use to get as close to the original github format as possible?

kramdown's GFM support seems broken, and redcarpet is somewhat picky and wants extra linebreaks before fenced backtick code, while github itself does not need that.

**Comment by rofr** [comment]
Is there a workaround for this? I'd like to write markdown using fencing, preview in atom using markdown preview package and have it rendered with syntax highlighting correctly on github-pages.

**Comment by rajohns08** [comment]
+1 @rofr

**Comment by pathawks** [comment]
This issue was closed a year ago, what are you expecting to have resolved?

**Comment by 304NotModified** [comment]
+1 @rofl

Not sure why this is ever closed. No fixes. No work arrounds.

**Comment by plexus** [comment]
I assume this issue is closed because it's not a Jekyll issue. There is no authoritative spec for Markdown. Github has their own extensions, and even renders the same input differently depending on if it's comments, files, gists, etc.

Some implementations have partially copied some of the Github extensions. For Kramdown I implemented bactick-fenced code blocks, and rendering newlines as line breaks. If you want highlighting in the codeblocks you can either use Coderay on the server side, or use something javascript-based like highlight.js.

If you want more of these Github-specific extensions in a specific implementation then start a conversation for the relevant project. State what features you want to see, and if you plan to implement them yourself or not, and then ask if the project maintainers would accept such a pull request. If they do, then write the code, ask for feedback, incorporate that feedback, until the PR is merged.

If that's done and the changes are part of a new stable release, then you can consider coming back to Jekyll to suggest they update their dependencies. Until then +1-ing here will not make a difference.

**Comment by 304NotModified** [comment]
Well, it's no problem to close a ticket and telling Jekyll wont support code fences.

But closing an issue without making really clear why, well, that confuses people and those will give +1's because the issue isn't fixed. 

There is a spec for GFM AFAIK. So setting the input on GFM, should support the GFM features IMO.

**Comment by envygeeks** [comment]
It is not our job to work around the problems of a markdown processor, I know you would like that to be so but that is on the maintainer of that library.  If you enable GFM in Kramdown and it doesn't work the way you expect, that is a bug in Kramdown, not in Jekyll.  If you enable fenced code blocks (which you can if you read: https://github.com/jekyll/jekyll/tree/master/lib/jekyll/converters/markdown) and it doesn't work that is a problem with Redcarpet.  There are clearly documented ways to work around this and if those ways do not work then that is a bug in Jekyll unless... it's because Redcarpet or Kramdown or the markdown library removed the feature or it's broken there but necromancing a ticket instead of checking the documentation and blaming us isn't going to solve the problem.

Please try to read the documentation and see if that works, if it does not then please file a ticket and we'll gladly debug the issue and let you know if it's an upstream problem.

**Comment by parkr** [comment]
If `GFM` input for Kramdown doesn't support a feature, please ask the Kramdown authors to add this feature.
