### ISSUE TITLE
Symlink assets instead of creating a copy when building

### ISSUE THREAD

**Issue by zanona** [jekyll/jekyll#278]
Hello, 
Sorry if this was covered somewhere else, but I am trying to get to this and it seems its not possible at the moment, at least for me :)

So, I am creating a jekyll project altogether with a .git repository which I am deploying to heroku for example. But obviously I like to also push my jekyll source so I can edit later and for that I am creating a rack web server that redirect the all requests to the `_site` folder.

but one thing I've noticed is that a copy is being created for all my assets within the project like if I have `root/stylesheets/main.css` or `root/images/logo.png` the same files will be created inside `root/_site/stylesheets` and `root/_site/images` respectively.

My question would be if its somehow possible to create a symlink for those when building instead of creating a copy. I believe this would save a significant space in my repository and also avoid duplicates.

I know that ideally I should just exclude the _site folder from my repository when then build it in the server like github but unfortunately this is not so easy to implement on "everyday clients' servers" we found. so this would still giving us the power of using jekyll even on low potential shared hosting servers.

I hope I was clear enough on my sayings. thanks again and congratulations for the excellent work

**Comment by brainyman** [comment]
It's actual for me also. in source folder i have symlink to big images folder. i use it for different sites, so i don't want to duplicate it for each site. and when jekyll is builing i need to duplicate only symlink but not all this huge directory. help me please

**Comment by ph03** [comment]
I would also need this feature since I'm creating a site with a lot of videos and it's just a waste of space to copy the video files to _site when building.. Could this be an optional feature that could be activated in the configuration?

**Comment by ssbarnea** [comment]
I think that this issue must be reopened because the issue of managing files (images, documents,...) with jekyll seems to be almost totally ignored and not documented. I am not trying to say that the symlinks are the solution but I would like to see a solution that deals with compilation and deployment.

Few problems:
* If an image is supposed to be copied towards the `_site` directory, this should be as hardlinks, I don't want to ruin my ssd lifespan or space duplicating static content too often. Obviously that we are not supposed to keep the `_site` in git.
* Deployment, I do not expect to have to copy all the files that were not touched every time. Rsync should work here.
* Filtering - I hope to see a way to deal with image conversion but I guess this would be outside the scope of jekyll, maybe a plugin would help here.
* Examples: documenting different ways to deal with static files would be critical. As someone in process of migrating from Wordpress, I am currently stuck at the problem of dealing with images. In Wordpress was very easy to upload files, even to edit them.

I am aware that is much easier to "outsource" the image issue outside jekyll but I am afraid that's not quite possible as nobody wants to end-up with broken images.

**Comment by envygeeks** [comment]
Hi @ssbarnea while I would normally ask that you open a new ticket I will address your questions concerns here:

1. I don't think your argument about SSD's is valid.  There is a misconception that SSD's can't handle that much data but for a modern SSD that's entirely hyperbolic.  Chances are if you read the specs papers for your SSD and did the calculations you would put yourself at ease over whether or not it's going to do harm.  If you have a Samsung device here is something for you (as far as the 840 series is concerned -- the 850 can handle much much more):

```
__ssd_smartinfo() {
  terabytes=$(sudo smartctl -A /dev/sda | awk '/^241/ { print ($10 * 512) * 1.0e-12 }')
     cycles=$(sudo smartctl -A /dev/sda | awk '/^177/ { print  $10 }')
  printf "You have written %s terabytes with %s out of 1129 P/E cycles.\n" \
    $terabytes $cycles
}
```

2. We do not do deployments so your argument to use rsync has no standing here.
3. We do not alter images, your argument for that has no standing here, there is jekyll-assets.
4. You problems with images should be filed under https://github.com/jekyll/jekyll-import
