### ISSUE TITLE
Add `find_file` Liquid filter

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#2866]
It's an immensely frustrating experience to loop through `site.pages` or `site.posts` to find a post or page you're looking for. To do something as simple as output the stylesheet, you might do this:

```liquid
{% for page in site.pages %}
  {% if page.name == "screen" %}
    <link href="{{ page.url }}" rel="stylesheet" />
  {% endif %}
{% endfor %}
```

But that sucks. What if you could do this:

```liquid
{% assign stylesheet = site.pages | find_file:"screen.css" %}
<link href="{{ stylesheet.url }}" rel="stylesheet" />
```

Nicer, eh?

Questions:

- [ ] How should the query be constructed and used? Should we check on `name`? Match against `url` with the string turned into regexp?
- [ ] Should we provide various functionality in different filters, i.e. `find_url_like:"regexp"` and `find_name:"screen"`?

**Comment by nicolas-f** [comment]
Hi,

This feature would be interesting for performance purpose only if the site.pages were indexed. May be use a hash for pages like `site.pages_index["screen.css"]` would return the page instance.

**Comment by envygeeks** [comment]
I think what you listed is a use-case not a performance-case because very rarely would somebody go searching for something outside of Ruby like what you just did and `Enumerator#lazy` solves that problem in modern Ruby.

**Comment by nicolas-f** [comment]
Internally the liquid filter require to loop over all row of site.pages ?

**Comment by envygeeks** [comment]
That's a pretty broad question, can you narrow it down? Of course in most cases we require a loop but that's because of the nature of what you are doing, the question is, what case would you not require a loop?  The asset example you gave doesn't necessarily answer any questions because I would never try to access an asset like that I just straight up know it's name and it's path so I do it statically because what goes in comes out in that case.

**Comment by nicolas-f** [comment]
Hi,

Ok. In this page:

https://github.com/jekyll/jekyll/blob/master/site/_includes/docs_ul.html

You know the page path because it is stored in `item_url` . But you loop over all `site.docs` in order to find the good page. If you were using the `where` filter, it would do exactly the same (slighty reduce time). Can you change the linked page to not iterate over all `site.docs` element (and without using where) ?

**Comment by envygeeks** [comment]
@nicolas-f no, you cannot by nature of the way that Liquid itself works, the where filter exists to solve that problem though as you previously pointed out, so why add in another way to do it when there is already a way to do what you wish to do?
