### ISSUE TITLE
Tags should be case insensitive

### ISSUE THREAD

**Issue by hazzik** [jekyll/jekyll#2977]
Brought to you by jekyll/jekyll-archives#24

When you have tags with different cases in different posts the archives plugin looses some entries on archive pages. There are some feelings that this issue needs to be resolved in jekyll itself.

**Comment by parkr** [comment]
> The problem here is that with 2 tags, lets say "Apple" and "apple", Utils.slugify produces the same slug...

@alfredxing Perhaps this is an archives issue? Or we make `slugify` case sensitive.

**Comment by alfredxing** [comment]
Archives isn't doing anything with tags whatsoever, other than iterating them and calling `slugify`... I guess it depends on whether you want tags to be case sensitive?

**Comment by parkr** [comment]
Tags should be case sensitive, yes.

**Comment by envygeeks** [comment]
Define "case sensitive", they should certainly be normalized by Jekyll as they go in (downcased, spaces converted "-" and special chars strip (most of them.) which is the standard behavior of most if not all all normal tagging systems  that care about multi-tenant situations.

**Comment by hazzik** [comment]
What about windows (and others with case insensitive file system) users?

**Comment by envygeeks** [comment]
The relevance of that should be nil since we make the tag pages and how your operating system cases is not relevant to the internet and how it ='s defacto standards work.

**Comment by envygeeks** [comment]
The matter is, that if you give something "Hello" as a tag, it need output "hello" as the tag and "hello.html" as the tag page, like most systems with tagging behave (except it gets written to html here, not stored in a transaction.)

**Comment by parkr** [comment]
I don't think we should downcase the tag, but :+1: on converting spaces and such.

**Comment by alfredxing** [comment]
I don't think tags are being normalized right now.

After thinking about it some more, I came up with an example where case sensitivity would be nice:
```yaml
title: Testing out Apple's new Force Touch trackpad
category: technology
tags:
  - Apple
  - trackpad
```

```yaml
title: My super yummy apple pie recipe
category: food
tags:
  - apple
  - pie
  - recipe
```

Given @parkr's suggestion above, I think it would be a good idea to change `Utils#slugify`, or make another version of it.

**Comment by envygeeks** [comment]
Why go against the grain?

**Comment by envygeeks** [comment]
And btw, Apple's name is "Apple Inc."

**Comment by stevemoser** [comment]
@parkr I agree that we shouldn't downcase tags but we should make them case-sensitive (case-preserving as well). Ideally they would be case-sensitive but in a world where the default file system on most dev machines is case-incentive I think we should stick to that. If we wanted to get fancy we could have a semantic title and a display title for each tag but I don't think we need that.

**Comment by parkr** [comment]
How does WordPress do this, again? I don't like the idea of transforming content you don't ask us to transform... The url's should be case sensitive I think, and match the case of the inputted tag. Maybe that could change.

/cc @spraints for whether Pages is case-sensitive.

**Comment by envygeeks** [comment]
Wordpress allows you to do whatever you want with hooks that allow you to enforce what you want. At least if: https://wordpress.org/support/topic/force-tags-to-lowercase is any indication.  We could do the same, we have a hook system we could create a hook for that point that allows people to transform and normalize however they want, which gives the opportunity for tons of plugins such as ones that do spell-checking, normalizing and all sorts of junk we probably don't want in core.

**Comment by envygeeks** [comment]
it looks like I misread that, that's for a plugin, I'll dig through their source and see later tomorrow.

**Comment by stevemoser** [comment]
Is there any good reason the rules for tags should be different than post titles (case-**in**sensitive, case-preserving IIRC)? Since as @envygeeks mentioned tags end as as their own pages it would case havoc in case-**in**sensitive dev filesystems.

**Comment by d3netxer** [comment]
is there a way I can downcase all of the tags in my Jekyll repo?

**Comment by spraints** [comment]
> whether Pages is case-sensitive.

Pages runs on linux machines, so anything file-related is case-sensitive.

**Comment by parkr** [comment]
> is there a way I can downcase all of the tags in my Jekyll repo?

@d3netxer Yes! But it requires going through all your posts and manually modifying tags. You could easily write a program to do this.

> > whether Pages is case-sensitive.
>
> Pages runs on linux machines, so anything file-related is case-sensitive.

Cool, thanks @spraints! I figured but wanted to check.

Windows and Linux are case-sensitive, but Mac is case-insensitive, which makes it the outlier. Do we cater to case-sensitivity or case-insensitivity?

**Comment by stevemoser** [comment]
@parkr I'm not a Windows expert but I thought it was case-insensitive. http://superuser.com/questions/165975/are-all-versions-of-windows-case-insensitive

If we go with case-sensitive I think we should make sure the error/warning thrown on case-insensitive filesystems because of two tags that are the same except for case should be very clear or else we might end up with a lot questions on here. Might be something to think about for jekyll doctor.

**Comment by envygeeks** [comment]
It depends on if you enable POSIX compliance and set ObCaseInsensitive to 0... Windows can go either way like OS X used to be able to (I don't know if it does anymore?) and Linux can with some file systems but by default NTFS is Case Insensitive and by default Linux is case sensitive (by way of EXT4 -- that is if you opt to use it, on Linux we do have our choices.)

**Comment by stevemoser** [comment]
One more thing to add to the discussion. I'm not sure if Jekyll is concerned with Wordpress compatibility/importing but I would like to bring up that Wordpress is case-insenstive when it comes to tags.

    Is Tag the same as tag?
    Yes. Capital letters do not change a tag. Blogging is the same as blogging.

https://en.support.wordpress.com/posts/categories-vs-tags/

Also, OS X can go either way though a lot of apps break when switching from the default. The default is case-insensitive and case-preserving.

**Comment by envygeeks** [comment]
That's apples to oranges. IMO.

**Comment by parkr** [comment]
> I'm not sure if Jekyll is concerned with Wordpress compatibility/importing but I would like to bring up that Wordpress is case-insenstive when it comes to tags.

We aren't all that worried about this, no. We have a jekyll-import WordPress importer which we point people to and which should downcase the tags.

That said, WordPress is prior art and can help inform our decision, notwithstanding their pedantic documentation.

**Comment by envygeeks** [comment]
```
That said, WordPress is prior art and can help inform our decision, notwithstanding their pedantic documentation.
```

When you got a billion users and don't want a billion tickets that happens :cry:

**Comment by nasht00** [comment]
I just noticed this thread, I want to add my input: case-insensitive.

Seeing this issue is still open I assume the case is not decided yet...

**Comment by xHN35RQ** [comment]
I ran into this problem, expecting `the tag` and `The Tag` to be the same tag. Coming from Wordpress I just assumed this would be the default behavior.

According to RFC 3986, the canonical URL form is lower-cased. (see https://tools.ietf.org/html/rfc3986#section-3.1) Quoting:

> Although schemes are case-insensitive, the canonical form is lowercase and documents that
   specify schemes must do so with lowercase letters.  An implementation should accept uppercase letters as equivalent to lowercase in scheme names (e.g., allow "HTTP" as well as "http") for the sake of robustness but should only produce lowercase scheme names for consistency.

So it follows that Jekyll should accept `apple` and `Apple` but resolve both to a single Jekyll tag of `apple`. This way Jekyll would behave according to the URL spec.

If a user wants to refer to the company founded by Steve Jobs instead of the fruit, a more explicit tag should be used, perhaps `Apple Inc` or `Apple Corp` which would normalize to the tags `apple-inc` or `apple-corp`.

Perhaps at a later date, Jekyll core could be modified to allow advanced tag manipulation as [suggested by envygeeks](https://github.com/jekyll/jekyll/issues/2977#issuecomment-122972020) which is a use case best handled by plugins.

**Comment by stevemoser** [comment]
@xHN35RQ Only the scheme is case-insensitive, the path isn't. Some URL normalization require uppercase characters like escape characters. https://en.wikipedia.org/wiki/URL_normalization

**Comment by xHN35RQ** [comment]
> Only the scheme is case-insensitive, the path isn't.

Right, but why is this relevant? Since Jekyll is using tags to generate URLs, then it should follow RFC 3986 and by default "should accept uppercase letters as equivalent to lowercase in scheme names (e.g., allow "HTTP" as well as "http") for the sake of robustness but should only produce lowercase scheme names for consistency." I don't understand why path casing is important here? Maybe I'm looking at this the wrong way.

**Comment by envygeeks** [comment]
@xHN35RQ in the URL https://domain.com/tags/my-tag, the only part of that, in what you mention in RFC 3986 that applies to us is "https" and it doesn't actually apply to us, that only applies to your browser and server, both of which normalize that on your behalf.  The RFC does not (and will probably never) dictate that we make things case-insensitive, that we force down-case (even if I feel this is the standard of the web) or that we make it all capitals.  It only dicates that matters to it: https://, gofer://, ftp://, http://, all of which must be case-insensitive, and only to the extent that it's allow to come in case-insensitive but will be enforced as lower-case in a browser and in some crazy applications all upper-case.

---

That said; Jekyll is a static site generator, this is a problem for your server, not for us.  If you want case insensitive URL's in Jekyll, you'll increase your files exponentially to an uncontrollable number quickly. My arguments (the ones that you linked to) were so that people can flag tags any way they  want, they can grep out a tag and and alter a files tag to that tag, normalizing and optimizing their site in a manner that makes them not have to care one iota about whether they got the case right.

---

On Wordpress being able to do it (it being case-insensitive tags/urls,) it can offer you that because it is an application that is always on.  They can offer something like that, we cannot, not feasibly anyhow because ***technically*** we can but realistically we won't and shouldn't because again, this creates an exponential problem that we do not want.  We write files on your behalf to be served by a server of your choosing (like Nginx) whereas with Wordpress all URL's land to them to deal with and they need not create thousands of files to do what you want... we would need to do that, which is the unrealistic situation we don't want to create.  Yes, Wordpress takes in URL's via Nginx or Apache too, but again, they are serving you the data through Wordpress, Nginx is serving your data directly for us.

**Comment by xHN35RQ** [comment]
Fair enough. Your explanation makes sense. And correct, the spec shouldn't dictate your behavior but it seemed to me that since Jekyll generates URL structures they should conform to expected web usage. For example, my clients tend to expect case-insensitivity, (`apple` = `Apple` = `/apple`)

I'm still left with the problem that given `the tag` and `The Tag` Jekyll treats these as two different tags, but only generates one tag URL `the-tag` and this page only contains the posts tagged with `The Tag`. Is there a way I can work around this? Is it currently pluggable?

**Comment by envygeeks** [comment]
@xHN35RQ in theory it should be: https://jekyllrb.com/docs/plugins/#hooks you can hook into `:pre_render` and edit the front-matter they supply to normalize it to a grep of all known tags.

**Comment by xHN35RQ** [comment]
@envygeeks cool, thanks! Also, I just noticed that jekyll-archives calls [`slugify` on titles](https://github.com/jekyll/jekyll-archives/blob/master/lib/jekyll-archives/archive.rb#L36) which if I'm not mistaken are sorted case-sensitively, lowercase before uppercase. This leads to upper-cased versions of tags `The Tag` being the only visible tags for a given URL of `the-tag`, so this issue might actually be a jekyll-archive specific problem to solve.

**Comment by xHN35RQ** [comment]
@envygeeks after re-reading the entire thread, and specifically [your explanation](https://github.com/jekyll/jekyll/issues/2977#issuecomment-215628405) it appears Jekyll is currently inconsistent in how it treats tags. Given two tags of `The Tag` and `the tag` Jekyll treats these as two distinct tags. However, it only generates one URL for both tags: `/the-tag`. Based on your explanation should not Jekyll actually generate two URLs, one for each tag? `The Tag` > `/The-Tag` and `the tag` > `/the-tag`. Instead Jekyll makes a decision for me to mash both tags into one URL (but due to the default sort method before `slugify` only posts tagged with one of the tags actually appears at that URL)

To be consistent, slugify default should be cased, correct? Tthe default should be to slugify both uppercase and lowercase, and generate an URL for both tags, as @parkr  and @alfredxing suggested earlier in the thread. Am I wrong in thinking this way?

**Comment by xHN35RQ** [comment]
@hazzik I think this is a `jekyll-archive` issue with how it reads in tag and category hashes, and I've [roposed a possible solution](https://github.com/jekyll/jekyll-archives/issues/43#issuecomment-218726064) on https://github.com/jekyll/jekyll-archives/issues/43, so this issue can be closed.

**Comment by mpchadwick** [comment]
Just wanted to note for anyone who finds their way to this thread that I built a tool which can help manage tag case sensitivity. It is part of a project I created called [jekyll-pre-commit](https://github.com/mpchadwick/jekyll-pre-commit), which uses git pre-commit hooks to run checks before allowing you to commit. I added a check called NoDuplicateTags which, once you've installed the gem [you'd declare in your _config.yml](https://github.com/mpchadwick/jekyll-pre-commit#usage). Then you'll get a warning for example, if you try to commit a post using the tag "mysql" but you already have a post that's using the tag "MySQL". Hope someone else also finds this useful.
