### ISSUE TITLE
`output` attribute is `nil` on collection documents

### ISSUE THREAD

**Issue by anandthakker** [jekyll/jekyll#2989]
The [docs](http://jekyllrb.com/docs/collections/) indicate that a document from a collection will have an attribute called `output`, which is:

> The rendered output of the document, based on the `content`

I'm finding that (even with `output: true`), the value of `mycollectiondocument.output` is `nil`, even though `content` has stuff in it.

Repro template code:

```
{% for mycollectiondocument in site.lessons %}
 {{ mycollectiondocument }}
{% endfor %}
```

There's one document in said collection, and the output of the above is:

```
{"layout"=>"lesson",
 "published"=>true,
 "title"=>"linear equations", 
 **"output"=>nil**, 
 "content"=>"{% raw %}some content{% endraw %}", 
 "path"=>"[myprojectpath]/_lessons/02-1-linear-equations.html", 
 "relative_path"=>"_lessons/02-1-linear-equations.html", 
 "url"=>"/lessons/02-1-linear-equations.html", 
 "collection"=>"lessons"}
```

**Comment by Fedjmike** [comment]
Why is that not documented?

http://jekyllrb.com/docs/collections/

That page lists output just as any other attribute, it doesn't say that it shouldn't be used.

**Comment by parkr** [comment]
@Fedjmike Where do you think it should go? PR's welcome.

**Comment by Fedjmike** [comment]
Well if Liquid templates aren't supposed to access the output attribute at all then maybe it shouldn't be in the documentation? Unless I've misunderstood what's been said.

**Comment by envygeeks** [comment]
It does list output as a variable they can access to see if their collection is "output."

**Comment by gynter** [comment]
@anandthakker and @Fedjmike, `collection.output` is the rendered output for that collection therefore it's impossible to access this vairable inside of the collection template itself, because the output for collection is yet to be rendered using that template. The value for `collection.output` is set after rendering the collection's output page.

On the other hand, You can access `collection.output` fine from any post or page. For example, You can flawlessy use `project.output` instead of `project.content` in [this included layout][1], invoked in the [projects layout][2] used in [projects page][3]. For that You just have to set `output: true` in [the config][4] for the [projects][5] collection (and Yes, I just tested it, works fine).

[1]: https://github.com/gynter/gynter.github.io/blob/source/_includes/project_category.html
[2]: https://github.com/gynter/gynter.github.io/blob/source/_layouts/projects.html
[3]: https://github.com/gynter/gynter.github.io/blob/source/pages/projects.markdown
[4]: https://github.com/gynter/gynter.github.io/blob/source/_config.yml
[5]: https://github.com/gynter/gynter.github.io/tree/source/_projects
