### ISSUE TITLE
Make permalinks work with pages

### ISSUE THREAD

**Issue by RobertAudi** [jekyll/jekyll#302]
Right now if I create an about page, I have to go to about.html. about/ doesn't work.

**Comment by matthewmcvickar** [comment]
Sorry to dredge this up, but I'm confused about the permalink behavior for `post`s vs. `page`s.

I want `post`s to have the permalink style `/:year/:month/:day/:title/` and `page`s to have the style `/:title/`. E.g., `example.com/2015/04/03/foo/` for a post, `example.com/foo/` for a page.

If I set `permalink: /:year/:month/:day/:title/` in `_config.yml` (instead of `pretty`, which includes the category, which I don't want), `page`s then lose their pretty URLs.

What is the best way to get pretty URLs back for `page`s?

**Comment by parkr** [comment]
@matthewmcvickar Sadly it's only in 3.0 beta, not in 2.5 or 2.4, so if you want @willnorris's fixes, you'll have to use the beta.

**Comment by matthewmcvickar** [comment]
@parkr Understood. Thank you!

**Comment by fulldecent** [comment]
I couldn't figure out how to implement the configuration discussed at #2691. However, this took me all day to figure out and just wanted to share here:

    # Site settings
    permalink: pretty

    # Pages permalink
    defaults:
      -
        scope:
          type: "pages"
        values:
          permalink: /:path/:basename:output_ext

This results in:

 * `_posts/2015-01-01-title.md` ---> `_site/2015/01/01/title/index.html`
 * `page.md` ---> `_site/page.html`

This illustrates that it IS possible to have separate default permalink structures for posts, pages, and collections!

**Comment by 5ervant** [comment]
Does anybody here know the exact list of working Jekyll permalinks in GitHub Pages?
http://stackoverflow.com/q/33175753/4883372
