### ISSUE TITLE
Make pages and posts instances of Jekyll::Document.

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#3169]
Can't take credit for this idea. @benbalter said it. The idea is that posts are a sort of collection, and pages are as well if you think kind of tilt your head and squint a little. It would make sense for them all to share a common interface. We abolish the Convertible module and make anything that was once convertible a Document, et voila.

**Comment by afeld** [comment]
Ha, just came to this same epiphany independently... which I guess makes me the Leibniz (the less well-known or handsome one) to your Newton :chart_with_upwards_trend: 

Really, I think *everything* could represented as collections (pages, posts, and data). Content is data! Everything is data!

![data all the things](http://cdn.meme.am/instances/500x/30793439.jpg)

Making the APIs between those existing data types completely consistent is really appealing, and it would simplify the internals a lot too. Might be worth thinking through what that implementation (rewrite?) would look like, and layering on APIs (maybe via a plugin gem?) to provide backwards compatibility.

**Comment by alfredxing** [comment]
I'm experimenting with this (posts only right now), and got it to somewhat work. A big issue I came across is how we are going to handle all of the post-specific features (like categories, tags, dates, permalink styles, etc.)?

**Comment by parkr** [comment]
> post-specific features (like categories, tags, dates, permalink styles, etc.)?

For categories & tags, we need an idea of `group_by` filters. Essentially that's what they do. The permalink styles could be applied with front matter defaults (or even just like them, i.e. collection name-based). As for dates, we'd need to bring over the `MATCHER` and `valid?` ideas to Document.

**Comment by fulldecent** [comment]
I'm chiming in as a user IMHO to discuss our API.

 **The `_` prefix is good, it clearly demarcates Jekyll-land and asset-land**

For example, just looking at it, I know that `/assets/bear.jpg` will wind up at `example.com/assets/bear.jpg`. Consider a world without `_` prefixes, and you are editing index.html and wanted to link to `cars/redCar.html`... you would need to first check `_config.yml` to see if `cars/` is a "special Jekyll folder".

**"Pages" and "Folders" are preferred terminology, with "Posts" being a specific type of "Page"**

This is intuitive and keeps convention web authors have used for decades. Here's an example of something that makes sense:

    {{ site.books | where:"ISBN","4109147509740" | map:"url" }}

This searches `/path/to/site/_books/*` and the Front Matter of each page there. Which is no more special than searching JSON files in the `_data/` directory:

    {{ site.data.bookList | where:"ISBN","4109147509740" | map:"author" }}

The only difference is that `url` is magically calculated for `site.books` because those are pages, but not for the data file `bookList.json` because that's not a page.

**Fuck backwards compatibility**

That why we use Semantic Versioning. After 10 years, PHP still makes an average of one backwards-compatibility-breaking release per year. By year 2023 we should be in a better position than PHP, that start by making good, hard decisions now.

**Comment by fj** [comment]
I wrote the short SpicyJekyll plugin ([blog post](http://jxf.me/entries/custom-collections-jekyll/), [repo](https://github.com/fj/spicy-jekyll)) to address some of the limitations that custom collections have in Jekyll and to make them more fully-featured.

I think it could serve as a useful template for unifying collection behavior in Jekyll 3 and future versions as per the subject of this issue, since it's fairly opinionated about reasonable minimums for a default collection:

* a [total ordering](http://en.wikipedia.org/wiki/Total_order) over the elements of a collection
* a name for the collection
* a filename format for members of that collection

and in exchange you get:

* `next` and `previous` links for each element of the collection
* fail-fast checking for required properties rather than silent failures
* stable, filename-based permalinks
* logging of collection actions during build time

**Comment by parkr** [comment]
Closed in #4055.
