### ISSUE TITLE
Using post_url causes pages to not build in Github

### ISSUE THREAD

**Issue by mdayaram** [jekyll/jekyll#3179]
I have a blog post where I link to a different post using the `post_url` feature like so:

```
[text]({% post_url 2014-08-30-my-title %})
```

When I run jekyll locally, everything is rendered correctly and the link appears properly.  Both the post with the markup and the post being linked are in the same directory.

However, when I push to Github, I get a build error notification without a description.  I've verified that removing the reference to `post_url` fixes the build.

My project uses the `gh-pages` gem, and I've verified that my environment locally matches the environment that Github uses (listed here:  https://pages.github.com/versions/)

The error email I get from Github is anything but helpful:

----
The page build failed with the following error:

Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-build-failures.

----

I've gone through the troubleshooting link and was not able to find any information regarding this problem.  Is there anything that I might be doing incorrectly?  For reference, here's the diff that breaks my build in github but works locally:

https://github.com/mdayaram/mdayaram.github.io/commit/a7efa6a0fc4cc622016fb307ddc2445c3bccb0f5

**Comment by edwinlunando** [comment]
Yes, i get this errors too. Is there any solution?

**Comment by parkr** [comment]
It's likely a timezone problem. We can't determine this though. Please write support@github.com

**Comment by iplus26** [comment]
Still have the problem. I've spent a whole afternoon but it turns out that I can't use {% post_url %} in GitHub Pages.

**Comment by parkr** [comment]
The feature is there, they're just running a version of Jekyll that's a little old and it's run in UTC-0700. post_url may get mixed up if that timezone shifts any of your dates!

**Comment by joshuaflanagan** [comment]
I just ran into this problem too. To clarify @parkr's comment, GitHub is still running version 2.4.0 ([check the latest version](https://pages.github.com/versions.json)), and jekyll used a timezone-sensitive implementation that wasn't [fixed](https://github.com/jekyll/jekyll/commit/50d0fc3c85feb287551f79a537c2ff81e3ecf5fa) until version 2.5.2.

Unfortunately, fixing it isn't as easy as I hoped. I *thought* I could just hardcode the post path. But it turns out that GitHub generates a different URL than what I generate locally, likely because of more Timezone bugs. For example, [check out this file](https://github.com/joshuaflanagan/blog/blame/94f2d0a66c0019368039730b61eefbc2ca076724/_posts/2015-11-02-infinity-ergodox.markdown#L4)

The filename contains "2015-11-02". The date in the front matter indicates "2015-11-02" in a specific timezone. But when it builds on Github, it [generates the URL](http://www.joshuaflanagan.com/blog/2015/11/03/infinity-ergodox.html) as "2015/11/03".

I would hope that jekyll would use the date from the front-matter. Since the timezone offset is specified, there is no ambiguity, or risk of it changing when run on different servers. But it appears to convert to UTC when generating the url.

**Comment by DanySK** [comment]
I am also experiencing an issue with ``post_url``. If I apply [this change](https://github.com/DanySK/danysk.github.io/commit/329e0f2e9e430d59e9eff44e17d40b7ad16d5153), the page does not build.

**Comment by envygeeks** [comment]
@parkr is there anyway Github can be pinged to send a hotfix?

**Comment by parkr** [comment]
@joshuaflanagan Did you specify a `timezone` in your `_config.yml`?

@envygeeks Probably. They usually only do security hotfixes though.

**Comment by joshuaflanagan** [comment]
@parkr I did not. That is interesting, I will look into it.
