### ISSUE TITLE
Catching Jekyll errors with Travis CI

### ISSUE THREAD

**Issue by CCoffie** [jekyll/jekyll#3232]
So I'm trying to use Travis CI to check for errors in my Jekyll repo but I noticed it was missing some. Upon further investigation I found it's because Jekyll isn't raising an error but rather just displaying an error message and then continuing on. Take the below as an example.

```
-> jekyll build      
Configuration file: /Users/ccoffie/Projects/tldrcode.com/_config.yml
            Source: /Users/ccoffie/Projects/tldrcode.com
       Destination: /Users/ccoffie/Projects/tldrcode.com/_site
      Generating... 
Error reading file /Users/ccoffie/Projects/tldrcode.com/_languages/javascript.markdown: (<unknown>): could not find expected ':' while scanning a simple key at line 34 column 3
                    done.
 Auto-regeneration: disabled. Use --watch to enable.
```

Is there a way to make jekyll abort building the site if it runs into an error like the above? Or at least raise an exception? I really just need the following output to give me an error in Travis. Should I just put a command to do a regex search of the output? Any help would be greatly appreciated. Thanks.

**Comment by envygeeks** [comment]
Is this still a problem? When I jekyll build my site with an error it exits with an error.

**Comment by parkr** [comment]
This can be punted on for 3.0. I think it's just a matter of preferring completely collapsing the build on an error like this, versus being more forgiving and building what we can. We usually err on the side of the former. We could always keep building and somehow keep track of the fact that there were errors and build but exit with 1 instead of 0.
