### ISSUE TITLE
Plugins are disabled during deployment to github pages

### ISSUE THREAD

**Issue by avityuk** [jekyll/jekyll#325]
Hi.

I am using github pages for deplyoing by Jekyll powered blog. Locally plugins work, but github pages ignores them.
Does it mean that plugings support is disabled in github pages and I should generate content locally and push `_site` dir?

**Comment by zaxebo1** [comment]
@gjtorikian  : https://help.github.com/articles/using-jekyll-plugins-with-github-pages/ lists the list of jekyll plugins whitelisted by github pages
**I desperately request you to  please please please "whitelist" the jekyll-asciidoc" plugin ( "https://github.com/asciidoctor/jekyll-asciidoc ) **

My reasons are:

A) I want to do Jekyll blogging on a tablet only, and then i have the choice of only MarkDown. 

B) Markdown has lots of limitations and non-portability across its various extensions; hence we adopted asciidoctor, and now just for putting pages in github.com, we will need to remember markdown! It would be great if asciidoctor(Written in ruby) was provided also to end-user for unified experience. Hence please whitelist "jekyll-asciidoc" plugin for jekyll ( https://github.com/asciidoctor/jekyll-asciidoc )

C) if jekyll-asciidoc is whitelisted, then it will give us the github.com's experience of "just works".

Please please , whitelist it.
==========

there is no other cultural hiccups in enabling asciidoc as:
A) asciidoc is already supported on github repositories http://asciidoctor.org/news/2013/01/30/asciidoc-returns-to-github/
B) asciidoctor (http://www.asciidoctor.org) is the asciidoc's leading implementation at the moment , which is written in "ruby". github people many tools are written in ruby, so there is no cultural propblem in enabling this ruby based tool of asciidoctor
C) "jekyll-asciidoc" is in "official" plugin list of jekyll at   http://jekyllrb.com/docs/plugins/

**Comment by envygeeks** [comment]
Our plugin list is by no means considered an endorsement of any plugin, please do not consider it so.

**Comment by zaxebo1** [comment]
@envygeeks 
agree.
My reasons/needs to whitelist were mentioned in 1.A, 1.B, 1.C, and not in 2.A,2.B, 2.C

The list 2.A, 2.B, 2.C are just additional points due to which there should not be any cultural hiccup. For example: My point (2.B) that "asciidoctor and jekyll-asciidoc has been implemented in ruby", this is not a reason of my need , but just a point that github prefers ruby , so this tool in ruby should not be a stalled/hiccup because a particular tool was not implemented in ruby.
 But just because something is implemented in ruby (2.B) can not be a reason. My reasons were mentioned in 1.A, 1.B, 1.C.

In The same way, (2.C) is  "jekyll-asciidoc is in plugin list" - not mentioned as a reason, but it was mentioned just as a point that - "as this plugin is listed there, hence its adoption should not get a hiccup due to not even being worth mentioned"

I do not know I was still able to convey my point or not.  But not all are from english speaking countries, so may be there is probably still some gap in what i want to convey

**Comment by zaxebo1** [comment]
1.A ,2.A ,3.A are those points/reasons - due to which it should be whitelisted

2.A, 2.B, 2.C  are those points - in **absence of which** , it would not be even be considered to **worth even holding discussion** that it should be whitelisted or not. 
But **presence** of the 2.A, 2.B, 2.C are not considered reasons, only its absence is considered to be hiccup.

**Comment by JosueDanielBust** [comment]
Hey, you can try to enable the plugins from [https://github.com/recurser/jekyll-plugins](https://github.com/recurser/jekyll-plugins)
For blogs sometimes is necessary the categories and in the moment github dont support categories plugins! Help please!

**Comment by envygeeks** [comment]
@JosueDanielBust Jekyll has categories built in.  That said, this is not the place to ask that question.  You need to ask your question at https://github.com/github/pages-gem since Github uses Jekyll and Jekyll does not dictate what Github does.

**Comment by danomanion** [comment]
Is there a setting in Github Pages that we can add to a config to tell Github pages this is the folder to load my pre-rendered static rendered pages from? 

Something like:
.githubpages (that contains something like) source: _sites
.nojeykll
...

I had to use a custom plugin but would like to continue to use Github pages as a host, however I wish to keep all of the files in the same repo if possible. Multiple repos or branches feel a bit messy to me, but can accept it as the only solution if it is indeed that way.

**Comment by fene** [comment]
@danomanion nope, there's no way

**Comment by JosueDanielBust** [comment]
@danomanion I see many repos using the `gh-pages` and `master` branches that serve only the `gh-pages`, I don't try this solution but I think that you can...
See this gist that If found recently...
[https://gist.github.com/chrisjacob/833223](https://gist.github.com/chrisjacob/833223)

**Comment by JosueDanielBust** [comment]
@danomanion check that you can change the site folder of jekyll and is not needed that use ever the `_site` folder with this 2 settings.
![https://cldup.com/NXhqo-RfOA.png](https://cldup.com/NXhqo-RfOA.png)
IMG from [Jekyll configuration page](http://jekyllrb.com/docs/configuration/)
