### ISSUE TITLE
baseurl / base-url: GitHub Pages Project Pages - Relative Links Fail

### ISSUE THREAD

**Issue by firemonkeyio** [jekyll/jekyll#332]
If you're not using a CNAME and hosting your Project Page on GitHub Pages it's served out of a "project-name" subfolder

http://user-name.github.com/project-name

Relative url's fail:

`<a href="/">home</a>`

resolves to

`http://user-name.github.com/`

Another example:

`<a href="/blog">blog</a>`

resolves to

`http://user-name.github.com/blog`

when I needed:

`http://user-name.github.com/project-name/blog`

The workaround I can think of for this is setting a "base-url:" in the `_config.yml` then put that in front of all `href`, `src`, `url` paths ... need it in .css and .js files, so they need to run through Jekyll (see: http://stackoverflow.com/questions/4305955/can-jekyll-act-over-css-or-js-files)... a "base-url:" is suggested in the wiki here: https://github.com/mojombo/jekyll/wiki/Configuration  ... but I can't seem to find anything that explains how this should be implemented within your actual files. e.g.

`<a href="{{ site.base-url }}/blog">blog</a>`

... am I missing something here? Is there a more elegant solution?

**Comment by fulldecent** [comment]
This sucks. I would much rather have a solution that allows the built files to be hosted from either of:

 * https://fulldecent.github.io/monitortech.org/
 * http://monitortech.org/

Using the same files. And the only way to do that is relative URLs.

**Comment by parkr** [comment]
Jekyll is not going to go into your code and change all your links. That's just asking for trouble. If anything, we can provide a liquid tag. But that said, you're asking for some voodoo in the above thay Jekyll can't provide. Using true relative URL's (e.g. `../another-page`) would be the best answer.

**Comment by fulldecent** [comment]
Yes, this is want I want! I would like my `index.html` to link to my main css file as `css/main.css` and my page `pages/bob.html` should link to the same file as `../css/bob.html`. This does not appear to be a feature.

I am reading the documentation on relative_permalink but I do not think it will do this for me. Also, now I am looking into an ugly liquid hack, which I will post back here. Thanks for following up.

**Comment by mjswensen** [comment]
@fulldecent , would following the pattern outlined in [the Project Page URL Structure docs](http://jekyllrb.com/docs/github-pages/#project-page-url-structure), committing `baseurl: 'monitortech.org'` in your `_config.yml`, and then passing `--baseurl ''` when you compile for the monitortech.org domain not be a viable solution?

**Comment by fulldecent** [comment]
@mjswensen Because I want to same compiled pages to be accessible when hosted via gh-pages or via a custom domain. Also, this helps with command line based link checkers.

If anyone else needs this, here is the code that works:

````
{% assign relative-baseurl = "" %}
{% assign canon = page.url | append: "page.html" | split: "/" %}
{% for item in canon offset:2 %}
  {% assign relative-baseurl = relative-baseurl | append:"../" %}
{% endfor %}
{{ relative-baseurl }}
````

FYI, the canonicalization in line 2 allows `/dir/` and `/dir/index.html` to be treated the same, both resulting in `relative-baseurl` equalling `../`

**Comment by mashdot** [comment]
Just to point out what is working for me now, since I found this page whilst looking for a solution.

I am using a custom domain on my github project, and Rakefile to publish my `_site` to the `gh-pages` branch.

So if my project repo is: `https://github.com/user/example`

My `baseurl: '/example'` to allow for local testing, stripping it with `jekyll serve -tw --baseurl`.

I simply amended my rake task with `"baseurl"     => ""` to strip it when generating the site.

```ruby
# "rake publish" to compile and publish
desc "Generate site files"
task :generate do
  Jekyll::Site.new(Jekyll.configuration({
                                          "source"      => ".",
                                          "destination" => "_site",
                                          "baseurl"     => ""
                                        })).process
end

desc "Generate and publish site to gh-pages"
task :publish => [:generate] do
  Dir.mktmpdir do |tmp|
    cp_r "_site/.", tmp
    Dir.chdir tmp
    system "git init"
    system "git add ."
    message = "Site updated at #{Time.now.utc}"
    system "git commit -m #{message.inspect}"
    system "git remote add origin git@github.com:#{GITHUB_REPONAME}.git"
    system "git push origin master:refs/heads/gh-pages --force"
  end
end
```

This allows me to use `{{ site.baseurl }}` to test the site locally, and publish to my custom domain with relative links. I simply hardcode in `{{ site.url }}` for header meta tag absolute links etc.

**Comment by almgwary** [comment]
it work with me when index.html file is in the root directory

**Comment by almgwary** [comment]
here example [ https://github.com/almgwary/almgwary_gallary/blob/gh-pages/index.html ] 
file are loaded

**Comment by whoisjorge** [comment]
This simple set up works for me:
`<a href="{{ "/sitemap" | relative_url }}">sitemap</a>`

It will redirect to http://<absolute&belovedURI>/sitemap
