### ISSUE TITLE
Research [layout] template file naming conventions

### ISSUE THREAD

**Issue by ldexterldesign** [jekyll/jekyll#3327]
Ref https://twitter.com/ldexterldesign/status/555478490209083392

Hey,

Anyone got any guidelines/conventions for template file naming; specifically layout?

I know Jekyll is much simpler than the following, but have any community guidelines materialised, like:
* http://codex.wordpress.org/Template_Hierarchy
* https://api.drupal.org/api/views/theme!theme.inc/group/views_templates/7

Yours hopefully,

**Comment by parkr** [comment]
(This is an example of an excellent post for a mailing list or discussion board, cc #2358)

I usually use `default` as the catch-all (still need to specify it, but I apply it to everything), then specific layouts for each data type, e.g. `post` and `page` layouts. For certain collections, I have custom layouts as well. It all depends on where you want your presentation to diverge and what the divergence is caused by and what it serves.

**Comment by ldexterldesign** [comment]
@parkr thanks - first piece of advice I've found/had on this topic

Perhaps a blog post when I have Jekyll more experience/time...

I'll leave this issue open for the time being in case anyone else has suggestions, but feel free to close if you want to..?

Thanks,

PS I'll look out for the mailing list in future. Foundation tend to operate this way too:
* http://foundation.zurb.com/forum - questions
* https://github.com/zurb/foundation - issues (e.g. bugs/features/fixes/enhancements)

**Comment by ldexterldesign** [comment]
PPS Just found https://github.com/jekyll/jekyll-help

**Comment by erlend-sh** [comment]
jekyll-help is deprecated. The new forum, [talk.jekyllrb.com](https://talk.jekyllrb.com/), would be the right place to re-post this if you'd like to resume this discussion.

Issue should be closed.

**Comment by parkr** [comment]
Thanks @erlend-sh! Please continue any discussion here on Jekyll Talk.
