### ISSUE TITLE
Content Negotiation and Pretty URLs

### ISSUE THREAD

**Issue by smizell** [jekyll/jekyll#3345]
I have a site that currently does not use Jekyll, and uses URLs in the form of:

```
http://example.com/weblog/2013/my-title
```

These URLs do no have the trailing slash, as they are simply files in a directory. Apache does this fun thing with content negotiation where you can put a file named `my-title.html` in a directory, link to `my-title` and it will look for the correct type based on the file extension and the `Accept` HTTP header. This allows you to have pretty URLs and not have to add the trailing slash (along with all the noise of having `index.html` files everywhere).

I have decided to move to Jekyll and see if I can simplify my site, but it seems impossible to get to this work on with `jekyll server`, though on Github Pages, HTML pages will actually be shown if you leave off the `.html`.

Here are the scenarios I tried.

1. I tried `/weblog/:year/:title`, but that added a trailing slash and created `index.html` files, which neither will work as they break all of my old URLs.
1. I tried `/weblog/:year/:title.html` and then used `remove: '.html'`, and while it created the correct links and files, it would return 404s when they were clicked because the server wouldn't find them. I can push to Github and it works, but not locally.

Question is, is there a way to do this and make the development server work correctly?

**Comment by envygeeks** [comment]
Try `/weblog/:year/:title.html` without the `remove: 'html'` and if that doesn't work show us the logs and make sure that everything matches your production server (as for as .htaccess is concerned.)

**Comment by smizell** [comment]
Ah, I should have mentioned that I tried that, too. If you use `/weblog/:year/:title.html`, it of course makes the correct files when building, but it also makes `post.url` include the `.html`. This was why I had to remove the `.html` to get all of the URLs to be correct.

I have the site running on Github pages as an example. If you go here:

http://smizell.github.io/

And click around, you see all of the links work and do not have the `.html` on the end (I'm using `/weblog/:year/:title.html` with `remove: 'html'`). But if you were to clone the repo and run Jekyll with it:

https://github.com/smizell/smizell.github.io

You would see that every link returns a 404 error unless you add .html on the end of it.

**Comment by parkr** [comment]
GitHub Pages doesn't support this as far as I know. This can only be supported on your own server. That said, Jekyll is not smart enough to generate a link without the extension but to write the file to the filesystem with the extension.

**Comment by smizell** [comment]
@parkr Actually, Github pages is working right now with it supported:

http://smizell.github.io/

The way I'm getting Jekyll to generate a link without the extension is to use `remove: 'html'`. This means that the file is `/weblog/:year/:title.html` but the links do not have `.html`. This is working on Github pages, but does not work on the development server `jekyll server`. 

Also, this seems to be working with other file types as well:

http://smizell.github.io/feed

That file is created as `feed.xml`.

**Comment by penibelst** [comment]
@smizell This wish came up several times since Jekyll exists (last one #2294, with patch). The directory index approach is very noisy, no question. 

@parkr Github Pages support content negotiation. This article is available with and without the file extension.

* http://tom.preston-werner.com/2008/11/17/blogging-like-a-hacker
* http://tom.preston-werner.com/2008/11/17/blogging-like-a-hacker.html

But supporting this feature requires Jekyll and *all related tools* (I think on Proofer) to be much smarter than now. This also would be a breaking change, since Jekyll interprets the permalink options `/:title` and `/:title/` same way: it creates `/:title/index.html`.

Even as a big lover of content negotiation I would say no to this feature. I wonder if Jekyll will ever support it. Directory index wins.

----

Funny side note: Apaches docs about content negotiation can’t do it.

* http://httpd.apache.org/docs/current/content-negotiation.html
* http://httpd.apache.org/docs/current/content-negotiation — doesn’t work

**Comment by smizell** [comment]
@penibelst Thanks for the great comment. I really wish there was a way to make them both work without complicating things too much. I guess I'll just keep doing things how I have it and type `.html` on the URLs to make it work in development.

Also, as a note, I don't think Github Pages does full content negotiation, as when I was testing it, it would always return the HTML version. If I had two files in a directory:

- my-file.html
- my-file.json

and request `/my-file` with `application/json` in the accept header, I get the HTML version.

> Funny side note: Apache’s docs about content negotiation can’t do it.

LOL

**Comment by penibelst** [comment]
> I don't think Github Pages does full content negotiation, as when I was testing it, it would always return the HTML version.

Good catch.

**Comment by envygeeks** [comment]
That's just pretty URL's and a bit of try_file magic in NGINX.

**Comment by penibelst** [comment]
I’ve found a deep analysis *[Why Not Conneg](https://wiki.whatwg.org/wiki/Why_not_conneg)* by WHATWG:

> The purpose of this page is to explain what's wrong with HTTP content negotiation and why you should not suggest HTTP content negotiation as a solution to a problem.

**Comment by medicart** [comment]
@smizell I had the same issue when trying to migrate from Drupal to Jekyll.
I found  a tricky yet simple way to do it. It requires you to have an Amazon AWS account.

- create a directory called docs (could be whatever you choose)
- Instead of creating posts in Jekyll, create a pages and save it to the docs directory.
- in the config file use pretty for permalink
- give your file the permalink my-title (following your example)
- install s3_website plug-in and follow the instructions in its docs (very simple)
- in the s3_website.yml file add the line extensionless_mime_type: text/html
- Generate your site and make everything works
- run the command s3_website push

That's it, you're done.

The cost of hosting a site on AWS S3 is next to nothing! same goes for cloudfront if you want your site to run even faster.

I use it and it works perfect for my sites:
http://medicart.co.il

Hope that helps

**Comment by parkr** [comment]
> I’ve found a deep analysis Why Not Conneg by WHATWG:

@penibelst I only skimmed that page, but it doesn't seem to hit on what we're doing here. Did I miss something? Thanks for sharing your research though. :)

**Comment by penibelst** [comment]
@parkr What we’re doing here is *negotiating by format*. The most important two points about this type of negotiating:

> Negotiating by format is a failure because: 
> * It is actually rather rare that format alternatives can be chosen without knowing the user's intent.
> * You can’t rely on format negotiation as Web author, because there are always clients that accept something they don’t declare. 

The article is written by @hsivonen.

**Comment by parkr** [comment]
That's fair, but I don't think it applies to us. In this case, Jekyll is really only concerned about HTML for human-readable content and JSON/CSV/XML for machine-readable content. And, as was mentioned, the GHP servers don't quite do true content negotiation. The idea is just to have `.html` files on your filesystem and `/my-cool-page` extensionless URL's in one's browser. I don't think we're really going for true content negotiation, so it seems like those two concerns don't apply.

**Comment by fulldecent** [comment]
https://wiki.whatwg.org/wiki/Why_not_conneg does not apply. Every browser supports HTML content, no browser advertises support for HTML, and neither of these will ever change.

In the same way that www.google.com/ returns a text/html response, so may www.google.com/page.

**Comment by smizell** [comment]
> In this case, Jekyll is really only concerned about HTML for human-readable content and JSON/CSV/XML for machine-readable content.

This is a good point here, as maybe it could allow for solving the issue and make Jekyll dev server act like Github Pages. Github pages always returns the `.html` file if it exists. You can then use accept to request different types like JSON or XML if desired. This isn't content negotiation, but it does sort of provide feature parity for the dev server with Github Pages.

**Comment by parkr** [comment]
@smizell: #3452

**Comment by smizell** [comment]
@parkr how cool! This is great stuff.

**Comment by willnorris** [comment]
Between #3452 and #3490, I think we can call this fixed.

**Comment by parkr** [comment]
:tada: Thanks for all the hard work, Will!

**Comment by smizell** [comment]
@willnorris @parkr Been away for the last week. Just wanted to circle back here and say thanks for doing this. Very cool stuff.

**Comment by neothemachine** [comment]
@fulldecent "no browser advertises support for HTML" -> Where did you get that from? I just checked several browsers and all send something like `Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`. While looking for information about content negotiation I stumbled upon this github issue and just wanted to add this to avoid confusion for others that might find it.
