### ISSUE TITLE
Simplify HTML code for the SVG icons

### ISSUE THREAD

**Issue by tkrotoff** [jekyll/jekyll#3374]
[Currently](https://github.com/jekyll/jekyll/blob/v2.5.3/lib/site_template/_includes/footer.html#L19):
```HTML
<a href="...">
  <span class="icon  icon--github">
    <svg viewBox="0 0 16 16">
      <path .../>
    </svg>
  </span>

  <span>...</span>
</a>
```

Simplified DOM:
```HTML
<a href="...">
  <svg class="icon icon-github" viewBox="0 0 16 16">
    <path .../>
  </svg>

  <span>...</span>
</a>
```

One `<span>` less and switch to more classical naming `icon-github` instead of `icon--github`.
The class name `icon` is probably too generic, adding a prefix like `jekyll-icon-*` would avoid name clashes when people include other icons:
```HTML
<svg class="jekyll-icon jekyll-icon-github" viewBox="0 0 16 16">
  <path .../>
</svg>
```

Examples around:
- Bootstrap: [`<span class="glyphicon glyphicon-search"></span>`](http://getbootstrap.com/components/)
- FontAwesome: [`<i class="fa fa-search"></i>`](http://fortawesome.github.io/Font-Awesome/icon/search/)
- Ionicons: [`<i class="icon ion-home"></i>`](https://github.com/driftyco/ionicons)
- [Open Iconic](https://github.com/iconic/open-iconic):
```HTML
<svg class="icon">
  <use xlink:href="open-iconic.svg#account-login" class="icon-account-login"></use>
</svg>
```

What do you think?

**Comment by parkr** [comment]
I'm beyond my depth here. @jglovier, oh master of the browsers, can thou helpeth guide this poor soul?

**Comment by jglovier** [comment]
So the original logic behind adding the class to the span instead of the of the svg element itself was for ease of customization. I wanted to make it easier for people who may want to swap out the existing icons for something else (like LinkedIn, etc) without breaking the layout if they didn't realize those classnames on the svg itself were layout dependent.

That being said, I'm not terribly opposed to simplifying that markup, I'm just not sure it really gains much while potentially making customizing the theme a bit more tricky.

>switch to more classical naming icon-github instead of `icon--github`

Totally :+1: for that. TBH I have no idea how that got a double dash in the first place. Looking at [my original pull for this markup](https://github.com/jekyll/jekyll/pull/2050/files) you can see that I just used `class="icon github"`, so that must have happened along the way somewhere since then.

**Comment by parkr** [comment]
Closing as abandoned.
