### ISSUE TITLE
Incremental regeneration doesn't update the frontpage when I update posts

### ISSUE THREAD

**Issue by sondr3** [jekyll/jekyll#3411]
Since the 3.0 release plan post was locked (sorry about that) I'll just repost this here as a separate issue:

Hey, quick question, I have a pretty wonky problem that I think has to do with incremental regeneration. I'm currently using the 3.0 beta1 release and whenever I update a post the index file isn't updated along with the post, but the post itself is updated when you visit it. I'm running Jekyll through Gulp so every time I save my posts it runs `jekyll build` but quite frequently the frontpage isn't updated. Occasionally it'll update however but I can't seem to figure out when it does/doesn't. Any ideas?

**Comment by alfredxing** [comment]
This is an interesting issue since incremental regen doesn't track Liquid dependencies (which is currently the biggest problem right now). You can get around this by adding `regenerate: true` to the front-matter of your `index.html` file.

I'm currently thinking of ways to fix this, but there doesn't seem to be many options.

**Comment by sondr3** [comment]
Yeah, that's what I figured too. I didn't know about the `regenerate: true` option but it's a decent compromise for me. Cheers.

**Comment by wh0** [comment]
Is this how Jekyll 3 is going to work, where users just put `regenerate: true` in various pages? If not, can we have this bug reopened?

**Comment by envygeeks** [comment]
Probably not, this bug overlaps a larger discussion about #3747 that was already kicked off.
