### ISSUE TITLE
Confusing message

### ISSUE THREAD

**Issue by eksperimental** [jekyll/jekyll#3412]
```sh
$ jekyll --serve
       Deprecation: Jekyll now uses subcommands instead of just switches. Run `jekyll --help' to find out more.
jekyll 2.5.3 | Error:  Whoops, we can't understand your command.
jekyll 2.5.3 | Error:  invalid option: --serve
jekyll 2.5.3 | Error:  Run your command again with the --help switch to see available options.
$ jekyll version
Invalid command. Use --help for more information 
```

> Deprecation: Jekyll now uses subcommands instead of just switches. Run `jekyll --help' to find out more.

It's telling me it uses subcommands, but the option that gives me to get help doesn't use it.

**Comment by pathawks** [comment]
`jekyll serve` is what you’re looking for, but yeah, that warning is not at all helpful.

**Comment by eksperimental** [comment]
@pathawks thanks, i know what I was looking for, I just typed that by mistake. but it just called my attention. same in the following error message.

i think `jekyll version`  should be supported. just to make it more consistent

**Comment by envygeeks** [comment]
I agree it doesn't hint at what you actually need to do to fix the problem.  Perhaps we could adjust that message to say something to the effect of `Deprecation: Jekyll now uses subcommands (jekyll subcommand) instead of just switches (jekyll --switch). Run `jekyll --help' to find out more.` that would be more clarifying.

/cc @jekyll/core

**Comment by alfredxing** [comment]
If we have subcommands already, doesn't that kind of imply that switches are mainly used for options? In that case we should make `jekyll help` a valid command as well (but keeping, of course,`jekyll --help` and `jekyll --version` for compatibility/muscle memory). `git` and `rails` (among others) use this behaviour.

**Comment by eksperimental** [comment]
yes, @alfredxing that's what I meant by confusing, i should have used the word "contradictory". 
@envygeeks my point is, it is saying it doesn't use switched anymore and the options to find out more is a switch itself.

to make it clear.
1) message should read `Run jekyll help to find out more`
2) and `jekyll version` should be supported.
```shell
$ jekyll version
Invalid command. Use --help for more information 
```

3) Messages containing `--help` or `--version` should be replaced with `jekyll help` and `jekyll version` should be replace across the project to make it consistent

**Comment by envygeeks** [comment]
They might be valid commands but git does not tell you to do `git help` and neither does Rails, because the standard convention is `--help` and will always be the case even if there is a sub-command system (at least to the convention applied to *nix.)  See: `git: 'lol' is not a git command. See 'git --help'.`  Our's and your first mistake is assuming that `--whatever` is a switch to begin with it, it's not, it's an argument that is parsed as `help` so if we label it as such the convention that it must stay as the main indicator stands.

I am :-1: on implying to use `jekyll help` at all because help is not a command, it is a argument that should be applied per-context (the way rails does it, `rails g --help`) I am however, not against aliasing it as @alfredxing partially suggested.

**Comment by eksperimental** [comment]
@envygeeks I absolutely agree with you.
so, then point number 3, should only consider replace `jekyll --version` with `jekyll version`, is that correct?

**Comment by envygeeks** [comment]
Don't replace them at all, alias them the way that most command systems do.  Prefer `jekyll --help` and `jekyll --version` *however* also allow `jekyll help` and `jekyll version` because well as you stated it's rather silly of us not to accept it if they are root level arguments.  So at the end of the day we should have both types but only at the root and only if you try it, otherwise we should spit out `--version` and `--help` as per standard conventions.

We don't break assumptions or conventions that way, what do you think @parkr?

**Comment by eksperimental** [comment]
by replacing i am talking about the messages displayed

**Comment by eksperimental** [comment]
Another thing to change will be : 

`jekyll help` shows this

```
Options:
...
        -h, --help         Show this message
```
It should read `Show help message for the given command`

**Comment by envygeeks** [comment]
The message displayed *should not be changed* as the convention is `--help` that is exactly what I am against, accepting `jekyll help` and enforcing an incorrect convention that has stood for decades and worked very well and is muscled into the entire planet won't work for me.  I'm absolute :-1: on any vote that asks to change any message from `--help` to `jekyll help`.

**Comment by eksperimental** [comment]
true. well, while `jekyll <command> --help` works, you can still access via `jekyll help <command>`
. so i woulnd't touch that.
