### ISSUE TITLE
jekyll generate empty tags

### ISSUE THREAD

**Issue by e-cloud** [jekyll/jekyll#3443]
i'm brand new to jekyll, i just follow some tutorial to create my first site.
but i found some thing ugly that jekyll generate **empty tags** like `<p>`

part of my code is here: 

```
      <li>
        <span class="post-meta">{{ post.date | date: "%b %-d, %Y" }}</span>

        <h2>
          <a class="post-link" href="{{ post.url | prepend: site.baseurl }}">{{ post.title }}</a>
        </h2>
        {% if site.excerpt_separator %}
        <p>{{ post.excerpt }}<p>
        {% else %}
        <p>{{ post.content }}</p>
        {% endif %}
      </li>
```

when i check on chrome dev tool, i found this:
![image](https://cloud.githubusercontent.com/assets/5255354/6149894/d8c661d4-b246-11e4-9d98-65b1726d60d1.png)

is there something i misunderstood? or it is just what it does?

**Comment by kleinfreund** [comment]
There is always a `excerpt_separator`, so they excerpt condition is always true. Better check for what you have: `{% if post.excerpt %}`.

**Comment by pathawks** [comment]
Questions like this really belong at [jekyll/jekyll-help](https://github.com/jekyll/jekyll-help).

What I imagine is happening is that, because `{{ content }}` is already formatted HTML, by wrapping it in `<p>` tags, something in the chain is just trying to balance the `<p>` and disallow having nested `<p>`s.

In short, don't wrap `{{ content }}` in `<p>`.

**Comment by parkr** [comment]
Thanks for answering this one, guys!!

**Comment by e-cloud** [comment]
**@kleinfreund** & **@pathawks** , thank you. I've try **@pathawks**'s answer. That's what i want! BTW, **@kleinfreund**'s advice is also very nice! Forgive my ignorance.
