### ISSUE TITLE
Question / documentation issue: URL for a page

### ISSUE THREAD

**Issue by fulldecent** [jekyll/jekyll#3470]
On my `index.html` I would like to link to the article that is at `_productsCategory/toyCars.md`.

Since I set up everything and I know what permalinks are defined in my `_config.yml`, I would achieve this by doing:

    <a href="/toyCars.html">Toy Cars</a>

Is this best practice, or are people doing something like this:

    <a href="{{ site.pages | where:"path","_productsCategory/toyCars.md" | map:"url" }}">Toy Cars</a>

**Comment by parkr** [comment]
The latter case is not considered best practice, the former is. The principle of making a URL and leaving it that way has been around since... well, it was Tim Berners-Lee's idea so I guess since the beginning of the internet. We've considered a `collection_url` plugin much like the `post_url` plugin before: #2540.

**Comment by fulldecent** [comment]
URLs don't move, that makes sense. Thanks
