### ISSUE TITLE
How to create spoilers ?

### ISSUE THREAD

**Issue by Arti3DPlayer** [jekyll/jekyll#3493]
How can i create spoilers with markdown syntax ?

**Comment by MartinRogalla** [comment]
I believe this should actually be posted in [jekyll/jekyll-help](https://github.com/jekyll/jekyll-help/issues), as this is not an issue with Jekyll itself.

As an answer to your question you could for example use the following:  

Add the following in the css file:
```css
.spoiler {
    background-color:#000000;
    color:#000000;
}
```
In your rst file:
```rst
.. class:: spoiler

Example Text
```

Then people need to select your text in order to see what it says. This is just one of the ways. There are many other ways of doing this.
