### ISSUE TITLE
Global configuration file

### ISSUE THREAD

**Issue by alfredxing** [jekyll/jekyll#3499]
I was thinking about this for a bit and I thought it would be useful to have a global configuration file (like a global `.gitconfig`) so users can set configuration defaults (instead of always having to use the `DEFAULTS` provided with no option of a global override).

Use cases:
- Setting a default Markdown processor
- Setting a default syntax highlighter
- Setting default timezone and encoding
- Specifying a list of default gems to include
- Setting default Kramdown settings
- Globally setting the port used by `jekyll serve`

Of course, there are many more options that can be specified, but these are the ones I'll find most useful.

**Comment by willnorris** [comment]
this could already be done by specifying both the global and local config files with the `--config` option, right?  And then add that to a startup script so you don't have to specify it each time?  Just a thought

**Comment by alfredxing** [comment]
@willnorris Yep, but then you would have to create aliases in your shell or whatnot, and then it would be a pain to use that option for something else later on.

**Comment by parkr** [comment]
An interesting proposition. I think if we want to add this file, it means our current defaults aren't sane enough. I'd love to hear what we should change for 3.0 to achieve greater sanity.

The experience of having a global configuration file would likely cause a lot of confusion. "It builds one way locally but then when I push to Pages or wherever, it builds totally differently. What gives?!" From a support standpoint, I think this idea opens up a strange can of worms.

I'd be more comfortable with something like #3175, where all the configuration files are there, but you can have `dev` for local and `prod` (or an equivalent) for Pages. I like the idea of a site being truly portable – you don't need to worry about dragging configuration files around with you if the folder you're interested in has all the configuration within.

**Comment by willnorris** [comment]
@alfredxing not sure what you mean about shell aliases.  For example, I have a simple [run script](https://github.com/willnorris/willnorris.com/blob/master/tools/run) that I use during development that pulls in my `_debug.yml`.

At the heart of my concern is the same thing @parkr articulated... As it is today, jekyll sites are effectively self-contained.  Changing that is likely to cause confusion, with unclear benefit.

**Comment by parkr** [comment]
I'm going to close this for now, but feel free to write back. Thanks for the ideas, Alfred! You rock!

**Comment by alfredxing** [comment]
Good point, it would make everything harder to push to Pages.
I think the current defaults are great, but in case someone else wants different defaults there's currently no way for them to set it.

**Comment by alfredxing** [comment]
@willnorris Something similar to what you have, but shell aliases let you alias/define commands without needing to create a script file: http://en.wikipedia.org/wiki/Alias_%28command%29

**Comment by parkr** [comment]
@alfredxing While they can't change the defaults in the gem, they have full configuration flexibility in each site. I think encapsulation is enough of a benefit to ask you specify your configs per site.

**Comment by kleinfreund** [comment]
Although I like the idea of having global configuration files which I can move between machines to get up and running quickly (which helped me recently, because my hard drive died) I think in the case of Jekyll it comes with the already mentioned caveats. But still, I like the idea. Maybe there are some sane opportunities for this.

**Comment by fredym** [comment]
This is how I ended up here:

I'm building a static site with **jekyll** in a Mac. Now I need to share this project with my colleagues. Most of them use Windows so I decided to create a **Vagrant** environment. Here is the `Vagrantfile`: https://gist.github.com/fredym/a1c560e6c3ddb210e36c

It turns out that in order to serve the site outside the **Vagrant** box I need to add `host:0.0.0.0` to `_config.yml`. This is not required to serve the site from my host therefore it's a good candidate to add it to the "global configuration file" in the **Vagrant** box. This is how my quest for this file started.

Something similar happens with the `--force_polling` flag which is required in order to auto-regenerate the site when the source files are updated outside the **Vagrant** box. Except that in this case there is no matching config option.

I agree with you, I'm still not sure if this is a good idea. I like self-containment. I think I'll go for the alias alternative for now.

**Comment by envygeeks** [comment]
@fredym instead of doing all that complicated stuff with Vagrant simply built your site as normal on your Mac, and ask them to install boot2docker and use our official Docker image, which does all the 0.0.0.0 forwarding and stuff for you.
