### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#3500]
There's a test that's kind of flaky. I think it has to do with autoregen. Usually it's fixed by just rerunning the tests with a different seed value, but that's not really a good solution. @alfredxing, would you mind looking into this?

```text
Finished tests in 58.696950s, 9.2168 tests/s, 15.7078 assertions/s.
Failure:
TestDocument#test_: a document in a collection with non-alphabetic file name should be output in the correct place.  [/home/travis/build/jekyll/jekyll/test/test_document.rb:356]
Minitest::Assertion: Expected: true
  Actual: false
541 tests, 922 assertions, 1 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to /home/travis/build/jekyll/jekyll/coverage. 1898 / 2203 LOC (86.16%) covered.
real	1m0.551s
user	0m45.644s
sys	0m2.374s
```

Thanks!

**Comment by alfredxing** [comment]
Hmm.. after a bit of testing it seems that even the tests in each `context` block are not run at the same time, and that `setup` is run before each.

I think the problem here is that a test in the context block runs, then a test in another block without the `methods` collection runs, then the failing test runs. The file doesn't exist because the middle test cleaned up the `dest` when processing, but since none of these were full rebuilds, the metadata file was not cleaned up.

The fix for this is to specify `'full_rebuild' => true` in the configuration passed in.

It's another thing that incremental regeneration doesn't cover. Thinking of this, I should probably write more docs before 3.0 to cover when incremental works and when it doesn't...

**Comment by envygeeks** [comment]
If there is no way to configure that globally why isn't there? Because having to replicate it dozens of times would lead to this problem happening over and over again, that or it should detect JEKYLL_ENV (which should probably be set to test by default if it's not already set that way) and disable the stuff that will ruin tests.

**Comment by mattr-** [comment]
If we're setting `JEKYLL_ENV` to `test` to disable stuff that will ruin tests, doesn't that defeat the whole purpose? (Not trolling. Just genuinely confused.)

**Comment by alfredxing** [comment]
In this case it wouldn't be too bad because incremental regen seems to span across tests, and since the test are run in an arbitrary order, there's just no way to predict what will happen (this should apply to Documents only though; Posts and Pages should work).

**Comment by parkr** [comment]
We could set full_rebuild config to true by default

**Comment by alfredxing** [comment]
I think it's more to do with this suite not making use of `fixture_site`. We could definitely set `full_rebuild` to true in that method, and then switch all of the site-making in this suite to use `fixture_site`?

**Comment by parkr** [comment]
Definitely

**Comment by alfredxing** [comment]
Sent in a PR! Turns out `fixture_site` already defaulted to `full_rebuild: false`.
