### ISSUE TITLE
redirect-from URL causes browser to download page

### ISSUE THREAD

**Issue by mbirth** [jekyll/jekyll#3513]
I have a page in `/know-how/hardward/_posts/2010-07-22-fortuna-gpsmart-bt.md` with a redirect_from tag in the front matter:

```
redirect_from:
  - /know-how/hardware/fortuna-gpsmartbt
```

The main page is available via GitHub Pages at http://wiki.mbirth.de/know-how/hardware/fortuna-gpsmart-bt.html just fine. However, the redirect_from URL http://wiki.mbirth.de/know-how/hardware/fortuna-gpsmartbt causes my Chrome to display a download window instead of redirecting me.

Also, the server sends a HTTP 200 OK instead of a more appropriate 301 Redirect. And there doesn't seem to be a "Location:" header.

Could we get a more SEO-friendly redirection, please?

**Comment by kleinfreund** [comment]
The `jekyll-redirect-from` doesn’t do 301 redirects, right? It does it via `meta http-equiv` IIRC. Not sure, though.

**Comment by pathawks** [comment]
What seems to be happening is, since the page does not have a file extension, the server is serving it as an octet-stream, which of course triggers the browser to download rather than displaying as HTML.

Serving 301 instead of 200 status would be awesome, but would require a much tighter integration between Jekyll and whatever the destination server is than is currently available.

All that said, this really has nothing to do with Jekyll proper. You should open this as an issue in the [jekyll/jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from) repo.

**Comment by parkr** [comment]
GitHub has support for writing an HTML file and dropping the extension in the URL. Add the extension to this link, then it should work again.

**Comment by mbirth** [comment]
Thanks for the heads up. Seems to be this issue: https://github.com/jekyll/jekyll-redirect-from/issues/37
