### ISSUE TITLE
Permalink setting assumes that filenames will end with “.html”

### ISSUE THREAD

**Issue by bdesham** [jekyll/jekyll#3554]
I like my permalinks to look like “http://example.com/2015/03/08/foobar”. What I’ve been doing is to set

```yaml
permalink: :categories/:year/:month/:title.html
```

in my \_config.yml and then configuring my server to serve .../foobar.html on requests for .../foobar. I also have to do a bunch of `{{ post.url | replace: ".html", "" }}` in my templates, since Jekyll only knows about my “internal” permalinks (the ones that end in “.html”) and not the external-facing ones.

It would be *way* easier, therefore, if I could just tell Jekyll about my “real” permalink format in the first place. In other words, my file “2015-03-08-foobar.md” would get turned into a file called “foobar”, with no extension. (The web server has to be configured to serve these files with the right Content-Type, but that’s easy.) When I tried to set

```yaml
permalink: :categories/:year/:month/:title
```

though, Jekyll acted as if I had actually said

```yaml
permalink: :categories/:year/:month/:title/index.html
```

This is not unreasonable—I think my case is probably uncommon. It is annoying, though, that there doesn’t seem to be a way to get Jekyll to generate filenames that have no extension at all. Is there any kind of workaround for this?

**Comment by parkr** [comment]
We actually just fixed this, thanks to @willnorris's recent work. Check out 3.0.0.beta2 – does that fix your problem?

**Comment by parkr** [comment]
(Also :wave: from a fellow (but former) Rochestarian!)

**Comment by bdesham** [comment]
:snowflake: :wave: :snowflake:

I installed the 3.0 beta but I’m not sure what I should be doing in my \_config.yml. I read through #3490 and #2294 (et al.) and I tried setting `use_post_dirs: false` in my config but I still get filenames ending in .html. Any pointers? (Are there any docs for 3.0 yet?)

**Comment by willnorris** [comment]
Sadly, no docs yet... that's my bad :disappointed:

Instead of writing extensionless files to disk and setting the web server to set a default content-type, we always include extensions on the files written to disk, and then configure the web server to serve those files when extensionless URLs are requested (using Apache multiviews, Nginx try_files, or something similar).

So, specify a `permalink` setting without a trailing slash or output_ext... something like:
``` yaml
permalink: /:year/:month/:title
```

Then for nginx for example, you would do something like:
``` nginx
try_files $uri $uri.html $uri/ =404;
```

**Comment by envygeeks** [comment]
One should probably do `@404` with a router so they can customize that ugly ass page.

**Comment by willnorris** [comment]
@envygeeks what do you mean?  You can just specify custom error pages using [error_page](http://nginx.org/en/docs/http/ngx_http_core_module.html#error_page)

**Comment by envygeeks** [comment]
This is a jack but I'll not reply again after this: Nginx would have you believe that but we always get quirks with error_page alone so we hack it in with `@404` routers, but that could very well be a platform bug or even an older bug, we are on an old ass version of Nginx because of Ubuntu LTS (well up until last month when we built our docker infrastructure.)

**Comment by bdesham** [comment]
OK, so it looks like the hacky approach I described above is actually the Right Way now :neutral_face: At least with Jekyll 3 I won’t have to do the `{{ post.url | replace: ".html", "" }}` dance.

**Comment by willnorris** [comment]
(just curious, why do you refer to this as a "hacky approach"?  This is a pretty standard way of handling extensionless URLs)

**Comment by bdesham** [comment]
I just remember going through a lot of trial and error trying to get nginx to issue redirects just so. Telling it to serve all unknown files as text/html is a lot easier to figure out in the first place (and then requires less arcana in my nginx.conf file). Now that I have the redirects set up it’s not a big deal, of course.

**Comment by pathawks** [comment]
I don't think you need to issue redirects.

[**How Can I Configure nginx to Use Pretty URLs for Static Sites?**](http://serverfault.com/questions/189431/how-can-i-configure-nginx-to-use-pretty-urls-for-static-sites/189475#189475)
