### ISSUE TITLE
Add a parameter to the markdownify filter for "inline" rendering

### ISSUE THREAD

**Issue by hubgit** [jekyll/jekyll#3571]
When Markdown is used for section headings, for example, the `markdownify` filter produces invalid (and inappropriate) HTML by wrapping the output in a paragraph tag.

I'm curently working around this by doing these conversions client-side using [markdown-it](https://github.com/markdown-it/markdown-it#usage-examples) which has a `renderInline` method, but it's a bit of a hack and is dependent on JavaScript.

Following the syntax of other filters that take optional parameters, `| markdownify: 'inline'` would be ideal.

**Comment by envygeeks** [comment]
Please post the HTML that you get without that plugin.

**Comment by hubgit** [comment]
Input:

```html
{% capture headingText %}Example heading{% endcapture %}
<h2>{{ headingText | markdownify }}</h2>
```

Desired output:

```html
<h2>Example heading</h2>
```

Actual output:

```html
<h2><p>Example heading</p></h2>
```

I've just realised, though, that it would actually make more sense to tell markdownify/kramdown that it's a section heading and let it handle this by itself, like this:

```html
{% capture heading %}## {{ headingText  }}{% endcapture %}
{{ heading | markdownify }}
```

**Comment by envygeeks** [comment]
Hmmm... that is highly undesirable.  I don't think we need an option for it though, this is an actually bug we need to fix... you should in theory get back the `<h2>` no matter what.  There is either a bug in our markdown library or there is a bug in what we send to the markdown library but that's a pretty serious bug no matter what because all things considered that is absolutely invalid HTML it's spitting back to you and shouldn't have even been output no matter what.

**Comment by hubgit** [comment]
The Markdown converter doesn't know it's inside an element where a paragraph isn't allowed, so it's not too surprising that it doesn't handle it automatically - it might only be possible to do this correctly by allowing the "inline" preference to be specified.

On the other hand, I'm totally fine with using concatenating `##` to the front and passing the whole heading to `markdownify`, now that I've realised it's possible, so don't consider this a bug on my behalf.

**Comment by envygeeks** [comment]
Actually you're right, I didn't notice that you were putting it that way.  I do apologize for not paying attention without coffee running through me.  That said, I don't think our preferred markdown converter supports such things (and I don't know that we should either since Redcarpets maintainer points out that the spec states it is not meant to be used in block level elements... https://github.com/vmg/redcarpet/issues/13) 

To do this ourselves without support from our preferred markdown processor would require us to use Nokogiri (or fancy regexp's that aren't always guaranteed to work.)  That's undiserable.  Or we would need to implement another markdown processor (but this has pitfalls in that we would need to normalize or face those consequences.)

I don't know that this is something we should be doing because it's a problem with the processor.

**Comment by hubgit** [comment]
Good point about the spec - I'll close this issue.

**Comment by Joshfindit** [comment]
Ran across this while looking for the 'quick and simple'. Wanted to add that Hugo simply strips off the `p` tags, as per https://github.com/spf13/hugo/commit/be627fa718d23278aeb53da5651a8a4a1be14c27 from their issue #1025 (will edit to link to the issue if it's desired)

**Comment by Convincible** [comment]
Why was this closed? I am up against this issue as well which I will probably solve by creating my own Liquid tag filter. But basically, there are lots of _inline_ situations where you still want Markdown, not just in headers – e.g. the text of a link. Markdown rightly wraps a plain line in paragraph tags, but would make sense to be able to specify that the content is inline only. It could then even ignore newlines in the input.

**Comment by jcubic** [comment]
The linked PR (that closed beause of inactivity) provide solution for this:

```
{{ 'markdown here' | markdownify | remove: '<p>' | remove: '</p>' }}
```

there is also this:

```
{{ 'markdown here' | markdownify | ltrim: '<p>' | rtrim: '</p>' }}
```
but the second one didn't work for me, maybe because whitespace before and after.

**Comment by CookiePLMonster** [comment]
If you need this only for short texts, eg. titles, then you may as well also use `strip_html`, like so:

```{{ post.title | markdownify | strip_html }}```

Since you are not supposed to use any formatting in YAML front matter, this may very well work fine.

**Comment by Convincible** [comment]
`strip_html` isn't a solution as this issue is specifically about wanting HTML – but only inline-level tags.

This is required wherever markdown is to be rendered into an inline context. A simple case: `<h1>{{ title | markdownify }}</h1>`. Why would you want inline HTML within your title element? Semantically, your title may contain things like citations, emphasis, language changes, etc. e.g. "My Review of <cite>Jekyll</cite>`

Stripping `<p>` tags is also prone to error especially if you can't trust the markdown that is passed, e.g. it comes from user input (by user I mean a non-developer editor). This is because it's possible to write markdown that will render straight out to a non-`<p>` initial block tag. e.g. if the editor has decided to name their article: `1. 2. 3. Go!` Now markdown will spit out an `<ol>` tag immediately, not a `<p>` tag.

**Comment by yatil** [comment]
I agree an inline-markdown flag would be really useful. Most md libraries that I used with PHP supported that.
