### ISSUE TITLE
3.0.0.pre.beta2 breaks permalinks on existing sites

### ISSUE THREAD

**Issue by kaatt** [jekyll/jekyll#3602]
> mkdir bugtest
> cd bugtest
> echo "gem 'jekyll', '3.0.0.pre.beta2'" > Gemfile
> mkdir foo
> cd foo
> echo -e '---\npermalink: /foo/baz.html\n---' > bar.htm
> cd ..
> bundle exec jekyll b
> find .
###
.
./.jekyll-metadata
./_site
./_site/foo
**./_site/foo/baz.html.htm**
./_site/Gemfile
./_site/Gemfile.lock
./foo
./foo/bar.htm
./Gemfile
./Gemfile.lock

beta1 has no problem and generates `./_site/foo/baz.html`

**Comment by willnorris** [comment]
Thanks @kaatt for the detailed steps to reproduce... that helps a lot.  And just to link this to the appropriate PR, this is actually related to #3490.

so strictly speaking, this is working as intended, though I agree that it seems somewhat unintuitive in this particular case.  The change that #3490 made was to ensure that output files always include the correct file extensions, where "correct" is determined by the return value of [output_ext](https://github.com/jekyll/jekyll/blob/a5b9df728766ce052d13429b36eb51ba237c1ddb/lib/jekyll/convertible.rb#L80).  

For file types that Jekyll has a converter for, the converter itself determines the extension.  For example, [the markdown converter returns ".html"](https://github.com/jekyll/jekyll/blob/a5b9df728766ce052d13429b36eb51ba237c1ddb/lib/jekyll/converters/markdown.rb#L57).  For file types that Jekyll does **not** have a converter for, we use the extension of the original source file.

**So why does Jekyll ignore the file extension in the permalink variable?**

Jekyll doesn't know that it's intended to be a file extension.  Jekyll supports permalinks that include dots in them.  So imagine that we had a markdown page with the front matter:

``` yaml
permalink: /i.like.to.separate.words.with.dots
```

What should the destination file's extension be?  Should it be ".dots"?  It seems very unlikely that that was what the author actually intended.  Since markdown files are rendered as HTML, it wouldn't be served properly by most web servers anyway.  Instead, we append ".html" to the permalink when outputting the file, and then [provide instructions](http://jekyllrb.com/docs/permalinks/#extensionless-permalinks) on how to configure a web server appropriately (or in the case of GitHub pages or WEBrick, no extra config is necessary).

So there are a few possible options for you:

1. rename your source file to use .html instead of .htm

2. you could change your permalink to either `/foo/baz.htm` or `/foo/baz`, depending on what style you like better.  The latter extensionless style would need some extra webserver config, and wouldn't work with GitHub Pages or WEBrick.

3. Create a very simple Converter that operates on `*.htm` files, and returns "*.html" as its output_ext

If none of those options can work for you, then I'd love to hear more about your use case.

**Comment by kaatt** [comment]
@willnorris I've already done option 1. The beta1 behaviour should be gracefully migrated to beta2's so that the user is notified. After upgrading from beta1 to beta2, I built the site and checked the git status. If I didn't (and a lot of users won't) a lot of permalinks would have been broken.

**Comment by willnorris** [comment]
I'm glad to hear you got things working again, and I'm sorry that this broke your site in the first place.  Jekyll 3 includes a number of breaking changes from Jekyll 2, this being among them.  When Jekyll 3 is released, the upgrade guide will identify these kinds of changes.  I'm not sure that any such guide exists between the various beta releases though... beta releases are, somewhat by definition, less stable and so some churn comes with the territory.  I would be very surprised if more than a handful of people were impacted by this change between beta1 and beta2.

**Comment by kaatt** [comment]
Yes that's what I meant – upgrading from Jekyll 2 to 3.

**Comment by willnorris** [comment]
oh, gotcha... I misunderstood.  We've discussed a bit about things that will need to go into the [upgrade guide](http://jekyllrb.com/docs/upgrading/), though it doesn't look like any of the 3.0 stuff has made it there yet.  It may be worth reorganizing that page to make it clearer which sections apply to which versions.  Either way, this permalink behavior is definitely something we'll need to document there.

**Comment by parkr** [comment]
> We've discussed a bit about things that will need to go into the upgrade guide, though it doesn't look like any of the 3.0 stuff has made it there yet. It may be worth reorganizing that page to make it clearer which sections apply to which versions.

I think an "upgrading from 2 to 3" guide would be helpful, and calling the current one "upgrading from 1 to 2"
