### ISSUE TITLE
A dumb but it breaking me question, sorry.

### ISSUE THREAD

**Issue by ianmartins** [jekyll/jekyll#3621]
Around a month I started my studies from nothing to reach all awesome ideas that I have and that it's really encouraged here.
After all that codes and doing and redoing to make some sense it's time to put my blog up online and runing.
Ok, so here is my problem. I put the files from terminal to github and really don't works even after that anxious night sleeping. Can you guys figure out what i'm doing wrong?

Edit: Oh, of course. Here's the link: https://github.com/ianmartins/ianmartins.github.io

Thank you, all.

**Comment by envygeeks** [comment]
While I hate to do this because you truly need help, I must be forced by general policy to ask you to put this on https://talk.jekyllrb.com because this ticket system is for bugs and feature requests only.  If you will place it there I (and plenty of others) will gladly help you sort out any issues you have with deploying!

**Comment by ianmartins** [comment]
Thank you @envygeeks, for the fast comment!
I'll do this and sorry come to the wrong place.
