### ISSUE TITLE
Auto-generation silently failing

### ISSUE THREAD

**Issue by cjerdonek** [jekyll/jekyll#3624]
I'm a new Jekyll user on Mac OS X.  I'm using Jekyll with [this project](https://github.com/sfbrigade/sfbrigade.github.io), but I can't seem to get auto-generation working (e.g. when changing files in the `_includes` directory).

I'm using Ruby 2.1.1 with Jekyll 2.4.0, which are the versions specified here: https://pages.github.com/versions.json (which is what appears in the project's Gemfile).  I've spent time looking through the troubleshooting areas of the docs for ideas on this, as well as at old issues in the tracker (though not exhaustively).  But I couldn't find anything.  Thanks in advance for any help.

**Comment by pathawks** [comment]
For troubleshooting, you should check out [talk.jekyllrb.com](https://talk.jekyllrb.com)

**Comment by cjerdonek** [comment]
@pathawks I wasn't able to find any relevant discussions on that site.

I'm not experiencing any error messages.  The feature simply doesn't work.  Another person using the same project says it works for them, which suggests that it's not a configuration issue.

**Comment by cjerdonek** [comment]
Okay, so it seems to regenerate if `--force_polling` is used, as suggested in https://github.com/jekyll/jekyll/issues/2926.  But that issue still doesn't explain why it's not working without `--force_polling`.  It seems like a bug somewhere.

**Comment by cjerdonek** [comment]
I suspect it's a case-sensitivity issue.  Jekyll reports the following:

    Source: /Users/chris/dev/codeforsf/sfbrigade.github.io

But running the following gives--

    $ pwd
    /Users/chris/Dev/codeforsf/sfbrigade.github.io

**Comment by pathawks** [comment]
> The feature simply doesn't work.

WFM :poop:

I cloned sfbrigade/sfbrigade.github.io, ran `bundle install`, `bundle exec jekyll serve`, and edited the file `_includes/open-graph.html`  
The site was updated to reflect the changes I made.

My path also has a mix of upper and lowercase letters:

```sh
$ pwd
/Users/pat/GitHub/sfbrigade.github.io
```

Jekyll recognizes this:

```text
$ bundle exec jekyll serve
Configuration file: /Users/pat/GitHub/sfbrigade.github.io/_config.yml
            Source: /Users/pat/GitHub/sfbrigade.github.io
       Destination: /Users/pat/GitHub/sfbrigade.github.io/_site
      Generating... 
                    done.
 Auto-regeneration: enabled for '/Users/pat/GitHub/sfbrigade.github.io'
Configuration file: /Users/pat/GitHub/sfbrigade.github.io/_config.yml
    Server address: http://0.0.0.0:4000/
  Server running... press ctrl-c to stop.
```

***

On a totally unrelated note, you have a very interesting `Gemfile`:

```ruby
source 'https://rubygems.org'

require 'json'
require 'open-uri'
versions = JSON.parse(open('https://pages.github.com/versions.json').read)

gem 'github-pages', versions['github-pages']
```

**Comment by cjerdonek** [comment]
Thanks, @pathawks.  Notice one difference between your situation and mine is that my `pwd` output differs from my "Source" output (which is why I made the comment and explicitly included the output strings).  I will edit that comment now to make the difference more visible.

**Comment by pathawks** [comment]
I noticed the difference, just not sure how to recreate.

What OS are you running?

**Comment by cjerdonek** [comment]
It's in the first sentence of my report (Mac OS X, specifically 10.10.2).  I'm pretty sure this issue is causing it: http://feedback.livereload.com/knowledgebase/articles/86239

**Comment by cjerdonek** [comment]
Obviously Jekyll can't fix a bug in Mac OS X, but it would be really helpful if Jekyll could warn the user if the bug is in play for the directories being used (and direct the user to relevant work-arounds, e.g. by using `--force_polling` or directing them to the livereload.com link above).

**Comment by envygeeks** [comment]
There is, `--force-polling`.  I'm sorry that you wasted time but we aren't OS X programmers and we aren't Apple Engineers and we had no idea this bug existed so putting the blame on us is a pretty odd way to take out anger on Apple.

I'm not happy to have to do this (because this really is an Apple bug) but it looks like we can detect this bug by doing `pwd` and `Dir.pwd` and if we detect a difference we can force polling, which should fix the problem.   Would this be sufficient for you?

**Comment by cjerdonek** [comment]
Hey, @envygeeks.  I didn't think I was expressing anger anywhere (I'm certainly not feeling any anger), and nor did I blame Jekyll or Ruby, etc, anywhere (I'm certainly not feeling that either).  Sorry if it came across that way.

**Comment by cjerdonek** [comment]
But to answer your question, something like that would be great, thanks!  Personally, I think a warning with info would be a little bit better (so the user can decide for him or herself whether to use force-polling or to try one of the work-arounds suggested in the livereload page).  Also, that way there wouldn't be a silent change in behavior.  It's also possible that things might still be working even if the case of those two paths differ.

**Comment by envygeeks** [comment]
If the software silently works around a bug doesn't matter, tons of software does it and I'm sure you never notice it, so much so that you probably never notice when a Linux kernel works around an ACPI bug silently, or when Ruby changes the way it behaves on Windows because it's Windows.  That's part of being a piece of software.  Users do not care if we have to work around the fact other programmers are dumb, they care that our software works out of the box.

**Comment by envygeeks** [comment]
Not that we aren't dumb programmers some times, so that was a bad choice of words but it was fitting.

**Comment by cjerdonek** [comment]
One difference about this situation from the examples you gave is that the underlying issue seems serious, and the user could fix it fairly easily if you tell them about it (and maybe complain to Apple, too).

It's probably causing other issues.  For example, when I googled about it, I think this issue can mess with Time Machine backups for the affected folders.  Another problem it seems to cause is that for the past couple years certain folders mysteriously wouldn't refresh in Finder for me if I created files from the command-line.  It was only today that I discovered the likely root cause.  I know it's not your obligation, but you could be doing the user a huge favor.

**Comment by cjerdonek** [comment]
I don't mean to belabor the point, but to give you an idea of the other types of issues this file system issue can cause, here are a couple other reports I've made that are probably caused by this, too:

* https://bitbucket.org/ned/coveragepy/issue/348
* http://bugs.python.org/issue23097

(So you can get a sense of how much time it has caused me :grinning:.)

**Comment by envygeeks** [comment]
I think @jekyll/core should step in here and take a vote because I feel like this is fear mongering.

**Comment by willnorris** [comment]
my two cents: the few times I've forced polling, it has completely pegged by CPU, so I would be concerned with us just silently enabling that.  +1 to printing out a warning to the user and leaving it up to them to use polling if they want.

**Comment by envygeeks** [comment]
So your solution is to not fix the polling problem and to just send a message?  Unacceptable IMO.

**Comment by envygeeks** [comment]
If you're going to send a message suggesting polling because fsevent doesn't work and then polling pegs your CPU, you just rendered the entire message useless you've given them no valid option to get Jekyll to work.

**Comment by envygeeks** [comment]
Let me add, since it seemed I made an ass of myself, I'm not against the message, I'm against the implying that we should send a message instead of fixing the polling problem.

**Comment by willnorris** [comment]
> So your solution is to not fix the polling problem and to just send a message? Unacceptable IMO.

no, I wasn't suggesting that at all.  I think actually trying to fix the problem (perhaps digging into the listen gem and see if there's anything different it can do) is certainly the ideal scenario.  I was responding to the suggestion of silently working around the problem, because (in my experience) it's not a workaround without some trade-offs, and I think the user should be aware that things are running differently.

> If you're going to send a message suggesting polling because fsevent doesn't work and then polling pegs your CPU, you just rendered the entire message useless you've given them no valid option to get Jekyll to work.

I think you **have** given them a valid option to get Jekyll working... you educate them about the force polling option, and suggest they use that if there is a problem.  Looking at some of the bugs @cjerdonek linked to, it doesn't appear that this is always a problem, so forcing the user into polling just because their setup *might* not work seems sub-optimal to me.

**Comment by alfredxing** [comment]
From what I can tell (correct me if I'm wrong), this issue isn't widespread and only happens occasionally (i.e. most of the time, even with mixed case paths, it works).

If this is the case, I don't think we really need to fix it. I believe renaming the folder to lowercase and then back again [fixes the problem](http://openradar.appspot.com/10207999).

**Comment by envygeeks** [comment]
I don't disagree with sending a message, I do disagree with not automatically working around the problem because I've (and I'm sure you have) worked around enough software in my life to appreciate automatic work around's and when I don't get sent on wild goose chases.

And I've never experienced this problem on my MacBook Paperweight so I definitely wouldn't be a big fan of fear mongering so we would have to be careful and address the concerns on our own site.

**Comment by cjerdonek** [comment]
> If you're going to send a message suggesting polling because fsevent doesn't work and then polling pegs your CPU, you just rendered the entire message useless you've given them no valid option to get Jekyll to work.

I know this wasn't in reply to my comment.  But just to be clear, in [my comment](https://github.com/jekyll/jekyll/issues/3624#issuecomment-87297256) I was suggesting that if the check fails, the message include both the option to use `--force_polling` as well as a link to a page with more information about the Mac problem and options to fix if the user is having problems.  One point to note is that if the check fails, we don't know for sure that auto-generation won't work and that a change in behavior is necessary.

Another option is to have `jekyll doctor` do the check (which the user would presumably try if auto-regeneration isn't working).

**Comment by envygeeks** [comment]
I am and will always be against anything that sends people on goose chases without us being direct that we are trying to fix it for them and if we can't then they should try the other options, we are programmers for a reason, to solve problems.  Not to send people to solve problems for themselves.

**Comment by alfredxing** [comment]
@envygeeks Apple engineers are programmers, too. They should be solving their own problems at least, instead of sending other programmers to solve their problems.
I do agree though, however, if this is the first and only case in hundreds or thousands of users, I'd be happy to just refer users with this problem to a helpful documentation page.

**Comment by cjerdonek** [comment]
@willnorris,

> I think actually trying to fix the problem (perhaps digging into the listen gem and see if there's anything different it can do) is certainly the ideal scenario.

If this could also be addressed at a deeper level in relevant dependencies, who would be the right people to contact for those (e.g. which projects and/or issue tracker links)?

**Comment by envygeeks** [comment]
Boo that didn't work the way I expected, /cc @e2 because it seems he is the one mostly maintaining Guard Listen right now.  But the project page is https://github.com/guard/listen

**Comment by envygeeks** [comment]
It looks like he also posted a way for us to get some info to see if it's us or them so can you (@willnorris and @cjerdonek) both post what he asks: https://github.com/guard/listen/issues/295#issuecomment-77533148

**Comment by cjerdonek** [comment]
I started following the debug/troubleshooting instructions, and then noticed that "FSEvent bug" is listed in Section 1: System/OS of [Known Issues](https://github.com/guard/listen/wiki/Troubleshooting#known-issues) (and also again as "Case sensitivity problems" under Section 3: File System, referencing the same FSEvent bug).

But for the record, things worked with `--force_polling`, and without force polling, I couldn't do anything to trigger auto-regeneration (e.g. editing from TextMate, touch from command-line, deleting/creating files and folders from Mac Finder UI).  Here is the debug log as instructed without polling:

    $ LISTEN_GEM_DEBUGGING=2 jekyll serve 
    Configuration file: /Users/chris/dev/codeforsf/sfbrigade.github.io/_config.yml
                Source: /Users/chris/dev/codeforsf/sfbrigade.github.io
           Destination: /Users/chris/dev/codeforsf/sfbrigade.github.io/_site
          Generating... 
                        done.
    I, [2015-03-30T10:41:30.774365 #45492]  INFO -- : Celluloid loglevel set to: 0
    I, [2015-03-30T10:41:30.774456 #45492]  INFO -- : Listen version: 2.10.0
    D, [2015-03-30T10:41:30.782426 #45492] DEBUG -- : Adapter: considering TCP ...
    D, [2015-03-30T10:41:30.782510 #45492] DEBUG -- : Adapter: considering polling ...
    D, [2015-03-30T10:41:30.782540 #45492] DEBUG -- : Adapter: considering optimized backend...
    I, [2015-03-30T10:41:30.805488 #45492]  INFO -- : Record.build(): 0.021843910217285156 seconds
     Auto-regeneration: enabled for '/Users/chris/dev/codeforsf/sfbrigade.github.io'
    Configuration file: /Users/chris/dev/codeforsf/sfbrigade.github.io/_config.yml
        Server address: http://0.0.0.0:4000/
      Server running... press ctrl-c to stop.

I didn't see anything from a quick scan of the issues in the way of plans to address or not address the FSEvent bug.  It seems like one thing the Listen gem could do is have the capability to detect if the bug is affecting the user.

**Comment by envygeeks** [comment]
I think we can hit a compromise here.  We detect the bug and output a link to Listen's help page (since that is one of our direct dependencies mentioning the problem and not an indirect link) and then go to them (Listen) and ask them to kick on polling automatically if they detect the problem since it would be a given that a generic file change software automatically fallback to what it knows works.

**Comment by cjerdonek** [comment]
That sounds pretty good.  A couple comments:

1. Would the "we detect the bug" and the "if they detect the problem" be using the same logic?  It seems like the "we detect the bug" step should be done using a function exposed by Listen.  Also, how different is asking them to kick on polling automatically if they detect the problem from Jekyll calling Listen with force polling if Jekyll detects the bug (e.g. using a detection function exposed by Listen)?

2. Depending on how susceptible the detection logic is to false positives, it seems like it would be good to let the user prevent the force polling.  This would be to address the CPU-pegging issue raised by @willnorris.

**Comment by envygeeks** [comment]
If you want them to handle all the logic and output then please do close this ticket and take the problem to them because at that point it's not our problem (not that it really is right now since it's not our software having problems, directly) otherwise we can provide a near immediate fix on master (well, near immediate as in when somebody has time -- and probably in the next beta, depending on when @parkr wants to release it) and output a help message and worry about removing that check later when they fix theirs (if they fix there's.)

To address 2. that is the listen gems problem to fix, I never said we would enable it automatically on our end, the compromise was letting them enable it and that is literally their problem to address.

**Comment by e2** [comment]
Hi guys, listen/guard maintainer here.

First, Listen basically slaps together a few optimized backends - and offers polling if all else fails.

Just to redirect issues with polling and cpu usage - that's often project/case specific with specific workarounds (e.g. watching way too many files/directories, unnecessarily watching constantly changing log files, database files, generated output files, etc.). There's a LISTEN_GEM_DEBUGGING flag to build a log that can be used for diagnosing (see listen wiki for info). Without output like that I usually can't say much.

Especially with Jekyll, a typical mistake is to watch the project root directory along with the `_site` directory - as opposed to having a `src` directory and just watching that by itself. The default Jekyll layout people have - without a specific `src` dir - is just asking for trouble. You can blame Apple, because there's no way to turn off recursion in rb-fsevent.

Ok, now on towards fsevent stuff.

First I don't have OSX (and I have minimal if any interested in using it). This means I can't even use XCode, let alone test or fix the issue on OSX. You can say Listen is basically one giant workaround for the Mac (OSX support in Listen is actually "half-polling").

I have no idea how to detect the problem - otherwise it wouldn't be a problem to show the message or expose the info in Listen. Technically though, the issue should be detectable within https://github.com/thibaudgg/rb-fsevent.

Specifically, reproduce the issue using this example code:
https://github.com/thibaudgg/rb-fsevent#singular-path

Then, fork and adapt rb-fsevent to at least detect the issue (maybe a workaround is possible?) (rb-fsevent is unmaintained AFAIK).

I can help with the stuff in Listen (just open an issue or PR), but rb-fsevent or FSEvent specifc issues are beyond what I can do.

**Comment by envygeeks** [comment]
@e2 would you be willing to accept a pull request if I were to create detection and send a brief message to the help doc?

**Comment by e2** [comment]
@envygeeks - I have no idea what "detection" here means, so just give it a shot.

**Comment by envygeeks** [comment]
Detecting means detecting (literally) you can detect the problem apparently by doing `pwd` and Dir.pwd and seeing if they show different values and if they do, you are apparently inside of the filesystem bug.

**Comment by e2** [comment]
@envygeeks - my suggestion would be something like this:

1. open an issue in rb-fsevent and cc me there
2. fork rb-fsevent and add failing tests there (probably by creating a path with uppercase characters and trying to watch the downcase version of the path - I don't know). 
3. see if you can create a workaround (instead of just detecting) - ideally, it shouldn't use `pwd` or `Dir.pwd` at all (unless it's the only way to detect it).
4. Depending on whether you have a fix or just detection, I could port those to Listen (especially since it  runs Travis on OSX). Ideally though, rb-fsevent would be fixed.

I don't think Listen can handle anything here, because Jekyll should decide whether to pass the `:force_polling` parameter or not - Listen has no API to "switch" to polling once it's initialized, and it starts the adapter asynchronously anyway. 

If there's a workaround, I'd happily port it to Listen's Darwin adapter - but if it's just detection, Listen isn't designed to switch (after being initialized), and overriding a user's choice (polling when user doesn't expect it) doesn't make sense inside Listen, because Listen is not the "user friendly" app here  - it's Jekyll.

A simpler workaround is to just force polling on Listen on OSX inside Jekyll (and provide non-polling as an option). Sass does this on Windows (for whatever historical reason). If you're getting lots of user problems - polling isn't that much more resource hungry than fsevent for small projects (both do directory scanning). And with a warning given when non-polling is used on OSX, this would be much less work than working around the FSEvent issue.

The polling CPU issues are a Jekyll config problem more of the time anyway - I'd suggest adding a capability to Jekyll to set the LISTEN_GEM_DEBUGGING and log to a file - so those CPU issues can be investigated, and then better detection/warnings/defaults can be implemented in Jekyll.

Listen is less suited than Jekyll for giving advice about project layouts, settings, ignore filters, etc.

**Comment by envygeeks** [comment]
At this time I feel it's best for Jekyll just to output a message (if we can unreliably but probably reliably detect a difference) and link to the Listen doc on the bug.  I will not be putting any effort into a superficial fix in Listen and will simply warn our own users and Link off and let the user decide how they wish to move forward.

**Comment by envygeeks** [comment]
If nobody has any objections I'll implement the message tomorrow:

```
We have detected that we might have trouble using using fsevent on your operating system, you can read https://github.com/guard/listen/wiki/Troubleshooting#known-issues for possible work arounds or you can work around it immediately with --force-polling on Jekyll."
```

**Comment by cjerdonek** [comment]
Thanks a lot for your work on this, @envygeeks.  That sounds great.

**Comment by e2** [comment]
> and link to the Listen doc on the bug

No such thing really. Probably a Wiki page in rb-fsevent is the right place for this. 

Otherwise, I'd prefer an in-depth technical explanation (I couldn't find one technical enough) of the problem - not just users saying "I did this and it worked (or not)".

In short: @envygeeks - *don't link to Listen*, because this is an OSX/rb-fsevent specific issue - and it will only create mass-confusion.

**Comment by cjerdonek** [comment]
@e2 By far the best page on this issue I have found is the LiveReload page: http://feedback.livereload.com/knowledgebase/articles/86239
which is listed twice on the page that @envygeeks is suggesting (which is why I support his suggestion).

The LiveReload page provides links to both rb-fsevents, as well as (a copy of) a bug report submitted to Apple, which are two things you mentioned.  For the technical description you were looking for, I would consult that bug report: http://openradar.appspot.com/10207999

The rb-fsevents page about the issue is not so helpful to users because the comment thread is super long, with the important stuff buried / scattered.

**Comment by e2** [comment]
@cjerdonek - yes, I went through all that. No one has a clue on how to reproduce the problem.

@envygeeks - link to this wiki page I just created: https://github.com/thibaudgg/rb-fsevent/wiki/no-fsevents-fired-(OSX-bug)

> For the technical description you were looking for, I would consult that bug report: http://openradar.appspot.com/10207999

Yeah, I went through it too: no relevant info there, especially this:
```
Steps to Reproduce:
1. not
2. a
3. clue
```

**Comment by envygeeks** [comment]
@e2 Fair enough! I will link to the new page! Thanks for creating a new one.

**Comment by parkr** [comment]
What's the conclusion here? Jekyll doctor check?

**Comment by envygeeks** [comment]
@parkr I'll be adding a message on watch to check if `pwd` and `Dir.pwd` mismatch and sending a warning above, I can add it to Jekyll doctor but it's probably best we throw it in their face, I was meant to add it a few days ago but I've been tied up with new deployments for some people so I had to push it to this weekends backlog.

**Comment by parkr** [comment]
@envygeeks Ok, can you quickly add a new issue for that? This issue is unwieldy.
