### ISSUE TITLE
Build fails if I have two .md files with the same name?

### ISSUE THREAD

**Issue by gergelypolonkai** [jekyll/jekyll#3625]
I have exported the posts of my old blog into markdown files so I can include them in the Jekyll version of my site. I have put the generated files into a `posts/` directory, then **copied** them to `_posts/`, edited it, and did a `jekyll build`. What I got is as follows:

    Configuration file: /home/polesz/Projektek/jekyll/gergelypolonkai.github.io/_config.yml
                Source: /home/polesz/Projektek/jekyll/gergelypolonkai.github.io
           Destination: /home/polesz/Projektek/jekyll/gergelypolonkai.github.io/_site
          Generating... 
    jekyll 2.4.0 | Error:  Is a directory @ rb_sysopen - /home/polesz/Projektek/jekyll/gergelypolonkai.github.io/_site/blog/2011/5/12/ethical-hacking-2011

As soon as I remove the `posts/` directory, the build succeeded. You can check the source tree I’m using [here](https://github.com/gergelypolonkai/gergelypolonkai.github.io/tree/2d3e91b0ccff1ace10966cc2638dc6c6bf19c11a). I was wondering if this causes a name clash, but the error persists if I rename `posts` to `migrated` or `any_random_name`.

**Comment by envygeeks** [comment]
What are the exact file names?

**Comment by penibelst** [comment]
@gergelypolonkai What happens, if you add a trailing slash to the permalink option?

```yaml
# /_posts/2011-05-12-ethical-hacking-2011.markdown
permalink: /blog/2011/5/12/ethical-hacking-2011/
```

**Comment by envygeeks** [comment]
I repeat, what are the exact file names.

**Comment by pathawks** [comment]
It's because Jekyll is trying to process all of the files in `posts/` as well as all the files in `_posts/`

Since each file in `posts/` is also in `_posts/` with the same `permalink` specified in the front matter, the two collide.

If you don't want to include the `posts/` directory, you only need to add this line to your `_config.yml`

```yml
exclude: ["posts"]
```

If you *do* want to include the `posts/` directory, you'll need to do something about all of these duplicate posts fighting for the same permalink. I can't really figure out why you've done it this way.

**Comment by gergelypolonkai** [comment]
Sorry, the identical permalink slipped my eye, you were right (and yes, I
do want to exclude posts from my output, I just didn't want to tamper with
the config yet, although I should have done it…)

**Comment by envygeeks** [comment]
Glad it's fixed, :heart: @pathawks

**Comment by penibelst** [comment]
@pathawks nice.
