### ISSUE TITLE
MathJax is not parsing correctly

### ISSUE THREAD

**Issue by blog1729** [jekyll/jekyll#3651]
MathJax is not parsing correctly in Jekyll site generated by Github, for example, the following image shows how Github renders the page:
![Incorrectly parsed](http://i.imgur.com/x9O6pj2.png)  

Surprisingly, in the local version of the site, Markdown parses correctly. Same example seen after using `jekyll serve` ![correctly parsed](http://i.imgur.com/cuw1U7n.png)

*What can be done to fix this?*

* * *
I'm using [Lanyon theme](http://lanyon.getpoole.com/),  Kramdown parser and the site repository can be found [here](https://github.com/blog1729/blog1729.github.io).

**Comment by envygeeks** [comment]
This is most likely a Github Pages problem, please email support@github.com

**Comment by alfredxing** [comment]
I think the problem is that Kramdown is parsing the underscores inside your math equations as italicized text. This was fixed in `1.6.0`, which is what is being used in the latest versions of Jekyll, but GitHub Pages is still using `1.5.0`, which exhibits this buggy behavior.

For now, you'll have to manually escape your underscores. So instead of this:

````latex
$G_\pi = (V_pi, E_pi)$
````

Use this, and everything should work:

````latex
$G\_\pi = (V\_pi, E\_pi)$
````

**Comment by blog1729** [comment]
@alfredxing I tried your suggestion and it worked! Thank you.
