### ISSUE TITLE
Log display bug? WARNING on line 76: This selector doesn't have any properties and will not be rendered.

### ISSUE THREAD

**Issue by gergelypolonkai** [jekyll/jekyll#3668]
When I regenerate my website’s data, I get the following message:

    ...done in 0.408632576 seconds.
          Regenerating: 2 file(s) changed at 2015-04-20 16:51:10 WARNING on line 76:
    This selector doesn't have any properties and will not be rendered.

As it says `selector`, I was suspecting my SASS sources, but there is no empty selector there. Is there a way to improve this log message so it tells me a file name, too?

**Comment by parkr** [comment]
Warnings are probably just pumped to `stderr`, so I don't know if there is a good way because it doesn't bubble up the call stack like an error would. Definitely a sass/SCSS problem though. :)

**Comment by parkr** [comment]
Ok so it looks like [the node being inspected when the warning is output has no filename](https://github.com/sass/sass/blob/d26e6fa17f55d64278c9f09b5ace5e256e363e3f/lib/sass/engine.rb#L594-L597). That's because [our converter converts just content directly](https://github.com/jekyll/jekyll-sass-converter/blob/master/lib/jekyll/converters/scss.rb#L94-L98), and has no idea what the filename would be. If the node (file) has no filename, it's almost definitely your main SCSS/Sass file, so check line 76 of that file.
