### ISSUE TITLE
tell us what version of ruby to install

### ISSUE THREAD

**Issue by Denubis** [jekyll/jekyll#3675]
Having experience with *other* ruby applications and ubuntu, I'm *very* hesitant of apt-get installing ruby. (and having done so, I know why I had feelings of foreboding)

With that said, it's useful to say "hey, if you're deploying on ubuntu, use such and such ruby to optimally deploy jekyll"

Having tried to do it in the naive fashion, I got  "/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)" which is almost certainly (as a function of prior experience) a function of using *the wrong ruby*.

**Comment by envygeeks** [comment]
We strive to support everything >= 2.0.0 so whatever version you use is up to you, we look for features.  That said, Ubuntu 15.04 fixed a lot of the problems we used to have with Ruby (installing 2.1/2.0 no longer brings in a ton of stuff you don't need or want and no longer brings in 1.9 -- the same applies for Nodejs.)

That said, Jekyll2 (non-master current-stable on Gemcutter) still supports 1.9 (as far as I'm aware we just recently discussed dropping support for it.) but 99% of the time that error is not caused by using the wrong version of Ruby, it's caused by not having the devel-headers.  Try installing `ruby1.9.1-dev` on >= Trusty.

**Comment by Denubis** [comment]
Yeah, the >2.0 is important for servers running LTS (or the note of 1.9.1-dev) . ... it's easy enough to do rbenv install 2.2.0, just confusing *not* to see these details on your "simple install screen". Did I miss a line there with these details? (all too easy).

**Comment by envygeeks** [comment]
The reason we don't mention it is because >= 2.0.0 is not EOL.  At this time Jekyll supports every version of Ruby that is not EOL so there is no reason to mention it, IMO I would prefer people to assume and complain if we have a bug on a non-EOL version of Ruby (but others on @jekyll/core might disagree) but I don't think it would be a big deal to simply just mention "oh, btw we support anything >= 2.0"

**Comment by Denubis** [comment]
Yep yep. That aside would be all that (as a new user) I would be looking for.

**Comment by Denubis** [comment]
Thanks.

**Comment by parkr** [comment]
"We recommend running Jekyll with Rubinius for optimal speed and agility. One day this pair will rule the world."

:trollface:
