### ISSUE TITLE
CLI help for build doesn't mention source or destination

### ISSUE THREAD

**Issue by cfjedimaster** [jekyll/jekyll#3688]
Running jekyll build -h does not show the --source or --destination options.

**Comment by parkr** [comment]
Can you try this with Jekyll 3 beta 3? I believe we fixed this. `gem install jekyll --pre`.

**Comment by cfjedimaster** [comment]
I'm *very* new to gem. I'm presenting on Jekyll in a few days. Is it easy
to return to the production version? (And if so, mind sharing it.)

Also - and this is OT I guess, is there a good guide for what Jekyll 3 will
have?

On Thu, May 7, 2015 at 11:19 AM, Parker Moore <notifications@github.com>
wrote:

> Can you try this with Jekyll 3 beta 3? I believe we fixed this. gem
> install jekyll --pre.
>
> —
> Reply to this email directly or view it on GitHub.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by parkr** [comment]
@cfjedimaster Yes, you'd do `gem uninstall jekyll` and choose the 3.0.0.pre.beta3 version.

**Comment by parkr** [comment]
No guide other than the History.markdown file.

**Comment by envygeeks** [comment]
There should be a meeting amongst the team or somebody should decide what issues should be back ported into the current stable as a new 2.5 release because even if 3.0 will become the new stable we can't expect everybody to be able to upgrade quickly and some issues would benefit those people who don't have time to upgrade immediately.

**Comment by cfjedimaster** [comment]
Speaking as a Jekyll noob, I'd think the expectation would be that if 3.0
is nearly here, and fixes the issue (will test in a sec), then there is no
reason to back port this. A bug fixed in the *release* build is, imo,
sufficient.

On Thu, May 7, 2015 at 2:17 PM, Jordon Bedwell <notifications@github.com>
wrote:

> There should be a meeting amongst the team or somebody should decide what
> issues should be back ported into the current stable as a new 2.5 release
> because even if 3.0 will become the new stable we can't expect everybody to
> be able to upgrade quickly and some issues would benefit those people who
> don't have time to upgrade immediately.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jekyll/jekyll/issues/3688#issuecomment-99986660>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by envygeeks** [comment]
My comment is not just about this issue, it's about *other* issues.

**Comment by cfjedimaster** [comment]
Oh I know, I was speaking generically too. :)

On Thu, May 7, 2015 at 2:53 PM, Jordon Bedwell <notifications@github.com>
wrote:

> My comment is not just about this issue, it's about *other* issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jekyll/jekyll/issues/3688#issuecomment-99995360>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by cfjedimaster** [comment]
I can confirm 3.0 CLI has the better docs. Thanks.

On Thu, May 7, 2015 at 2:55 PM, Raymond Camden <raymondcamden@gmail.com>
wrote:

> Oh I know, I was speaking generically too. :)
>
> On Thu, May 7, 2015 at 2:53 PM, Jordon Bedwell <notifications@github.com>
> wrote:
>
>> My comment is not just about this issue, it's about *other* issues.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jekyll/jekyll/issues/3688#issuecomment-99995360>.
>>
>
>
>
> --
> ===========================================================================
> Raymond Camden, Developer Advocate for MobileFirst at IBM
>
> Email : raymondcamden@gmail.com
> Blog : www.raymondcamden.com
> Twitter: raymondcamden
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by envygeeks** [comment]
Then your comment doesn't hold, major and minor exist for a reason and it's to let systems guys like me know when we should heed to caution and testbed changes or try a dry-run and then full upgrade, with this being a major version many people will fall on the later part of caution and some people won't update for months and some issues probably need be backported for them in the meantime.

Whether that is important is subjective because to me it's not (and because I maintain my own fork where I constantly backport what I need for clients) but having dealt with problems that only get solved in a new major release before I can say it would be annoying if one these issues did affect me and I couldn't immediately test a new major upgrade and it wasn't a feature upgrade or problem tied directly to this branch.

**Comment by pathawks** [comment]
> if 3.0
is nearly here, and fixes the issue (will test in a sec), then there is no
reason to back port this.

So, if somebody can’t upgrade to 3.0 right away, it’s just too bad for them?

**Comment by cfjedimaster** [comment]
Just sharing my opinion. :) In general, my projects support one version
(latest), but if Jekyll wants to support a 2.x and 3.x branch concurrently
than certainly it makes sense to fix it there too. Thanks all.  (And again,
I can confirm fixed in 3.)

On Thu, May 7, 2015 at 3:00 PM, Pat Hawks <notifications@github.com> wrote:

> if 3.0
> is nearly here, and fixes the issue (will test in a sec), then there is no
> reason to back port this.
>
> So, if somebody can’t upgrade to 3.0 right away, it’s just too bad for
> them?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jekyll/jekyll/issues/3688#issuecomment-99997329>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by envygeeks** [comment]
There is no reason to support 2 branches, you backport a few minor changes that fix a few major bugs and then add a message stating that this version is deprecated and upgrade and then move on.  There is never a reason to maintain multiple versions, this isn't OpenSSL where legacy really is legacy because some people are nuts (I've seen some OpenSSL like 10 years old that I've had to port and fixup it was insane and I thought I would turn into a nut.)

**Comment by parkr** [comment]
> I can confirm 3.0 CLI has the better docs. Thanks.

Thank you!
