### ISSUE TITLE
Change code block wrapper element

### ISSUE THREAD

**Issue by goodguyry** [jekyll/jekyll#3738]
I'd like to change the element code blocks are being wrapped in. Rouge/Jekyll is currently wrapping all code blocks in a `<div>`.

```html
<div class="highlight">
  <pre>
    <code class="language-php" data-lang="php">
      <!-- highlighted code here -->
    </code>
  </pre>
</div>
```

Is there a way to change the wrapper element in Rouge through Jekyll? Thank you.

**Comment by parkr** [comment]
We do this: https://github.com/jekyll/jekyll/blob/master/lib/jekyll/tags/highlight.rb#L111-L117

Haven't considered allowing it to be configurable – we'd really rather stay away from configuration whenever possible. Why can this `div` not be there?

**Comment by envygeeks** [comment]
I don't know about @goodguyry but for us (locally on sites I build) we unwrap Jekyll's highlight div with nokogiri and re-insert the pre it into a `<figure>` http://html5doctor.com/the-figure-figcaption-elements/ because all is not well unless we take advantage of HTML5 in it's proper form!

**Comment by kleinfreund** [comment]
To be honest, is there any reason why the highlight class should not be applied to the present tag directly?

**Comment by goodguyry** [comment]
@parkr My use case is exactly the same as @envygeeks.

I can totally understand not wanting to add complexity with configuration. It's a relatively minor issue, so I can throw together a workaround on my end, but is this something you'd consider baking in?

Thanks.

**Comment by envygeeks** [comment]
Switching to just using `<figure>` gets a :+1: from me because it won't break most sites because people generally target `.highlight` directly rather than `div` or `div.highlight` (who would be crazy like that?) so I assume it would be a relatively minor change to support semantics.

**Comment by pathawks** [comment]
From [w3schools.com](http://www.w3schools.com/tags/tag_figure.asp):

> While the content of the `<figure>` element is related to the main flow, its position is independent of the main flow, and if removed it should not affect the flow of the document.

There are times when discussing code when it very much does fall into the main flow of the document. `<figure>` would *not* be appropriate in these situations.

**Comment by kleinfreund** [comment]
Again, do we really need a wrapper element? Adding `figure` should be optional as well as adding `div`. Why is the `highlight` class not added to the `pre` element itself?

**Comment by envygeeks** [comment]
Might I suggest you stop using w3schools? They are absolutely horrible at explaining things, let me point you to a page that gives an example of how to detach flowed content the way books do: https://www.w3.org/wiki/HTML/Elements/figure

What they should have said was "While the content of the <figure> element is related to the main content, it's position can be independent and you should refer to it by label even when directly positioned so that it can remain detached and referenced."

**Comment by envygeeks** [comment]
@kleinfreund we probably provide a wrapper for design convenience not  to mention fixed scrolling and several other benefits that come with a wrapper.

**Comment by kleinfreund** [comment]
@envygeeks I fail to see the benefits here. If you don't want to do some extra positioning of the code block which you would like to use a wrapper for, the pre element itself works just as fine.

**Comment by envygeeks** [comment]
I don't even know what to say to that because anything I say will come out looking like I'm an ass so I'll just let you keep your opinion no matter how wrong it might be.

**Comment by kleinfreund** [comment]
I'm not sure why you're moving this to a personal level now. I just want to know what the mere benefit of using a wrapper for a code block is compared to using the pre element itself as a target for the highlight class.

The default scenario for the `highlight` class is serving as an anchor to apply the CSS rules like `.highlight .c { … }` to. I'll stop that discussion now, since I'm getting offtopic a bit here.

**Comment by envygeeks** [comment]
Save the bullshit I won't fall prey to it.  I'm not new to the internet.

**Comment by envygeeks** [comment]
To address the non-bullshit parts of your statement, what Jekyll does with it and what a designer does with it are two different things.  Jekyll targets .highlight because it's the proper way to do things, why would you blindly target every pre when you should directly target .highlight but a designer would use that wrapper to allow the pre to block out while the div/figure holds the content in proportion (like an iframe with a set width and height -- this used to be common and still is to an extent to keep scroll down.)  Not to mention one should not blindly style a pre tag (actually I wouldn't style a pre tag at all past w+h, position and a few other layout things, at most an inner border targeted from the wrapper.)

There are many benefits to having a wrapper and if you cannot see those I won't explain them all.

**Comment by pathawks** [comment]
That escalated quickly

**Comment by goodguyry** [comment]
Aaaaanyway....

Glad to see this has at least *some* support. Thank you.

**Comment by envygeeks** [comment]
I do want to apologize to @kleinfreund I was not trying to be personal and instead of saying that I got angry at the thought that I was.  Most anything I say in a programming capacity is never going to be a personal.

**Comment by envygeeks** [comment]
Is there any consensus on what we should do here, this ticket is starting to get stale and we are soon coming to a final 3.0.0 release so we should probably make a decision on what to do.

/cc @jekyll/core

**Comment by parkr** [comment]
Would it be better to just add a `figure`? It's supported everywhere: http://caniuse.com/#search=figure

**Comment by envygeeks** [comment]
@parkr the div would become the figure so that nobody has to modify their source since figure is a block level element like div except it has an attached context for most people nothing at all would need to change really.

**Comment by parkr** [comment]
@envygeeks I think `div` ~> `figure` is good. :+1:

**Comment by goodguyry** [comment]
@envygeeks This is exactly what I was hoping for. Adding `figure` in place of `div`.

**Comment by envygeeks** [comment]
I'll get it done sometime today then.  Unless you would like to submit a pull for it.

**Comment by goodguyry** [comment]
While I appreciate the offer, and as simple a change as it seems to be, without knowing Ruby I don't feel comfortable doing it myself. Thanks though.

**Comment by envygeeks** [comment]
This is now fixed.

**Comment by goodguyry** [comment]
Thank you!
