### ISSUE TITLE
Jekyll 安装问题和升级问题

### ISSUE THREAD

**Issue by wsgdrfz** [jekyll/jekyll#3741]
![7485b1fd-2715-4ddd-b1db-bb7bd61b6e38](https://cloud.githubusercontent.com/assets/9074358/7859297/22e50030-0572-11e5-93d4-2e73eeea2a45.png)
安装Jekyll的时候出现了问题 然而我以为是没有升级的缘故 然而 还是有问题 求解答

**Comment by envygeeks** [comment]
I'm sorry you are having trouble but this is not RubyGems support, you can request help from https://github.com/rubygems/rubygems/issues however perhaps I can guide you, there is no need for a "--system" flag when doing Gem install because it defaults to a global install, try again without the "--system" flag and if you continue to have problems with the SSL_connect then please file a ticket with https://github.com/rubygems/rubygems.org/issues

**Comment by parkr** [comment]
Also check out https://github.com/jekyll/jekyll/issues/1409 in the meantime :)
