### ISSUE TITLE
themes.jekyllrb.com

### ISSUE THREAD

**Issue by ariestiyansyah** [jekyll/jekyll#3749]
We are concern about Jekyll themes so I am asking about creating themes.jekyllrb.com as the theme collection of jekyll. We are discussed about this in this issue[1].

If you can provide this domain and add me to the jekyll github repo I'll help manage all the thing about the jekyll themes.

I am waiting good news from you :D
cheers,

[1] https://github.com/mattvh/jekyllthemes/issues/118

**Comment by envygeeks** [comment]
In my opinion (and this is only my opinion) this should be grouped with the upcoming plugins - in theory even though they are different it would be drastically efficient and awesome to have them both under the same umbrella, making your life easier,) I've got a prototype started and this week sometime I should have it completed but it'll still need to make the rounds of approval.

**Comment by ariestiyansyah** [comment]
We know that plugins and themes is different, if we need to have them both under the same umbrella it'll make user complicted because it have different functions.

for example, if we need use plugin we need  _plugins, _config.yml and Gemfile be used simultaneously only that's different with themes.

So in my opinion just create themes.jekyllrb.com and plugins.jekyllrb.com (if need)

Can't wait your prototype :D

**Comment by envygeeks** [comment]
I don't believe your reasoning one bit because the UX can sort out the difference between the two and so can the search UX.  We are not hosting your data anyways (we do not have that kind of money) we are simply acting as an index to your data so in the case of a theme it would go to a Github repo, in the case of a plugin it would link to the Github Repo and a the Gem Home Page (since Jekyll is moving towards jekyll-plugin-name.gem -- see many of the recent Jekyll plugins from Jekyll itself.)

**Comment by ariestiyansyah** [comment]
Ok I understand now, I am referenced this issue to another issue which talk about jekyll theme

At this time we are requested subdomain (themes.jekylrb.com) but if not possible we can buy domain like themejekyll.org or anything and hosted it on github pages. Which one you prefer?

**Comment by Phlow** [comment]
I suggest http://jekyll-themes.org/

**Comment by envygeeks** [comment]
Do what you want, but it won't be an official project unless @parkr agrees on it.
