### ISSUE TITLE
Disable Emoji on footnotes

### ISSUE THREAD

**Issue by leo** [jekyll/jekyll#3751]
I don't know if this problem is related to the markdown-converting engine or if Jekyll has something todo with this (please correct me, if I need to post this somewhere else).

**The problem is:** When visiting a post that contains footnotes on iOS, the reversed arrow at the end of each footnote will be turned into an Emoji (take a look at the attachments).

I think we could solve the problem by replacing `&#8617;` with `&#8617;&#xfe0e;`. Doing so will always show the reversed arrow instead of an Emoji on iOS.

### How it looks
![how-it-looks](https://cloud.githubusercontent.com/assets/6170607/7901950/3f1e3046-07a2-11e5-8f92-4cd48ec7f033.png)

### How it should look (please ignore the font-size)
![how-it-should-look](https://cloud.githubusercontent.com/assets/6170607/7901953/46650884-07a2-11e5-85f6-42f2cb75d010.png)

**Comment by kleinfreund** [comment]
This is neither an issue of a Markdown engine or Jekyll itself. This is the operating system (iOS in this case) using the _emoji_ you see as a replacement for the character you show in the second screenshot.

That's why using more special Unicode characters can be problematic at times. Namely when OS manufacturers screw with already existing ones instead of relying on the private use area.

A solution? You could replace the character in question with one that is not used by (especially mobile) OSes.

**Comment by leo** [comment]
Hehe, that's not how I meant it.

I'm aware of the fact that iOS is responsible for converting those Unicode chars into graphics. However, the markdown engine (or Jekyll) is at fault for generating the HTML `.footnotes`-element that contains the reversed arrow (there's no position in my template where I could change it, it's part of the engine).

Also, why are you providing me with another solution? :blush: I already posted one up there (replacing the old unicode string with another one that prevents the conversion).

Anyway — is there a way to replace the string **before** Jekyll outputs it? (So that I don't need to use JS or anything else that's front-end based).

**Comment by kleinfreund** [comment]
Oh, welp, I completely misread that. Sorry for that. Do you have information on how appending `&#xfe0e;` interacts with the character before it?

**Comment by envygeeks** [comment]
Replace the converter and correct the output is your only solution IMO (https://github.com/jekyll/jekyll/tree/master/lib/jekyll/converters/markdown) Other than asking the maintainers of the libraries to fix those problems. I don't necessarily think it's our job to backtrack and correct the behavior of the markdown processor (except in certain cases) and this really isn't one of those cases.  We are not the ones outputting this and we are not the ones who should be fixing this and doing so tightly couples us to their state which is bad for business.

I want to also mention that your pulls on those libraries are broken because you neglected to test.

**Comment by leo** [comment]
No problem! :smile:

As you can see, I already reported this problem on the repo's of markdown engines used by Jekyll. Hopefully someone will merge them.

Sorry for disturbing you, now I know where the problem lies.
