### ISSUE TITLE
ERROR: IPv6 address must be 16 bytes during gem install

### ISSUE THREAD

**Issue by egig** [jekyll/jekyll#3752]
by `gem install jekyll`, I simply get this:
```
ERROR:  While executing gem ... (ArgumentError)
    IPv6 address must be 16 bytes
```
I use Ubuntu 14.04

**Comment by envygeeks** [comment]
Please file this ticket with RubyGems at https://github.com/rubygems/issues as it is their software that is causing this error... not Jekyll directly or itself.  The easiest way to work around this is to disable IPv6 on the system but I would also file a ticket and give them much more information than you have given us (such as the address -- if you feel like it -- or an example otherwise,) Ruby Version and Gem version.

**Comment by egig** [comment]
Thanks for the response.

Disable IPv6 raises error too:
`IPv4 address expects 4 bytes but 1 bytes`
