### ISSUE TITLE
Does jekyll support subdomain -> subdirectory? 

### ISSUE THREAD

**Issue by serious198706** [jekyll/jekyll#3757]
I mean:
http://music.example.com will show the content at https://username.github.io/music.

**Comment by eugene2candy** [comment]
i got the same question!! how to solve it ??

**Comment by HoBi** [comment]
It is a thing of GitHub, isn't it?

Take a look here https://help.github.com/articles/adding-a-cname-file-to-your-repository/

**Comment by envygeeks** [comment]
Yes, this is a Github thing because a user is only allowed on sub-domain and that is their username.github.io and any project that wishes to have a website is grouped under said username into a folder (even if there is a pre-existing repo username.github.io - afaiw.)

I don't know if CNAMES work properly for this but @HoBi already pointed to a doc that seems to imply that it does work.  If you need more help on this please use https://talk.jekyllrb.com because this communication medium (ticket system) is for bugs only.

**Comment by serious198706** [comment]
Brilliant. Thanks.
