### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by NicoHood** [jekyll/jekyll#3764]
Using the latest Ubuntu 64 bit, installed ruby, rubygem and node.js.
Using java8 by default, java7 also installed.

Installed like this:
```
#installation via repositories
sudo apt-get install ruby-full nodejs

#manual download from website:
sudo ruby setup.rb
```

`sudo gem install jekyll` fails with this error
```
RDoc::Parser::Ruby failure around line 1 of
vendor/pygments-main/tests/examplefiles/ruby_func_def.rb

Before reporting this, could you check that the file you're documenting
has proper syntax:

  /usr/bin/ruby1.9.1 -c vendor/pygments-main/tests/examplefiles/ruby_func_def.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

	(NoMethodError) undefined method `name' for #<RDoc::RubyToken::TkLPAREN:0x0000000461ed48>

ERROR:  While executing gem ... (NoMethodError)
    undefined method `name' for #<RDoc::RubyToken::TkLPAREN:0x0000000461ed48>
```

**Comment by envygeeks** [comment]
Update your Ruby version.  Not only is 1.9.1 unsupported by Ruby itself but it's unsupported by us.
https://github.com/jekyll/jekyll/blob/stable-2-5/jekyll.gemspec#L10

**Comment by NicoHood** [comment]
And how if the ubuntu package is outdated? Do I have to uninstall it first and download from their website? This should be described somewhere that you need a newer package than the stable ubuntu package.

**Comment by envygeeks** [comment]
@NicoHood On principle I must ask you move your question to https://talk.jekyllrb.com where I'll be more than glad to help you update your Ruby on Ubuntu (I am a Debian/Ubuntu user myself -- for now) but unfortunately we no longer accept generic questions unrelated to actual bugs in Jekyll on this bug tracker.  I'm sorry to do this to you but this is so that we can keep our bug tracker clean and unfilled with generic questions.

Thanks.
