### ISSUE TITLE
Problem with Jekyll installation

### ISSUE THREAD

**Issue by Awake99** [jekyll/jekyll#3789]
I have the latest versions of Ruby and RubyGems installed on my Mac OS X Yosemite. When I type in the following command:$ gem install jekyll, I receive an error message (Could not find a valid gem 'jekyll' (>= 0) in any repository). Then when I enter the command: $ gem source -a http://rubygems.org, I get the message (Error fetching http://rubygems.org:
	Errno::ENOMEM: Cannot allocate memory - connect(2) (http://rubygems.org/specs.4.8.gz))

I have 8 GB of RAM on my Mac. I would appreciate any assistance.

**Comment by envygeeks** [comment]
If you have a firewall then please disable it and see if it works, if it does then you have a misconfigured firewall... this could also be a problem with your internet (or even theirs in rare cases) but past this suggestion I'm sorry there is nothing we can do to help you.  If you continue to have issues the proper place to ask about this is at RubyGems: https://github.com/rubygems because the problem surfaces from their software but this is most likely an issue with your internet or firewall and not their software.

**Comment by parkr** [comment]
If you're in China, try #1409.
