### ISSUE TITLE
NOT support osx 10.11

### ISSUE THREAD

**Issue by bunnyblue** [jekyll/jekyll#3803]
Building native extensions.  This could take a while...
ERROR:  Error installing jekyll:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
creating Makefile

make "DESTDIR="
make: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin15/ruby/config.h', needed by `yajl.o'.  Stop.

**Comment by parkr** [comment]
This is a problem on all systems, not just on 10.11 as far as I can tell. You need the Ruby development headers in order to install native extensions. Install RVM or rbenv and install a Ruby version to use via those ruby version managers in order to get around this.

Can you also try `gem install jekyll --pre` and see if that works without any modifications?

**Comment by bunnyblue** [comment]
same error /
System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
creating Makefile

make "DESTDIR="
make: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin15/ruby/config.h', needed by `hitimes.o'.  Stop.
