### ISSUE TITLE
The limit of Jekyll? 

### ISSUE THREAD

**Issue by joacimmelin** [jekyll/jekyll#3831]
So I may have hit the limit of how many posts Jekyll can handle. At least that's what it seems like. My blog has as writing this 6934 posts in the _posts directory. The last post seems to have been the straw that broke the camels back since I can't build Jekyll anymore. I get this error: 

Jekyll 2.5.3 | Error:  undefined method `gsub' for {"options"=>{}}:Hash

I have no idea what this means, but if I remove a couple of posts from the _posts directory, Jekyll builds just fine. Granted - it takes 24-25 minutes to build on my Core i7 retina Macbook Pro with 16GB RAM and pretty decent flash storage (running OS X 10.10.4), but still it builds. 

Still - this presents me with a pretty urgent problem: what do I do about it?  Change my blogging platform (rather not do that)? 

Thanks in advance for any advice you may have. 

Joacim

**Comment by envygeeks** [comment]
Is there source available?

**Comment by joacimmelin** [comment]
You can have my entire site in a zip archive if you want to play around with it.

**Comment by envygeeks** [comment]
That would be great, because I have a feeling this is more to do with Ruby than it is with us and my largest site is about 2K some odd files and has no problems but having a site as large as yours would help me clean up some of our source and improve the efficiency of it it also stands as a good starter for my want to implement Liquid drops to solve some of these problems I forsee in large sites like yours.

**Comment by joacimmelin** [comment]
You want the posts alone or the entire thing?  Where do I send it?

**Comment by envygeeks** [comment]
How big is the archive? It would be preferable to have everything so I don't have to fill in anything but depending on how big it is when it's archived depends on how I'll need to retrieve it because email will be slow as dirt but something like Google Drive (you can email the GDrive link to me if you don't want it public, my email should be public on my GH profile.)

**Comment by parkr** [comment]
> Jekyll 2.5.3 | Error: undefined method `gsub' for {"options"=>{}}:Hash

Can you run it again with `--trace` and print where this is happening? Looks like a bug in either your post or our code's handling of your post. This isn't an OOM error or anything like that.

**Comment by joacimmelin** [comment]
Building the site again. It's been at it for almost 30 minutes and the _site directory is still empty except for the RSS feed file.  Hasn't crashed though but I'll get back to you with any trace output I get.

**Comment by joacimmelin** [comment]
I got tired of waiting and did some investigating. 

A bit more info: I have been trying this new theme (Lanyon) that I really like. One thing led to another (don't ask...) and suddenly my current theme and site would not build, but the new one did with a few test posts. So I moved all my posts to the new site and also wrote a new story about the new look of the site. 

And the new one would not build properly, instead it threw the error message on the screen or, as I witnessed tonight, just kept on building and building. 

I decided to start over after and do some more testing and the thing with Lanyon is that it builds a separate directory for each page of posts. It also builds a yearly folder with each month and date under it (ie /_site/2015/06/30/name of post/index.html).  

My guess is that it simply is too much for Ruby, or the file system, or both (or maybe none of them, what do I know) to handle close to 7000 posts at once. 
So I added them year by year and granted, the build time gets longer by every year added but it has built the site with articles from 2012 - 2015 so far.  

I'm sorry if I created much fuss over nothing (or maybe something) but if it's one thing I've learned from this is that any theme I'm gonna work with in the future will be tested with a couple of thousand posts just to make sure it works. 

Maybe some guidelines for theme developers would be a good idea?

**Comment by envygeeks** [comment]
Well, it would still be nice to test it out and see if there is anything we can do in Jekyll itself I might do that myself but in the meantime, why not try Jekyll3 and see if that helps a bit, we do have incremental regeneration, which does a great job for the most part and should help you out at least a tiny bit with building considering how much RAM you have.

It is well known that Ruby doesn't handle large memory payloads very well in some scenarios and it's not to do with the memory but in your case it could be that we are obliterating the GC which can sometimes surface in weird edgy ways (which is why large sites often adjust the GC in Ruby to be less aggressive.) There is a lot that could be going on.

@parkr is right that this isn't an OOM issue, your kernel would have killed it if it was (at least if you are on Linux or OS X) but this could be a GC surface (probably not, I would have to see it myself to determine that) but more importantly this probably isn't an IO issue because systems and modern HDD/SSD's queue IO and so do modern kernels, you would have just been uber slow (at least for Linux -- I don't have much experience with a saturated IO pipe on OS X -- and not because Linux is worse but because I'm a Linux user so of course I experience everything here first!)

But, at the end of the day, try Jekyll3, maybe that will help a bit with incremental regeneration in that perhaps it can surface the cause faster after the initial build, I don't know if it can or will because I've never seen it used on such a large base before.

There are things we can do to significantly improve our performance though and Liquid::Drops are one of those things that we should and can be doing to improve this situation and this is something that was discussed before but got pushed off for other things but it's definitely still a front-thought for me to get done.

**Comment by joacimmelin** [comment]
Gonna try Jekyll 3 now!

**Comment by joacimmelin** [comment]
Oh yeah @envygeeks I emailed you a dropbox link last night. Did you get it?

**Comment by envygeeks** [comment]
@joacimmelin I did get it and will be playing with it to see what I can do next week.

**Comment by joacimmelin** [comment]
Hi @envygeeks had any time to look at this?

**Comment by envygeeks** [comment]
I haven't but it's still in my active backlog to get to as soon as I have a chance.

**Comment by alistaircom** [comment]
Any update on this?  I have a site I would like to convert to Jekyll that has a large number of posts, but I'm concerned about the potential limit discussed here.

**Comment by parkr** [comment]
@alistaircom If you're using Jekyll v3.x, try running with `--incremental`.
