### ISSUE TITLE
Jekyll 2.5.3 Issue

### ISSUE THREAD

**Issue by MOH117** [jekyll/jekyll#3850]
I keep getting this when i run ( jekyll serve ) 

Windows 8.1 (64bit)
Ruby 2.2.2p95
Python 2.7.10

![untitled-1](https://cloud.githubusercontent.com/assets/5793194/8665209/39cc4efa-2996-11e5-9cf1-91d4770d02f5.jpg)

![untitled-2jpg](https://cloud.githubusercontent.com/assets/5793194/8665218/4f8e6d4a-2996-11e5-8b42-e850909c5d93.jpg)

can anyone help me pls ?

**Comment by envygeeks** [comment]
Hi,

I don't remember if this has been published yet but please have a look here: https://github.com/jekyll/jekyll/blob/0125af80a39841aea1d55838eb99064ce2352b39/site/_docs/windows.md#installation this seems to be a known issue with Windows and hitimes and the work around seems to be to roll back to Ruby 2.1 instead of 2.2.

**Comment by MOH117** [comment]
Downgrading to ruby 2.1 solved the problem
thanks @envygeeks
