### ISSUE TITLE
Jekyll's future posts command line switch is kind of weird

### ISSUE THREAD

**Issue by nateberkopec** [jekyll/jekyll#3882]
So, it seems that Jekyll's default value for the `future` option is `true`. So, by default, posts with a future date are published. OK, fair enough, I might not have chose that value, but you've probably thought about it longer than I have.

What's weird, though, is that there's also a command line switch `--future`. So, by default, `jekyll build --future` doesn't do anything - `future` is already true.

Is it weird to have a switch that, by default, does nothing? Are the only people getting use out of the `--future` switch those of us who set `future` to false in our configs? Is there some way to `jekyll build --future=false` that I'm missing?

**Comment by alfredxing** [comment]
I agree! Having the `future` options is not very useful IMO, especially since we already have `published`...

There is also a comment beside the `future` option in Configuration saying that it should be removed, and I think now is a good time to do it since it will technically break compatibility.

/cc @jekyll/core

**Comment by envygeeks** [comment]
I'm :+1: on dropping the option to false by default.

**Comment by nateberkopec** [comment]
@alfredxing I want to disagree with removing `future` entirely, because `future` enables a very cool workflow for me:

1. I write a post with a date in the future in the `_posts` folder. With `future` set to false, it is not built into the site. 
2. I have a script running every hour that rebuilds my site and uploads it to S3.
3. Thus, when the posts date comes around, my post is automatically added to the site.

That sort of publish-at-this-time workflow is, AFAIK, not possible with just `published` or the current drafts feature.

@envygeeks Is there any backwards-compat concerns for changing default config options like this? We could be dropping posts from people's sites, right? Just wanted to bring it up.

**Comment by parkr** [comment]
`future` should definitely default to `false`... it was probably just overlooked in a previous release. Would you update that for us? Then the flag will make more sense... :smile:

**Comment by nateberkopec** [comment]
Sweet. Can do.

**Comment by fizerkhan** [comment]
+1

**Comment by mykagrove** [comment]
+1
With the current version it always seems to publish posts with future dates no matter what I do.
That is to say, files named similar to: ```2017-01-01-test-post.md```
Compiling with any of:
```
jekyll build
jekyll build --future
jekyll build --future false
```

**Comment by nateberkopec** [comment]
Fixed in #3892.

**Comment by d3netxer** [comment]
so I spent a lot of time trying to figure out why some of my posts were not displaying. There was no warning when running Jekyll that my posts were not being published. Therefore I support for future being set to true as default.

**Comment by mykagrove** [comment]
Logic dictates that posts set with future dates shouldn't be published until those dates (by default).
However, suggesting that jekyll outputs a warning is a good idea.

**Comment by petemoore** [comment]
@d3netxer @mykagrove @nateberkopec Yes, I got tripped up on this too, since the `date` field in the post seems to be UTC, but my local timezone is currently UTC+0200. The warning would be awesome, as users east of GMT (e.g. most of Europe and Asia) will hit the same issue if they don't realise the date in the posts is UTC, and set the post time to their current local time. Users in America probably will not notice as they lag behind UTC, but for others, troubleshooting this without a warning can be a real time waster. Should we file a separate issue for logging the warning?
