### ISSUE TITLE
Design updates for 3.0 for `jekyll new` theme

### ISSUE THREAD

**Issue by jglovier** [jekyll/jekyll#3921]
I'd like to make some design updates to the `jekyll new` theme. Mainly, I think we can take the typography to the next level, and add some more advanced styling for things like the next article section, etc.

## Typography

I'm thinking for typography to go for something more Medium-esqe and pair a nice bold sans-serif typeface for headings with a nice serif typeface for body copy. I've used Open Sans (headings) and Lora (body copy) on my own site for such typography, and it's very readable. 

One consideration is that this proposal would mean moving from default webfonts to using the Google Fonts API (still with the webfonts as a fallback). I don't have any performance concerns about this personally because a) this is intended to be a starter blog for the average person, which means high traffic performance concerns are negligible, and b) Google Fonts API is about as performant as you can get for a third party typography system (Open Sans was served [18.5 billion times](https://www.google.com/fonts/specimen/Open+Sans#stats) in just the last week, which means many uses are likely to have it cached anyway).

## Layout

- Add options for heading images

## Config

- Add an option to display article reading times

## New new stuff

- Add ability to pass the `--boilerplate` flag to get a design-agnostic, bareboness Jekyll setup (basically just basic file and directory structure and markup without any styling).

## etc

Thoughts? Other ideas?

**Comment by alfredxing** [comment]
I think improving the typography and making the theme a bit cleaner is a good idea.

For a sans-serif heading, I'd recommend Roboto, Open Sans, and [League Spartan](https://www.theleagueofmoveabletype.com/league-spartan). Raleway is good too.
For a readable body font, Libre Caslon Text, Libre Baskerville, and Source Serif Pro.

I'm kind of iffy on adding things like header images and reading times, since those aren't necessarily core features that all of our bloggers would want and use (better left for plugins/themes?)

I'm also a teensy bit wary because you bring up Medium in particular. I think its design is great, but I think the default Jekyll theme needs to maintain its own identity instead of adopting the nowadays quite generic (and I think you phrased this very well) Medium-esque style. It's always nice running into a blog using the current default theme and being able to recognize it immediately.

Just some of my thoughts! ¯\_(ツ)_/¯

**Comment by envygeeks** [comment]
I was cool up until you suggesting using Google fonts URL by default.  Then I jumped off the ship.

**Comment by alfredxing** [comment]
@envygeeks Anything in particular against Google Fonts?

**Comment by envygeeks** [comment]
It's Google, and Google loves to track you across the web and their fonts API is an easy way to do that.  Some will argue they don't, some will argue they do, some assume that Google is an advertising company with some very high powered brains that can easily track with Google fonts.

**Comment by alfredxing** [comment]
Well, in that case, I run an open-source webfont service, [Brick](https://github.com/alfredxing/brick). No tracking or whatever, and should be quite reliable and fast (same CDN network as GitHub). But I'm probably biased.

**Comment by envygeeks** [comment]
I'm fine with Google to be honest (to an extent.)  As long as I can disable it, I'm fine with brick too.

I think we can have multiple options here.  People like my client (who I posted that comment about Google for) who don't want anything to do with Google and would probably opt to use Brick or their current CDN... we only host their data and they use the default Jekyll theme. People like me who like to provide their own integrity and would rather host it themselves, and people who just don't care and like to waive their hands in the air and will go with whatever we default to.

**Comment by envygeeks** [comment]
Maybe `--fontcdn=brick|google|false`

**Comment by alfredxing** [comment]
:+1:

**Comment by akhyarrh** [comment]
I would choose custom fonts as optional

**Comment by parkr** [comment]
Thanks for submitting your ideas, @jglovier! I have two concerns:

> One consideration is that this proposal would mean moving from default webfonts to using the Google Fonts API (still with the webfonts as a fallback).

I saw your tweet to Tom the other day and have given this a bit of thought. I'm not particularly fond of the idea of relying on a third-party service like Google Fonts. To me, this starter website should help you get one step closer to a website you want, without having to remove things you don't. One thing I saw with Octopress 2.0's classic theme was that while people liked it, there was a _lot_ of removing things they didn't want. I would love to keep this starter site drop-dead simple for newbie web developers – it shows off the power of Jekyll's abstractions but contains things you don't want. I'd rather `--boilerplate` be the default, and maybe we have something floofy if folks want it.

I would also like the default `jekyll new` theme to be the same with WiFi on and with WiFi off. Shouldn't require an internet connection.

> Add an option to display article reading times

What's the value-add here?

**Comment by geraldb** [comment]
FYI: Just my two cents. The more themes the better. I've also put togehter the "missing Jekyll theme package manager" that is, [drj/drjekyll](https://github.com/drjekyllthemes/drjekyll).   For example, if you put together a new theme (hosted on github lets say /starter25) than you simply install it using $ drj new starter25   - if you want to add some configuration questions upfront e.g. use google font service (yes/no) etc. you can use a Mr. Hyde wizard script (and the [mrh/mrhyde](https://github.com/mrhydescripts/mrhyde)) tool e.g $ mrhyde new starter25.  Keep it up. Great themes. Cheers.

**Comment by jaybe-jekyll** [comment]
I appreciate and am excited by a solid, functional, instructional, reliable, reasonable, modest `jekyll new` default theme.

Having a basic, straight-forward, comprehendible default theme provides value for the end users and the community which supports them.

Many times a new user has, self-assured they've troubleshooted impeccably, declared, "...because jekyll...", and are legitimately frustrated. After the following exercise, they generally, a) figure out the problem they had, themselves, and b) spend time exploring the default theme to [swiftly] identify a few best practices and gain a baseline understanding and opinion about what jekyll stands for:

`cd ~ && jekyll new mytest && cd mytest && jekyll serve`

Does it work? Yup. This is a common troubleshooting technique on irc://#jekyll@freenode. It proves a working ruby and jekyll environment, quickly and easily, and reassures the end user things can, and do work, so time to refocus. Point--

My points and opinions are in favor of a clever and functional default theme, but one without any external dependencies by default... particularly the third party in discussion.

I like the idea of a basic default image with the ability to configure a replacement image. Per-page replacement of said image would be possible. i.e. `{{ page.image.header }}`.

I really like the current jekyll theme approach to using CSS for the adaptive menu versus javascript... and those types of approaches to design and function.

**Comment by parkr** [comment]
In summary: always happy to bring new updates into the site, but let's keep dependencies to the World Wide Web to 0 if possible. :smile:

**Comment by parkr** [comment]
Looks like this discussion has wrapped up. Looking forward to a PR @jglovier! We're looking to release Jekyll 3.0 around the beginning of September, probably before Labour Day.

**Comment by jglovier** [comment]
Sorry I've been completely MIA here! Been heads down focused on some work projects the last few weeks. Lots of great input here, thanks everyone for the thoughts.

@parkr I've clearly missed your desired goal for 3.0 of early Sept, but how far away am I from the actual release? If it's right around the corner, at this point I might just punt on changes until a bit later. But if it's been pushed back several weeks, then I could try to get a PR in with a few updates.

**Comment by parkr** [comment]
> @parkr I've clearly missed your desired goal for 3.0 of early Sept, but how far away am I from the actual release? If it's right around the corner, at this point I might just punt on changes until a bit later. But if it's been pushed back several weeks, then I could try to get a PR in with a few updates.

@jglovier So have I! I just have one more PR to do, but it's a whopper and I keep putting it off to spend time with friends and family. Feel free to work on something. If it doesn't go into v3, we'll put it in v3.1!

**Comment by jglovier** [comment]
@parkr right on! :zap:
