### ISSUE TITLE
Adopt a code of conduct.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#3924]
/cc @jekyll/owners @jekyll/core

I like many in the community think we need a code of conduct but I like a lot of the community think that some parts of the Open Code of Conduct by the TODO group is a bit ambiguous and hostile so in keeping with good faith I think we should adopt the https://github.com/rails/rails/blob/master/CODE_OF_CONDUCT.md (except name it CONDUCT.md or COC.md.) I am proposing that we adopt a conduct like a lot of the community but pick one that everyone can agree on.

**Comment by envygeeks** [comment]
I am not saying that Jekyll really needs on either because like @parkr pointed out last night, our community is actually quite peaceful most of time but it's still nice to have one even so.

**Comment by mattr-** [comment]
I agree that we should have one.

**Comment by parkr** [comment]
:+1:

I like the CoC that Rails adopted. We can block folks from our org so maybe we could say something like "If a user continuously violates the code of conduct, they may be blocked from interacting with any or all repositories owned by the "jekyll" organization at any maintainer's discretion." Or maybe something like that but shorter.

**Comment by gynter** [comment]
@parkr imo You can do that too, because You are the maintainer of the project.

This Is my personal opinion, but I see code of conducts as oppression of freedom of speech. On the other hand for me it's elementary to consider ethnic and sexist slurs, extreme trolling, harassment etc inadmissible behavior. One does not need rules for a common sense.

**Comment by envygeeks** [comment]
As many people much wiser than me used to tell me growing up:

```
You are free to say what you like but when you are in my house that does not mean you are free from consequence for what you say.  Freedom does not pardon consequence and freedom must be used wisely lest you lose it.
```

**Comment by lnwdr** [comment]
Since the "free speech" concern came up, as in literally **every other CoC discussion before**: https://xkcd.com/1357/

No, a code of conduct does not interfere with your right to express yourself. It simply doesn't.

And regarding the "we don't need a CoC because we are already awesome to each other" argument: It's not primarily about how nice you are in the existing community. It's about who is not part of a community because they regularly experience, let's say, less-than-awesome behaviour. Those are the people who benefit from a CoC, not the ones who already feel like everything is ok.

**Comment by jaybe-jekyll** [comment]
I see a code of conduct as assistive for both participants and administrators, and sets expectations of both conduct in advance... but also advanced notice of potential consequences should one choose to not adhere.

Most arguments and suits justify they their positions by stating the rules/details were not known/posted. An analogy would be the inability to prosecute someone on your land when you've failed to provide proper postings/notice on said land.

A code of conduct doesn't have to be ridiculous, but instead reasonable, common sense, helpful, and provide legitimate advanced notice of policy.

**Comment by ttimsmith** [comment]
:+1:

**Comment by parkr** [comment]
Everyone happy with the language in #3925?
