### ISSUE TITLE
Test all current gems with both Jekyll-3 and Jekyll-2 before release.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#3945]
Right now we have a lot of gems, some of them get heavy usage but currently the only Gem we test with Jekyll 3 (AFAIW) is the new `jekyll-feed`.  We should test these gems with Jekyll 3 through and through on the public CI before releasing Jekyll into the wild with possible broken plugins under our umbrella.

- [x] jekyll-assets (Was always Jekyll 3 ready)
- [x] jekyll-feed (https://github.com/jekyll/jekyll-feed/pull/53)
- [x] jekyll-sitemap (https://github.com/jekyll/jekyll-sitemap/pull/83)
- [x] jekyll-gist (https://github.com/jekyll/jekyll-gist/pull/19)
- [x] jekyll-import (https://github.com/jekyll/jekyll-import/pull/227)
- [x] jekyll-sass-converter (https://github.com/jekyll/jekyll-sass-converter/pull/41)
- [x] jekyll-docs (https://github.com/jekyll/jekyll-docs/pull/4)
- [x] jekyll-archives (@alfredxing?) (https://github.com/jekyll/jekyll-archives/pull/48)
- [x] jekyll-compose (https://github.com/jekyll/jekyll-compose/pull/31)
- [x] jekyll-paginate (https://github.com/jekyll/jekyll-paginate/pull/32)
- [x] jekyll-redirect-from (https://github.com/jekyll/jekyll-redirect-from/pull/72)
- [x] jekyll-mentions (https://github.com/jekyll/jekyll-mentions/pull/22)
- [x] jekyll-watch (https://github.com/jekyll/jekyll-watch/pull/30)
- [x] jemoji (https://github.com/jekyll/jemoji/pull/19)
- [x] jekyll-textile-converter (https://github.com/jekyll/jekyll-textile-converter/pull/1)
- [x] jekyll-coffeescript (https://github.com/jekyll/jekyll-coffeescript/pull/13)
- [x] jekyll-opal (https://github.com/jekyll/jekyll-opal/pull/8)
- [x] github-metadata (https://github.com/jekyll/github-metadata/pull/21)

**Comment by parkr** [comment]
Great idea. Let's start a checklist and make sure we have passing builds for each.

**Comment by parkr** [comment]
Will do this week. I don't think we can tackle all of those plugins before the release... Hopefully #4058 will mitigate issues.

**Comment by envygeeks** [comment]
I'll start pushing out PR's this week as well since I've nothing better to do.  Should ease up some of the strain, I vote that once they pass the test just push it since most of them are drastically simple.

**Comment by parkr** [comment]
> I vote that once they pass the test just push it

Absolutely :+1:. Some will be converted to hooks later, probably./

**Comment by Stargator** [comment]
Added a PR for jekyll-paginate at jekyll/jekyll-paginate/pull/32 for migration to Jekyll 3.

**Comment by Stargator** [comment]
Added a PR for github-metadata at jekyll/github-metadata/pull/20. No changes needed, but the builds passed using Jekyll 3. Though the PR would help if anything should break later down the road.

**Comment by Stargator** [comment]
Just as a quick update for the check list above:

jekyll-import, jekyll-docs, and jemoji were tested and updated by @parkr with jekyll/jekyll-import/pull/227, jekyll/jekyll-docs/pull/4, and jekyll/jemoji/pull/19, respectively.

Additionally, he added Jekyll 3 coverage for jekyll-textile-converter with [jekyll/jekyll-textile-converter/commit/f406bd](http://github.com/jekyll/jekyll-textile-converter/commit/f406bde53d89adb689812fe7a863f82c67ba2904)

jekyll-sass-converter and jekyll-compose were tested and updated by @envygeeks with jekyll/jekyll-sass-converter/pull/38 and jekyll/jekyll-compose/pull/29, respectively.

jekyll-mentions was tested and updated by @benbalter with jekyll/jekyll-mentions/pull/22

The only gem left outstanding is jekyll-opal since classifier-reborn does not depend or use jekyll.

**Comment by envygeeks** [comment]
Hulk: backlog +jekyll/jekyll ++priority:high
