### ISSUE TITLE
Layout of blog is messed up when open index.html in browser but fine when using jekyll serve

### ISSUE THREAD

**Issue by Steve-luo** [jekyll/jekyll#3982]
I just installed jekyll and created a new blog, after tying jekyll serve, which works fine, I opened the index.html in _site folder but the layout is all messed up. What went wrong?

<img width="1280" alt="screen shot 2015-09-19 at 5 55 13 pm" src="https://cloud.githubusercontent.com/assets/8736917/9975682/a21f07d6-5ef7-11e5-80b1-08a424bd2dfe.png">

**Comment by kleinfreund** [comment]
This is not a bug. Check the source of the `index.html` you just opened. You'll see that the CSS file is referenced with a slash prepended. The browser looks for a file **relative** to the root directory (i.e. `/`). This works as expected when running a local server or uploading the files to a web server, because the root directory there is the same as the project directory (where the css directory is located). However the root directory on a operating system is not the same as your project directory.

You can test this by removing the slash and opening the generated index file again. It'll work. The solution is using the local server started by `jekyll serve`.

**Comment by Steve-luo** [comment]
@kleinfreund Thanks I get it now.

**Comment by parkr** [comment]
Thanks, @kleinfreund!
