### ISSUE TITLE
gem install jekyll failed on Mac OS X 10.11

### ISSUE THREAD

**Issue by chmaynard** [jekyll/jekyll#3984]
$ gem install jekyll
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

Mac OS X 10.11 (15A282a)
Xcode 7.0 (7A220)

**Comment by jaybe-jekyll** [comment]
I prefer...

`$ gem install --user-install --bindir ~/bin --no-document --pre --verbose jekyll`

Then... i.e....

- `$ ~/bin/jekyll new ~/Sites/testjekyll`
- `$ ~/bin/jekyll serve --watch --verbose ~/Sites/testjekyll`

And or add `~/bin` to your `$PATH` shell variable to avoid requiring full path to `jekyll`.

Installing this way installs for and within the user account [only], instead of system-wide.

**Comment by envygeeks** [comment]
This is not a Jekyll bug, please ask your question at https://talk.jekyllrb.com as this medium is for bugs.

**Comment by chmaynard** [comment]
@jaybe-jekyll Brilliant, thanks.

Successfully installed jekyll-3.0.0.pre.beta8
17 gems installed

FYI, I think Apple has locked down the system directories in OS X 10.11, so the easy-install instructions on http://jekyllrb.com may need to change. Even using sudo won't work.

**Comment by chmaynard** [comment]
@envygeeks Is there a process for reporting documentation bugs?

**Comment by envygeeks** [comment]
What do you think is a bug @chmaynard?

**Comment by chmaynard** [comment]
The easy-install instructions for jekyll don't seem to work in OS X 10.11 (El Capitan). Apple plans to release this new version of OS X in a few weeks, so you folks might want to investigate.

**Comment by envygeeks** [comment]
If you are using RVM or Rbenv to do the install ( -- they installed ruby and rubygems -- ) via non-root userland you'll need to file a bug with them, if you are using system Ruby, it never worked the way you expected it to because you need to `sudo` to do system installs.  If it did work before that then that is a glaring security bug for OS X.

**Comment by envygeeks** [comment]
We also hint at t he need to sudo in the troubleshooting: http://jekyllrb.com/docs/troubleshooting/#installation-problems it could use a reworking though and if I recall somebody submitted or is going to submit the changes.

**Comment by chmaynard** [comment]
@envygeeks I know almost nothing about Ruby, so please excuse my ignorance. It sounds like I must have used "sudo gem install" at some point in the past. I'm now wondering what will happen when the average user tries to install jekyll on a clean copy of OS X 10.11. Maybe I'll try that myself.

**Comment by fulldecent** [comment]
If the install instructions do not work on Mac, it should not be stated that this project supports Mac OS X.

**Comment by envygeeks** [comment]
Your comments help us none @fulldecent provide more information or refrain from commenting.

**Comment by fulldecent** [comment]
My sarcasm is used to illustrate that this issue should remain open.

This approach worked for me with OS X 10.11 15A282b. However, the other Mac advice at http://jekyllrb.com/docs/troubleshooting/#installation-problems did not work.

    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew install ruby
    gem install jekyll

This is contrast to Yosemite where I needed to use sudo:

    sudo gem install jekyll

Since I no longer have a "stock" system, it would be helpful if someone else who just installed could validate this approach.

**Comment by chmaynard** [comment]
William,

Thanks for your advice. I hadn't thought about using Homebrew to install Ruby. That makes perfect sense because Homebrew will install Ruby into /usr/local instead of /Library/Ruby, which I think is off limits when Apple SIP is enabled.

Craig

**Comment by chmaynard** [comment]
### Summary to Date

The installation problem occurs because OS X ships with a copy of Ruby in /Library/Ruby, a directory which is owned and controlled by the OS. In past versions of OS X, a new jekyll user could use `sudo gem install jekyll` to install software into this directory. That may not be possible in OS X 10.11, because Apple is now using System Integrity Protection (SIP) to further restrict write access to /Libary.

@fulldecent found a good work-around for 10.11:

    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew install ruby
    gem install jekyll

The big drawback with this work-around is that the user needs to install Homebrew and Ruby before installing jekyll.

**Comment by chmaynard** [comment]
It would be helpful to re-open this issue to give it more visibility.

**Comment by chmaynard** [comment]
I just tried the work-around described above and it worked flawlessly.

**Comment by fulldecent** [comment]
@chmaynard Thanks for your help. Is your system a stock upgrade or install? And have you installed Xcode command line tools before doing this?

I just want to track all the factors here.

**Comment by chmaynard** [comment]
I'm an iOS developer, so I use both Xcode and Homebrew all the time. We definitely need to refine your procedure by trying to install jekyll on a partition with a clean copy of El Capitan.

**Comment by chmaynard** [comment]
#### Checklist

- [ ] Install the Xcode command line utilities `xcode-select --install`
- [ ] Install the Homebrew package manager (instructions at http://brew.sh)
- [ ] Prepend $PATH with `/usr/local/bin` e.g. `export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
- [ ] Install the latest version of Ruby `brew install ruby`
- [ ] Install the latest version of Jekyll `gem install jekyll`

**Comment by chmaynard** [comment]
Please add the "Documentation" label to this issue.

**Comment by chrisfinazzo** [comment]
@envygeeks, I'm almost certain I have a branch where I was working on this at some point, will take another look...

@chmaynard, In the past, I can recall discussions with the Core team regarding how the installation of Ruby should be handled. While installing in the manner you suggest does solve the problem of putting Jekyll's Ruby in an isolated environment, I have had fewer gem conflicts when using a version that is slightly older than what Homebrew will give you. To facilitate that, might I suggest pointing to any of the various Ruby managers out there and people can choose which one suits their needs. Not as an outright requirement, but perhaps an "Information" block [here][].

[here]: http://jekyllrb.com/docs/installation/#optional-extras

This probably will go away as 3.0 makes many things "opt-in", but it's still something to consider.

Lastly, to provide a definitive answer regarding SIP and available directories, the following information is directly from Session 706. The only change since then is (I think) `Applications/Utilities`, but as I am not running the GM build, I cannot verify this. As it has been disclosed [elsewhere][] and El Capitan is scheduled to ship next week, this is likely considered public knowledge. 

[elsewhere]: http://www.macworld.com/article/2948140/os-x/private-i-el-capitans-system-integrity-protection-will-shift-utilities-functions.html

<img width="927" alt="screen shot 2015-09-23 at 10 24 27 am" src="https://cloud.githubusercontent.com/assets/1534882/10103991/46f492a4-6375-11e5-8ba5-3dc48841c492.png">

**Comment by chmaynard** [comment]
@chrisfinazzo Thanks for the info about SIP. I wasn't sure about `/Libary`, so that's good news. Apple is advising developers to stop using `/Library` for kernel extensions, so I assumed that applied across the board.

I still think that Homebrew is a good option for two reasons: sudo isn't required, and it doesn't disturb Apple's native Ruby software in `/Library/Ruby`.

I believe Homebrew can install previous versions of Ruby. What version would be best for Jekyll?

**Comment by chmaynard** [comment]
> To facilitate that, might I suggest pointing to any of the various Ruby managers out there and people can choose which one suits their needs.

These are package managers for Ruby?

**Comment by parkr** [comment]
@chmaynard RVM, rbenv, chruby, etc.

**Comment by jaybe-jekyll** [comment]
Have a few moments and want to reiterate, and re-share-- in a summary format, that installing `jekyll` (`gems` in general) by leveraging the `gem` executable capabilities to isolate ruby gem installations works out of box with OS X 10.11 for example with [only] the following, with the added benefit of leaving the system completely alone, and isolating `jekyll` and its dependencies to the current user/group [only]:

> OS X XCode Command Line Utilities
>> Can be installed via calling a developer command such as `git` and following prompts.

> With OS X' native `ruby` and `gem`:
>> `gem install --user-install --bindir ~/bin --no-document --pre --verbose jekyll`

> export PATH=$PATH:~/bin

```bash
$ jekyll --version
jekyll 3.0.0.pre.beta9

$ ruby --version
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
$ which ruby
/usr/bin/ruby
```
If System-wide meddling with a tinker-hostile environment is not your interest, and or you don't want/need custom/specific Ruby environment(s) (`rbenv`, `chruby`, `RVM`, ...), then a --user-install approach may be worth considering. And it works with stock OS X (`10.11 currently`).

**Comment by chrisfinazzo** [comment]
@chmaynard, My rule of thumb has been to follow the base version in `.travis.yml`, and thus far, I've had no issues that I couldn't figure out. The versions there have been tested and we know they work.

@jaybe-jekyll Are you sure? I would be concerned that when 10.11.1 comes out (which might be sooner rather than later), the Installer either does `chown` to whatever it finds in this directory or blows away the contents entirely.

The message from Apple seems to be pretty clear: If you have things that you compile yourself, put them in `usr/local` under the appropriate subdirectory. Otherwise, proceed at your own risk.

**Comment by jaybe-jekyll** [comment]
@chrisfinazzo I am sure.

My agreement with Apple does not permit me to openly discuss details of beta or GM releases.

However, I can state the information and experience I provided was performed within such an environment.

Regarding "the installer" performing `chown`, and concerns about how it works, see the documentation for `gem` and you'll find corresponding information about each switch and option.

This approach, summarized, can be described as:

> "Using OS X 10.10+ system `ruby` and `gem`, and without requiring `homebrew`, kindly install `jekyll` (pre-release version even!) with `gem` and tell `gem` to install it as and for my/this/current user [only], within the user' ~ ($HOME), and place binaries in users ~/bin. Thanks! (Oh- and leave OS X system alone!) :)

**Comment by envygeeks** [comment]
Most people's home directories look like a garbage dump.

**Comment by chrisfinazzo** [comment]
See #3999.

**Comment by debbarmaonit** [comment]
" sudo gem install jekyll " gives me -

While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/jekyll

What do I do?

**Comment by chrisfinazzo** [comment]
@debbarmaonit The short answer to your question is that you can't set `usr/bin` as the install location on 10.11 because [SIP][] prevents it. There are [instructions][] on Jekyll's website for how to resolve this issue.

If however, you are familiar with either [rbenv][] or [RVM][], you can instead create an isolated environment that doesn't conflict with the system's version of Ruby and then install with just `gem install jekyll`. 

[SIP]: https://support.apple.com/en-us/HT204899
[instructions]: https://jekyllrb.com/docs/troubleshooting/#jekyll-amp-mac-os-x-1011
[rbenv]: https://github.com/rbenv/rbenv
[RVM]: https://github.com/rvm/rvm

**Comment by charlesfayal** [comment]
I ended up using
sudo gem install jekyll and it worked perfectly

**Comment by aaroncampbell2311** [comment]
I'm using Mac El Capitan version 10.11.5 and sudo gem install jekyll worked just fine.

**Comment by regetskcob** [comment]
I'm also running into this issue on current macOS Mojave.

```bash
$ sudo gem install jekyll
Building native extensions.  This could take a while...
ERROR:  Error installing jekyll:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20181125-42813-1vdjstq.rb extconf.rb
creating Makefile

current directory: /Library/Ruby/Gems/2.3.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR=" clean

current directory: /Library/Ruby/Gems/2.3.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR="
make: *** No rule to make target `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin18/ruby/config.h', needed by `ruby_http_parser.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/http_parser.rb-0.6.0 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/http_parser.rb-0.6.0/gem_make.out
```

I've recently installed `ruby` and `rbenv` successfully using `brew`, but the error is still there.

**Comment by TheTechAngle** [comment]
Hi I got the same error as you did, likely because of macOS's system integrity protection.
This fixed it for me
1) Install homebrew
2) brew install ruby
3) You will need to have ruby first in your PATH run
echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.bash_profile
4) source ~/.bash_profile
5) sudo gem install jekyll

**Comment by matthieuviglietti** [comment]
On Mojave, you can also desactivate temporarly SIP MAC protection, by restarting in recovery mode and use terminal with
csrutil disable; reboot

to re-eanble it csrutil enable; reboot

**Comment by liamrosenfeld** [comment]
This worked for me (on Mojave):

1. Install homebrew:
      `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" `

2. Update ruby:
      `brew install ruby`

3. Set ruby in your PATH:
      `echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.bash_profile`
      `source ~/.bash_profile`

4. Install Jekyll into a folder that isn't protected by SIP:
      `sudo gem install -n /usr/local/bin/ jekyll﻿`

The docs probably should be updated to reflect these workarounds in the near future.

**Comment by MalayaliRobz** [comment]
what worked for me was:
open /Library/Developer/CommandLineTools/Packages/

Run the package macOS_SDK_headers_for_macOS_10.14.pkg

**Comment by coooliang** [comment]
`sudo gem install -n /usr/local/bin jekyll bundler`

**Comment by andreas-eg** [comment]
Solution for me was  https://github.com/ffi/ffi/issues/611#issuecomment-364621532

> 
$ brew install automake autoconf libtool
$ gem install ffi -v '1.9.21'
