### ISSUE TITLE
[GH-Pages] Kramdown syntax highlighting does not work?

### ISSUE THREAD

**Issue by Jeeppler** [jekyll/jekyll#3996]
Github-Pages switched to [Jekyll 2.2.0 and Kramdown as default Markdown engine] [1]. 
Kramdown uses three tilde for fenced code blocks:
~~~
def what?
  42
end
~~~

which is actually easier to write on most European keyboards, because ` are used for accents.
Additionally Kramdown supports highlighted fenced code blocks: 

~~~ ruby
def what?
  42
end
~~~

the problem is that Jekyll's standard Kramdown Markdown engine does not support the language highlighting. 

This plugin allows the above described syntax: https://github.com/mvdbos/kramdown-with-pygments
but the problem is it does not work on GH-Pages, because plugins are not allowed. 

Yes, I know there is a liquid tag for syntax highlighting, but this looks ugly in raw markdown files:
{% highlight ruby %}
def what?
  42
end
{% endhighlight %}

really ugly.

[1]: https://github.com/blog/1867-github-pages-now-runs-jekyll-2-2-0

**Comment by envygeeks** [comment]
This is an upstream issue, file it there.

**Comment by Jeeppler** [comment]
@envygeeks can you explain that a little bit more in detail?

**Comment by envygeeks** [comment]
It means it's an upstream issue, if Kramdown does not support Pygments like you wish, or Github Page does not support Coderay/Pygments if Kramdown it's their issue not ours.  We do not control either, we use their libraries, we do not program them.

**Comment by envygeeks** [comment]
On the Github Pages part, we don't control them because they are independent of us.  We do things to help them but ultimately they will do what they wish on their systems.

**Comment by Jeeppler** [comment]
@envygeeks this feature of Kramdown is in their official reference as example: https://github.com/mvdbos/kramdown-with-pygments. The question is, why this feature is not supported by the default Kramdown Markdown engine?

**Comment by envygeeks** [comment]
I can't speak for Github, maybe @benbalter can provide more insight but I'm to assume it's because Kramdown uses CodeRay and Github Pages does not provide it: https://pages.github.com/versions/.  Really your options here are to use Pygments.rb with triple grave and RedCarpet or `{% highlight %}` with Kramdown.

**Comment by parkr** [comment]
@Jeeppler We do have (and I believe GitHub Pages has as well) support for backtick code blocks. The docs you reference use the tilde `~` instead of the backtick. This should definitely be available on GitHub Pages. If you can show us a repo where it doesn't work, maybe we can help further.

**Comment by Jeeppler** [comment]
@parkr http://jeeppler.github.io/ I mean it works, but there is no syntax highlighting for this code:

~~~ bash
h="Hello World!"
echo "$h"
~~~

but here in the comments it works fine.

**Comment by parkr** [comment]
Ok ok ok now it makes sense. Our syntax highlighting with `~~~` is non-existent. We had to monkey-patch backtick code blocks and we have no interest in adding support for the tildes.

**Comment by Jeeppler** [comment]
Like I stated above backtickets are hard to write on European keyboards and it is part of the Kramdown reference. Furthermore the work is already done by this guy and his small plugin:
https://github.com/mvdbos/kramdown-with-pygments

But I can also understand that you don't want to add support for tildes.

PS: On a German keyboard layout you have to press 6 times the ` key for 3 backticks

**Comment by envygeeks** [comment]
@Jeeppler sure, it's supported by Kramdown, but only if you provide CodeRay, Github pages chooses not to provide CodeRay... and this is where it becomes an upstream problem... File a ticket with Kramdown and ask them if they can also support Pygments.rb and then in theory it should start working once Github pages updates to that new version.  One could argue it's a Github problem, but in the back of my mind it's not a Github problem because Github chooses to use Pygments.rb which is what they use internally and what they know and support.  It's really a feature request for Kramdown.
