### ISSUE TITLE
JSON files with UTF-8 are not sent as UTF-8

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#4003]
May be a problem with the WEBrick server – should send charset as utf-8 by default, unless `encoding` is set in config.

Continuation of https://github.com/Shopify/liquid/issues/654 by @d3netxer

**Comment by parkr** [comment]
@d3netxer, would you post a screenshot of the response headers from the inspector in Chrome?

<img width="337" alt="screen shot 2015-09-29 at 8 15 20 am" src="https://cloud.githubusercontent.com/assets/237985/10168577/489191a6-6682-11e5-86df-e617ba8d6a69.png">

**Comment by envygeeks** [comment]
I'd like to see both request and response to be honest.

**Comment by d3netxer** [comment]
yes, here are the request and response headers. Thanks

<img width="1079" alt="screen shot 2015-10-01 at 1 35 09 am" src="https://cloud.githubusercontent.com/assets/2665840/10213557/be04b214-67dc-11e5-9a46-e2939e9df3ba.png">

**Comment by envygeeks** [comment]
I wonder if that's a webrick bug, it should be responding with a charset=blah but it didn't...

**Comment by d3netxer** [comment]
Here is a screenshot of the request and response from the live site, which is showing the quotes correctly. I don't know if it because it is using the apache server, or it is a slightly older version. I'll probably be updating the site with the latest changes in a few days so I'll see if the live site still displays the quotes or not.

<img width="1077" alt="screen shot 2015-10-01 at 8 35 52 am" src="https://cloud.githubusercontent.com/assets/2665840/10220711/79e77cac-6817-11e5-99f8-e7c2e723a9a3.png">

**Comment by envygeeks** [comment]
Nginx and Apache will both always respond with a charset if it can, this is a bug in webrick, what we should figure out is if it's something we can work around or if we need to take it upstream as something we can't fix.

**Comment by parkr** [comment]
I don't see a charset in the response from my nginx server. Maybe webrick has the same issue?

**Comment by stephenhowells** [comment]
I had to tell nginx to explicitly send all json as utf-8. This still seems like a webrick issue though. I'm not sure if this is already possible but maybe we could have a config option to use thin or puma instead of webrick when running `$ jekyll serve`. My current work around is to have all my Jekyll sites in a Vagrant box accessible via nginx. :neckbeard:

**Comment by parkr** [comment]
We should just default to UTF-8, no config option needed.

**Comment by Crunch09** [comment]
Is this still an issue? Wasn't able to reproduce it with jekyll 3.1.2

**Comment by envygeeks** [comment]
It is not because we enforce the users encoding by default.
