### ISSUE TITLE
Suggest an overwriting warning.

### ISSUE THREAD

**Issue by hanbang-wang** [jekyll/jekyll#4023]
I was building a page with jekyll on my server, but I just accidentally typed in a wrong directory and it just overwrited anything in that dir. All my things just gone in a second, and it is hard to recover them. I know it's my fault to use root permission but I really want an overwrite warning for writing into a non-empty directory.
A lot thanks.

**Comment by parkr** [comment]
Oh man, I'm sorry to hear that! It always sucks to love your files.

What command did you use?

**Comment by hanbang-wang** [comment]
jekyll build -d /var/www (it should be a subdirectory in www), so you know...

**Comment by envygeeks** [comment]
We would have to find a way to differentiate internally over whether or not you set the directory or we set the directory because that message hinders normal behavior (re: _site) by warning because it probably will never be empty after the first build, unless you clean.

**Comment by hanbang-wang** [comment]
Yes, I'm just suggesting to have a warning like
{% highlight bash %}
"The directory you are going to write is not empty, overwrite? (n)"
{% endhighlight %}

**Comment by envygeeks** [comment]
And that's exactly what I'm trying to avoid, the (n) implies it's a prompt which would get annoying for a standard Jekyll user.   Actually, it's quite unintuitive with our own default folders.

**Comment by envygeeks** [comment]
Let me clarify, by avoid I mean only prompt for a non-standard write folder, I do like the idea in general of asking if it's fine to overwrite, just not if we are writing to `./_site`

**Comment by parkr** [comment]
I think if you use `--destination` and it's full, it's not unreasonable to fail and say "Use `--force` to overwrite."

**Comment by envygeeks** [comment]
I don't know if that's bad UX or not because by nature we overwrite.  I'm not against it, I just don't know if that's bad UX because of the nature of what we do.  Ultimately though on our systems I think I would much prefer a mixture between the two ideas if `--force` is sent assume yes otherwise ask like @hanbang-wang suggested.

**Comment by hanbang-wang** [comment]
I think --force will be great. Enter a --force after the destination directory allows you to double-check it.

**Comment by Leo2807** [comment]
Shouldn't we use something like `--force-overwrite` or `-f overwrite`  instead of `--force`? There might be some other things in the future that one'd like to force.

**Comment by envygeeks** [comment]
`--force` is a standard switch used by standard applications across the board.  `-f whatever` is not (normally `-f whatever` is used for files.)  `--force-overwrite` would be fine, but it's longer, I'm neutral on that subject. We do not force many actions (actually this the first I recall) so a conflict can be resolved later... 

On a note: whether or not you add something to our commands is not something we should consider when making our switches.  Not to be mean, but we cannot possibly foresee what you might do and we don't necessarily want to support changes you make (*that is a personal stance and is not reflective of the entirey of everybody else* -- because it's your job to support those changes.)

**Comment by Leo2807** [comment]
@envygeeks thanks for the feedback. I have to admit `-f something` isn't good. Also, on the matter of detecting if a folder was filled by jekyll, maybe we could put a `.jekyllout` file in every output. That's just my 2c though, I can't `--force` you to do it. :wink:

**Comment by hanbang-wang** [comment]
That's a great idea! @Leo2807
