### ISSUE TITLE
SIMHash as an alternative to LSI (LSI is very slow)

### ISSUE THREAD

**Issue by bbalet** [jekyll/jekyll#4024]
Hi,

Running LSI is very slow even if you've installed GSL lib on your system.

Have you ever considered SIMHash as an alternative ? The approach is different:
* For each post, we calculate a fingerprint (i.e. a 64-bit or longer Hash that is representative of the content).
* Getting the list of related posts is faster because it is an ordered list of the distance between these  fingerprints (the lower, the closest).

We can compare the fingerprints using various methods :
* Hamming distance.
* Kernighan method.

There are many implementation of this algo. Below is a link to a Ruby implementation (with which you can generate a longer hash in order to improve the precision).

https://github.com/bookmate/simhash

I see many advantages:
* It is 10.000x faster.
* Some people are not able to get LSI working (eg for Github pages) so they manually compile a list of related entries.
* Many people are relying on a plugin that calculates the related posts based on tags.
* You'll be no more dependant to any external library.

Unfortunately, I don't know Ruby but I can help by testing.

**Comment by envygeeks** [comment]
In cases like this I like to take the provide the proof it's faster and better and backwards compatible with our current solution or provide a plugin.   As far as LSI not working on Github pages, we are not Github pages so we cannot dictate to them what they do on their servers so you'll need to file a ticket with support@github.com and ask them to support LSI.

**Comment by parkr** [comment]
@bbalet This isn't on the radar right now, but if you create a plugin, we could add support for it.

**Comment by bbalet** [comment]
As I mentionned, I don't know ruby and this language seems very complicated.

I've found another static generator written in golang that's very similar to Jekyll. As I know go, I've made a PR for Simhash support and will migrate my websites to this system as it is faster.

I guess that you can close this issue as you have little interrest in this approach.

**Comment by parkr** [comment]
@bbalet If you know Go, you can definitely learn Ruby – I know both and I'd argue Go is more complicated! Perhaps that's just a matter of personal opinion.

> I guess that you can close this issue as you have little interrest in this approach.

Interest is not the issue here; we are most certainly interested in speeding up LSI. That said, the Core team works on Jekyll in their spare time and therefore doesn't have time to write every line of code for every feature requested. We need some help from programmers like you! You understand clearly the issue at hand. All our LSI code is in [lib/jekyll/related_posts.rb](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/related_posts.rb), and it uses the [classifier-reborn](https://github.com/jekyll/classifier-reborn) library to handle the actual computation. Feel free to reach out with any questions if you have them! We're happy to help, but we can't be expected to write all the code :)

Thanks!

**Comment by envygeeks** [comment]
Sometimes Go is harder but for the most part Ruby's syntax is much easier.  I agree, if you learned Go then Ruby will be a breeze to learn.

**Comment by bbalet** [comment]
Hi,

If you want to evaluate simhash algo, I've created a minimal Jekyll plugin that calls a program developped in go:
https://github.com/bbalet/gorelated#how-to-use-it-with-jekyll

It creates a JSON file into `_data` folder that you can use with Liquid tags. It computes the list of 5 related articles (you can change this limit) for 100 articles in 50ms on my old i5-2500k.

**Comment by parkr** [comment]
@bbalet Great! Just submitted a PR to you: https://github.com/bbalet/gorelated/pull/1
