### ISSUE TITLE
files named .htm end up as index.html.htm (3.0)

### ISSUE THREAD

**Issue by rdyar** [jekyll/jekyll#4082]
I have a page, the file name is order-now.htm

In the front matter I have the permalink as: permalink: /order-now/

When I build it it creates a folder named order-now (correct) but inside the file is named index.html.htm instead of just index.html.

It worked fine in jekyll 2.x, apparently I named some of my files .html and others .htm. Anything that I named .htm is broken.

This seems like the same thing as this persons shtml problem: https://talk.jekyllrb.com/t/shtml-weirdness/1367/6

This is on Win 10.

**Comment by parkr** [comment]
@XhmikosR found this, too. In extensionless URL's we still write the extension out to the filesystem (i.e. `/my-page` is written as `/my-page.html`) and were aggressive in adding the output extension.

@envygeeks I believe it's caused by this line: https://github.com/jekyll/jekyll/blob/a0f3860cfa8a4f22e0d55991f9c535f8e41597ec/lib/jekyll/page.rb#L139

Just needs a regression test and a fix for the case that you specify a permalink that doesn't end with the converter's output extension (e.g. ends with `.php` instead of expected `.html`).

**Comment by XhmikosR** [comment]
Just for reference, my currently failing use case is

**file**: external-filter-crash.md
```yml
---
layout: default
permalink: /external-filter-crash.php
---
```
results in **`external-filter-crash.php.html`** with Jekyll v3.0.0; it works fine with v2.5.3.

It's not the most common use case that's why no one caught it earlier, but, hey, at least I'm not the only one :P

*Hoping for a quick bugfix release*

**Comment by envygeeks** [comment]
I'll have a fix on master today or tomorrow you can play with @XhmikosR

**Comment by XhmikosR** [comment]
Thanks, I hope I'll manage to test it with bundle using the master branch.

**Comment by XhmikosR** [comment]
Sorry for bumping, any luck with this?

**Comment by envygeeks** [comment]
@XhmikosR Sorry I haven't had time to look at it.  I will try to have a look today, but tomorrow I've made time to make all my pulls for Jekyll so that we can get a release for 3.0.1 quickly.

**Comment by XhmikosR** [comment]
Thanks, I'll wait for the fix!

**Comment by XhmikosR** [comment]
Any news on this?

**Comment by parkr** [comment]
@envygeeks Have you had time to look at this?

**Comment by XhmikosR** [comment]
*bump* Any news?

**Comment by envygeeks** [comment]
@XhmikosR yes, I am working on this problem this afternoon now that 3.0.1 is out.  I haven't had time as this was low in the backlog for me but I will be getting it done today.

**Comment by XhmikosR** [comment]
I wonder if this applies to my use case with .php. Is that fixed too?

**Comment by XhmikosR** [comment]
https://github.com/mpc-hc/mpc-hc.org/pull/58#issuecomment-159450803

So this doesn't fix my use case for `php` files which works with v2.5.

**Comment by parkr** [comment]
@XhmikosR Ok. Would you mind opening another issue? This one's title points to something slightly different than yours. Thanks!

**Comment by XhmikosR** [comment]
#4182
