### ISSUE TITLE
Installing on Ubuntu

### ISSUE THREAD

**Issue by markmaas** [jekyll/jekyll#4108]
Looking at the documentation an installation would so simple as:

```
~ $ gem install jekyll
~ $ jekyll new myblog
~ $ cd myblog
~/myblog $ jekyll serve
```

but the first command already bummed out with first: 
```
mark@enterprise:~/Documents$ gem install jekyll
The program 'gem' can be found in the following packages:
 * ruby
 * rubygems
```

makes sense, so I installed ruby.

But then:
```
mark@enterprise:~/Documents$ gem install jekyll
Fetching: liquid-3.0.6.gem (100%)
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /var/lib/gems
```

Ok, so now:
```
mark@enterprise:~/Documents$ sudo gem install jekyll
Fetching: liquid-3.0.6.gem (100%)
Fetching: kramdown-1.9.0.gem (100%)
Fetching: mercenary-0.3.5.gem (100%)
Fetching: safe_yaml-1.0.4.gem (100%)
Fetching: colorator-0.1.gem (100%)
Fetching: rouge-1.10.1.gem (100%)
Fetching: sass-3.4.19.gem (100%)
Fetching: jekyll-sass-converter-1.3.0.gem (100%)
Fetching: rb-fsevent-0.9.6.gem (100%)
Fetching: ffi-1.9.10.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing jekyll:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:4:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/ffi-1.9.10 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/ffi-1.9.10/ext/ffi_c/gem_make.out
```

Which means I need to install ruby-dev. So I do: `mark@enterprise:~/Documents$ sudo apt-get install ruby-dev`

After which I'm still left with:
```
mark@enterprise:~/Documents$ gem install jekyll
Fetching: jekyll-3.0.0.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /var/lib/gems/1.9.1 directory.
```

Guys, this should be simple. This is not simple. And I'm on a very bland Ubuntu 14.04.

Plus; it should have been a `apt-get install jekyll` anyway. Either in the default package repo's or via a ppa. this whole `gem install` and `pip install` stuff is pointless and error prone.

"Now get off my lawn" ;-)

**Comment by envygeeks** [comment]
It's more like you are on my lawn and then blamed me because you ran into a tree but no worries, you ran into my tree so I will try and make sure you are okay.  As an Ubuntu user since it's inception and previous to that a Debian user, on my systems I allow root installs for testing I do: `sudo apt-get install ruby2.0 ruby2.0-dev build-essential libxml2-dev libxslt1-dev libyaml-dev && sudo gem install jekyll`

**Comment by mafagafogigante** [comment]
I agree with everything you said. But I'd say that "I'd **like** it to be simple". It is very complicated to solve this issue, at least I wouldn't know an easy way (except for an install script or an official package).

Also, if you are used to the linux environment and run into several different libraries and languages often, you should be used to talking to `apt-get` almost as much as you talk to your colleagues.

Lastly, the example **works** if you have all those libraries up-to-date, which is something I believe most ruby developers do.

**Comment by envygeeks** [comment]
I don't know what @parkr thinks on this subject but the reason I personally won't build an install script for Debian or Ubuntu or any distro is because we provide Docker images, those images are meant to make everything simple for you because Docker does provide packages and then you simply download our image and it provides *everything* you need in isolation without you needing to worry.  From the latest Ruby, to testing that Jekyll just works, to automatically installing gems, booting Jekyll, building the site, watching the site and everything just from a simple `docker run --rm -it jekyll/jekyll:stable`

There was a time I built Debian packages and had my build server (through my bot) attach them to our releases but I opted to stop having our build server do that because I was unwilling to build RPM's, exe's and we could not decide if we wanted to land on Traveling Ruby or otherwise for OS X (that ticket is still open,) it was unfair for me to provide debs and not care about other distros so I stopped building the Debian packages and it was at that time we started building the Docker image which is just as easy so I had no qualms about telling my build server to stop building debs.

**Comment by mafagafogigante** [comment]
As I think debian is far more used than other distros (I have no statistics whatsoever to back this up), I think that only providing debs is not unfair at all. Besides that point, I agree with and understand you. Also, in a development environment, you'd only have to install the dependencies once, so even if it is a bit complicated, it is still pretty manageable.

**Comment by envygeeks** [comment]
First: That is the exact definition of unfair.  Literally almost. Also: It's not complicated or convoluted at all to get Jekyll up and running in a matter of seconds.  The example I gave is exactly what I do on a fresh Ubuntu install with root access.  That's a single simple line.

**Comment by parkr** [comment]
I think we're allowed to do whatever we want to a certain degree, and docker images give us the best bang for our buck because they're compatible with many platforms. So instead of building a separate package for each distro, we have opted to use Docker which is a one-size-fits-all solution.

That said, one can always install Ruby and RubyGems and run `gem install jekyll` oneself. The limitations there are permissions as noted by Mark above. Recommendation and supported method: Docker containers. https://github.com/jekyll/docker

**Comment by andersonweb** [comment]
@envygeeks after hours looking for ... you finally helped me thanks you!!!
