### ISSUE TITLE
Includes with page variables are suddenly empty

### ISSUE THREAD

**Issue by gossi** [jekyll/jekyll#4117]
Given the following:

**my-page.md**:
```
---
layout: package
package: bla
---
hello world
```

**_layouts/package.html**:
```
{% assign filename = page.package | prepend: 'nav-' | append: '.html' %}
{% include {{ filename }} %}
```

will result in the following error:
```
Liquid Exception: Included file '_includes/nav-.html' not found in _layouts/package.html
```

However if I output the variable, like this:
```
{% assign filename = page.package | prepend: 'nav-' | append: '.html' %}
{{ filename }}
```

It clearly says: `nav-bla.html` (the file `_includes/nav-bla.html` exists)

A bug or am I doing something wrong here?

jekyll: 3.0.0

**Comment by envygeeks** [comment]
It's hard to tell where this bug could be at so I'm going to group this under the larger tag redesign we are working on to make Jekyll tags a bit more robust.

**Comment by envygeeks** [comment]
Once that's implemented we can see where it's at and update this ticket.

**Comment by darwin** [comment]
some of my variables also suddenly stopped working after I upgraded to Jekyll 3.0.1

my observations:
1) I have a bit deep layout hierarchy: default.html < blog.html < post.html < some-actual-post.md
2) blog.html contains a variable `products`
3) product list renders correctly in case of: 

  * `default.html < blog.html < index.html`
  * source: https://github.com/binaryage/blog/blob/web/index.html
  * live page: http://blog.binaryage.com

4) product list fails to render (it is empty) in case of:
  
  * `default.html < blog.html < post.html < 2015-06-27-el-capitan-update.md`
  * source: https://github.com/binaryage/blog/blob/web/_posts/2015-06-27-el-capitan-update.md
  * live page: http://blog.binaryage.com/el-capitan-update (note the product list is missing in sidebar)
5) also additional variables defined in post.html matter, do not work in case #4
had to do a workaround here: https://github.com/binaryage/shared/commit/6ff8f33b46309dfc2779a30d6b4c050a78be9081

because it works most of the time and fails just in few cases, here are my theories:
1) it might break only for blog posts
2) it might break for pages with layout hierarchy deeper than 3

**Comment by eepp** [comment]
@darwin I'm having the exact same issue.

Minimal site to reproduce this: http://localhost:8000/2015/11/30/post/.

Works as expected with Jekyll 2.5.3; `post` layout's `banana` variable is not propagated with Jekyll 3.0.1 (whereas `page` layout's is).

**Comment by parkr** [comment]
@darwin @eepp For posts, this variable is accessible via `layout.blah`. See http://jekyllrb.com/docs/upgrading/2-to-3/#layout-metadata.

It's a bug that it works in pages and doesn't work in posts – it should be just `layout.X` for all.

**Comment by eepp** [comment]
@parkr Ahhh thanks, will try that, should solve everything.

**Comment by darwin** [comment]
Thanks @parkr. Interesting is that I've read this page (before I have discovered that problem) and it didn't "click" in my head that it is my case. So I skipped that section (my bad).

Maybe I don't have full picture here, but my opinion is that by this change you have introduced inconsistency. Layout can munge parents' layout variables, but page/post can not? In my view pages/posts are conceptually layouts too, they just happen to be leafs of layout hierarchy rendering final content. Why they should be treated differently? If you wanted to introduce non-munged variables, you should have introduced them under a new namespace (for example `locals`) and make it consistent across everything. Layouts/pages/posts could access `locals.blah` which would be guaranteed to be non-munged by anything and whole system would stay backwards-compatible.

**Comment by eepp** [comment]
I agree with @darwin.

In my use case, the `default` layout uses some variables to alter the HTML. Some pages set those variables individually and use the `default` layout directly. Other pages share common variable values, so they use another layout, which itself uses the `default` layout and set those variables.

How am I suppose to treat this in the `default` layout? Test for an existing `page.variable`, and if it fails, use `layout.variable`? For each variable?

I consider the `layout` variable of a page to mean "extend" or "inherit from" the given layout. Inheritance does not usually change the scope name. In some languages, inheritance is allowed to override variables. In others, it's considered an error. But you always access all the hierarchy's variables using the same identifier (whether it's `this`, `self`, or `page`).
