### ISSUE TITLE
Jekyll 3 ignores future collection posts

### ISSUE THREAD

**Issue by iBobik** [jekyll/jekyll#4118]
Hello,
I have collection for events, what are usually in the future. In Jekyll 2 there were no problem with it, but Jekyll 3 does not process events what not happened yet.

It process future events if I add —future to jekyll command, but it is just workaround, not proper solution.

**Comment by budparr** [comment]
Hey, @iBobik - I use a different word than "date" to sort events (I use "start_at") so I can show future dated items from a collection.

I believe the ``` future: true ``` flat in the config file is only for posts, though I could be wrong about that.

---

_fwiw, I think you'll get more responses to questions like this at https://talk.jekyllrb.com/_

**Comment by iBobik** [comment]
Yes, rename of attribute should work (btw, I use attribute named `datetime`
and same date in filename), but it will be better if Jekyll 3 does not
brake sites developed with Jekyll 2 and behave same if there is not good
reason.



Jan Pobořil

2015-11-08 22:14 GMT-06:00 Bud Parr <notifications@github.com>:

**Comment by envygeeks** [comment]
Jekyll 3 is not Jekyll 2 so it's the perfect time to break sites and adopt new ideologies and software practices.   It is drilled home from the day that people start using software that "if it's a major release then anything can change."  I don't know if I would consider this a bug (actually I don't but I'll digress to @jekyll/core and what everyone else thinks) but tbh I agree with @budparr in general use a different attribute and update for Jekyll 3 instead of expecting us to maintain legacy parity in a major software release.

**Comment by iBobik** [comment]
You are true, if there is need to break something, it is perfect time now.
Is there a need? If yes, there should be info in README or at another well
visible place and document explaining all important changes for updaters.
Not all users are Ruby devs and follow development.

Also @jekyll/docker should allow fixing to major version by tag as usual in
other images (good example is PHP <https://hub.docker.com/_/php/>),
currently it allows fixing only to relative versions. (If I use „builder“
tag, I it means „stable“ Jekyll version and it means that in some time my
site will be broken if I do nothing.)



Jan Pobořil

2015-11-09 2:38 GMT-06:00 Jordon Bedwell <notifications@github.com>:

**Comment by Stargator** [comment]
@iBobik I think the biggest influence here is [Semantic Versioning](http://semver.org/), which basically,  it used to denote for any version number (ex 1.2.3) that will undergo a huge change to the API that prevents backwards compatibility then the first ordered number (in this case "1") will be incremented.

Since Jekyll is moving from 2.5.3 to 3.0.0, then the Jekyll devs are signaling their intention to introduce incompatible changes to Jekyll which necessitates moving away from 2.5.3 significantly.

Semantic Version is still relatively new, but is being adopted by a lot of libraries (primarily) and software that has a public API.

**Comment by envygeeks** [comment]
Yes, Semver as a spec is relatively new but most of us developers have had policies like that for way longer than Semver has existed (well at least I did,)  I don't know about others because sometimes I see some weird versions.

**Comment by iBobik** [comment]
Agree and closing.

Now let's make semantic versioning useable with Docker container: jekyll/docker#55

**Comment by envygeeks** [comment]
@iBobik I don't support the idea personally but yes, it's coming, it's waiting for the new Docker system I built to be finalized and released, it will add the concept of alias tags and make it possible to do all that without any burden on me to care about it.  It should be less than a week since it's a major piece of my own stack and build server being rewritten so it's ultra-top priority.

**Comment by iBobik** [comment]
Great, thanks :-)



Jan Pobořil

2015-11-17 3:42 GMT-06:00 Jordon Bedwell <notifications@github.com>:
