### ISSUE TITLE
"jekyll" doesn't run after I install jekyll using RubyGems on Mac OS

### ISSUE THREAD

**Issue by ashokaditya** [jekyll/jekyll#4127]
<img width="565" alt="screen shot 2015-11-11 at 15 00 15" src="https://cloud.githubusercontent.com/assets/1849116/11092606/f95fda64-8884-11e5-86c4-411b04f0bd1c.png">

I update rubygems and then install jekyll.
But "jekyll" command is not recognised in the system.
I don't know why that is?!

Please help.

**Comment by chrisfinazzo** [comment]
As you're using rbenv, I would run `rbenv rehash` to make sure that the proper shims are installed. 

Details [here][].

[here]: https://github.com/sstephenson/rbenv#rbenv-rehash

**Comment by envygeeks** [comment]
This is not a bug with Jekyll so I must ask that you please ask your question at https://talk.jekyllrb.com because this system is for bugs only.  As suggested by @chrisfinazzo this could just be a case of needing to rehash.  Please try that and if you continue to have problems with rbenv ask your question at the aforementioned url.
