### ISSUE TITLE
Advertisement or promotion on Jekyll wiki page

### ISSUE THREAD

**Issue by meisyal** [jekyll/jekyll#4138]
Hello all,

I saw there are many advertisements or promotion on [Jekyll wiki page][wiki] after adding some Jekyll themes into Themes wiki page. Here are below the example of the advertisement or promotion:
* https://github.com/jekyll/jekyll/wiki/toko-spare-part-alat-berat-pekanbaru-081281000409
* https://github.com/jekyll/jekyll/wiki/toko-spare-part-alat-berat-di-Surabaya-081281000409

I know there isn't permission to edit the wiki page. So, may I delete the page that contains the advertisements or promotion?

Thank you. 

[wiki]: https://github.com/jekyll/jekyll/wiki

**Comment by envygeeks** [comment]
I have removed some of your text because it felt hateful and to me it felt like it violated our code of conduct: https://github.com/jekyll/jekyll/blob/master/CONDUCT.md.

I've also tasked my bot with cleaning up the Wiki and removing all the spam that user created, it seems that Github already removed the user, it just didn't remove all their posts and stuff, it should be done in a few minutes.

**Comment by envygeeks** [comment]
It is done, thanks for reporting the spam to us!

**Comment by meisyal** [comment]
I am so sorry pointing out to the subject explicitly.
You're welcome.
