### ISSUE TITLE
page.url drops ".html"

### ISSUE THREAD

**Issue by ochrons** [jekyll/jekyll#4145]
I have a recursive doc nav generator and after upgrading to Jekyll 3.0.0 the `page.url` seems to drop the `.html` at the end of the URL. Had to resort to this workaround (remove `.html` from the comparison target) to get it working ok.

```
{% assign navurl = page.url | remove: 'index.html' | remove: '.html' %}
<ul>
    {% for item in include.nav %}
    <li>
        <a href="{{ site.baseurl }}{{ item.url }}">
            {% assign itemurl = item.url | remove: '.html' %}
            {% if itemurl == navurl %}
            <b>{{ item.text }}</b>
            {% else %}
            {{ item.text }}
            {% endif %}
        </a>
    </li>
    {% if item.subitems and navurl contains item.url %}
      {% include docnav.html nav=item.subitems %}
    {% endif %}
    {% endfor %}
</ul>
```

**Comment by envygeeks** [comment]
The point of a major release is so that things can change and reverting those changes makes the point of semver worthless. I would consider this a non-issue unless there is an inconsistency and your source seems to imply there isn't and your description to me implies that too, can you further elaborate the problem with more clarity please?

I would also note it's up to @parkr if he wants to revert it because it was an accident too!

**Comment by uraimo** [comment]
I'm facing an issue related to this too, i'm using a sitemap.xml generator (the usual https://github.com/kinnetica/jekyll-plugins ) and since it uses page.url to get the sitemap file names it's unable to get the full name for pages like "archive.html", page.url now lacks that final ".html".

@envygeeks @parkr, can i get the *full* filename from somewhere else (i've searched, couldn't find it)? 

Thanks.

**Comment by dsusco** [comment]
Same issue, I've written generators that need a page's URL to have it's extension.

There's definitely an inconsistency here, given a .html page and a .js page the former's URL won't include the extension but the latter's will.

The best workaround I've found at the moment is using page.dir + page.name

**Comment by envygeeks** [comment]
I honestly don't know, you'd have to ask @parkr if this is a bug.

**Comment by parkr** [comment]
Hey, folks. What are your `permalink` settings? Ensure `:output_ext` is at the end if you did specify one. The [default for posts is `"/:categories/:year/:month/:day/:title.html"`](https://github.com/jekyll/jekyll/blob/5d8be167d9c5ca1353689a561c75c2287e97a300/lib/jekyll/configuration.rb#L310) and the [default for collections is `"/:collection/:path"`](https://github.com/jekyll/jekyll/blob/5d8be167d9c5ca1353689a561c75c2287e97a300/lib/jekyll/collection.rb#L192) with the output extension applied according to [these rules](https://github.com/jekyll/jekyll/blob/5d8be167d9c5ca1353689a561c75c2287e97a300/lib/jekyll/utils.rb#L181-L219).

**Comment by dsusco** [comment]
That's it for me:

    defaults:
        scope:
          type: pages
        values:
          permalink: /:path/:basename:output_ext

**Comment by uraimo** [comment]
Thanks all, looks like the default permalink for pages changed with the fix for issue #2691 committed with 0d1586a5c471d322a79177e3e9c2f5813c697c32, that now by default adopt the *pretty* style (previously, if pretty was not explicitly selected, [the default was "/:path/:basename:output_ext"](https://github.com/jekyll/jekyll/commit/0d1586a5c471d322a79177e3e9c2f5813c697c32#diff-6257bc8ccdf5697787354024f8d97a78L75)).

In my _config.yml i just had a top level "permalink: /:year/:month/:day/:title" (no default:, it's an old _config) and that's what broke the page.url content (removing that, page.url gets the missing .html). The "archive.html" i had in the root was still generated as "_site/archive.html" though. Seems a bit weird, like if there is a misalignment between what is actually generated and how the permalink is built. 

Thanks @dsusco , that helped, to also preserve my original path for posts i've modified your snippet like this:

````
 defaults:
  -   
   scope:
     type: pages
   values:
     permalink: /:path/:basename:output_ext
  -   
   scope:
     type: posts
   values:
     permalink: /:year/:month/:day/:title
````

**Comment by envygeeks** [comment]
@ochrons does what solved it for them solve it for you?

**Comment by deanc** [comment]
@dsusco Thanks this fixed for me. I had the same issue after upgrading my jekyll

**Comment by ochrons** [comment]
Yes, this fixes it for me too, thanks! Had a `permalink: ` entry in `_config.yml`.
