### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by StevenBlack** [jekyll/jekyll#4166]
Here following instructions on the [Code of Conduct](https://github.com/jekyll/jekyll/blob/master/CONDUCT.md) page, specifically citing this instruction:  

> Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by opening an issue or contacting one or more of the project maintainers.

Without being specific.

In my view, a rotation of individuals in and out of front-line support is recommendable for any active project.  

People naturally need breaks, but don't always take them.  

It's good to take a break, step-back for awhile, to re-charge.

**Comment by parkr** [comment]
Hey, @StevenBlack. Thanks for the issue.

> In my view, a rotation of individuals in and out of front-line support is recommendable for any active project.

This is a great idea. I have longed for this for a number of years now. The issues here are reliability and management. Reliability is the issue of whether every issue will get a reply and be resolved to the point where it become actionable. People are busy and even a week or two of being "on-call" for issues and PR's is tough with family, work, and so on. Management is the issue of who is going to organize and enforce the "on-call" schedule. What if someone is slacking? Lots of unanswered questions here, so I'm not sure this is feasible without a much larger contribution to Jekyll (such as it being "acquired" by a company or some other org with more time to dedicate to it).

If someone is being abusive, is harassing, or otherwise acting unacceptably, please email me personally (even if it is me) and I will resolve the matter. Sorry if you have felt you have been subject to this behaviour; you are protected by our Code of Conduct and it is my (and the other maintainers') duty to ensure you have a pleasant experience contributing to Jekyll and engaging with the rest of the community on all of our official resources.

Thank you for the issue!
