### ISSUE TITLE
Unable to output .php files with 3.x

### ISSUE THREAD

**Issue by XhmikosR** [jekyll/jekyll#4182]
https://github.com/mpc-hc/mpc-hc.org/pull/58#issuecomment-159450803

All the info are on that PR and repo; let me know if something else is needed.

**Comment by envygeeks** [comment]
I'm gonna be honest and @jekyll/core can input more if they want, this might have to wait until 3.2 because all things considered we probably need to add a configuration option and that will take low priority over bigger bugs.

**Comment by parkr** [comment]
> probably need to add a configuration option

How come?

**Comment by envygeeks** [comment]
Because there are more than just PHP files, that's just one example of files that will pass through and get their extension changed, so we should probably just call it easy and add a configuraiton option that says: "ignore these files and keep the extension"

**Comment by XhmikosR** [comment]
I see the point of @envygeeks regarding the new config option. What I don't get because I didn't quite follow 3.x development is why this change in the first place.

**Comment by envygeeks** [comment]
@XhmikosR more than likely it was an accidental change that happened in the switch over to Documents  and collections.

**Comment by parkr** [comment]
This changed because of the work to allow extension-less URL's. We write to disk based on the URL, but if the URL has no extension, we write it out to disk like `$URL.html` because it's most common to do something like `try_files $uri $uri.html` where the server tries to find a corresponding HTML file for the URI specified. If your URL comes back from Jekyll without an extension, we add it at write time. We could do a check like `File.basename(url, ".*").eql? File.basename(url)` which would have the following output:

| `url` | `File.basename(url, ".*")` | `File.basename(url)` | add ext? |
|----|----|----|
| `/my/pretty-url` | `pretty-url` | `pretty-url` | `true` |
| `/my/pretty-url.html` | `pretty-url` | `pretty-url.html` | `false` |
| `/my/index.php` | `index` | `index.php` | `false` |

etc. So only when the `basename` of `url` is the same as `basename` without ext would we add the extension.

**Comment by envygeeks** [comment]
Yeah that fix is much nicer,  I'm down for that instead of YACO.

**Comment by SoniEx2** [comment]
Should have "overrideext" on the frontmatter. It'll be more user-friendly that way.

**Comment by XhmikosR** [comment]
Any news about this? It's been too long already since v3.0 was out.

**Comment by parkr** [comment]
Hey @XhmikosR, I haven't submitted a PR for my suggestion above. Things have been pretty crazy for me personally so I haven't had much time for open source in general. If you have any time to take a crack at the suggestion above, that would be great! Otherwise I'll try to get to it soon.

**Comment by XhmikosR** [comment]
@parkr: I wish my Ruby knowledge was good enough to do this, so I'd better wait for someone else to fix this :)

Just wanted to make sure it's not forgotten.

**Comment by parkr** [comment]
My solution above kills the `deals.with.dots.html` example because of `File.basename(url, ".*")`.

**Comment by SoniEx2** [comment]
Why not "overrideext" on the frontmatter, then?

**Comment by parkr** [comment]
> Why not "overrideext" on the frontmatter, then?

That's not a very elegant way to tackle this issue – I'm holding out for a better way! I think we can solve it...
