### ISSUE TITLE
On Mac OSX cannot install without 'sudo', should update documentation

### ISSUE THREAD

**Issue by xenographer** [jekyll/jekyll#4196]
I am an admin on my mac (natch, as it's my own machine), and when I ran the 'gem install jekyll' command it says I don't have permission to write to certain directories. I have to run the command using sudo. When I do that, it works. Might be worth updating your documentation to reflect this.

This was experienced on Mac OS X El Capitan on a Mac Book Pro Retina Mid-2012

**Comment by envygeeks** [comment]
I'm sorry but we are not psychics, please link to the page.

**Comment by xenographer** [comment]
Sorry, but I don't think you're psychics, and sorry, but I don't think you understand the problem I'm stating. I wasn't referring to specific documentation page.

If you must be pedantic, how about the front page: https://jekyllrb.com/, or the quick start guide http://jekyllrb.com/docs/quickstart/, or the installation page http://jekyllrb.com/docs/installation/ which *all* say run the command 'gem install jekyll' to install it. Except that you can't on OSX without 'sudo'. 

Sorry if that's somehow implied, but, you know, I'm not psychic....

**Comment by envygeeks** [comment]
It's not pedantic to ask where the problem is. One cannot fix something unless they know where it's broken.  That said, I don't assume any of those are problems in the documentation because we don't specifically tailor any documentation (except for OS X specific documentation) for OS X.  All of those are generic examples, if you prefer to use `sudo` then we leave that to you to decide, if you prefer to use `rvm` and no-sudo then we also leave that for you to decide, if you prefer to use `rbenv` and no-sudo then we leave that to you to decide, if you prefer to use one of the various CLI package managers for OS X then we leave that for you to decide as well.

The only time we get involved that deeply (and this is why I asked you to point out the problem) is on this page: http://jekyllrb.com/docs/troubleshooting/#jekyll-amp-mac-os-x-1011 where we provide a work-around for trying to `sudo gem install` on some systems that keep system integrity enabled (I don't know if you do or not.)  There we point out the various methods.

**Comment by xenographer** [comment]
That link would have been suitable. Thanks for the explanation. Closing the issue.
