### ISSUE TITLE
Unclear warning: Deprecation: Collection#each should be called on the #docs array directly

### ISSUE THREAD

**Issue by nasht00** [jekyll/jekyll#4199]
My plugin contains the following loop:

        site.posts.each do |post|
          # do something
        end

I get the following warning on that line:

`Deprecation: Collection#each should be called on the #docs array directly.`

I have no idea what it wants from me, I'm not using any `#docs` anywhere...

Is this a bug? Or is the warning just not clear at all?

**Comment by envygeeks** [comment]
It's telling you to use "site#docs" and not "site#posts" because that API will be cut off when @parkr decides to cut it.  It's a bug in your plugin not in Jekyll and it's only a bug in your software because of the aforementioned API being cut-off, not because your plugin is broken.

As a side-note: Questions like these are best asked at https://talk.jekyllrb.com where there is actually already a documented case of a question like this.

**Comment by nasht00** [comment]
I'm learning from this: http://jekyllrb.com/docs/plugins/

I can't find any documentation about this `site#docs`, what it contains, etc.

This page also contains no mention of the deprecation and what it means: http://jekyllrb.com/docs/upgrading/2-to-3/

In any case the warning does not explain anything...

**Comment by nasht00** [comment]
Also this page: http://jekyllrb.com/docs/variables/

Says to use `site.posts`

**Comment by envygeeks** [comment]
The warning explains everything, and if it doesn't clarify how it does not.  As a programmer that message is perfectly clear to me, even if I were to have never of used that  API before it would be perfectly clear.  If you are using our Ruby API's we expect you to understand the API's you are using and Ruby idioms, it's not Liquid.

I'll reopen this so that we can update documentation though.

**Comment by parkr** [comment]
It's asking you to call `site.posts.docs.each` instead of `site.posts.each` because `site.posts` is a `Collection`. We could make this clearer, maybe? What about

```text
Deprecation: Collection#each should be Collection#docs#each.
```

Not sure if we can know that you called it via `site.posts` or not – maybe in the `caller` info available in the method but I'm not sure. @nasht00 Did it give you a line number?

**Comment by chrisfinazzo** [comment]
@nasht00 The relevant Jekyll Talk thread is [here][1], fix is [here][2] (Tracked in #4114). Do you have a repo for this plugin?

[1]: https://talk.jekyllrb.com/t/what-is-docs-array/1425
[2]: https://talk.jekyllrb.com/t/deprecation-warning-ruby-2-2/1475

@parkr I assume the fix is the same - scope to `site.posts.docs` for these instances? (Plugins, Variables, etc.)

**Comment by nasht00** [comment]
Thanks @parkr that was it.
Yes it gave me a line number. And yes the warning you provided seems a bit clearer already.

`site.pages` is still an array? Because it did not give me any warning for `site.pages.each`.

@envygeeks the part that is not clear is the `should be called on the #docs array directly`. You have to understand, you've been working with the Jekyll source code so the concept of a collection of docs is obvious to you. But considering that `docs` are absolutely nowhere in the documentation, I had no way of knowing what this `#docs` array is.

And yes, you could say I could go to the forum and ask someone to translate this warning for me, but I think that if someone has to go to the forums, then the meaning of the warning failed - no?

In any case, I think the documentation on Plugins should mentioned this whole concept of collection of documents, and the upgrading guide as well. My first instinct is to browse the documentation, not the forums...

**Comment by envygeeks** [comment]
@nasht00 does this seem clearer to you because we can make this message happen one way or another using caller in Ruby 2.0 now that we require 2.0+ or through the `method_missing`: `Deprecation: #each should be called on posts#docs instead of on #posts.`

**Comment by envygeeks** [comment]
On the documentation note, that's a definite need.

**Comment by nasht00** [comment]
@envygeeks yes that message is the best so far
