### ISSUE TITLE
Feature request: render user-input files

### ISSUE THREAD

**Issue by kaatt** [jekyll/jekyll#4211]
Similar to how `git add` lets you specifically select which files you want to add, what do you think about Jekyll having the option to build only the files/folders passed as a argument to `jekyll b`?

This is one of the things that I think will be very useful when a user wants to build the site faster.

**Comment by mattr-** [comment]
This is not a bad idea. Unfortunately, due to the way Jekyll sites are structured, there's a large dependency chain that would need to be built before you could even build one file, which makes this impractical.  Have you tried the (so far, experimental) incremental regeneration feature yet? If you're using Jekyll 3, you can pass `--incremental` to `jekyll build` or `jekyll serve` to give a spin and see if that does enough of what you want to accomplish.

**Comment by kaatt** [comment]
I understand Matt.

I've been testing the incremental regen since the betas, it isn't working very well. A real world example: http://www.gfycat.com/SevereMassiveGangesdolphin?speed=0.1&theme=dark

Normal build took 8.4 and incremental took 7.4 after creating just one new file. Even if nothing changes between builds, it takes 7-8s.

This is on a normal SSD, builds twice as fast on my PCIe SSD.

**Comment by parkr** [comment]
@kaatt Try using the `--profile` flag in 3.x. Please open a ticket on talk.jekyllrb.com to discuss this further. :)
