### ISSUE TITLE
[Question] Why does Jekyll not supports normal markdown?

### ISSUE THREAD

**Issue by VikramTiwari** [jekyll/jekyll#4265]
Not sure if this is the place to ask the question, but here it is.

Why KramDown? Most of the docs/blogs that one is writing are in GitHub Markdown format that are pretty easy syntactically and are supported on various editor, so that changes are easy to do. So it makes sense to provide GitHub Markdown as one of build systems for markdown in Jekyll.

Am I missing something here?

**Comment by parkr** [comment]
Hey @VikramTiwari, this is a great question. Let's see if I can answer this completely for you.

[GitHub-Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/) was invented the original Markdown, [as conceived by John Gruber](https://daringfireball.net/projects/markdown/), didn't have some features that GitHub was looking to add to its core product. Other projects in Ruby were started to convert Markdown into HTML: RDiscount, RedCarpet, kramdown, etc. GitHub Flavored Markdown has since become wildly popular (hey, I'm using it now!) and arguably the most-used and most-loved Ruby-compatible implementation.

The implementation that GitHub uses to process its flavor of markdown has never been fully open-sourced or marketed as such, however. Attempts to approximate it have been made, such as [kramdown's GFM parser](http://kramdown.gettalong.org/parser/gfm.html).

Jekyll has always shipped with various Markdown parsers; three are available in Jekyll 3: kramdown, RedCarpet, and RDiscount. Due to the proprietary nature of GitHub's own engine and the availability of very close approximations, we opted not to press GitHub for their Markdown parser and have shipped documentation [which helps you achieve the closest GitHub Flavored Markdown experience you can get](http://jekyllrb.com/docs/configuration/#kramdown) short of publishing code to a GitHub repository, gist, or writing a comment.

It is worth noting that there is no such thing as "normal markdown," not if you think "normal" as a sort of global standard. Efforts to standardize the Markdown spec have been fairly successful, and [CommonMark is the result](http://commonmark.org/). That said, CommonMark development seems to be slowing, and [no official Ruby client is available](https://rubygems.org/search?utf8=%E2%9C%93&query=common+mark).

Jekyll has simply used what markdown parsers and renderers that were desired by users. In Jekyll 3.1, we will default the GFM option in kramdown (#4202) so that the experience for most users is as close to writing Markdown for GitHub as is allowed by pre-existing tools.

Hope this answers your question satisfactorily. Happy Jekylling!

**Comment by VikramTiwari** [comment]
This is a perfect answer! :+1: Covers everything with perfect details and links. Thanks. :smile:

**Comment by VikramTiwari** [comment]
So I was going through setting up Markdown processor as [described in docs](http://jekyllrb.com/docs/configuration/#kramdown) and it seems that the gem `funky_markdown` is no longer available. Time to update docs!

**Comment by parkr** [comment]
> @parkr So I was going through setting up Markdown processor as described in docs and it seems that the gem funky_markdown is no longer available. Time to update docs!

It's a fake name :) No such gem exists!
