### ISSUE TITLE
Reading values incorrectly

### ISSUE THREAD

**Issue by Resonanz** [jekyll/jekyll#4294]
I am relatively new to Jekyll 3.0.1 so this may be me rather than Jekyll, but perhaps not...

I have a page (not a post) containing this in the front matter:

`file-number: 16`

And I read this value and display it from all my pages using the following:

```{% for page in site.pages %}
<ul>
<li>{{page.file-number}}</li>
</ul>
{%endfor%}
```

Now, the displayed output of this for the number 16 is `16`. But if I change it to:

`file-number: 016` then the output is exactly `14`, and 

`file-number: 00007` then the output is exactly `7`, and 

`file-number: 00008` then the output is exactly `00008`.

Yeah, this is pretty weird... any ideas?

**Comment by envygeeks** [comment]
016 is octal (base-8), and it's octal for the number 14, this is both YAML and Ruby doing this, as Ruby supports Octal's.  The reason "00007" works is because Ruby assumes you made a mistake and strips your leading 0's for you... which traditional numbers do not use.

Weird? No.

This is not a bug in Ruby, YAML or Jekyll.  Sorry.

**Comment by Resonanz** [comment]
Ah, yes I did consider that and then thought "nah".... it was the leading zeros that made me do it :-)  Thanks!
