### ISSUE TITLE
Documentation on {% assign %} variable scope is difficult to find or possibly non-existent

### ISSUE THREAD

**Issue by brianthelion** [jekyll/jekyll#4370]
If I use an `{% assign %}` in a template, is that variable then available in all templates called through `{% include %}` thereafter? Those that my parent template call, or just the ones that my child templates call? Is there such a thing as a writable global scope?

These questions and others deserve elaboration in the docs, IMHO, including some clear examples. For folks coming from other programming languages, running up against subtleties like https://github.com/jekyll/jekyll/issues/1956 can be quite maddening without a clear source of authoritative answers. If the answers are out there, somewhere, they need to be easier to find.

Cheers!
~br

**Comment by brianthelion** [comment]
I'm sure at least half of this issue is on Liquid, but I'll let you all figure that out.

**Comment by envygeeks** [comment]
Liquid is not a programming language and it actually has one of the most complete documentation sites of any I've ever seen.  Googling "liquid assign" took me straight to https://docs.shopify.com/themes/liquid-documentation/tags/variable-tags which took me here: https://docs.shopify.com/themes/liquid-documentation/tags/variable-tags#assign.

I'm not saying we can't improve our Liquid docs, however we could never do what Liquid themselves do because it's their template language and it would be a burden for us to maintain a complete set of documentation.

**Comment by brianthelion** [comment]
Neither of the links provided mention the term "scope".

**Comment by envygeeks** [comment]
Sorry, I'm slowly typing today, hurt a finger, you replied before I finished this.

To address the other parts of your question, you cannot use a variable in the parent, it has to be in the child, and I don't remember if anything ever came of content_for for Jekyll, I know @imathis was working on content_for but I don't remember if it is Jekyll 3 ready.

**Comment by brianthelion** [comment]
Can a variable be used in a sibling template given an appropriate call order as in [this](http://stackoverflow.com/questions/34814277/jekyll-liquid-setting-post-state-in-included-templates) example?

**Comment by envygeeks** [comment]
No, you cannot.  It is a different cope as far as I'm aware, and I don't know if we can work around that.

**Comment by brianthelion** [comment]
This stuff just needs to get documented somewhere.

**Comment by envygeeks** [comment]
I'm going to digress as I agree but I only agree if it's Liquid documenting it, so I'll let @jekyll/core decide that bit and whether we should document these quirks directly or file tickets upstream with updates to their documentation.

**Comment by brianthelion** [comment]
Awesome! Thanks.

**Comment by parkr** [comment]
@brianthelion Hi! The Liquid team is working on documentation over on https://github.com/Shopify/liquid/pull/513. The way in which scope works (like using `assign` and then `include`) is unclear to me, too, and I've been doing this for a number of years. I believe @benbalter ran into this problem or a similar one on Thursday or Friday of last week, so it's something that we have to consider: why is `context` not updated by `assign`'s at render-time? 

Perhaps you can open an issue on Shopify/liquid with an example of what doesn't work, the expected behaviour, and the actual behaviour. Sorry you're having this issue; I think it's a Liquid bug (or "feature," but that one would be hard to justify to me :wink:).
