### ISSUE TITLE
keep_files not working as expected

### ISSUE THREAD

**Issue by mynimi** [jekyll/jekyll#4387]
So I first found `keep_files` within the docs today. Not sure if I missunderstood the intention of this or if I made some mistake, because I cannot make it work.

So the Docs say:
> When clobbering the site destination, keep the selected files. Useful for files that are not generated by jekyll; e.g. files or assets that are generated by your build tool. The paths are relative to the `destination`

So I think this means that all except the files mentioned within `[ ]` will be wiped when jekyll builds the site. This would be perfect since I build my css file using a grunt task and I'd like not to have to rebuild the whole site when just changing a line of CSS.

So in my config file I have the following:

```yml
destination: jekyllbuild
keep_files: [css/main.css]
```

Then I added a comment within the _main.css_ file in the _jekyllbuild_ folder and then ran `jekyll build`
Comment did not stay, so I suppose this `keep_files` is not doing what it's supposed to?

I just updated to the newest version of jekyll (3.0.2). Running on Win10

Any help on how I could make this work would be highly appreciated.

**Comment by envygeeks** [comment]
The answer to your question was in the quote:

> Useful for files that are not generated by jekyll

In short, without more information we are lead to assume that because the file was place again, without the comment, Jekyll is in-fact generating that file.  You need to not only `exclude`, but keep the file if you wish Jekyll not to handle it.  If this assumption is incorrect, can you provide more details about your configuration and said layout (or provide a repo with the source in it so we can see what's going on better.)

**Comment by mynimi** [comment]
Well that makes sense. I totally forgot to exclude it, so it was handled by jekyll. 
Excluded it and works perfectly fine now.
Thanks a ton for answering so fast!
