### ISSUE TITLE
jekyll 3.1.0 | Error:  undefined method `[]' for nil:NilClass 

### ISSUE THREAD

**Issue by mgdomthbws** [jekyll/jekyll#4421]
Hi guys, 
I'm lost and need some help. When generating, I run into the following error: 

```
user@host:~/Repositories/project (master)$ jekyll serve
Configuration file: /home/user/Repositories/project/_config.yml
            Source: /home/user/Repositories/project
       Destination: /home/user/Repositories/project/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '/index.md':
                    undefined method `[]' for nil:NilClass
jekyll 3.1.0 | Error:  undefined method `[]' for nil:NilClass`
```

Funny thing, when I run ...
```

user@host:~/Repositories/project (master)$ bundle exec jekyll serve
Configuration file: /home/user/Repositories/project/_config.yml
            Source: /home/user/Repositories/project
       Destination: /home/user/Repositories/project/_site
      Generating... 
                    done.
```

The following line is 

`jekyll 2.4.0 | Error:  uninitialized constant Jekyll::Watcher`

I believe I have two different Jekyll versions installed. What can I do now? I am on Debian Jessie (current stable).  The available version of Jekyll in Debian Jessie is, according to https://packages.debian.org/jessie/jekyll jekyll (2.2.0+dfsg-2). I initially installed from there.

What can I do to clean this mess up? I have actually no idea how I ended up here.
Can anyone help? I appreciate your help!

**Comment by budparr** [comment]
The best place to get community help is https://talk.jekyllrb.com/ as this is for reporting bugs.

Do you have a Github or other public repository you can link to? That'd be helpful too.

Looks like you've got 2.4 in your Gemfile (bundle exec), which is good (and probably where you should be running the site from), but getting an error on something in 3.1. which is the Gem you have installed locally. Just stick to running bundle.

As for your error, I'd look in that template and make sure you have variables wrapped in conditionals (e.g. 
```{% if page.foo %}{{ page.foo }}{% endif %}``` 
Because if you have "foo" in front matter on one template and not another, you'll get an error.
that's a start.

Anyway, probably best to move this over to Jekyll Talk

**Comment by mgdomthbws** [comment]
Hey Budd, thanks for pointing me in a certain direction. Jekyll Talk sounds like the the place to take this.
I will look into this tomorrow. Today I can't see the see the forest for the trees anymore. 
Thanks!
