### ISSUE TITLE
Blog posts with trailing slashes no longer work in Jekyll 3

### ISSUE THREAD

**Issue by daattali** [jekyll/jekyll#4440]
([crosspost from jekyll-talk](https://talk.jekyllrb.com/t/github-pages-with-jekyll3-blog-posts-with-trailing-slash-no-longer-work/1877/1))

I host a GitHub Pages site, and since its upgrade to Jekyll 3, I've noticed myself and from other people that pages that previously worked both with and without a trailing slash no longer work with a trailing slash. This can be problematic because there are many URLs out there on the web linking to pages with a trailing slash, and now they're all 404s. I temporarily wrote a hacky JavaScript redirection , but is there a proper fix for this? Is this a deliberate behaviour by the new Jekyll?

**Comment by jezen** [comment]
:+1: All my links recently 404d, so I had to explicitly add trailing slashes to permalinks in all of my posts.

**Comment by daattali** [comment]
I'd mainly like to know if this was a deliberate change of behaviour, or if it's a regression bug

**Comment by ploeh** [comment]
I'm having this problem as well. Although I've deliberately removed the trailing slashes when providing links manually, Google has indexed my site with the slashes.

Hundreds of links no longer work :disappointed:

**Comment by daattali** [comment]
For anyone who comes to this issue, a temporary workaround is to use javascript to remove the trailing slash on the 404 page, see example [on my site](https://github.com/daattali/daattali.github.io/blob/master/404.html#L14-L21)

**Comment by pathawks** [comment]
Do you have a specific example of something that worked with Jekyll 2 and not with Jekyll 3?
I imagine this has to do with #3490, but it is difficult to say without specific details.

It does not sound like anything has been *broken*, but it is difficult to know for sure without specific steps to recreate the problem.

**Comment by daattali** [comment]
All my blog posts on [my GitHub Pages-hosted website](https://github.com/daattali/daattali.github.io) automatically had a trailing slash at the end, and there are many links online to my blog posts with a trailing slash. For example, http://deanattali.com/2015/05/09/setup-rstudio-shiny-server-digital-ocean/ was the URL to a popular blog post, but it now doesn't work (I added a hacky javascript redirect for now). This also means that all my Disqus comments (there were about 100 comments on that page) now disappeared because Disqus registered that post as having a trailing slash, but now I have to remove that slash in order to have the page render.

**Comment by envygeeks** [comment]
Change your default permalink to have index.html at the end and it will be bring back the trailing slash, the problem is we switched to `/page.html` which Github supports for Pretty URL's, trailing slashes are added by their server when it's folder because they don't disable them.

**Comment by kevinushey** [comment]
If I understand correctly, the issue related to how Jekyll 2 constructed permalinks based on the `_config.yml`'s `permalink:` field:

- Jekyll 2 automatically added trailing slashes to permalinks, even if none was provided in the `permalink:` field;
- Jekyll 3 now supports + 'respects' the absence of a trailing slash in the `permalink:` field.

Without that change, Jekyll was now generating links without a trailing slash, and the links including a trailing slash would 404. Unfortunately, since Google had already indexed links with a trailing slash, those were now 404s.

A blog I contribute to, the [Rcpp Gallery](http://gallery.rcpp.org/), was affected by this -- we fixed it by ensuring our `_config.yml` had a trailing slash for the `permalink:` field: https://github.com/RcppCore/rcpp-gallery/commit/70fc8606ca79f05bc8ec20c9885d37905a35e2c5

I think the Jekyll 3 behavior is correct, but this change could have been better advertised / documented, I think.

**Comment by daattali** [comment]
Thanks @envygeeks, I tried that, and you're right that now old links work and I can access the page with a trailing slash. But now the default URL for each blog post contains `.index.html`, which is different from the previous URL. So if you are on the landing page of the blog and are navigating to a post from the paginator, this will break Disqus comments because the URL will contain `.index.html` while the traditional URL didn't have it.  Is there a way around this?

**Comment by ploeh** [comment]
> Change your default permalink to have index.html at the end

If I understand this suggestion correctly, the suggestion is to have permalinks defined like this in `_config.yml`:

```
permalink: /:year/:month/:day/:title/index.html
```

This looks like it sort of works with the trailing slashes, but also causes _all_ permalinks to now be generated with `/index.html` (e.g. `http://localhost:4000/2015/12/22/tail-recurse/index.html`). This would mean that I'm now putting a technical concern into the URLs of my articles, which goes against the philosophy of the WWW, [as outlined by Sir Tim Berners-Lee](https://www.w3.org/Provider/Style/URI.html).

This is, in my opinion, not an acceptable solution, because it'd make it more difficult for me to change platform in the future (nothing lasts forever).

**Comment by envygeeks** [comment]
@ploeh @daattali See: https://github.com/jekyll/jekyll/blob/master/lib/site_template/_includes/head.html#L10 on how to fix that problem now, which is how we (at EnvyGeeks) do it for all our production sites regardless of how we build the permalinks (and whether or not we host it on Github or on EnvyGeeks / otherwise.)

**Comment by envygeeks** [comment]
Note, the canonical (while recommended it be there) is not the part you need worry about, it's the replace and other stuff that normalizes the entire URL.

**Comment by daattali** [comment]
@kevinushey you're right I agree the current behaviour is more correct, but maybe there should be a way to keep enforcing the old behaviour .....

![xkcd](https://imgs.xkcd.com/comics/workflow.png)

But I do think Kevin's solution is the best @ploeh you should try that

**Comment by ploeh** [comment]
Thank you, @kevinushey, that seems to solve the immediate problem :+1:

**Comment by tobyspark** [comment]
Well, if only I had decided to do a website update tomorrow, I'd have read this in the docs! Thanks @daattali for posting about the issue as I had it, @kevinushey for the explenation, and @daattali again for #4454

**Comment by daattali** [comment]
There is now a note in the jekyll 2 --> 3 migration page about this issue and how to solve it http://jekyllrb.com/docs/upgrading/2-to-3/

**Comment by moodmosaic** [comment]
Adding a trailing slash to the permalink template in `_config.yml` seems to be solving the problem also for me.
