### ISSUE TITLE
Collections not working

### ISSUE THREAD

**Issue by isaacrg** [jekyll/jekyll#4443]
A project I am working on ([moonsquads/moonsquadstatic](https://github.com/moonsquads/moonsquadstatic), built version at [moonsquads/moonsquads.github.io](https://github.com/moonsquads/moonsquads.github.io), via [travis](https://travis-ci.org/moonsquads/moonsquadstatic)) is failing to output collection `games`.

`_games` folder contains one item, [`steam-259080.md`](https://github.com/moonsquads/moonsquadstatic/blob/master/_games/steam-259080.md):
```
---
title: "Just Cause 2: Multiplayer Mod"
steam_id: 259080
---

Some content here
```

And [`config.yml`](https://github.com/moonsquads/moonsquadstatic/blob/master/config.yml) contains:
```yml
collections:
  games:
    output: true
```

What is causing Jekyll to silently ignore this?

**Comment by pjmay** [comment]
This is not an issue, maybe you only need to **restart** your jekyll server cause you modified your `config.yml`

**Comment by parkr** [comment]
@isaacrg In your `--profile` output, I see no `_games/`. This means Jekyll didn't read your games collection at all. I see that you have conflicting data types in your [`config.yml`](https://github.com/moonsquads/moonsquadstatic/blob/master/config.yml) and [`admin/config.yml`](https://github.com/moonsquads/moonsquadstatic/blob/master/admin/config.yml). In the admin config, use hashes all the way down instead of an array:

```yaml
collections:
  posts:
    output: true
    some_other_metadata: "its value"
    # ...
```
