### ISSUE TITLE
Hard wrap modification

### ISSUE THREAD

**Issue by borisschapira** [jekyll/jekyll#4471]
There was a modificiation into the way kramdown interprets wraps between jekyll 3.0 and jekyll 3.1.
What was written in Markdown as :

```
> First line.
> Second line.
``` 

Was, before, hard wrapped (`<br/>` where included, even if it's not Markdown standard, it's more consistent with GMF) :
> First line.
> Second line.

Now appears like :
> First line. Second line.

**Comment by envygeeks** [comment]
This issue is resolved and will be fixed with 3.1.2.  It stems from changes that were made to make the Kramdown class more optimized but we (me actually since it was me who wrote that) forgot to enable symbols, this was fixed with #4428 where we now allow Kramdown and it's libs to access our hashes indifferently.  Please update your Gemfile to include `gem "jekyll", :github => "jekyll/jekyll"` and confirm this is the case and we can close this.

**Comment by borisschapira** [comment]
Just tested, does not do the trick unless I had this to my _config.yml :

```
kramdown:
  hard_wrap: true
```

**Comment by envygeeks** [comment]
I do apologize.  I misread what you had stated slightly.  You wish wish to have hardwraps enabled by default.  At this time we default to them being off intentionally to behave like Github.  I do not know what GMF is (unless you mean GFM) however if you do mean GFM then we are consistent with most of their processing of Markdown, which does not wrap.

My vote is for keeping it as is.

**Comment by borisschapira** [comment]
Oups, yes, I mean GFM.

I'm confused : the [description of the `hard_wrap` option](http://kramdown.gettalong.org/options.html#option-hard-wrap) in Kramdown seems to state the opposite of what you explain and when I edit my first comment, I can clearly see that GitHub translated my line breaks as line breaks.

![capture d ecran 2016-02-05 a 12 26 33](https://cloud.githubusercontent.com/assets/284742/12845093/cfc84110-cc03-11e5-83b3-3fe74c8244f3.png)

**Comment by envygeeks** [comment]
This
Shouldn't
Wrap

**Comment by envygeeks** [comment]
It seems Github hardwraps comments (for very good reason, ticket comments should probably wrap for easier formatting so they can do less cleanup.) However if you look at:  https://gist.github.com/envygeeks/4755dec0a39ea2e6103b and https://github.com/jekyll/jekyll/blob/master/site/_docs/assets.md it doesn't hardwrap (and this is what we base our default on.)

**Comment by borisschapira** [comment]
As far as I understand it, [GFM](https://help.github.com/articles/about-writing-and-formatting-on-github/) is what we are writing right now, here, not the way Github displays markdown code is gist and projects…

**Comment by borisschapira** [comment]
Obviously, the use of GFM by Github itself is not obvious : http://stackoverflow.com/questions/18019957/where-is-github-flavored-markdown-gfm-actually-used-in-github

**Comment by envygeeks** [comment]
I admit being wrong about where Github uses GFM, my vote does not change though.

**Comment by envygeeks** [comment]
Let me elaborate on why my vote doesn't change, a while back there was a huge discussion about Github switching to Kramdown, and the decision that prevailed was to make Kramdown consistent with Github's default markdown processor (which is why hardwraps were turned off.) During that time we fixed up Kramdown to do just that (behave like the default processor for Github pages.)

**Comment by borisschapira** [comment]
OK so maybe there is a need to update Kramdown options and communicate on Jekyll changelog, that's all.

**Comment by envygeeks** [comment]
:+1:
