### ISSUE TITLE
Jekyll 3 changed the way internal URLs are treated

### ISSUE THREAD

**Issue by daattali** [jekyll/jekyll#4483]
I just realized that all the internal links I have on my website are now broken.  In Jekyll 2, if I was on a page "mysite.com/page1" and there was link to "page2", it would go to "mysite.com/page2".  Now with Jekyll 3, it goes to "mysite.com/page1/page2".  This means any CSS/JS dependencies as well as links to other pages which previously didn't include a leading slash and worked, are now all broken.

The migration docs do say that **permalinks** have a changed behaviour for relative paths, but they don't say anything about this bug.

**Comment by parkr** [comment]
@daattali This doesn't look like a bug to me because we don't do any link rewriting at all. Are you using `page.url` or `site.url` or `site.baseurl`? `page.url` should _always_ include the leading slash and be absolute from the root of the `_site` directory (destination). You need to prepend the baseurl or url depending upon your situation. If it's a static link like `<a href="page2"></a>` then that has more to do with how your browser interprets those and nothing to do with how we generate them because we simply copy them over. If you moved from a different markdown parser to kramdown, see if reverting helps. If so, write an issue on gettalong/kramdown describing how it works differently and why it should work the old way instead of the new way.

**Comment by daattali** [comment]
I am talking about static links. Last week, `<a href="page2"></a>` worked, and now it doesn't.  I understand it *could* be a change in how Chrome treats links, but that sounds like a big coincidence in timing, and it seems more likely that a change in Jekyll or GitHub Pages caused this. I realize you're not responsible for github pages, but I'm not aware of any changes they made other than upgrading to jekyll 3, so the most reasonable assumption I could make is that it's related to jekyll
