### ISSUE TITLE
Trouble installing jekyll 

### ISSUE THREAD

**Issue by thegaffers** [jekyll/jekyll#4513]
I get the following message every time I try to install jekyll

Mulindis-MacBook-Pro:~ mulindijohnson$ gem install jekyll
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
Mulindis-MacBook-Pro:~ mulindijohnson$

**Comment by Crunch09** [comment]
That's probably because you're using the preinstalled Ruby from Apple. You should use a [Ruby version manager](http://stackoverflow.com/questions/14607193/installing-gem-or-updating-rubygems-fails-with-permissions-error) instead.

**Comment by parkr** [comment]
What @Crunch09 said. :smile:

**Comment by SenHeng** [comment]
@parkr 

I've just installed rbenv and am still getting the same permission problems.

**Comment by SenHeng** [comment]
Managed to solve it after taking various steps, though I'm not sure which of them directly contributed to it.

```
brew uninstall ruby
rbenv init #and then adding the eval(... instructions to bash
```

This issue seems to come up quite often on here and stack overflow. I would suggest adding clearer install instructions for OS X, especially for people unfamiliar with ruby (and bash in general).
