### ISSUE TITLE
'if' tag was never closed

### ISSUE THREAD

**Issue by steveklabnik** [jekyll/jekyll#4564]
###### What version of Jekyll are you using (`jekyll -v`)?

3.0.3

###### What operating system are you using?

Linux, but also manfiests on github pages

###### What did you do?

GitHub upgraded from Jekyll 2 to 3 for GitHub Pages

###### What did you expect to see?

My site to build

###### What did you see instead?

  Liquid Exception: Liquid syntax error (line 2): 'if' tag was never closed in /home/steve/src/json-api/_format/index.md/#excerpt
  Liquid Exception: Liquid syntax error (line 2): 'if' tag was never closed in _layouts/page.html

* https://raw.githubusercontent.com/json-api/json-api/gh-pages/_format/index.md

* https://github.com/json-api/json-api/blob/gh-pages/_layouts/page.html#L15-L23

Both of these look clearly closed to me, and worked just fine with Jekyll 2. I couldn't find anything existing about this, sorry if it's a duplicate

**Comment by parkr** [comment]
Hey @steveklabnik! I'm sorry you're having trouble with the new version of Jekyll.

It looks to me like an issue with excerpts. [Post excerpts are generated with the first paragraph of content](https://github.com/jekyll/jekyll/blob/v3.0.3/lib/jekyll/excerpt.rb#L120). The excerpt separator is by default `"\n\n"`. In the case you described, the excerpt was trying to render just the opening `for` and `if` blocks before the two newlines.

If you don't need excerpts, set `excerpt_separator: ""` in your `_config.yml`. If you need them, then removal of the `\n\n` in the file you linked to should do the trick, or choose a different separator like `<!-- more -->`, which is more explicit.

Excerpt generation is not a wonderful aspect of Jekyll, especially because it does not respect Liquid. If you have any thoughts on how we could fix this, please let me know, or feel free to submit a PR!

Thanks, I hope this helps!

**Comment by steveklabnik** [comment]
This did in fact work. Thank you so much for the prompt response!

**Comment by steveklabnik** [comment]
(We don't use excerpts at all, so I don't have any advice, unfortunately.)

**Comment by parkr** [comment]
@steveklabnik Glad to hear you have your site building again. Let us know if you run into any other issues. Happy Jekylling! :smile:

**Comment by vibrantabhi19** [comment]
"Liquid Exception: Liquid syntax error (line 43): 'if' tag was never closed in /_layouts/default.html jekyll 3.2.1 | Error: Liquid syntax error (line 43): 'if' tag was never closed" I am getting this error while building the jekyll theme. I am also tried setting the excerpt_separator to " " but it didnt helped either.
@steveklabnik @parkr  Kindly help me with this Link: https://github.com/vibrantabhi19/vibrantabhi19.github.io﻿

**Comment by djuth** [comment]
I'm getting the same error with a simple for loop in my /_layouts/default.html, and `excerpt_separator: ""` does not fix it.
