### ISSUE TITLE
Posts on a leap day do not publish

### ISSUE THREAD

**Issue by dylankb** [jekyll/jekyll#4607]
###### What version of Jekyll are you using (`jekyll -v`)?
I'm using Jekyll 3.1.2

###### What operating system are you using?
Mac OS Yosemite

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I wrote a blog post with in a file `2016-2-29-a-beginners-guide-to-jekyll.md` and put this in my `_posts` directory. When running `jekyll serve` this file would not be served up and placed in the `_site` directory. 

###### What did you expect to see?

I expected to see my post served up as `2016-2-29-a-beginners-guide-to-jekyll.html` in my `_site` directory when I ran `jekyll serve`.

###### What did you see instead?

Nothing would happen. However, once I changed the date portion of the file to 2016-2-28 the content was served up correctly in the `_site` directory.

**Comment by glasnt** [comment]
I can confirm also seeing this issue on a GitHub pages hosted blog (which according to https://pages.github.com/versions/ is Jekyll 3.0.3)

Reproduction of error in public github repo (hopefully this helps):
The markdown file [in the repo](https://github.com/glasnt/blog/blob/gh-pages/_posts/2016-02-29-phantom-leap-day-post.md) does not appear on website ([should be here](http://glasnt.com/blog/2016/02/29/phantom-leap-day-post.html)), nor on the [archive list](http://glasnt.com/blog/archive)

**Comment by glasnt** [comment]
Further: If I explicitly add `gems: [jekyll-paginate]` to my `_config.yml` file, the page appears in the archive listings ([diff reference](https://github.com/glasnt/blog/commit/9bfbef86c5cad794d4aa3dd0c6307e025de7ce6b))

Since `jekyll-paginate` is now retired as of Jekyll 3 according to the [description of the repo](https://github.com/jekyll/jekyll-paginate), I'm going to speculate that there's a bug in the reproduction of the functionality of the pagination that's now been internalised within jekyll. 

(Though since this is a leap year bug, this won't be a problem in <24 hours time. Whee time-dependant bugs!)

**Comment by pathawks** [comment]
It is not Feb 29 yet. By default, Jekyll does not publish future dated posts.

**Comment by glasnt** [comment]
> It is not Feb 29 yet. 

That depends where in the world you're living. I'm in UTC+11, so it's been Feb 29 for ~14.5 hours now.


> By default, Jekyll does not publish future dated posts.

Trying not to jump in for @dylankb here, but it sounds like this is a cascading issue. I don't know what timezone the GitHub pages servers are in, but since future-posts is now disabled, anyone east of the servers trying to post at certain times of day where their relative date doesn't match the server's date may experience this same issue. The fact this feature comes with Jekyll 3, which has only just been released on GitHub pages (which I assume @dylankb is also using) might be compounding matters. 

Also, the fact this was logged on a specific-day of the year known for these kind of errors might have created a bias in the error attribution.

**Comment by mj1856** [comment]
Take note that many servers follow the best practice of running in UTC, so this may affect many, regardless of where they physically are located.

This is particularly true for cloud environments.

**Comment by dylankb** [comment]
I'm in UTC +800, so for me it is not February 29th yet. I was not aware that Jekyll 3 does not publish future dated posts, so @glasnt is right about the bias towards thinking there was a leap year error going on.

> Further: If I explicitly add gems: [jekyll-paginate] to my _config.yml file, the page appears in the archive listings (diff reference)

The same think happened with me; post failed to build with `jekyll serve` but did when I did pushed the post to my Github Pages repo. I do have `jekyll-paginate` gem in my config file.

**Comment by hidroh** [comment]
Same problem with `jekyll-paginate` in config.

**Comment by brianweet** [comment]
Same like a leap year problem. 
My post on February 29th does not show up with `jekyll build` or `jekyll s --draft`. 
I tried jekyll 3.0.2 and 3.1.2 on Win 10.

No file is created in the _site directory.

**Comment by Salzig** [comment]
For me it does work using `--future`

**Comment by parkr** [comment]
Hey everyone!

This is a problem with the way the date is parsed, I believe. If you can, please specify a date **with the timezone** in the post in question. GitHub Pages's servers run in Pacific time and honor Daylight Savings Time. The fix is to add `date: 2016-02-29 00:00:00 +1100` to your post, subbing out your UTC offset as your current location finds it. Alternatively, set `timezone: Australia/Sydney` (defined by [tzdata](https://en.wikipedia.org/wiki/Tz_database)) in your `_config.yml` so Jekyll knows which timezone to use.

Thanks, all!

**Comment by Salzig** [comment]
@parkr i'm not hosting on github.

**Comment by parkr** [comment]
> @parkr i'm not hosting on github.

@Salzig Then I recommend setting `timezone` in your `_config.yml`. Thanks!

**Comment by rvvincelli** [comment]
@dylankb I have just rebuilt my GitHub blog and couldn't see any posts, yes Jekyll 3 definitely does not show future-dated posts!

**Comment by mj1856** [comment]
@parkr - was the root cause of this issue ever resolved? If so, please let me know by which version, pr, or commit.  Thanks.

**Comment by DirtyF** [comment]
@mj1856 I don't think so, I just changed my date system to 2016-02-29 and add a jekyll post with this date and nothing is published, if I switch back to current date, it's OK.
