### ISSUE TITLE
No way to specify location of .sass-cache

### ISSUE THREAD

**Issue by ctubbsii** [jekyll/jekyll#4667]
###### What version of Jekyll are you using (`jekyll -v`)?
jekyll 3.1.2

###### What operating system are you using?
CentOS 7 (Linux) x86_64, Fedora 23 (Linux) x86_64

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
jekyll build -d /tmp/jekyll.tmp/
jekyll serve -d /tmp/jekyll.tmp/

###### What did you expect to see?
I expected an option, like `-d`, which could be used to specify the location of the `.sass-cache` directory.

###### What did you see instead?
No such option is available.

Ideally, an option should exist to specify the location of the `.sass-cache` directory, or to prevent it from being created entirely. It currently "dirties" my git workspace and an execution with the `-d` option could interfere with another execution of jekyll without the `-d` option, because the .sass-cache is created in the same directory regardless of the `-d` option.

What I *wouldn't* want is for it to automatically use the same directory specified with `-d`, because that will have other side-effects (for example, I have a post-commit hook to automatically do a jekyll build in a temporary directory and create a git commit to another branch, and I would not want that post-commit hook to start picking up the` .sass-cache` directory)

It's possible that such an option already exists which can be set in the `_config.yml` file. If so, I cannot find any good documentation on how to do that. But, it would still be useful to be able to specify the cache directory on the command-line on a per-build basis.

**Comment by envygeeks** [comment]
This belongs upstream at https://github.com/jekyll/jekyll-sass-converter as a requested feature.

**Comment by ctubbsii** [comment]
Even if it is a feature available in @jekyll/jekyll-sass-converter, it would still be useful to add a command-line into jekyll proper for build-time exposure to the configuration.

**Comment by envygeeks** [comment]
We do not tell Jekyll Sass Converter where to put it's folders, it creates it's own cache folder and does it's own job.  If you wish to have that folder customized it needs to go through that plugin so that they can file a downstream ticket asking for a more targeted feature than you are.  The surface of your issue belongs there as they are the ones who ultimately have to implement anything we implement to allow them to implement what you want.

This issue belongs there, or you can file a more targeted issue.

**Comment by ctubbsii** [comment]
One way to achieve this might be to simply add an option to specify the build working directory to change to before doing a build (and before evaluating any relative paths in the other options). That way, there'd be no need to address any specific plugin explicitly. This feature is quite useful for the `tar` command (it's `-C, --directory=DIR: change to directory DIR`), and would be useful for jekyll, for the same reasons.

I suppose users could use the `-s` option with clever use of `cd` and subshells, but the `-C` option is *really* useful, I think.

**Comment by envygeeks** [comment]
There is no solving this without them implementing and changing their behavior, ***we do not create the .sass-cache folder, jekyll-sass-converter creates it's own folder***, the most we could do is create a feature that allows them to set an option on our CLI to set their own folder agnostically or create a folder for them to place their folders in so that you can move that folder wherever you want.  Past that it is jekyll-sass-converters problem as they create their own folders, they manage their own data.  We do not control it, we do not tell it where to go.  It does it all on it's own.

**Comment by ctubbsii** [comment]
I understand that... but without changing jekyll-sass-converter at all, or any other specific plugin which has this behavior of treating the "current working directory" for a special purpose, they could be controlled by giving users the option of changing the current working directory (the `-C` option I proposed) during jekyll's execution. If that's still not something jekyll wants to add, that's fine... the workaround is to use `cd`, along with `-s` and `-d` options to switch manually prior to execution of jekyll. (It's just easier if the `-C` option were available... but not necessary).

(FWIW, I did try adding `sass: { cache: false }` to my `_config.yml`, but it seems to be ignored. But that's not really relevant in the context of the current discussion about a general solution for changing the current working directory, and is probably a specific bug related to jekyll-sass-converter.)

**Comment by parkr** [comment]
I don't agree that this should be a switch on the executable (e.g. `jekyll build -C sass-cache-location`). If at all, it should be configured in the `_config.yml` via `sass: { cache_location: "myLocation" }`, but that's still up for debate. 

I'm going to close this here because we will not be accepting more switches for `serve/build` for things like this. If you want to talk about customizing the location of the cache, please write an issue on the jekyll-sass-converter repository and justify why you believe it should be customizable, what it prevents when it cannot be customized, and the configuration structure you'd like to see for setting the location.

Thanks!
