### ISSUE TITLE
Dependency Error

### ISSUE THREAD

**Issue by yifanchen** [jekyll/jekyll#4688]
###### What version of Jekyll are you using (`jekyll -v`)?
jekyll: 3.1.2
gem: 2.5.1 
ruby: 2.2.3p173

###### What operating system are you using?
OSX El Capitan

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I downloaded Notepad theme, tried to run `jekyll build`, I also tried `gem install pygments.rb` and `gem 'pygments.rb'`. It still threw me errors when run `jekyll build`.

###### What did you expect to see?
no error, build success.

###### What did you see instead?
`Dependency Error: Yikes! It looks like you don't have jekyll-paginate or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-paginate` 

Thanks,

**Comment by pathawks** [comment]
Sorry to hear you're having trouble.

Neither **jekyll-paginate** nor **pygments** are required by Jekyll. It sounds like you are having some trouble with your theme.

This issue tracker is for bugs within Jekyll itself. For help using Jekyll, you might find more help by asking your question at [talk.jekyllrb.com](https://talk.jekyllrb.com/)

**Comment by yifanchen** [comment]
@pathawks I tried couple different themes, same errors.

**Comment by envygeeks** [comment]
What is inside of your `_config.yml`?

**Comment by parkr** [comment]
@yifanchen This doesn't look like a bug with Jekyll so I'm going to close this.

Remove `jekyll-paginate` from your `_config.yml`, or run `gem install jekyll-paginate`. Please search talk.jekyllrb.com for your issue and post a topic if you can't find anything that will help. The community is happy to help solve your problem there. 😄

**Comment by prasadariyawansa** [comment]
C:\Users\Dhanu\Desktop\jekyllblog>jekyll new .

New jekyll site installed in C:/Users/Dhanu/Desktop/jekyllblog.
Dependency Error: Yikes! It looks like you don't have bundler or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- bundler' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
jekyll 3.3.1 | Error:  bundler


I want to create new jekyll file structure but I get this error. Please help me to  solve this problem

**Comment by quiltbag** [comment]
@prasadariyawansa looks like you need to run `gem install bundler`

**Comment by prasadariyawansa** [comment]
Thanks . I fixed this error.
