### ISSUE TITLE
any interest in abstracting post file location?

### ISSUE THREAD

**Issue by hackerhasid** [jekyll/jekyll#4740]
I have a need to generate posts using a source other than the local filesystem. There's a couple ways to handle this:

1. Write a script that reads from the remote location and generates the local post files and then run vanilla jekyll
2. Modify Jekyll to use different Readers based on configuration (default would of course be the current PostReader that uses the filesystem)

The way I see it path 2 is preferred _only if_ there's interest in this change upstream. If you guys don't see this as fitting in to the goal of Jekyll (or see it making the codebase overly complex) then I'll go with option 1. But I'm proposing path 2 because I _think_ it could be useful to others.

Thoughts?

**Comment by parkr** [comment]
Hey @hackerhasid –

We have considered this, and this is one reason that `Document`, a relatively new class, has its `#read` method called directly rather than reading a file through `#initialize` like `Post` and `Page` did/does.

What kind of reader were you thinking? I don't want to do this with configuration ( /cc @jekyll/stability ) if this does happen because configuration is what makes Jekyll hard to work with for newcomers in the first place, but I think plugins could easily provide and change readers themselves. ( #4703 )

I could see a database reader being useful for certain folks, but not within core. What I'd really recommend is that you "monkey patch" `Site#read`.

**Comment by hackerhasid** [comment]
I currently have a need for a mysql database reader but could see this being useful for generating sites from a CMS, git, or even s3.

I definitely don't think 3rd party readers belong within core - it's def an advanced use case. I'll look into monkey patching `Site#read` and get back with thoughts.

**Comment by hg** [comment]
yeah, if it's done, then not in core, rather in an official plugin perhaps?

**Comment by parkr** [comment]
This is a better discussion to be had on [Jekyll Talk](https://talk.jekyllrb.com), so I'm going to close this out. Best of luck!
