### ISSUE TITLE
Detect user agent in plugin using jekyll hooks

### ISSUE THREAD

**Issue by mfbx9da4** [jekyll/jekyll#4764]
###### What version of Jekyll are you using (`jekyll -v`)?
3.03

###### What operating system are you using?
mac os x el capitain

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Created a plugin with the following hook

```ruby
Jekyll::Hooks.register :pages, :pre_render do |a,b|
  # code to call after Jekyll renders a post
  user_agent = a["user_agent"]
  message = "Got something pages #{a}, startb #{b}"
  puts message
end
```

###### What did you expect to see?

I hoped to be able to get the user agent from one of the variables. I would like to be able to render differentially some html based on the device. Ultimately would like to do this

```html
{% if is_mobile %}
    <!-- mobile html -->
{% else %}
    <!-- desktop html -->
(% endif %}
```

###### What did you see instead?

Reading [PR #3553](https://github.com/jekyll/jekyll/pull/3553/files) I think I saw the site payload, all the html and config? Is it not possible to get the user agent in a plugin?

**Comment by envygeeks** [comment]
You cannot get the users agent unless you integrate with WEBRick which is a bad idea since WEBRick is not production ready so the feature just isn't worth it because it'll only be viable for development.

A static webpage can only get the user agent from JavaScript and alter the page via the front-end with front-end languages (again like JavaScript.) Otherwise you'll need a full-blown app like Rails to achieve what you wish which will bring you out of the realm of what we are trying to achieve here.

Sorry.
