### ISSUE TITLE
Jekyll sees ruby 1.9.3,  but I installed ruby 2.2.3

### ISSUE THREAD

**Issue by amihaiemil** [jekyll/jekyll#4770]
###### What version of Jekyll are you using (`jekyll -v`)?
Jekyll v 2.5

###### What operating system are you using?
Ubuntu 14.04 LTS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I wanted to install jekyll using ruby gems: 
 ``sudo gem install jekyll`` - this failed with error:
``ERROR:  Error installing jekyll:
	jekyll requires Ruby version >= 2.0.0.``

I then noticed I have ruby 1.9.3 installed, so I installed ruby 2.2.3, but jekyll has the same behaviour,

###### What did you expect to see?

I would have expected to be able to install jekyll using ``sudo gem install jekyll``

###### What did you see instead?

Ruby version 2.2.3 still wasn't spotten.

However, when I run ``ruby -v`` I get ``ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]``,
so I assume ruby installed fine. 

Finally, I managed to install Jekyll v 2.5, but everytime I run a command I see the following message:

```DEPRECATION WARNING:
Sass 3.5 will no longer support Ruby 1.9.3.
Please upgrade to Ruby 2.0.0 or greater as soon as possible.```

**Comment by envygeeks** [comment]
How did you install Ruby?  That said, your Gem is pointing to Ruby 1.9.3, regardless of what your Ruby version is, your gem command is attached to the Ruby 1.9.3 you have installed we will see Ruby 1.9.3 and there is nothing we can do about that. Since Ubuntu does not provide Ruby 2.2 I'm to assume you either compiled it yourself, used RVM (of which we can do naught to help you) or by another means.

In your case start with finding out where `gem` points to with `which gem`, catting that file to see what Ruby it points to and then find out why your intended gem is not within your path properly.

Ultimately though this is a systems problem, if you need more help please feel free to ask at https://talk.jekyllrb.com and I'll continue to help you but this medium is for Jekyll bugs only.

**Comment by amihaiemil** [comment]
@envygeeks Thanks for the information.

**Comment by harry-wood** [comment]
I had a problem like this when I was trying to install jekyll in a Vagrant virtual machine. Vagrant runs bash in "non-interactive" mode. Are you doing anything like that? or just typing the commands directly in a terminal? More details here in case it helps: https://talk.jekyllrb.com/t/install-problem-with-rbenv/3068/1

I had the same thing, that `ruby -v` looked fine. I can't help feeling a bit suspicious that there may be something non-standard jekyll is doing when it comes to choosing which ruby to run with.

**Comment by amihaiemil** [comment]
@harry-wood I was doing everything in my terminal, no virtual machine. To be honest, I dont remember what the exact issue was, but it was on my side. In the end I just reinstalled the OS from scratch, had a fresh start and everything worked fine :D
