### ISSUE TITLE
[website feature] #jekyll irc sync with gitter + sidecar on website

### ISSUE THREAD

**Issue by strages** [jekyll/jekyll#4841]
The #jekyll irc channel would see more engagement if the accessibility would be improved. This would be doable by creating a mirrored irc gitter channel like on https://hearthsim.info/ .

When this is available a gitter chat could be added to the jekyll homepage like in: https://sidecar.gitter.im/

**Comment by envygeeks** [comment]
We have forums for engagement.  The IRC channel and the likes see very little traffic AFAIW (so much so that in the past I didn't even bother logging into it more than once or twice.) And while I don't think they should be taken down, I do think like most modern projects, most traffic should be directed to the forum.

**Comment by parkr** [comment]
@strages Nifty idea! I'm definitely with @envygeeks on this one – our forum is the primary place we are asking folks to post questions, ideas, etc. Our IRC _is_ fairly active (I was just there today!), moderated by the venerable @jaybe-jekyll and logged to https://irc.parkermoo.re and https://botbot.me/freenode/jekyll/ so we can refer back to conversations. I use IRC via LimeChat for Mac OS X and find it very approachable indeed and we list it on https://jekyllrb.com/help/.

We try to provide the best resources for our users, but only have so much time and energy to maintain them. We hope you understand! Hope to see you around. 😄
