### ISSUE TITLE
HTTPS+Let's Encrypt  support in jekyll serve

### ISSUE THREAD

**Issue by tomer** [jekyll/jekyll#4983]
With the recent announcment of [efforts to add a built-in CMS to `jekyll serve`], I think the `serve` command should support HTTPS, so people will be able to run it over the web without worrying of sending data over clear text. This won't be an issue for people who run `serve` locally and than push changes to the server, but if someone will run it on the production server, well, it might be an issue. 
[efforts to add a built-in CMS to `jekyll serve`]: https://jekyllrb.com/news/2016/06/03/update-on-jekyll-s-google-summer-of-code-projects/

Here is my suggestion: 

* An `--https` flag should be added to `jekyll serve` to trigger HTTPS support. This will change the default `--port` to 443 instead of 80.
* If `--host` is omitted, provide self-signed certificate; preferably generated on the first run, so it will be unique to every server.
* If `--host` is included, and looks like a valid domain, try to retrieve valid certificate from [Let's Encrypt] service.
* If `--host` is included, and Let's Encrypt certificate is soon to expire, update it in the background, so there won't be any interruption on the service. 

[Let's Encrypt]: https://letsencrypt.org/

**Comment by envygeeks** [comment]
All but the enabling of SSL if you provide a key is up to you and is an ops problem.  We are not an ops tool.  Adding most of those options is a burden on support and development and adds complexity for us on topics that really belong to you, your system (your ops.)

On the enabling of SSL if you provide a key, that's already in Jekyll, it's been there since I added it probably a year ago and the GSoC people ***should*** keep the same interface to reduce friction but they shouldn't use webrick to do it (they would preferably use a  forked server like Unicorn for obvious reasons.)

```
jordon@who [talk.jekyllrb.com:up:noerr] ~/development/jekyll/jekyll
→ jekyll help serve

jekyll serve -- Serve your site locally

Usage:

  jekyll serve [options]

Options:
            --ssl-cert [CERT]  X.509 (SSL) certificate.
            --ssl-key [KEY]  X.509 (SSL) Private Key.
```

As for adding an `--https` flag on top of that, I think that adds no value (if little) to something that's already automatic if you provide `--ssl-cert` and `--ssl-key`.  The port shifts to 443 and the url shifts to https automatically on your behalf when you provide a key and certificate.

**Comment by tomer** [comment]
I don't see SSL/TLS support on my Jekyll installation (3.0), so I'm very sorry about opening an issue for something that is already implemented. As for the letsencrypt part of this issue, I think it worth implementing, as the most important part of letsencrypt is the server taking care of renewing certificates automatically, so the user don't have to. Since `jekyll serve` is the server, and letsencrypt agent require placing some random files for the authentication process to complete, I think that Jekyll should support letsencrypt and [the ACME protocol]. 

[the ACME protocol]: https://letsencrypt.org/how-it-works/

**Comment by envygeeks** [comment]
It does add value, I can see that, I also think it adds no value to core, this is a feature that should be implemented as a plugin (and if enough people voice support for this I'll happily build the plugin if nobody else on @jekyll/core wants to) because it requires non-parallel releases.  It also requires some additions to support hooks in the interfaces so that things can tie into the interface cleanly without having to take it over making things even more unclear and unmanageable and so that it can be optional.

I for one would be absolutely livid to the point I would voice it aggressively if Jekyll started generating (or even tried pulling an) SSL certificate for me because we have bots that already do that and we already have high throughout balancers and routers that deal with all that outside of the server and because our Jekyll's could land on any number of servers at any given time.

Ultimately though I think this is a problem for a plugin though, the only part of this that belongs here is the hooks to the interface which requires some thoughts because hooks load late so there would need to be a early load system for interface hooks.

**Comment by parkr** [comment]
I think this is a great plugin idea. Sounds like it kind of mimics [rsc.io/letsencrypt](https://godoc.org/rsc.io/letsencrypt) but for Jekyll.

I agree however that it's not suitable for core. More to the point for me, `jekyll serve` is NOT a suitable production server and we do not recommend it. I would rather spend what little time I have for OSS on building out the stability of Jekyll as a static site generator, not its teeny development server. That said, @envygeeks, if you want to build this, I'm sure there are tons of folks who would find it really useful! 👍 

Thanks again for the suggestion 👍
