### ISSUE TITLE
Filter to get absolute URL

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll#5070]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

It would be nice if there were some way on a Liquid template to get the absolute URL of a Jekyll document.

Currently, several plugins have different incantations of prepending `site.url + site.baseurl` or `site.github.url`. It would be nice if core included One True Way to facilitate this. This way, a Liquid template could just do something equivelant to:

```text
{{ page.url | absolute }}
```

or

```text
{{ page.absolute_url }}
```

For background, see [jekyll/jekyll-sitemap#112 (comment)](https://github.com/jekyll/jekyll-sitemap/issues/112#issuecomment-222330371)

I would be happy to submit a pull request if others agree this would be of value.

**Comment by envygeeks** [comment]
Personally I feel this is entirely out of scope for Jekyll.

**Comment by pathawks** [comment]
> Personally I feel this is entirely out of scope for Jekyll.

The other two alternatives I see are:

 1. Each plugin/theme develops its own (probably quirky) way to handle URLs.
 2. A plugin is developed that handles URLs, and any plugin/theme that needs absolute URLs can reference this plugin as a dependency.

The current situation (Alternative 1) has caused users to run into edge cases where their URLs are handled correctly by some plugins and not others, and differing expectations of how they even _should_ be handled.

So it sounds like Alternative 2 is your recommendation?

**Comment by envygeeks** [comment]
Two, it sounds okay.  If @jekyll/core and @jekyll/plugin-core agree we could make it a default plugin too.

**Comment by parkr** [comment]
I think hyperlinks are a core part of what Jekyll does. It builds webpages and other content and in doing so we have always offered template-based URL building. [My post about `baseurl`](https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/) is easily one of the most-referenced pages on my site. `site.baseurl`, `site.url` and now `site.github.url` cause a lot of confusion. It'd be nice to provide a unified/centralized way of doing this.

I'd be up for the idea of releasing filters (our `lib/jekyll/filters.rb` file) separately from the `jekyll` gem (but as a standard dependency) and adding a core set of filters there, including this one. There is definitely value in having some kind of `absolute_url` that knows about the github-metadata plugin (`site.github.url`) as well as the standard jekyll values of `site.url` and `site.baseurl`.

Increasing the number of plugins users have to contend with without a lot of visibility is frustrating. I also see value in including a filter like this in Jekyll core to reduce the overhead of Yet Another Default Gem.

| | Pros | Cons |
|:--:|:--:|:--:|
| filters plugin | separate from jekyll core release cycle, more easily extendable & isolated, could ship with liquid extensions or something which empower tags and filters to be easier to write | Yet Another Gem to manage or have conflicts with, Yet Another Gem to maintain on our side, Decentralization of a major piece of Jekyll (standard Liquid extensions) |
| jekyll core filter | no extra gems to download, all plugins can just assume jekyll dependency instead of separate filters plugin dependency, fewer moving parts for users w.r.t. changing versions and updating | slower updates as it's tied to jekyll core release cycle, more maintenance burden on Jekyll Core Team, depends on liquid values from a plugin (github-metadata) that isn't always present |

**Comment by pathawks** [comment]
Now that themes exist, there really ought to be One True Way to create absolute URLs in Jekyll. Without this, users risk breaking links just by switching themes or – worse – themes and plugins creating URLs _differently_.

**Comment by parkr** [comment]
> Now that themes exist, there really ought to be One True Way to create absolute URLs in Jekyll. Without this, users risk breaking links just by switching themes or – worse – themes and plugins creating URLs differently.

:+1:. @benbalter, does this have your 👍 ?

**Comment by pathawks** [comment]
Fixed by #5399

**Comment by jubayed** [comment]
how to get # tag or ? 

like localhost:400/#something
