### ISSUE TITLE
Jekyll Error while installing with RubyGems!

### ISSUE THREAD

**Issue by AndyChen2005121** [jekyll/jekyll#5105]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [ ] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [ ] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [x] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps
<img width="571" alt="2016-07-15 08 22 08" src="https://cloud.githubusercontent.com/assets/16534460/16859884/449d810a-4a65-11e6-993a-eec3719cdd24.png">

Ruby installed, OpenSSL installed, RubyGems installed but still that problem.

## The Output I Wanted
 Installing successfully via RubyGems.

**Comment by parkr** [comment]
Hey @AndyChen2005121, did you try the suggestions we have [in our Mac OS X 10.11 troubleshooting docs](http://jekyllrb.com/docs/troubleshooting/#jekyll-amp-mac-os-x-1011)?

Try with `sudo`. If that doesn't work, don't use the system Ruby (install via rbenv or homebrew).

Hope that helps! This isn't a bug with Jekyll so I'm going to close it out, but I'll still get pinged if you reply.

**Comment by AndyChen2005121** [comment]
You...... 😡😡😡

ANOTHER PROBLEM!!!!!!!!!!!!
@parkr ?????????

Used homebrew to rebuild ruby, but still failed! SAME PROBLEM!!
And i can't find jekyll in homebrew!!!

LIER!!!!!!
😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡

**Comment by DirtyF** [comment]
Hey @AndyChen2005121, sorry you're running into troubles, but anger won't help you ;)

In order to proper install a ruby environnement on OS X : 

- First you must install OSX command line tools if you haven't
- then you can install homebrew in order to install rbenv (not ruby or jekyll)
- then you can install ruby gems like bundle, jekyll or github-pages on your machine

I suggest you follow this howto to setup your environnement:  https://gist.github.com/r-brown/a0b50d56cfb3596e0d17

@parkr What do you think of adding a section on this kind of setup in the Jekyll documentation?
