### ISSUE TITLE
localhost serving; warning in log about auth-key that should be irrelevant

### ISSUE THREAD

**Issue by paul-hammant** [jekyll/jekyll#5132]
- [x ] I believe this to be a bug, not a question about using Jekyll.
- [x ] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x ] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

- [x ] I am on (or have tested on) ***OS X*** 10.10.5

- [x ] It was another bug.

## My Reproduction Steps

>$ bundle exec jekyll serve --watch --incremental
> [...]
> Regenerating: 4 file(s) changed at 2016-07-25 04:40:43    **GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.**
...done in 6.506134 seconds.

## The Output I Wanted

I wanted Jekyll to serve without warnings. 

I don't want to have to specify a phone-home credential just to serve on localhost.

**Comment by parkr** [comment]
Hey @paul-hammant, this can be fixed by removing `jekyll-github-metadata` from your `gems` directive in your `_config.yml`, by not using the `github-pages` gem, or by [providing the credentials](https://github.com/jekyll/github-metadata#authentication).

In our assessment, it was better to present a warning indicating that some data may be missing or incorrect when that may be the case. It only affects the `site.github` namespace.
