### ISSUE TITLE
quote handling in front matter title incorrect

### ISSUE THREAD

**Issue by dret** [jekyll/jekyll#5171]
https://github.com/dret/webconcepts/blob/gh-pages/specs/IETF/RFC/6271.md uses jekyll front matter and has quotes in the title. it thus escapes those quotes. http://webconcepts.info/specs/IETF/RFC/6271 is the web view of that. while the HTML body//h1 title is correct, the HTML head//title incorrectly escapes the escaped quote. this results in browser displaying the page title incorrectly, for example in tabs or in the history.
steps to reproduce are to simply create a jekyll page with an escaped quote in a quoted title in the front matter. i see this bug on my locally installed jekyll 3.1.6, as well as on github.

**Comment by jake-low** [comment]
Hi @dret, thanks for the bug report!

I wasn't able to reproduce this on my own site, so I cloned yours and poked around. I think the issue is that your `head.html` include, which comes from the theme you're using (jekyll/minima) uses an `escape` filter when setting the page title.

```
<title>{% if page.title %}{{ page.title | escape }}{% else %}{{ site.title | escape }}{% endif %}</title>
```

This takes the ampersands in the page title and escapes them again, causing the mangled title you're seeing.

The minima theme is doing this so that you don't have to; it's designed so that you can use HTML-unsafe characters in your title strings without worry. But since you're escaping "manually" it escapes your escapes, which isn't what you want.

I think your best bet is to write your titles as plain, un-escaped strings, and let Jekyll take care of escaping them where necessary. In this case, you could make this change:

```diff
- title:  "The Atom &#34;deleted-entry&#34; Element"
+ title:  "The Atom \"deleted-entry\" Element"
```

Or even this:

```diff
- title:  "The Atom &#34;deleted-entry&#34; Element"
+ title:  The Atom "deleted-entry" Element
```

... since Liquid doesn't require quotes around strings.

Hope this is helpful!

**Comment by dret** [comment]
On 2016-07-30 18:41, Jake Low wrote:
> Hi @dret <https://github.com/dret>, thanks for the bug report!

and thanks a lot for the detailed response!

> - title: "The Atom &#34;deleted-entry&#34; Element"
> + title: "The Atom \"deleted-entry\" Element"

https://github.com/dret/webconcepts/commit/b5efe07942988a02dfa74e2643cb515a33310ee7 
is doing this and seems to work. thanks for the suggestion.

> - title: "The Atom &#34;deleted-entry&#34; Element"
> + title: The Atom "deleted-entry" Element

this did not work (i would have preferred it) because it created some 
problems with other characters in titles. but having one working 
solution definitely is good enough. thanks!

**Comment by parkr** [comment]
Glad you got this sorted! We're at the mercy of Liquid and YAML here, sadly. :/

**Comment by dret** [comment]
i guess that's what you get yourself into when you happily mix markup languages a la YAML and HTML and MD. thanks for your help on this one!

**Comment by parkr** [comment]
@dret happily! and thanks to @jake-low 😄
