### ISSUE TITLE
jekyll serve not working on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by TAGraves** [jekyll/jekyll#5233]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

---

- [x] I am on (or have tested on) ***Windows*** 10+

---

- [x] It was another bug.

## My Reproduction Steps

```
jekyll serve
Configuration file: /path/to/_config.yml
            Source: /path/to
       Destination: /path/to/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.062 seconds.
jekyll 3.1.6 | Error:  Invalid argument - Failed to watch "/path/to/.git/hooks": the given event mask contains no legal events; or fd is not an inotify file descriptor.
```

This is almost certainly due to https://github.com/Microsoft/BashOnWindows/issues/216. I'm not sure if there's any viable workaround at the moment, but figured (1) it was worth bringing this to the jekyll team's attention, and (2) having a public issue for other users who run into this problem.

**Comment by envygeeks** [comment]
I'll get on my Windows system tonight to determine if we can reliably detect Windows+Bash Subsystem, I don't know if we can because last I remember the system information thought it was Linux but there must be a way.  I can always push something up to Jekyll-Watch that detects the lack of /proc/fs structure and retreats to polling instead.

That said, you should in theory be able to poll. Try running your command again with "--force-polling" and see what happens (you might have to do "--force_polling" I don't remember if the CLI treats them the same.)

**Comment by TAGraves** [comment]
Thanks for the response! `--force_polling` does indeed work.

**Comment by cnryb** [comment]
@envygeeks Thank you! I got the same question。
