### ISSUE TITLE
Custom Plugins are Ignored

### ISSUE THREAD

**Issue by jamiefolson** [jekyll/jekyll#5265]
I am trying to create a custom plugin and cannot get anything to work.  I've tried all of the examples, which did nothing and resorted to a simple test tag:

In `_plugins/testplugin.rb`
```ruby
module Jekyll
  class TestPlugin < Liquid::Tag
    def render(context)
      "It's Working!"
    end
  end
end

Liquid::Template.register_tag('testplugin', Jekyll::TestPlugin)
```

I even added this to my config:

```
plugins_dir: ./_plugins
```

But I still get an error:

```
jfolson@Ubuntu-Workstation:~/repos/jamiefolson.github.io.jekyll$ bundle exec jekyll build 
Configuration file: /home/jfolson/repos/jamiefolson.github.io.jekyll/_config.yml
            Source: /home/jfolson/repos/jamiefolson.github.io.jekyll
       Destination: /home/jfolson/repos/jamiefolson.github.io.jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid syntax error (line 3): Unknown tag 'testplugin' in plugin_test.md
jekyll 3.1.6 | Error:  Liquid syntax error (line 3): Unknown tag 'testplugin'
```

 when processing this file:

```
---
layout: default
title: Plugin Test
---

the quick brown fox jumps over the lazy dog.

Testing plugin output of '_plugins/testplugin.rb': {% testplugin %}
```

- [x ] I believe this to be a bug, not a question about using Jekyll.
- [ x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`

---

- [x ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux

- [x ] I was trying to build.

**Comment by Crunch09** [comment]
Hi @jamiefolson ,

you're using the `github-pages` gem and [it is always started in safe mode and the plugin_dir is a random string](https://github.com/github/pages-gem/blob/bd1018072aab370ddf63aa9c3938867e2133ac80/lib/github-pages/configuration.rb#L45-L70). If you want to use custom tags you need to use the `jekyll` gem directly. Hope this helps!

**Comment by jamiefolson** [comment]
So there's no way to use bundle exec with jekyll?  I removed the `github-pages` after I started using other plugins.

**Comment by jamiefolson** [comment]
Thanks, I didn't realize I'd need to remove it locally, too.

**Comment by errordeveloper** [comment]
I've just tripped over this also! Thanks @Crunch09 👍

**Comment by maxfarrior** [comment]
I've been trying to solve this problem for 3 days now. I could **not** figure out why my plugin **would not run**. I made sure all the software was installed, my _config.yml was good, all the directories existed, and even looked over the ruby plugin itself... Everything looked fine.

Then I found this post and changed 'github-pages' to 'jekyll' in my Gemfile and it worked. Great thanks to @Crunch09.

I knew that I couldn't use the plugin with Github Pages (from trying to figure out the problem), but I wasn't using Github Pages, I was building locally. This was the only info that I found that said to check my Gemfile.

**Comment by pathawks** [comment]
@maxfarrior Why were you using `github-pages` in your Gemfile to begin with? Was there something in our documentation?

Unless a user has a specific reason, we should be instructing them to use `jekyll` directly rather than `github-pages` I think.

**Comment by maxfarrior** [comment]
@pathawks I was using `github-pages` because I was modifying (somebody else's) theme that was intended to be hosted at Github Pages. I have no idea if they should be using `github-pages` or `jekyll`. But I didn't understand the difference, which caused the problem.

I misled myself. It was not the documentation.

**Comment by benbalter** [comment]
It sounds like the best solution here would be to post warning level feedback to the build output when a plugin is requested but ignored?

**Comment by errordeveloper** [comment]
Ben, that sounds good to me :)

**Comment by Thatkookooguy** [comment]
I'm having problems with this. Can someone point me to what I need to change in my `_config.yml`? where do I change `gh-pages` to `jekyll`?

**Comment by paradite** [comment]
For anyone experiencing this issue with `github-pages` gem:

I was trying to update `github-pages` gem to address a security vulnerability with jekyll, and bumped into this issue, it was working fine on `github-pages` version 50.

After some digging, I found that somewhere between version 60-75, the plugins starts to get ignored. I am not able to dig into it because the build was failing until I reached version 75.

I am surprised that a external gem can influence how `jekyll` works. I would expect `bundle exec jekyll serve` to work as documented: https://jekyllrb.com/docs/plugins/installation/. However, it seems that having an extra dependency breaks the behaviour even on local. Not sure why that happens.

**Comment by paradite** [comment]
> I'm having problems with this. Can someone point me to what I need to change in my `_config.yml`? where do I change `gh-pages` to `jekyll`?

Just replace 
`gem 'github-pages', group: :jekyll_plugins`
 with
`gem 'jekyll', group: :jekyll_plugins`
should be enough.
