### ISSUE TITLE
Add support for user overrideable theme files.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#5343]
One of the requirements we have for turning our themes into Gem based themes is that we be able to override a few theme files and have Jekyll use ours over theirs.  We provide a lot of broilerplate but it's not always that simple, sometimes we need to edit a single file for that specific site.

I propose we support overriding theme files locally if we can find them!

**Comment by pathawks** [comment]
It seems like this might lead to designing themes as a collection of many small files, so if a particular site wants slightly different wording in a themes footer, it can replace just that one part without loosing the ability to recieve updates from the theme in the future.

Are we cool with that? Is that the best direction for things to go? (I think probably; just trying to make sure we are all on the same page re: big picture)

**Comment by envygeeks** [comment]
@pathawks it's something we would need here,  and that's exactly what I would like but a little more tuned to a specification in our case.  The problem for us is adding stuff to a particular page, for example we could provide `__footer_extras.html`, and have it be blank (it has nothing in it, we care not about it upstream,) but include it, now you can include it in your site and boom, you just inserted extra content into my footer.  And if we really need to override a very specific theme file then we can also do that.  This solution solves many problems we would have with upstream themes that in things like Wordpress are simply solved with PHP or because themes are "local" by editing the theme directly, that's not so possible (easily -- at least) without either forking the theme, embedding the theme or creating a plugin (not supported on Github Pages.)

**Comment by envygeeks** [comment]
I should also /cc @jekyll/core @jekyll/ecosystem @jekyll/performance @parkr @benbalter

**Comment by pathawks** [comment]
WordPress also has a concept of child themes, where files in the child theme are used instead of files in the parent theme, and files in the parent theme are used when a file is _not_ provided be a child theme.

I agree that something like this would be good, and I like your idea of themes including blank files to be overridden.

I just want to make sure that some of these problems wouldn't be better served by some standard config options, or a concept like WordPress's filters and actions.

**Comment by envygeeks** [comment]
@pathawks I'm open to anything that would make us providing themes easier!

**Comment by parkr** [comment]
@envygeeks I think I'm misunderstanding but isn't that what we already do? The local site's `_layouts/default.html` takes precedence over the theme's `_layouts/default.html`. https://github.com/jekyll/jekyll/blob/master/site/_docs/themes.md#overriding-theme-defaults

**Comment by envygeeks** [comment]
@parkr I've not personally tried it but @ashmaroli implied it wasn't possible: https://github.com/jekyll/jekyll-assets/issues/331#issue-175917348 that is, for files other than the layout.

**Comment by ashmaroli** [comment]
Oh.. I stated that w.r.t. ***jekyll-assets*** `README` instruction to move `css/main.css` to `_assets/css/main.css` .
(I decide to move `/css/main.scss` instead since `/css/main.css` aint available yet.)

***this feature requested in this ticket works as intended, otherwise.***

--
**to reproduce (using Jekyll 3.2.1):**
-  `jekyll new test_blog`
-  `cd test_blog && mkdir _includes _assets`
-  copy `~gems/minima-1.0.1/_includes/head.html` to `~test_blog/_includes/`
-  move `/css/main.scss` to `/_assets/css/`
-  rename `/_assets/css/main.scss` to `/_assets/css/demo.scss/`
-  edit ~test_blog/_includes/head.html: replace `<link rel="stylesheet" [...]/>` with `{% css demo %}`
- add `jekyll-assets` to gemfile
- add `jekyll-assets` to `gems:` array; define `sources: [_assets/css]`; set `url` to `''` (all in `_config.yml`)
- `bundle exec jekyll serve` and head to `http://localhost:4000`

--
**obs**:   index.html reference `/css/main.css` not found.

**Comment by ashmaroli** [comment]
What I would like to see is to have `_assets` included as a theme-scaffold-directory and let users override theme assets (boilerplate .scss, .js and images) with their own.

**Comment by vwochnik** [comment]
+1 allowing files other then layout or includes, i.e. images, to be part of a theme

**Comment by benbalter** [comment]
> Oh.. I stated that w.r.t. jekyll-assets 

I believe this should be supported in Jekyll core.

**Comment by benbalter** [comment]
Can this be folded into https://github.com/jekyll/jekyll/issues/5341 or are the feature requests sufficiently distinct?

**Comment by envygeeks** [comment]
Yessum, that's fine with me @benbalter closing this in favor of #5431
