### ISSUE TITLE
Minor oddity in YAML_FRONT_MATTER_REGEXP

### ISSUE THREAD

**Issue by trans** [jekyll/jekyll#5390]
Quick back story: I just submitted a pull request for a small change to the `YAML_FRONT_MATTER_REGEXP`. (The change simply allows front matter to also be in `<!-- -->` style comments; useful for using a wiki as a post source, for example.)  In so doing I was using Rubular to test the regexp, and noticed a minor oddity in the regexp. It occurs both in the current regexp and my proposed change. 

The oddity is when adding text on the line directly after the final `---` or `...`. If text is present the 2nd regexp match is the `---` or `...`, but if the line is blank, then the 2nd match is blank and the `---` or `...` ends up tacked on to the 1st regexp match.  See http://rubular.com/r/aZ59Z6zd0I

I suspect this oddity does not actually break anything, some other portion of the code must handle the inconsistency without issue. Nonetheless it might be a good idea to have a look to see if the regexp can't be "evened out" to prevent any future problems arising.

**Comment by parkr** [comment]
That is interesting. I think you're right–it doesn't break anything AFAICT. If you want to take a crack at fixing it, please do! The tests will likely explode (e.g. can't read a document's yaml front matter properly anymore) so our test suite should protect us from breakages here.

Going to close this out because [our reading process](https://github.com/jekyll/jekyll/blob/87c745573fde23d5b7416e57774f95484752e288/lib/jekyll/document.rb#L408-L415) is unaffected by this oddity, but having this conversation preserved for posterity could be very helpful down the line.

Thank you, @trans!
