### ISSUE TITLE
JekyllAdmin not working with Jekyll 3.3.0.rc1

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll#5451]
I'm not able to serve a new jekyll site with Jekyll 3.3.0.rc1 if `jekyll-admin` has been included.

## I'm using
- Jekyll 3.3.0.pre.rc1
- Ruby 2.3.1
- Windows 7 x64

## To reproduce
```
jekyll new test-blog
cd test-blog
```
add `gem "jekyll-admin"` to `Gemfile`
add `- jekyll-admin` to `site.gems` in `_config.yml`
```
bundle exec jekyll serve
```
## What I get:
```
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.796 seconds.
                    --watch arg is unsupported on Windows.
                    If you are on Windows Bash, please see: https://github.com/Microsoft/BashOnWindows/issues/216
Configuration file: ~/_config.yml
  JekyllAdmin mode: production
jekyll 3.3.0.pre.rc1 | Error:  wrong number of arguments (given 2, expected 3..4)
```
## Also tried:
update Gemfile:
```ruby
gem "jekyll-admin", :github => "jekyll/jekyll-admin"
```
```
bundle update
bundle exec jekyll serve
```

--
/cc @jekyll/ecosystem

**Comment by ashmaroli** [comment]
@DirtyF, if you're still online, can you confirm this?

**Comment by Crunch09** [comment]
@ashmaroli I can confirm this. Seems related to https://github.com/jekyll/jekyll/pull/5431/commits/a945a658188d4cd8ac04f919ec2d0e0dc59e01e0 . Looking into this now.

![screen shot 2016-10-06 at 08 58 53](https://cloud.githubusercontent.com/assets/570608/19143268/228c614c-8ba3-11e6-9e19-10efcd88d0d7.png)

**Comment by Crunch09** [comment]
Thanks @ashmaroli , just submitted a PR to jekyll-admin to fix this.

**Comment by ashmaroli** [comment]
ohh.. that means Jekyll 3.3.0 release should be postponed further..

**Comment by Crunch09** [comment]
When i think about it, maybe it would be wiser to just revert https://github.com/jekyll/jekyll/pull/5431/commits/a945a658188d4cd8ac04f919ec2d0e0dc59e01e0 .  #5431 would still work without it and jekyll-admin would not need to require at least jekyll 3.3 for the new code to work.

**Comment by DirtyF** [comment]
@Crunch09 IMHO that's it's better to ask `jekyll-admin` users to upgrade as there are a lot of people who have problems with `site.github.url` locally.

**Comment by ashmaroli** [comment]
But if PR-5431 would work without the `refactoring`, then `revert` should be like best of both worlds..

**Comment by Crunch09** [comment]
I left the PR open for now and let the maintainers decide but i agree that the revert of the refactoring probably would be the best solution as the fix of `site.url` would still work.

**Comment by benbalter** [comment]
Suggested how `jekyll-admin` can code around this over in https://github.com/jekyll/jekyll-admin/pull/227#issuecomment-251971461.

**Comment by interglobalmedia** [comment]
Hi,

I have been installing and re-installing Jekyll 3.3.1 all day trying to get it right, but I also have the above issue. Before I installed Sierra, it was worse. Now at least I got my gems working (separate issue), and so I don't get errors with Jekyll, but I do get this in iTerm2 when I `gem install jekyll bundler`:

gem install jekyll bundler                                           ⏎
Fetching: liquid-3.0.6.gem (100%)
Successfully installed liquid-3.0.6
Fetching: kramdown-1.13.2.gem (100%)
Successfully installed kramdown-1.13.2
Fetching: mercenary-0.3.6.gem (100%)
Successfully installed mercenary-0.3.6
Fetching: safe_yaml-1.0.4.gem (100%)
Successfully installed safe_yaml-1.0.4
Fetching: colorator-1.1.0.gem (100%)
Successfully installed colorator-1.1.0
Fetching: rouge-1.11.1.gem (100%)
Successfully installed rouge-1.11.1
Fetching: sass-3.4.23.gem (100%)
Successfully installed sass-3.4.23
Fetching: jekyll-sass-converter-1.5.0.gem (100%)
Successfully installed jekyll-sass-converter-1.5.0
Fetching: rb-fsevent-0.9.8.gem (100%)
Successfully installed rb-fsevent-0.9.8
Fetching: ffi-1.9.17.gem (100%)
Building native extensions.  This could take a while...
Successfully installed ffi-1.9.17
Fetching: rb-inotify-0.9.7.gem (100%)
Successfully installed rb-inotify-0.9.7
Fetching: listen-3.0.8.gem (100%)
Successfully installed listen-3.0.8
Fetching: jekyll-watch-1.5.0.gem (100%)
Successfully installed jekyll-watch-1.5.0
Fetching: forwardable-extended-2.6.0.gem (100%)
Successfully installed forwardable-extended-2.6.0
Fetching: pathutil-0.14.0.gem (100%)
Successfully installed pathutil-0.14.0
Fetching: public_suffix-2.0.5.gem (100%)
Successfully installed public_suffix-2.0.5
Fetching: addressable-2.5.0.gem (100%)
Successfully installed addressable-2.5.0
Fetching: jekyll-3.3.1.gem (100%)
Successfully installed jekyll-3.3.1
Fetching: bundler-1.14.0.gem (100%)
Bundler and RubyGems.org are free for anyone to use, but maintaining them costs more than $25,000 USD every month. Help us cover those costs so that we can keep the gem ecosystem free for everyone: https://ruby.to/support-bundler
Successfully installed bundler-1.14.0
19 gems installed
```

Then when I do a jekyll install with `jekyll new front-end-developer-portfolio` I get:

New jekyll site installed in /Users/mariacam/Development/front-end-developer-portfolio.
Running bundle install in /Users/mariacam/Development/front-end-developer-portfolio...
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using public_suffix 2.0.5
Using colorator 1.1.0
Using ffi 1.9.17
Using forwardable-extended 2.6.0
Using sass 3.4.23
Using rb-fsevent 0.9.8
Using kramdown 1.13.2
Using liquid 3.0.6
Using mercenary 0.3.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using bundler 1.14.0
Using addressable 2.5.0
Using rb-inotify 0.9.7
Using pathutil 0.14.0
Using jekyll-sass-converter 1.5.0
Using listen 3.0.8
Using jekyll-watch 1.5.0
Using jekyll 3.3.1
Installing jekyll-feed 0.8.0
Installing minima 2.1.0
Bundle complete! 3 Gemfile dependencies, 21 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from minima:

----------------------------------------------
Thank you for installing minima 2.0!

Minima 2.0 comes with a breaking change that
renders '<your-site>/css/main.scss' redundant.
That file is now bundled with this gem as
'<minima>/assets/main.scss'.

More Information:
https://github.com/jekyll/minima#customization
----------------------------------------------
```

And these are the files I get with my installation:

```
Maria-Campbells-Computer-2 ॐ  ~/development/front-end-developer-portfolio:
11580 ◯  ls
Gemfile      Gemfile.lock _config.yml  _posts       about.md     index.md
```

And when I run `bundle exec jekyll serve` I get:

```
Configuration file: /Users/mariacam/Development/front-end-developer-portfolio/_config.yml
Configuration file: /Users/mariacam/Development/front-end-developer-portfolio/_config.yml
            Source: /Users/mariacam/Development/front-end-developer-portfolio
       Destination: /Users/mariacam/Development/front-end-developer-portfolio/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.487 seconds.
 Auto-regeneration: enabled for '/Users/mariacam/Development/front-end-developer-portfolio'
Configuration file: /Users/mariacam/Development/front-end-developer-portfolio/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
[2017-01-20 22:10:44] ERROR `/favicon.ico' not found.
```

**Comment by pathawks** [comment]
@interglobalmedia That seems totally unrelated to this issue.
