### ISSUE TITLE
Configure MIME type in front matter?

### ISSUE THREAD

**Issue by samholmes1337** [jekyll/jekyll#5454]
I've had an idea for a feature that I believe would be a wonderful addition to the engine!

I'm not entirely sure if this is the right place for this kind of feature request so please redirect me if I should consult the liquid templating repo instead. I'd also be happy to implement this myself if there was a chance it would be merged.

```
---
type: application/json
---
{ "message": "Hello, world!" }
```

Or something along these lines. The reasoning behind this is so you could host JSON files with pretty URL's (such as `example.io/data` to deliver `data.json`). Also if there would be a better way to go about this without requiring an intermediate step (such as `htaccess` or a web proxy) that would be ideal.

Thank you!

**Comment by envygeeks** [comment]
Jekyll is a static site generator, I don't think this idea will work out the way you think it will, in that... well, even if we can accept one and serve it internally in devmode, we've no way to tell your server of your custom mimetype, so ultimately this feature is just a dev feature that makes little sense (unlike say... the server itself that makes sense because it's annoying to have to boot up nginx to develop.)

That said, Jekyll doesn't host your site, and when Github hosts your site, they don't read your markdown files on the fly (which would be required) and would bring their scale down considerably and their costs up considerably... the burn on the feature would start demanding a price be paid in some way.

**Comment by samholmes1337** [comment]
Thank you for explaining! I wasn't sure whether `jekyll serve` was at all a similar process to what GitHub Pages uses so that really helps clarify. I'll continue thinking of other ways to do this, much appreciated! 👍

**Comment by envygeeks** [comment]
AFAIW (and I'm just guessing based on circumstantial evidence) Github generates your site and serves it through a high-throughput ha-proxy (I think it was Varnish? I thought I seen hints of Varnish in the headers -- can't remember)  @parkr or @benbalter can explain it more but I do know this much, they generate the site and then it's all static at that point with a standard setup at scale, it really is all static at the end of the day which is probably why they don't charge for it, because it's mostly bandwidth after the site is generated.

**Comment by samholmes1337** [comment]
That makes total sense. I was wondering if it would be possible to deliver a static json file without requiring the `.json` extension in the URL but it appears that the GitHub Pages routing configuration simply wouldn't allow for that.

**Comment by parkr** [comment]
@samholmes1337 Yeah, we use vanilla setup to reduce complication for the user. We vendor these: https://github.com/jshttp/mime-db/blob/master/db.json
