### ISSUE TITLE
collections pages loop not working on github

### ISSUE THREAD

**Issue by vincent-louis** [jekyll/jekyll#5589]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [x] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps
1. Build on locally and the looping of collections `site.collections.guides.docs` shown, generated the correct `.html` in `_site` folder as well.
2. However, when I deploy to github, it doesn't show the loop content.

## The Output I Wanted
shown the loop in github pages, appreciate if someone have a look [on my repo](https://github.com/vincent-louis/pixelcss/tree/gh-pages).

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by mmistakes** [comment]
Looks like you're using a really old version of Jekyll and the GitHub Pages gem locally. That would explain why it works for you locally but not on GH Pages. Perhaps updating the gems locally would give you parity with GH and could further test what the issue is.

What I would suggest is simplify your `Gemfile` to this:

If you run `bundle update` that should update the gems for you. Your `Gemfile.lock` should show `github-pages` being at version 39 instead of 35 verifying you're using the same version as GH Pages.

Then run `bundle exec jekyll serve` when firing up a local server or `bundle exec jekyll build` if just building.

**Comment by mmistakes** [comment]
Also I think you can simplify your collection loops to `site.guide` instead of `site.collections.guides.docs`

ref: http://jekyllrb.com/docs/collections/#accessing-collection-attributes

```html
<div class="row">
    <div class="col--12 col-md--10">
        {% for doc in site.guides %}
            <section id="section-{{ doc.anchor }}">
                {{ doc.content }}
            </section>
        {% endfor %}
    </div>
    <div class="show-md col-md--2 padding--left padding--top">
        <ul>
            {% for link in site.guides %}
            <li>
                <a href="#section-{{link.anchor}}">{{ link.title }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
```

**Comment by pathawks** [comment]
Looks like you're running into github/pages-gem#351

You might have to manually lock `pages-gem` to `104`
