### ISSUE TITLE
generate a site with about 60K posts, take forever

### ISSUE THREAD

**Issue by 404pnf** [jekyll/jekyll#560]
Tried to migrate a site from drupal to jekyll.  Unfortunately no migrate script for drupal 7.  So, I generated all individual posts(57882 of them) in _posts folder.   Ran jekyll.  Took forever and never succeed on a server (RAM: 12GB, CPU: 16 cores)

Is jekyll suitable for such volume of site?  What should I do to speed things up?

**Comment by davepeck** [comment]
Here's a case where I ran into this wall.

I've slowly been making moves to collect everything I post online under one (jekyll-managed) roof. As part of this, I exported my entire Twitter history and wrote a quick script to shred tweets into post files. Git handles these ~13,500 new files gracefully; Jekyll doesn't.

I'm not _surprised_ I ran into this wall; I certainly didn't expect Jekyll to perform nicely here. Then again, perhaps an argument can be made that somewhere in the distant future, Jekyll really _should_ handle this scale gracefully?

**Comment by parkr** [comment]
> perhaps an argument can be made that somewhere in the distant future, Jekyll really should handle this scale gracefully?

@davepeck We are working toward this goal, however Jekyll will still have to process all 13000 posts. Jekyll 3 does have an `--incremental` flag to ease pain after the initial regeneration, but there are still some missing pieces. Known improvement points:

- Read & write in parallel (disk I/O is expensive)
- Build dependency tree instead of naïvely rendering sequentially
- Cache more aggressively & ensure we're only producing what we need (ruby GC is very slow)

If you're willing to work on the above items or have further input, we can start a tracking issue for speeding up Jekyll if there isn't on already. Thanks!
