### ISSUE TITLE
All include paths should filter out nil

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll#5639]
### Steps to reproduce

1. Create a theme without an `_includes` directory
2. Create a page with an include
3. Build the site

### Expected

Include is loaded from the site directory

### Actual

Site errors out:

```
Liquid Exception: no implicit conversion of nil into String in index.html
Fatal: TypeError
no implicit conversion of nil into String
/hoosegow/.bundle/ruby/2.3.0/gems/jekyll-3.3.1/lib/jekyll/tags/include.rb:115:in `join'
```

The issue is that https://github.com/jekyll/jekyll/blob/master/lib/jekyll/site.rb#L438 returns nil, meaning there's a nil entry in the configure_include_paths array.

For includes (and layouts and sass, and assets) we should run the array through `compact` before returning from the method (to remove the null entries and prevent errors).

//cc @jekyll/ecosystem

**Comment by ashmaroli** [comment]
### Test Run..:
- create new jekyll site at `./test`
- configure to use new theme without `/_includes`
- add a page to *include* a file
- initial run `jekyll serve`:
```
[...]
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: no implicit conversion of nil into String in [layout]
```
- create `/_includes/includee.html` at source.
- run `jekyll serve` again..
```
[...]
Incremental build: disabled. Enable with --incremental
     Generating...
                   done in 1.856 seconds.
```

My opinion is that the current behavior is **not a bug**.  
If a layout requests an include and there is no `/_includes` dir itself in the hash, there should be something to inform the user (theme-developer / end-user) of the situation..

**Comment by ashmaroli** [comment]
*Update: This becomes a bug when `jekyll-assets` is added to the build*

--
/cc @envygeeks

**Comment by envygeeks** [comment]
Prove it's caused by Jekyll-Assets, if this is anything to do with _assets or "/assets" we ***will not be changing under any circumstance as we used that folder first and long before Jekyll even considered it so it's Jekyll's job to work nicely with us not our job to work around Jekyll.*** otherwise I see no clear proof this is caused by Jekyll-Assets and I'm not about to do all the work in tracking down such a vague bug that you think is caused by me.

**Comment by envygeeks** [comment]
That said, we don't go anywhere near Jekyll's stuff, how many times do I need to state that?

**Comment by ashmaroli** [comment]
Whoa! I wasn't incriminating **you**.. just pinged you because you maintain that plugin..

**Comment by ashmaroli** [comment]
from [here](https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/processors/liquid.rb)
```ruby
        def self.call(context, jekyll = context[:environment].jekyll)
          if context[:environment].parent.asset_config["features"]["liquid"] ||
              File.extname(context[:filename]) == ".liquid"

            payload_ = jekyll.site_payload
            renderer = jekyll.liquid_renderer.file(context[:filename])
            context[:data] = renderer.parse(context[:data]).render! payload_, \
              :filters => [Jekyll::Filters],
              :registers => {
                :site => jekyll
              }
          end
        end
```

**Comment by envygeeks** [comment]
Read that source again, we don't go anywhere near Jekyll's source by editing it.

**Comment by envygeeks** [comment]
I'll figure out where this bug comes from, something has changed somewhere and jekyll-assets might be the one triggering the bug, but I don't know that we are the one who owns the bug, we are just throwing filters into a Jekyll context along with Jekyll into Jekyll's own renderer process, we don't edit anything within those objects, we simply pass them to Liquid through Jekyll's renderer's, so I don't quite understand how us using Liquid through Jekyll could cause that problem.

Ultimately in another ticket I said there was nothing I could do about it, but there is one thing I can do about it, I can avoid Jekyll's Liquid renderer entirely and spin up my own wich might avoid this bug or surface where the bug originates, but ultimately I can't see how me throwing filters into Liquid would cause this, something is modifying the state where it shouldn't be (and we don't modify the state of Jekyll outside of a hook to add assets, and we surely don't modify the state of the configuration past ["assets"] and we certainly don't modify the state of Jekyll's own filters.)  We stick to our own lane strictly.

Like I said in Jekyll assets ticket, I'm intrigued as to how we are causing this.)

**Comment by envygeeks** [comment]
To note -- these are the places:

https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/hooks/jekyll/drops.rb
https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/env.rb#L46 (a removable relic)
https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/env.rb#L215

In the aforementioned source at: https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/processors/liquid.rb that context comes directly from Sprockets and [:data] is the result that we pass to Sprockets context to extract later, we don't write to Jekyll there, and the filters are only passed in so that users have access to those filters, we don't personally modify their state and if the state is being modified it would have to be within Jekyll or Liquid, along with `jekyll` as all that is modified long before that point and only in those few places.

**Comment by benbalter** [comment]
> My opinion is that the current behavior is not a bug.

At the very least, the error could be more descriptive (and for someone who contributes to Jekyll regularly and knows the internals, the behavior was unexpected).

If a theme doesn't have an includes (or assets, or sass) directory, I would expect that the theme would not affect the site's behavior in that regard.

If neither the theme nor the site have an include directory, the user should get a descriptive error that the include cannot be found.

Put another way, if today I try to include a file and get an include not found error, adding a theme to the site that also doesn't have an include shouldn't result in a less-descriptive error.

**Comment by ashmaroli** [comment]
> If neither the theme nor the site have an include directory, the user should get a descriptive error that the include cannot be found.

### Edge-case scenario:
- none of the documents at source has an `{% include -- %}` in it.
- none of the *layouts* within *theme-gem* has an `{% include -- %}` in it.

Then Jekyll rightly wouldn't raise any error if `/_includes` were not found in any of the sources because it doesn't matter.

But, I'm all :+1:  for a descriptive error message otherwise.
In the rare situation where a *plugin* unintentionally causes Jekyll to ignore overrides in `source_dir` and only read `theme_dir` (like this present issue), it would be *better* to be informed along similar lines to:
```
Liquid Exception: no implicit conversion of nil into String in index.md
           Error: '/_includes' directory not found in any of the sources!
```
