### ISSUE TITLE
downcase and cyrillic characters dont work

### ISSUE THREAD

**Issue by sdamo** [jekyll/jekyll#5656]
_posts/2016-12-01-example.md codepage UTF-8
```
---
layout: default
date: 2016-12-01 00:00:00 +0300
categories:
  - "Пример 1"
  - "Пример 2"
  - "Пример 3"
---
```

_layouts/default.html
```
<ul>
{% for category in page.categories %}
<li><a href="/{{ category | downcase }}">{{ category }}</a></li>
{% endfor %}
</ul>
```

**Comment by pathawks** [comment]
The `downcase` filter is part of [Liquid's standard filters](https://github.com/Shopify/liquid/blob/3-0-stable/lib/liquid/standardfilters.rb#L21-L24), so this is a Liquid issue rather than a Jekyll issue.

Unfortunately, the filter is just a wrapper around [Ruby's `downcase `](https://ruby-doc.org/core-2.1.0/String.html#method-i-downcase) which is only effective for ASCII characters.

**Comment by ashmaroli** [comment]
Ruby 2.4 has added `upcase`/`downcase`/`swapcase`/`capitalize` [support for non-ASCII characters](https://bugs.ruby-lang.org/issues/10085)
