### ISSUE TITLE
Overriding theme sass partials

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll#5704]
- I think this is a bug with Jekyll
- I'm using Jekyll 3.3.1 on Windows 7

At present, if a user needed to override one of minima's sass partials, they have to:
  - have a copy of the concerned sass partial at `source_dir` (expected, documented)
  - have a copy of the **main sass file (`_sass/minima.scss`) at `source_dir` as well.** (unexpected, undocumented)

#### Inference
  - Jekyll loads sass partial(s) at `source_dir` only if the main sass file importing the partial(s) is also present at `source_dir`

**Comment by parkr** [comment]
I think overriding sass partials with jekyll is a much too complicated procedure. CSS naturally cascades so add the styles you need and CSS will do its thing. I think we should be sticking to output CSS files instead of getting into the business of dealing with overriding sass partials.

That said, we do set the Sass LOAD_PATH to the site's source then to the theme so this should already be possible.

**Comment by ashmaroli** [comment]
hmm.. 
> I think overriding sass partials with jekyll is a much too complicated procedure... I think we should be sticking to output CSS files instead of getting into the business of dealing with overriding sass partials.

Our documentation does not say that though.. hence users tend to use the same formula for overriding any other theme file:
- copy partial to `<source>/_sass`
- make changes
- run `jekyll serve`

> so this should already be possible.

I'll try to come up with a cucumber feature to demonstrate this on my fork.

**Comment by ashmaroli** [comment]
> I'll try to come up with a cucumber feature to demonstrate this on my fork.

@parkr : 
branch compare: [review-me](https://github.com/jekyll/jekyll/compare/master...ashmaroli:theme-sass)
travis-log: [review-me](https://travis-ci.org/ashmaroli/jekyll/jobs/187614602#L448)
