### ISSUE TITLE
How to use the _site folder as source file?

### ISSUE THREAD

**Issue by etiennedesign** [jekyll/jekyll#5706]
Hi,

I would like to use my Jekyll _site folder as source folder for my website. I have sitemap and css minify plugin setted on my Jekyll site but Github pages display the files in the root and not in the generated _site folder. So the css/styles.css is used and not the _site/css/styles.css which is minified.

Do you know a way to achieve that?

Thanks!

Etienne

**Comment by DirtyF** [comment]
👋  Etienne,

Yes, GitHub does not support css minify plugin. In order to use css minification you have many options : publish the content of your `_site` folder (take a look at this [rake task](https://gist.github.com/DirtyF/2eacfb7ecec18b3b738af1c3c8d1fe5e) for instance) or host your site elsewhere where Jekyll plugins are not whitelisted (Netlify, GitLab, Now, etc.).

Please note that you can ask questions about Jekyll's usage on https://talk.jekyllrb.com/ or directly to GitHub support. This repo is intented for jekyll issues only. 😉

**Comment by etiennedesign** [comment]
Ok cool thanks for your reply.

I think i will have two repositories, one for the dev environment, and in the other one i will publish the content of the _site folder so it will be the actual production site.


Best Regards,
Etienne Leprette

WorkflowGen by Advantys <http://www.workflowgen.com/> 

Confidentiality Notice: The information contained in this email (including any attachments) is Confidential, it may contain proprietary information and may also be subject to legal privilege or otherwise protected from disclosure. It is meant solely for the intended recipient. If you are not the intended recipient, any disclosure, copying, distribution is prohibited. Please notify the sender immediately by e-mail if you have received this e-mail by error and delete this e-mail from your system.

**Comment by DirtyF** [comment]
@etiennedesign FYI you can publish this as two branches on the same repo, one with your source and one with the content of the site folder.

**Comment by etiennedesign** [comment]
@DirtyF But if i want to keep the development version of the site online, i have to use the gh-pages branch right?

I would like to have staging.mycustomdomain.com or XXX.github.io with the source files
Then mycustomdomain.com with the content of the _site folder

Can i have two online sites (dev&prod) on the same repo if i make a second branch?
