### ISSUE TITLE
Theme dependency missing from SASS load_path

### ISSUE THREAD

**Issue by straight-shoota** [jekyll/jekyll#5729]
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [x] I was trying to build.

## My Reproduction Steps
In a theme I want to use the [`bourbon`](https://github.com/thoughtbot/bourbon) gem for SASS. I added `bourbon` to `gemspec` and the `gems` setting in `_config.yml`. It is included in `theme.scss` with `@import "bourbon";`. Running `jekyll build` in the theme works perfectly including the bourbon styles.

Then I setup my main Jekyll folder to use the theme and got this error:
```
Jekyll::Converters::Scss encountered an error while converting 'css/main.scss':
File to import not found or unreadable: bourbon. Load path: /home/vagrant/.gem/ruby/2.3.3/bundler/gems/my-theme-c997ba6e749b/_sass
```

I also tried adding `bourbon` in the main Gemfile as well as adding it to the `gems` setting in the main `_config.yml`.

From the error output I suspect, the Jekyll theme loader sets the SASS load_path to the theme's SASS folder overwriting any other load_path that would have been set before by the `bourbon` gem.

# The Output I wanted
I would expect sass libraries from theme dependecies to be added to the load_path when the theme is used.

/cc @jekyll/build

**Comment by pathawks** [comment]
Seems related to #5704

**Comment by ashmaroli** [comment]
@straight-shoota Since you've not provided a link to your repo, we wont be able to give you an exact solution.  
Moreover, its not clear to me whether you're using a pre-existing theme-gem or developing a new theme-gem, and if you're developing a new theme, how exactly you are testing (e.g by using a `Rakefile` ?).

Nevertheless, the following steps outline how to go about using a fictional `bonbon` library alongwith Minima in a Jekyll site:
  - Create a `_sass` directory at `source`.
  - Include the `bonbon` library within the above `_sass`. This will give you:
    - `<source>/_sass/bonbon.scss`
    - `<source>/_sass/bonbon/_partialA.scss`
    - `<source>/_sass/bonbon/_partialB.scss`
  - Create an `assets` directory at `source` and **copy** Minima's `main.scss` over.
  - Import my fictional library into the main stylesheet:
  ```sass
  // <source>/assets/main.scss

  [... existing styles ...]

  // Import partials from the `minima` theme.
  @import "minima";
  @import "bonbon";
  ```

**Comment by straight-shoota** [comment]
Thank you @ashmaroli for the reply. I am creating my own theme-gem [smj-fulda-theme](https://gitlab.com/smj-fulda/smj-fulda-theme) and using it in [this jekyll repo](https://gitlab.com/smj-fulda/smj-fulda.org). Testing is done with gitlab-ci (see `.gitlab-ci.yml` in both repos), basically just `jekyll build`.
As a temporary workaround ([commit 9407454d](https://gitlab.com/smj-fulda/smj-fulda.org/commit/9407454d753ef758a0841e698cde05e55f58e8fc), I have remove the theme stylesheet include from the main site and instead included the prebuilt stylesheet from the theme-gem deploy.
The failing commit is [46ebcc20](https://gitlab.com/smj-fulda/smj-fulda.org/commit/46ebcc20f291429eba088dc47299a3e50fc852cb).

Your proposed steps put the sass source code for the library into the theme-gem repository. There are certain pros and cons of this approach, you get everything in one place but need an additional step to manually update this dependency instead of just running `bundle update bourbon`, since this SASS library is provided as a gem.
For my use case it would probably be sufficient to include the bourbon files directly into the `_sass` folder of the theme-gem. But I'd still consider this a bug in Jekyll: In the theme-gem `@import "bourbon";` works without putting the bourbon files into the repository, but in the main site it fails because the load path from bourbon-gem is ignored.

**Comment by ashmaroli** [comment]
Ah! Since you're developing your own theme-gem, then you have greater control, and hence, the recommended route is to *"install `bourbon`"* in your theme-gem's `_sass`. Manually update the library when required and bump your theme-version accordingly.  
Release a minor update of your theme if you update to `bourbon`'s minor release, else if you're updating to `bourbon's major release, then release a major update of your theme to prevent breaking of existing site(s) that use your theme.

> In the theme-gem @import "bourbon"; works without putting the bourbon files into the repository

I'm quite surprised when you say that `@import "bourbon";` actually fetches sass files from another gem entirely.

**Comment by straight-shoota** [comment]
Well, using `@import "bourbon";` is just one way it is supposed to work ;) 
I'm fine now with having copies of the bourbon files in the gem. From my point of view, this issue could be closed, unless you want to dig deeper into the different behaviour between theme and theme include.
