### ISSUE TITLE
Lazily build pages when serving

### ISSUE THREAD

**Issue by thejameskyle** [jekyll/jekyll#5846]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

I was wondering why Jekyll needs to build every single file when starting a server. If pages were lazily built when they were requested for the first time the server startup time would be significantly shorter.

Re-building could be a simple as invalidating every page in the cache and building them when requested again.

**Comment by parkr** [comment]
Hey. This is something we have actively worked on over time–you are not the first to suggest this. In short, we have an `--incremental` flag which offers users the ability to, after the initial build, only compile the necessary pages. The initial build is necessary because Jekyll doesn't know what `_site` contains and must therefore overwrite it. In essence, the cleanliness of `_site` is not guaranteed so we re-build it each time.

You may use `--skip-initial-build` with `jekyll serve` if you're restarting your server often and can trust the contents of `_site`.

Hope this clarifies things for you. Cheers!
