### ISSUE TITLE
Need permission to reply to thread on Jekyll Talk

### ISSUE THREAD

**Issue by tomjohnson1492** [jekyll/jekyll#5872]
With the newly reborn Jekyll Talk forum, it seems permissions to reply are restricted until a moderator adds the reply permission to my account. 

![accounthold](https://cloud.githubusercontent.com/assets/6385062/22799794/e3504148-eebb-11e6-8179-9e985d997ded.png)

@pathawks can you give me reply permission? maybe also set the default behavior on the forum to allow users to reply without review?

Thanks,

Tom

**Comment by pathawks** [comment]
It looks like it is freaking out if a user posts multiple links to the same domain, even if that domain is github.com

**Comment by parkr** [comment]
WOMP. Sorry about this! I'll get this sorted out here momentarily.

**Comment by parkr** [comment]
You should be good to go now. Sorry for the hassle!

**Comment by tomjohnson1492** [comment]
Thanks.

**Comment by lsrdg** [comment]
Sorry if a bit out of the scope of this issue, but is the forum working? It has been almost one month since last time it worked here... and I hadn't seen any issue about the forum so far, that's why the comment is here (feel free to delete it though). (:

**Comment by pnn** [comment]
@lsrdg http://talk.jekyllrb.com is loading fine for me, where are you trying to access it from?

**Comment by lsrdg** [comment]
@pnn, from home, same machine and connection I used to to load it before. In the beginning (of the year) it would take many minutes untill the browser gave up,  but on the last few weeks it has been:

> An error occurred during a connection to talk.jekyllrb.com. The server uses key pinning (HPKP) but no trusted certificate chain could be constructed that matches the pinset. Key pinning violations cannot be overridden. Error code: MOZILLA_PKIX_ERROR_KEY_PINNING_FAILURE

Sorry, I don't feel like flooding this issue with unrelated stuff... Since it's not a "Jekyll" problem it probably shouldn't be here, but how to report it on the forum if it is not even opening? :/

**Comment by ashmaroli** [comment]
perhaps doing a hard-refresh or clearing the browser-cache may help.

**Comment by lsrdg** [comment]
Thanks, @ashmaroli. It might be something related to that, because I just tried to open it again and it worked with chrome and chromium (but it *_wasn't_ last week). At least now I have access the forum again. o/

(May I just delete delete my previous comments - since they are unrelated to the issue?)

**Comment by pathawks** [comment]
@lsrdg You are correct. It was not working last week; it is now working again.

No need to delete comments. That would just make it look as if the rest are talking to ourselves 😛

**Comment by lsrdg** [comment]
Fair enough, and thank you for sharing the information, @pathawks (:
The forum is still working in a weird way, but if necessary it can hopefully be solved on the forum. ;)

**Comment by parkr** [comment]
The HPKP error is because it used certificate key pinning and we have a new
certificate now which uses a different key. Not sure when the pin expires,
but you are OK to ignore it as long as you can connect to talk.jekyllrb.com
with an HTTPS connection.

**Comment by lsrdg** [comment]
Thanks, @parkr. The forum is working in Chromium and Chrome but not in Firefox, despite of cleaning the cache etc. Weird, but as you said, as long as there's connection to talk.jekyllbr.com it is OK. 
Thank you everyone (:
