### ISSUE TITLE
When will there be Jekyll for Windows? =(

### ISSUE THREAD

**Issue by lffg** [jekyll/jekyll#5911]
When will there be Jekyll for Windows?

**(Official)**

**Comment by pnn** [comment]
@lffg are you having any sort of trouble with installing jekyll on windows? it should work if you follow the [installation instructions](https://jekyllrb.com/docs/installation/)

**Comment by lffg** [comment]
Yes.
Jekyll is not working.

**Comment by pnn** [comment]
@lffg could you detail your problems? what does the console output say?

**Comment by ashmaroli** [comment]
@lffg There may not be an "Official" version of Jekyll for Windows for the near future because the recent releases work just fine. I'm using it on Windows myself.

To help us get an idea what exactly might be the issue here, please provide us with as much as information as possible:

Windows version:
Ruby Version: ( run `ruby --version` )
Rubygems Version: ( run `gem --version` )
Jekyll Version: ( run `jekyll --version` )
Any Jekyll plugins you're using:

**Comment by pathawks** [comment]
Windows is not an officially supported platform, but Jekyll should work on Windows. If you would like to lend a hand, pull requests are always welcome.

A good place to start would be joining the [Windows affinity team](https://teams.jekyllrb.com/)

**Comment by ashmaroli** [comment]
@pathawks I think you closed this ticket prematurely. He did say, Jekyll was not working for him

**Comment by pathawks** [comment]
> He did say, Jekyll was not working for him

That should be taken care of in a new ticket. This issue was specifically asking about official support for Jekyll on Windows.

**Comment by pathawks** [comment]
Sorry if I appeared curt, it just becomes difficult to follow issues if they start with one question and then morph into something else. Any issue with Jekyll on Windows should be opened as a bug report with a clear description of the problem and the relevant boxes checked in our issue template :+1:
