### ISSUE TITLE
Jekyll 3.2.1 Error: No such file or directory

### ISSUE THREAD

**Issue by chmaynard** [jekyll/jekyll#5923]
I believe this to be a bug, not a question about using Jekyll.
I am on (or have tested on) ***macOS*** 10+
I am using a docker container: $ docker pull jekyll/jekyll

```
~ $ docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll -it -p 127.0.0.1:4000:4000 jekyll/jekyll
Configuration file: none
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.2.1 | Error:  No such file or directory @ rb_sysopen - /srv/jekyll/brew/etc/fonts/conf.d/10-hinting-slight.conf
```

**Comment by pnn** [comment]
cc @jekyll/docker

**Comment by parkr** [comment]
I'm afraid I don't know much about what's going on here. Can you run the following?

```text
docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll -it -p 127.0.0.1:4000:4000 jekyll/jekyll jekyll build -s /srv/jekyll -d /srv/jekyll/_site --verbose --trace
``` 

?

**Comment by envygeeks** [comment]
I don't think this is a problem with the Docker image.  We don't include brew, it's not OS X, and we don't include any fonts or any font configurations because it's unnecessary unless you use Java or anything X11 (of which we do not.)  As far as testing with an explicit source, we already set all that for Jekyll automatically, except for the destination, and we also `cd` to `/srv/jekyll` before doing any work too.

**Comment by envygeeks** [comment]
Try setting the UID: `docker run --rm -v $PWD:/srv/jekyll -e JEKYLL_UID=$(id -u) -it jekyll/jekyll`

**Comment by chmaynard** [comment]
Thanks for taking a look at this. I started over with a new image pulled from Docker Hub (jekyll/jekyll:pages) and everything seems to be working fine now. OK to close this issue.

**Comment by parkr** [comment]
Glad to hear you got it working. Thanks, too, @envygeeks!
