### ISSUE TITLE
Command --watch doesn't work

### ISSUE THREAD

**Issue by adrienpayen** [jekyll/jekyll#5955]
Hi,
I'm not sur but, `jekyll --watch` seem doesn't work. 

```
$ jekyll --watch
```
```
jekyll 3.4.2 | Error:  Whoops, we can't understand your command.
jekyll 3.4.2 | Error:  invalid option: --watch
jekyll 3.4.2 | Error:  Run your command again with the --help switch to see available options.
```

**Comment by ashmaroli** [comment]
you're doing it wrong.. from your Jekyll project directory, run
```
$ bundle exec jekyll build --watch
```

**Comment by pathawks** [comment]
> I'm not sur but, jekyll --watch seem doesn't work.

Sorry you're having trouble @adrienpayen.

`--watch` isn't a command, but rather a _switch_ to be used with the `build` or `serve` command. It will tell those commands to keep watching for changes.

`jekyll build --watch` tells Jekyll to build the site, but instead of quitting once finished, keep watching for new changes and rebuild the site when any changes are noticed.
