### ISSUE TITLE
sort: 'modified_time' not working on Github Pages

### ISSUE THREAD

**Issue by buha** [jekyll/jekyll#5964]
I am running `jekyll 3.4.2` locally and I am successfully sorting a collection with the `sort: 'modified_time'` filter. However, on Github Pages it does not work. It falls back to alphabetical ordering.

I think Github Pages runs the same 3.4.2 [source](https://pages.github.com/versions/)

**This is most likely not a bug** in Jekyll, but I ask here because there might be a configuration I need to activate on Github Pages. Let me know if you have any ideas.

Thanks

**Comment by pathawks** [comment]
On GitHub Pages, all files have the same modification time as far as the file system is concerned. GHP only does a shallow clone of the repository, which makes build time much faster than it would be otherwise at the expense of file modification times.

Unless I am misunderstanding where the modification time is coming from?

**Comment by buha** [comment]
In that case I don't know how to work around this.
