### ISSUE TITLE
No _sass, _includes, _layouts folders 

### ISSUE THREAD

**Issue by Rolando-Barbella** [jekyll/jekyll#6047]
- [ ] I believe this a question about using Jekyll.`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] I am on (or have tested on) ***macOS*** 10+

---

I have no experience with Jekyll or Ruby, I created my first site  by running **Jekyll new my-site** then Jekyll serve which worked fine, however, I don't have the _sass, _includes, _layouts folders, on the docs and every explanation or tutorial I saw, they talk about those main folders ( I only have  _posts and _site ) any reason why I don't have them? is that the new file structure?

├── CNAME
├── Gemfile
├── Gemfile.lock
├── _config.yml
├── _posts
│   └── 2017-04-02-welcome-to-jekyll.markdown
├── _site
│   ├── CNAME
│   ├── about
│   │   └── index.html
│   ├── assets
│   │   └── main.css
│   ├── feed.xml
│   ├── index.html
│   └── jekyll
│       └── update
│           └── 2017
│               └── 04
│                   └── 02
│                       └── welcome-to-jekyll.html
├── about.md
└── index.md

gem "jekyll", "3.4.3"

gem "minima", "~> 2.0"

---
Thank's

**Comment by DirtyF** [comment]
@Rolando-Barbella you're right since we shipped minima as a gem-based theme, default structure has changed, theme folders are now stored in the gem path. We added an info note on https://jekyllrb.com/docs/structure/, but any feedback is welcome if you think it's not enough.

The structure remains valid, you can create these folders to [override theme files](https://jekyllrb.com/docs/themes/#overriding-theme-defaults) if you need or start fro scratch with `--blank` option.

The tutorials you'll find about Jekyll also remain valid, there's just another way (not) to deal with these files if you just want to get going without having to modify a theme.

**Comment by Rolando-Barbella** [comment]
Thanks for the reply, the [themes](https://jekyllrb.com/docs/themes/#overriding-theme-defaults) docs explains it all very well, (sorry I miss that), however, I got a bit confused when I read the follow on the directory structure page:

> Directory structure of Jekyll sites using gem-based themes
> Starting Jekyll 3.2, a new Jekyll project bootstrapped with jekyll new uses gem-based themes to define the look of the site. This results in a lighter default directory structure : _layouts, _includes and _sass are stored in the theme-gem, by default.

This is when it might be a good idea to have extra info or maybe adding the themes link right there, when you try something new, I guess you first want to get it running, second step will be doing a quick change and seeing its life but I couldn't. 

Hope it helps :)

**Comment by DirtyF** [comment]
Please feel free to open a PR and propose those changes, we'll be happy to review and merge any improvements to ours docs.

**Comment by lachlanearle810** [comment]
--blank does not work.. it says it isint even a option.. help?

**Comment by DirtyF** [comment]
`jekyll new my-awesome-website --blank` works fine.

To benefit from the community support on Jekyll, head over to https://talk.jekyllrb.com
