### ISSUE TITLE
Jekyll Dependency Error, I'm fail to solve it. 

### ISSUE THREAD

**Issue by kousherAlam** [jekyll/jekyll#6121]
I'm new in Jekyll and I was working fine in my gh-pages Jekyll Project. But when I trying to do post loop from the _posts directory then the following error happened. And I try to resolve this by `gem install redcarpet` and `gem install rough` but it installs rough successfully. And give an error when trying to install redcarpet.

The Error is: 

![m39pn](https://cloud.githubusercontent.com/assets/14360099/26827471/3c39136e-4adf-11e7-89cf-04836576104a.png)

And when I use `gem install carpet` it gives me the following error:
![m39pn](https://cloud.githubusercontent.com/assets/14360099/26827482/5859ece4-4adf-11e7-9ff8-9e8a9b78dcbe.png)

My _posts directory looks like:
![capture](https://cloud.githubusercontent.com/assets/14360099/26827491/676067ae-4adf-11e7-9bbb-aa7ab1b6cc16.PNG)

## **_ My Operating system is: Windows 10 64 bit_**

**Comment by ashmaroli** [comment]
This is not a Jekyll issue. Looks more like an issue with the Ruby 2.4.0 Installation. You may either open an issue at the concerned project, use Ruby 2.3 on Windows for now or avoid using Redcarpet.

Is the site source available online? If yes, pls post a link so that we can tell you if Redcarpet is absolutely necessary.

**Comment by DirtyF** [comment]
Default markdown processor should be set to kramdown (cf. https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/)

Please use https://talk.jekyllrb.com/ for getting help on Jekyll's configuration and usage. Thanks.
