### ISSUE TITLE
.nojekyll in any directory feature

### ISSUE THREAD

**Issue by reinvantveer** [jekyll/jekyll#6122]
Hi, it would be really cool to be able to [bypass jekyll processing files](https://github.com/blog/572-bypassing-jekyll-on-github-pages) in any specific directory, rather than in the root for the entire repo. This way I can sync my CSS files with underscores in the filenames (this isn't up to me) to my github pages project, but I can have the markdown processed. Seems like `keep_files` and `include` options in _config.yml doesn't do this trick for me... Thanks!

**Comment by parkr** [comment]
`.nojekyll` is a feature of GitHub Pages and it simply bypasses Jekyll for the entire build as you mentioned. I don't see a future where Jekyll allows itself to be stopped from normal processing in a directory. If you mean bypass filtering of files (i.e. automatically pick up underscore-preceded files instead of ignoring them like we do now) then that's in a similar boat: the `include` directive should help you there, so I don't see us adding a special feature for this. We don't even allow markdown in CSS files (unless it ends in a .md extension) and that's certainly not on the roadmap. Perhaps [Jekyll Talk](https://talk.jekyllrb.com) can help you come to a solution?

Sorry we can't be of more help here!
