### ISSUE TITLE
Jekyll reverted to default theme; custom changes lost

### ISSUE THREAD

**Issue by bhuzzy** [jekyll/jekyll#6205]
i'm not sure what I did, i am very discouraged right now. is it because I ran it in terminal with jekyll serve --watch? is that what reset it? plz help.

**Comment by pathawks** [comment]
I am sorry you are having trouble. You haven't really provided much information for somebody to help you.

You were building a site in a folder, and now that folder is empty or its contents have changed? Have you ran anything other than `jekyll serve` or `jekyll build`? Have you been using `git` to track your changes?

**Comment by ashmaroli** [comment]
Looks like @bhuzzy edited the rendered contents in `_site` instead of editing copies of the theme files.

#### Things to consider while editing a Jekyll Theme
  - contents of `_site` will always be deleted and regenerated every time one issues a `build` command or a `serve` command.
  - To edit the default theme (or any *theme-gem*), you'll need to create copies, of the concerned files, at the site's `source_dir`. i.e. if you need to edit `<theme>/_layouts/default.html`, then you need to have a duplicate at `<source>/_layouts/default.html`
  - `jekyll new --` doesn't initialize Git by default. But its recommended that you track changes with Git which simplifies retrieving history and undoing accidental deletes.

**Comment by DirtyF** [comment]
Hi @bhuzzy, 

If you look for help on Jekyll, feel free to ask questions on our forum https://talk.jekyllrb.com. We mainly deal with bugs here.

If you read the docs and find anything unclear, please let us know.
