### ISSUE TITLE
Duplicate content when generating multiple pages

### ISSUE THREAD

**Issue by white-gecko** [jekyll/jekyll#6296]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [x] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

We've (@Simaris) created a MWE for reproducing this issue, you can find it here:
https://github.com/white-gecko/MWE-jekyll-duplicate-content-issue
it is inspired by Plugins: Generators https://jekyllrb.com/docs/plugins/#generators

Just build the according site, it will generated four testfiles `Testfile1.html Testfile2.html Testfile3.html Testfile4.html`

`Testfile1.html` has the expected content, but `Testfile2.html` also reproduces the content of `Testfile1.html`, `Testfile3.html` has the content of `Testfile2.html` and `Testfile1.html`, further `Testfile4.html` has the content of all previously generated pages.

## The Output I Wanted

All four files should just contain their own content i.e. be similar to `Testfile1.html`

/cc @jekyll/ecosystem @jekyll/stability

**Comment by pathawks** [comment]
You've included `{{ content }}` in the generated page, but you've not provided any content, so it just kind of freaks out. If you remove the `{{ content }}` tag from `_layouts/document.html` the four generated files are identical.

What are you trying to do?

**Comment by i-give-up** [comment]
From what I observed, `{{ content }}` contains the rendered output of the most recent rendered file, so it makes sense that your files contain the rendered content of previously rendered files.

>it is inspired by Plugins: Generators https://jekyllrb.com/docs/plugins/#generators

I think the confusion here stems from the fact that the `CategoryPageGenerator` example in the link above uses a layout file called `category_index.html`, but doesn't show what the content of that file looks like. Since `category_index.html` is a layout file, users may think that it has `{{ content }}` in it like all the other layout files, when in fact that's not the case with `category_index.html`. It probably looks like this instead

``` liquid
---
layout: page
---

{% for cat in site.categories %}
  {% if cat[0] == page.category %}
    {% for doc in cat[1] %}
    <p><a href={{ doc.url }}>{{ doc.title }}</a></p>
    {% endfor %}
    {% break %}
  {% endif %}
{% endfor %}
``` 
No `{{ content }}` there. 
I'm also thinking whether it's correct or not to place this file in the `category_index.html` directory because it doesn't do what layout files typically do, i.e. get rendered content as input and apply layout to it.
