### ISSUE TITLE
undefined method `length' for nil when iterating site.pages

### ISSUE THREAD

**Issue by niccottrell** [jekyll/jekyll#6340]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

I'm working on setting up a search plugin, but before that I am trying to configure an index page in JSON.

My `search.json` has a placeholder head to trigger the jekyll build, i.e.

```
---
layout: none
---
```

and the following line `{% for page in site.pages %}` is throwing:

` Liquid Exception: undefined method `length' for nil:NilClass in search.json`

However I use this exact same line in `my _pages/index.html` file. I'm using a local `jekyll-pages-directory.rb` plugin to keep my pages in `_pages` rather than in the root. 

## The Output I Wanted

I would expect the code in search.json to be executed like in index.html

**Comment by DirtyF** [comment]
HI @niccottrell  

Not sure this will fix your issue but a few things considering Jekyll's usage:

1. To trigger a build you can just add empty Front Matter delimiters:
```
---
---
```
2. You can use `layout: null` if you don't want to trigger a layout for your JSON file.
3.  You don't need a plugin to keep your pages in `_pages`, just add an `include` list in you `_config.yml`
```yaml
include:
 - _pages
```
4. For a search index, you might consider using `site.html_pages` rather than `site.pages`.

This not does look like a Jekyll bug to me, as I already create similar JSON files recently without any issue.
