### ISSUE TITLE
Suggest re-running command with --trace in limited error message

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#6359]
If the user did not use `--trace` and receives an error message, we should suggest that they re-run the command using that trace switch.

**Comment by ayastreb** [comment]
Hi @parkr
do you think it should be done in [Jekyll::Command.process_site](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/command.rb#L29) error catch?
If so, how would it be better to check if `--trace` is switched on?
Add it to [build options](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/command.rb#L52), so that we can access it on `site.config` in the `rescue` block?
As far as I udnerstand, `--trace` is a Rake argument and not really specific to Jekyll, right?

**Comment by parkr** [comment]
The `--trace` is a switch Mercenary adds to all the commands. The [default error handling can be 
 found here](https://github.com/jekyll/mercenary/blob/160b237aaeccd7be4cc58012c32a44cff2b11b97/lib/mercenary/program.rb#L46-L51). `process_site` doesn't have access to the `Mercenary::Command` object. [`--trace` is a default option](https://github.com/jekyll/mercenary/blob/160b237aaeccd7be4cc58012c32a44cff2b11b97/lib/mercenary/command.rb#L203-L205).

One option is to define the `--trace` option in the Build & Serve commands such that it sets a variable somewhere (maybe in the options hash) to know if it's true.

Another option is to `rescue SystemExit` in the `action` block in Build & Serve and suggest using `--trace` if `c.trace` is false. 

I'm not picky on the details, so go with what you think is cleanest & most straightforward.
