### ISSUE TITLE
Jekyll code profiler

### ISSUE THREAD

**Issue by mneumegen** [jekyll/jekyll#6571]
The Liquid profiler is good for pinning down bottlenecks in Liquid, it would be great to have similar insights into Jekyll itself.

I've been playing around with [ruby-prof](https://github.com/ruby-prof/ruby-prof) and [ruby-prof-flamegraph](https://github.com/oozou/ruby-prof-flamegraph) to generate [this graph](https://mikeneumegen.com/images/example.svg) for one of my Jekyll sites. Is it worth having this as part of Jekyll you could switch on with a flag? My gut feeling is it's too technical to be useful for most people.

**Comment by ashmaroli** [comment]
@mneumegen is there a table or legend of sorts associated with the flame-graph?

**Comment by mneumegen** [comment]
There's a number of different formats you can output to. I found this the
easiest way to see where time is being spent, not sure if you can add a
legend to the svg.

**Comment by ashmaroli** [comment]
okay.. after a shallow-investigation, my opinion is that, this does not belong in Jekyll Core; mainly because the average user (most are not very fluent in Ruby) does not benefit from the resulting flamegraph.

The maintainers here may consider adding this to Jekyll's dev environment to gauge Jekyll, but even then the gem usage would be via shell scripts.

Anyone coming across this thread is welcome to write a Jekyll Plugin

**Comment by parkr** [comment]
@mneumegen I would recommend taking a look at `script/stackprof` in this repo! It has helped me a bunch. For the most part, the lion's share of time for our docs site is spent in the kramdown pipeline rendering.

**Comment by mneumegen** [comment]
Nice, I'll take a look.

**Comment by parkr** [comment]
I'd love to see the `--profile` flag provide more information about markdown render time. That's where most of the time goes and `--profile` doesn't show it.
