### ISSUE TITLE
GitHub Project Wiki permission

### ISSUE THREAD

**Issue by sashabrava** [jekyll/jekyll#6708]
Hello. In the wiki/Sites of your GitHub project it is written that users can add their Jekyll blogs into your wiki using the template of adding new website. But the permission probably changed (I contacted other users, and they had an "Edit" option - although currently it is unavailable for non-your-project users).

Is this option of "adding website into list" already turned off and just the wiki description of it is wrong?

**Comment by pup** [comment]
@sashabrava Yeah, editing the wiki is restricted to people who work on the project, although I have no idea when this was changed... @jekyll/core, any idea?

**Comment by parkr** [comment]
If I remember correctly, we were starting to see an uptick in spammy entries. It's very difficult for us to keep up with the pace of the entries so I believe someone suggested we restrict access since so many of the projects are old or outdated or the links are broken, and we were getting spam. 

The ideal place to share your new site is on [Jekyll Talk](https://talk.jekyllrb.com)! We have [a showcase thread already started](https://talk.jekyllrb.com/t/jekyll-showcase-share-your-sites-built-with-jekyll/44).

**Comment by sashabrava** [comment]
@parkr, if you explain it in Wiki, it will fix the problem described in my issue.

And it can be a good idea to add this info at Jekyll website as well - I can't say that I surfed it all over, but I haven't found the info you shared on GitHub there.

**Comment by parkr** [comment]
I updated the wiki pages. Pretty much the entire wiki has been replaced by Jekyll Talk.

The only place this wiki is linked to is on https://jekyllrb.com/help/. It would be a good idea to upgrade.

**Comment by sashabrava** [comment]
@parkr , :+1:

**Comment by parkr** [comment]
Thanks for bringing this to our attention, @sashabrava!

**Comment by DirtyF** [comment]
https://jekyllrb.com/help/ has been updated with proper link to look for jekyll sites and themes.
