### ISSUE TITLE
can not stop jekyll serve on 127.0.0.1:4000

### ISSUE THREAD

**Issue by nimocat** [jekyll/jekyll#6733]
I've download a jekyll theme on github which is called jekyll-theme-mdui and run it on my localhost, then I close the serve and the computer, after a while, I opened my computer to surprisingly find the theme is still running on 127.0.0.1:4000 without start the jekyll serve!  Here comes the problem, I can't even shut down the serve because I don't know what is hosting the theme, even delete the whole folder didn't work. Does anyone can help me to close the 127.0.0.1:4000?? I'm so desperate!

**Comment by ashmaroli** [comment]
First things first..
  - **Relax!**. There's no need to panic..
  - This issue tracker is meant for bugs in Jekyll.. for assistance / support, please use https://talk.jekyllrb.com
  - But I'll give you the benefit of desperation just this one time..

I'll close this ticket since its not a Jekyll bug.. but you are free to post comments to my questions below..

Coming back to the issue,
  - How can you tell the local `server` is still running..? Are you able to navigate through your served site on your Browser?
  - Did you try <kbd>Ctrl</kbd> + <kbd>C</kbd> or the equivalent for your OS?
  - Jekyll runs primarily via a Command Prompt.. If you're on Windows, its either `cmd.exe` or a bash.exe`.. On macOS or Linux, the programs are similarly named.. Close any active sessions of your "terminal" program..

**Comment by Ryuno-Ki** [comment]
Assuming you are running on Linux, you could look for the PID (process ID) of Jekyll with a tool like `ps` and send a `SIGKILL` to it.

**Comment by nimocat** [comment]
yep I can still browse web pages on 127.0.0.1:4000 while I terminated all the command lines. This happened even if restart the computer. And if I try to terminate process with the PID, it will shows like that:
````
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
tianyidexiaobenben:~ aitianyi$ kill -9 $(ps aux | grep '[j]ekyll' | awk '{print $2}')
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
tianyidexiaobenben:~ aitianyi$ kill -9 $(ps aux | grep 'jekyll' | awk '{print $2}')
-bash: kill: (1093) - No such process
tianyidexiaobenben:~ aitianyi$ kill -9 $(ps aux | grep 'jekyll' | awk '{print $2}')
-bash: kill: (1097) - No such process
tianyidexiaobenben:~ aitianyi$ kill -9 $(ps aux | grep 'jekyll' | awk '{print $2}')
-bash: kill: (1113) - No such process
````
the process seems to change the PID every time I try to search it. And there is no way to kill it....
I still can see the f**king site occupied on 127.0.0.1:4000

**Comment by nimocat** [comment]
well, that's really a lesson to me, if anyone else use chorme!! I even don't know why it would cache my site in the browser...It goes well after I clean up the cache and cookie... THAT IS REALLY A LESSON, for overall cause a 20 hours debugging

**Comment by pathawks** [comment]
@nimocat Oh no! I’m glad you got it figured out.
Hopefully this thread can help somebody else in the future.

**Comment by nimocat** [comment]
All the problems come from some parts of pwa options, so if another pwa theme shows up with the same problem, this issue may be helpful.
