### ISSUE TITLE
when  i serve the page my content  duplicates !

### ISSUE THREAD

**Issue by CarlasHub** [jekyll/jekyll#7025]
strange bug: every time i run :`` bundle exec jekyll serve --watch --baseurl "`"` my footer duplicates i have 3 footers currently and this must be a jekyll issue so i was wondering if someone can help me with this also why my projects page is not rendering? I added the required front matter...

I hope you guys can help me with this, thanks very much

**Comment by pathawks** [comment]
Please use the standard issue template.

This seems like a question about using Jekyll rather than a specific bug report. Without a link to your repository or any example, there is no way for somebody else to reproduce the issue and help you debug.

**Comment by CarlasHub** [comment]
Hi @pathawks im sorry.  https://github.com/CarlasHub/carla
https://github.com/CarlasHub/carla.git

**Comment by pathawks** [comment]
You have some Liquid syntax errors: https://github.com/CarlasHub/carla/blob/f32b11d20da509045f01110943083d1ef922e5e9/_layouts/post.html#L31

I'm not sure what that stray `href` is intended for anyway.

It looks like the main problem is due to a Git merge gone wrong: https://github.com/CarlasHub/carla/blob/07e38a0752fa73e640947f875403038b6542370f/_includes/footer.html

There is duplicate content in `_includes/footer.html`

**Comment by pathawks** [comment]
In the future, please use the issue tracker only for bugs in Jekyll. If you have further questions about using Jekyll, I would suggest you try asking them at [talk.jekyllrb.com](https://talk.jekyllrb.com)
