### ISSUE TITLE
Is Jekyll a compiler like Gcc?

### ISSUE THREAD

**Issue by MatheusRV** [jekyll/jekyll#7055]
I am conducting a scientific study on static sites and my biggest doubt is in the relationship that SSGs have between compilers?

In a generator it has a syntactic, lexical, semantic analyzer. If not how do I explain what a generator is?

Thank you

**Comment by oe** [comment]
@MatheusRV I think a static site generator is significantly simpler than a compiler since it excludes the AST stage and just works on the files directly. Essentially, it's a three step process: input, transformation, and output, and during the transformation process stuff like "compiling" can happen to, for example, Markdown. However, I'd argue against this "compilation" step being an integral part of a static site generator, as the simplest static site generator should be a program that takes a directory of files and copies it somewhere else.

If you want to have a further discussion on this (this issue tracker isn't the place for it), please email me at `olivia [at] fastmail [dot] com`!
