### ISSUE TITLE
Error:  File name too long @ rb_sysopen

### ISSUE THREAD

**Issue by sarahfang9292** [jekyll/jekyll#7174]
Hi! When I use $ jekyll build, it shows $ jekyll 3.8.3 | Error:  File name too long @ rb_sysopen.
How can I fix this probem? Thanks

**Comment by crispgm** [comment]
@sarahfang9292 as the error message shows, file name is too long. try reduce file path, it might be okay.

**Comment by sarahfang9292** [comment]
Thanks for your advice:) My file path is '/Users/zhijun'. I don't think it's too long...

**Comment by pathawks** [comment]
Sorry you are having this issue @sarahfang9292. Can you run `jekyll build --trace` and copy the output here?

Is this something that has changed recently, or is this your first time building a site with Jekyll? Is the site you are trying to build in a public repository so that somebody else can try to build it and get this error message?

**Comment by sarahfang9292** [comment]
@pathawks Thanks for helping:)
The output:
<Configuration file: none
            Source: /Users/zhijun
       Destination: /Users/zhijun/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/Users/zhijun/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/jekyll-3.8.3/lib/jekyll/utils.rb:146:in `initialize': File name too long @ rb_sysopen - /Users/zhijun/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/Frameworks/Steam Helper EH.app/Contents/Frameworks/Steam Helper EH.app/Contents/Frameworks/Steam Helper EH.app/Contents/Frameworks/Steam...... >

I just started to build it with Jekyll.

**Comment by pathawks** [comment]
@sarahfang9292 Thanks for the quick reply. It looks like you will need to create a subdirectory for your Jekyll site.

Right now, you are trying to run `jekyll build` inside your home directory. This means that Jekyll is trying to process every file that you have access to, including applications that you've installed. This is a problem.

Instead, you will want to create a site inside your home directory. Since Jekyll is already installed, you can run `jekyll new myblog` to create a new Jekyll site. Then you can change into the created directory with `cd myblog` and run `jekyll build` again from there. When done this way, Jekyll will only process files in `/Users/zhijun/myblog/` instead of everything in your home directory.

I believe you should be able to find more detail about getting started with Jekyll in our [quick-start guide](https://jekyllrb.com/docs/quickstart/). ☺️

**Comment by sarahfang9292** [comment]
@pathawks It works now. Thanks!
