### ISSUE TITLE
Step by step tutorial not applicable for gem-based themes

### ISSUE THREAD

**Issue by ioana-st** [jekyll/jekyll#7242]
I am a first-time Jekyll user and I tried to follow the step-by-step tutorial, with no success. After googling for a bit, I realized that the current themes are gem-based, therefore a large part of the tutorial is no longer applicable and it would actually cause you to break the theme if you don't already know what you are doing.

The tutorial should be updated or maybe there should be two versions, but the main tutorial should be applicable to the theme (minima) that actually gets installed the first time you try Jekyll.

Unfortunately I've only been toying with Jekyll for a few hours and I have zero knowledge about Ruby, so I can't update the pages myself.

**Comment by oe** [comment]
@ioana-st The step-by-step tutorial assumes that you don't create a site using `jekyll new`, but rather do it manually. Considering that our homepage boasts usage of `jekyll new`, though, this is a valid discrepancy.

**Comment by mneumegen** [comment]
I feel like doing `jekyll new` for a first time users has too much magic. The idea of the step-by-step tutorial is the user will (hopefully) understand all the basic concepts of Jekyll so when it comes to using a gem theme, they will understand what it is doing.

**Comment by mneumegen** [comment]
Yeah true. The problem is there's two types of users Jekyll is trying to target:

1. A semi-technical user who wants to write markdown and not worry about styling/HTML.
2. A front-end developer who wants to build a site from scratch

For #1 it's easy for them to get up and going with `jekyll new` and start writing markdown files. Anything beyond that is probably up to the theme itself to document as the user isn't really using Jekyll features directly.

For #2 I think it makes sense to start without a theme, expose them to Jekyll concepts. Later if they have multiple sites with similar layouts or want to start with something already half-built, a theme is perfect. 

GitHub Pages optimizes for #1 as they're wanting people to set up easy documentation pages. I would argue that Jekyll should optimize for #2 or at least make it clearer, as you mentioned, in differentiating the use cases.

**Comment by DirtyF** [comment]
Addressed, thanks for your feedback @ioana-st
