### ISSUE TITLE
Jekyll Server not serving custom 404 page

### ISSUE THREAD

**Issue by ali-hardan** [jekyll/jekyll#7451]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |     Arch Linux 32       |
| `jekyll`         | Latest     |
| `github-pages`   | not used     |

---

## Explain the bug

When I try to browse a wrong URL in Jekyll local server, It should always return `404.html`. but when I set global permalink to `pretty`, the result is:

![screenshot from 2019-01-02 20-37-31](https://user-images.githubusercontent.com/4679877/50603024-4bd7da80-0ece-11e9-87d3-fbd08305fa15.png)

I have set that on `_config.yml`:
~~~YAML
permalink: pretty
~~~

**Comment by pathawks** [comment]
See also #5944

WEBrick is not intended to be used in production. It does not currently support custom 404 pages.

**Comment by ashmaroli** [comment]
> It does not currently support custom 404 pages.

@pathawks That is not true.
If you have a `404.html` at the root of your site, our server will load that instead of the WEBrick boilerplate.

@ali-hardan Unfortunately, I was not able to reproduce your issue at my end.
Can you try cloning this repository and attempt again with *our docs site..?*

- For example
  ```
  git clone https://github.com/jekyll/jekyll.git
  cd jekyll/docs
  bundle install
  ```
- Edit config file with `permalink: pretty`
- Serve docs site:
  ```
  bundle exec jekyll serve
  ```
- Point your browser to `http://localhost:4000/abcd`

**Comment by ali-hardan** [comment]
@ashmaroli, done. In jekyll docs, jekyll correcly shows 404 page after I set permalink to pretty.

Now I understand why it was not work in my test. the `404.html` file was in root of my project, after I put it to `pages` folder (like what in jekyll docs done), it works, even if I set permalink to pretty.

Is it a bug, or It's normal? is any docs about it?

**Comment by ashmaroli** [comment]
> Is it a bug, or It's normal? is any docs about it?

@ali-hardan The only requirement for `404.html` pages is that it **should be at the root of your site**
The easiest way to ensure this is by setting `permalink: /404.html` in the `404.html` page's front matter.
It is possible that when you set `permalink: pretty` globally, `404.html` is getting generated into the path
`_site/404/index.html` instead of `_site/404.html`

*Disclaimer: The above requirement is only for our development server and GitHub Pages. Elsewhere, you can customize the location of your HTTP Error pages.*

**Comment by ali-hardan** [comment]
Now I understand, Thanks.

My previous comment was wrong; That not worked because I put `404.html` into `pages` folder, that was worked because I was copied 404.html from jekyll docs to my project, which was includes `permalink: /404.html`.

**Comment by ali-hardan** [comment]
I think jekyll default 404.html should be contains `permalink: /404.html` as default to avoid this problem.

**Comment by ashmaroli** [comment]
@ali-hardan Feel free to submit a PR.. :smiley:

**Comment by ali-hardan** [comment]
Oops, It is currently merged, but not released. (#7132)
