### ISSUE TITLE
include tag with variable filename.ext fails on page without permalink

### ISSUE THREAD

**Issue by jameswilson** [jekyll/jekyll#7513]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |   Mac OS         |
| `jekyll`         | 3.7.4     |
| `github-pages`   | Latest     |

---

## Expected Behaviour

Using the [documented](https://jekyllrb.com/docs/includes/#using-variables-names-for-the-include-file) `{% include {{ page.my_variable }} %}` syntax to include a JSON filename defined in a frontmatter variable, I expected to load the page and see a Javascript alert message popup with the contents of the JSON file: "this is valid JSON".

## Current Behavior

Jekyll compiler complains:

Error message: `Invalid syntax for include tag. File contains invalid characters or sequences:`

## Code Sample

**_includes/data/filename.json:**
```
{
  "items":  [
    {"_comment": "this is valid JSON"}
  ]
}
```

**_config.yml**
```
---
theme: jekyll-theme-slate
url: https://example.github.io
baseurl: ""
title: Testing Include Tag
---
```

**index.md:**
```
---
title: JSON Embed
dataset: data/filename.json
---
```

**_layouts/default.html:**
```
<html>
<head>
<title>{{ page.title }} | {{ site.title }}</title>
</head>
<body>
<script>
  const data = {% include {{ page.dataset }} %};
  alert(data.items[0]['_comment']);
</script>
</body>
</html>
```

## Workaround

The only way I've been able to resolve this bug is by adding a specific `permalink` value to the frontmatter, i.e.:

**index.md:**
```
---
permalink: /
title: JSON Embed
dataset: data/filename.json
---
```

**Comment by jameswilson** [comment]
This issue may not be directly related to JSON, it's just that this is what I was trying to do...   

I bet the file extension really has nothing to do with this bug.

**Comment by ashmaroli** [comment]
@jameswilson This is quite an interesting case.
Even though you've not provided us with the complete error message. (`Invalid syntax for include tag. File contains invalid characters or sequences:`; What is the invalid character?)

I tried to reproduce this error at my end..

The reason for this issue is because the "include tag" is **inside the `default` layout** from which every other layout inherits.

So while your `index.md` has `dataset` defined in the front matter, another page `about.md` (or a post) **doesn't have the `dataset` key defined**. So for `about.md` (or the post), the include tag is simply
`{% include "" %}` which we do not allow..

The proper solution here is to either define a new layout (that may inherit from the `default` layout) and insert your script there. Or ensure that `{{ page.dataset }}` does not return `nil` or `null` or `''` or any other invalid filename characters for any page / document in your site.
