### ISSUE TITLE
Blog post timezone bug/misunderstanding

### ISSUE THREAD

**Issue by Ramobo** [jekyll/jekyll#7516]
# Example

Post date:
`date: 2019-02-10 15:00`

Configuration file:
`timezone: Etc/GMT`

For clarity below: my timezone is UTC-3.

# Expected behaviour

Built post date when viewing locally from UTC-3: 12:00

# Actual behaviour

Built post time when viewing locally from UTC-3: 15:00

They are 3 hours apart, but seemingly inverted.

From my understanding, the time on posts should be in the timezone specified in the configuration file, and when a user views that page, the displayed time is the post time converted from the configuration timezone to the user's system's timezone, but that doesn't seem to be the case.

**Comment by ashmaroli** [comment]
@Ramobo What OS are you using?
What are your "expected" and "actual" behaviors for TZ offset at `UTC-5`

**Comment by Ramobo** [comment]
I'm using Windows 10.

For UTC-5 (using 15:00 post time with the timezone Etc/GMT):
Expected: 10:00
Actual: 15:00
They don't seem to change with the system timezone.

Now I'm doing some more testing, and it looks like the post time is absolute, and the offset offsets the time by that offset, no matter your timezone. What's the point of that, then?

How are these offsets even supposed to work?

**Comment by ashmaroli** [comment]
@Ramobo The offsets are supposed to work as following (w.r.t Jekyll on Windows and `tzinfo-v1.2.5`):
- A post's date is *absolute* if it doesn't specify the timezone
  ```yaml
  # Timezone-agnostic date
  date: 2019-02-10 15:00
  ```
  ```yaml
  # Timezone-dependent date
  date: 2019-02-10 15:00:00 -0300
  ```
- The offset is calculated w.r.t to the configured `timezone`

  date | timezone setting | result
  ---- | ---- | ----
  2019-02-10 15:00:00 -0300 | N/A | 2019-02-10 15:00:00 -0300
  2019-02-10 15:00:00 -0300 | **`Etc/GMT`** | 2019-02-10 18:00:00 +0000
  2019-02-10 15:00:00 -0300 | **`America/New_York`** | 2019-02-10 13:00:00 -0500

*Note: The above observations are for `gem 'tzinfo', '~> 1.0'`. `tzinfo-2.0` introduced changes to offset computation logic.*

**Comment by Ramobo** [comment]
This is too confusing. I expected it to work like this: you specify a timezone in your configuration file and write the dates on your posts to match that timezone, then the time is automatically converted to the timezone of whoever is viewing the post.
I might as well just go with absolute GMT times.

**Comment by ashmaroli** [comment]
@Ramobo You've got it all wrong. The time is never automatically converted to the timezone of the viewer. Jekyll generates static sites. All computation is done only at build.

The `timezone` setting is to maintain consistency in timestamps.

For example, say, you have been publishing posts every week at 10AM New York time. Every post has the `time` clearly rendered (`10:00 -0400`) in the post's header.
Now for some unavoidable reason, you move to a timezone 2hrs ahead of NY time. When you then publish a new post at 10AM *local time*, your readers in New York will see the post at 8AM (NY time) but, it'll have a 10AM timestamp because of your local time.
Moving to another timezone will introduce another layer of discrepancy.

Instead of having to change your computer's timezone manually to NY time to overcome the discrepancies, (and affect other applications), you just set the `timezone` key to `America/New_York`. Now Jekyll will build with respect to New York time, irrespective of where you are.

Of course, the above scenario is just theoretical and there is always complexity involved when it comes to matters of Date and Time.

**Comment by Ramobo** [comment]
Alright, I see.
