### ISSUE TITLE
_config.yml exclude rule crashes jekyll

### ISSUE THREAD

**Issue by by-lufog** [jekyll/jekyll#7537]
When i add to `_config.yml`:
```yml
exclude: [readme.md]
```
or
```yml
exclude: 
 - readme.md
```
 
I get the following error: 
`Error: could not read file /mnt/e/dev/jekyll/site/vendor/bundle/gems/jekyll-3.8.5/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb: Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/gems/jekyll-3.8.5/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.`

When I remove the `exclude` from `_config.yml`, everything works fine.

**jekyll v3.8.5**
**bundler v2.0.1**
**ruby v2.6.1p33**
**gem v3.0.1**

**Comment by DirtyF** [comment]
https://jekyllrb.com/docs/troubleshooting/#configuration-problems

This happens because `vendor/bundle` is excluded by default, and should stay present when you override defaults includes:

```yaml
exclude: 
  - readme.md
  - vendor/bundle
```

@jekyll/core As the message is clearly disturbing for users, could specifying *additionnal* excludes *add* those to the defaults?

**Comment by ashmaroli** [comment]
@DirtyF I have a proposal at #7188. Feedback invited.
