### ISSUE TITLE
That add multidimensional arrays to the code reference syntax resulted in an error

### ISSUE THREAD

**Issue by mengxunQAQ** [jekyll/jekyll#7575]
When I write this in code reference syntax of markdown：
```
  1 #include <stdio.h>
  2
  3 int main(void)
  4 {
  5     int x[2][2] = {{1, 2}, {3, 4}};
  6
  7     printf("x[0] = %p, x = %p, &x = %p\n", x[0], x, &x);
  8     printf("x[0] + 1 = %p, x + 1 = %p, &x + 1 = %p\n", x[0] + 1, x + 1, &x + 1 );
  9
 10     return 0;
 11 }

```

I got an error like this:

> jekyll 3.8.5 | Error:  Liquid syntax error (line 8): Variable '{{1, 2}' was not properly terminated with regexp: /\}\}/
The command "jekyll build" exited with 1.

**Comment by avidyut1** [comment]
Hi @mengxunQAQ,
On investigating the issue, I found out that the issue is because of Liquid gem which tries to parse {{var}} and insert value of var into the template.
You can prevent liquid from processing the template by enclosing your code inside 

{% raw %} 
      code
{% endraw %}

This should fix your issue. Thanks
