### ISSUE TITLE
Pages posts and collections

### ISSUE THREAD

**Issue by bert-bruggeman** [jekyll/jekyll#7624]
Why are these still separated, woudnt it be more logical if all content is a collection?

**Comment by ashmaroli** [comment]
Posts have been a "collection" since Jekyll 3.0

Pages *may* end up being a collection in Jekyll 4.0. But personally, I'm not in favor of that idea.
To me, pages represent the standalone entities that do not belong together.
*Pages may exist anywhere in the source directory without constraints.* But under the hood, they all end up as part of the same family.
