### ISSUE TITLE
pop and shift invalid return

### ISSUE THREAD

**Issue by cup** [jekyll/jekyll#7730]
Jekyll pop and shift return remaining items instead of popped or shifted items. This is the exact opposite of Ruby proper:

> Removes the last element from self and returns it

https://ruby-doc.org/core/Array.html#method-i-pop

> Removes the first element of self and returns it

https://ruby-doc.org/core/Array.html#method-i-shift

and, frankly, every other programming language I have ever worked with.

**Comment by ashmaroli** [comment]
@cup I agree with you. This is unexpected.
Even our documentation isn't correct. The examples for `pop` and `shift` should be interchanged!

![Screenshot_2019-06-30 Liquid Filters](https://user-images.githubusercontent.com/12479464/60392878-e0439280-9b29-11e9-87f9-70afcf4d5f60.png)

However, we won't be able to "fix this" for Jekyll 3.8 because that'd be a breaking-change.
Luckily, Jekyll 4.0 development is underway.

**Comment by mattr-** [comment]
Sorry, I'm sure I'm being daft here but without a clear example, I'm not sure I'm understanding what the actual problem is. Could you provide a short example please?

**Comment by cup** [comment]
@mattr- I am not doing that.

If it means you need to close the issue for lack of information, or simply because you consider me rude, go ahead.

but I am not going to explain what `pop` does in Jekyll vs what it should do, on principle. Sorry but there has to be a bar somewhere and you just crossed it.

Good day.

**Comment by mattr-** [comment]
@ashmaroli since you seem to understand the problem, I'll leave it to you to fix it.

**Comment by ashmaroli** [comment]
@mattr- The issue here is that the behavior of our Liquid filters `pop` and `shift` are incoherent and orthogonal with the namesake methods for Ruby Array.
For example,
## pop
### Liquid Filter
https://github.com/jekyll/jekyll/blob/a87ca206dad4e2c026a3141612a02c6bffc72519/lib/jekyll/filters.rb#L251-L258

(The return value of the filter is either **the *popped* Array** or the given input `array` if it wasn't an Array &mdash; No clue about what got removed from the input)

### Ruby proper
```ruby
items = %w(lorem ipsum dolor sit)
# => ["lorem", "ipsum", "dolor", "sit"]

items.pop
# => "sit"
# *The Array element that got removed*

items.pop(2)
# => ["ipsum", "dolor"]
# *The Array of elements that got removed*
```

And similarly for `shift`:
## shift
### Liquid Filter
https://github.com/jekyll/jekyll/blob/a87ca206dad4e2c026a3141612a02c6bffc72519/lib/jekyll/filters.rb#L268-L275
(The return value of the filter is either **the *shifted* Array** or the given input `array` if it wasn't an Array &mdash; No clue about what got removed from the input)

### Ruby
```ruby
items = %w(lorem ipsum dolor sit)
# => ["lorem", "ipsum", "dolor", "sit"]

items.shift
# => "lorem"
# *The Array element that got removed*

items.shift(2)
# => ["ipsum", "dolor"]
# *The Array of elements that got removed*
```

Therefore, there is a discrepancy.
**If we were to "fix the discrepancy", it'd be a breaking-change.**
Is that desirable ?

@DirtyF Addressing this would be a breaking-change. If not 4.0, then it'll have to be pushed to 5.0

**Comment by DirtyF** [comment]
I think so, hence the bug label, those filters were meant to be Ruby proxies.
https://github.com/jekyll/jekyll/issues/2892#issuecomment-58720757

Originally added in https://github.com/jekyll/jekyll/pull/2895

**Comment by ashmaroli** [comment]
> those filters were meant to be Ruby proxies.

But in a [future comment](https://github.com/jekyll/jekyll/issues/4880#issuecomment-218803246) @parkr states otherwise:
>> Yes, this is as intended. It isn't the same as Array#pop in Ruby.
>>
>> I'd be up for a PR to add `pop_item` and `shift_item` which would just proxy to `Array#<method>` in that case.

**Comment by mattr-** [comment]
The way the current filters are implemented is the original behavior. What I'd like to see us do in this case is the following:
 - Deprecate the _behavior_ of the pop and shift filters. We'll be keeping the names. If there are other filters that behave the same way, let's deprecate their behavior too, if we notice them. If we don't notice them, it's not something to anguish over.
 - Implement _new_ `pop_item` and `shift_item` filters. We'll need to modify the existing array passed to the filter, make sure that modification sticks, and return the actual item(s) popped or shifted. This is basically making them proxies for `Array#pop` and `Array#shift` respectively. Basically, this implements [@parkr's comment](https://github.com/jekyll/jekyll/issues/4880#issuecomment-218803246)
 - Deprecate the newly created `pop_item` and `shift_item`. We'll replace `pop` and `shift` with their item versions in Jekyll 5.

This gives people the most amount of signal we can possibly give them before we break five year old behavior.

**Comment by mattr-** [comment]
Also, let's make sure we update the documentation to match the real behavior of the filters.
