### ISSUE TITLE
Categories and Tags

### ISSUE THREAD

**Issue by cup** [jekyll/jekyll#7781]
This one sentence is the only official documentation I could find on the
difference between category and tag:

> The difference between categories and tags is a category can be part of the
> URL for a post whereas a tag cannot.

https://jekyllrb.com/docs/posts#categories-and-tags

Further, I see both are listed under predefined variables:

https://jekyllrb.com/docs/front-matter#predefined-variables-for-posts

This leaves several questions open for me:

1. If `categories` and `tags` are predefined, what are they predefined to?

2. How does Jekyll know what category or tag to apply to something?

3. What are the point of tags?

4. I see that category has the benefit that it can be part of a URL, but I am
   assuming it doesnt have to be. So why not just use category without making it
   part of URL if thats why I desire?

5. In this scenario it seems tags are pointless. Do tags have some benefit over
   category that is not detailed, such as faster build time or some such?

**Comment by ashmaroli** [comment]
> 1. If `categories` and `tags` are predefined, what are they predefined to?

They're predefined to an empty array or in other words, something *non-nil*.
You can always use the `inspect` Liquid Filter to gain more insights into an object. For example:
```html
{% for doc in site.posts %}
  <div>
    <a href="{{ doc.url | relative_url }}">{{ doc.title }}</a>
    <pre>{{ doc | inspect }}</pre>
  </div>
{% endfor %}
```
You'll see that your posts have a `"tags"`, `"categories"`, `"date"` field even if they don't explicitly exist in a given post's front matter.


> 2. How does Jekyll know what category or tag to apply to something?

- Jekyll won't know about `tags` unless you define their values in the front matter.
- Categories for posts are derived from their paths *and* their front matter. For example, say you have a file at path `movies/_posts/2019-08-15-aloha.md`.
Since, there's `_posts` in the path and the basename follows the pattern `YYYY-MM-DD-TITLE.EXTN`, Jekyll will consider that file to be a *post* irrespective of whether it has front matter at the very beginning or not.
The director(ies) *preceding* `_posts` (superdirectories) will be considered as the post's categor(ies). Therefore if you were to *inspect* the post via Liquid, you'll see that this file has
 `"categories": ["movies"]` in it.
And if you were to have `categories:` defined in the post's front matter, those values will be present in the array above as well (and alters the resulting URL accordingly).


> 3. What are the point of tags?

Tags can be used to filter posts by creating a "tag cloud" and setting up a layout for rendering such results. Say, you have a series of posts on a vacation to a certain place, and another series of posts about those *hangout sessions* instituted by your workplace for unwinding. In both these series, there are some common grounds which you express via `tags` (similar to having "hastags" on the social media). When set up nicely, your readers will be able to see all posts that were tagged `fun`, `NewFriends`, etc.


> 4. I see that category has the benefit that it can be part of a URL, but I am assuming it doesnt have to be..

By default, categories will be part of the URL. No leeway unless you configure a custom permalink template in your config file.


> 5. Do tags have some benefit over category that is not detailed, such as faster build time or some such?

No there's no such benefit.
Different users have different needs. For some users, both categories and tags have no meaning while some find meaning in using only one of them while another section of users value having both features.
Categories and tags work differently even if they appear to be similar and are applicable to not just posts but also to all collections in the site.

**Comment by ashmaroli** [comment]
Please head over to https://talk.jekyllrb.com for insights from the community.

**Comment by cup** [comment]
@ashmaroli thanks.

It still seems to be significant overlap between the two, but I appreciate the detailed response. Take care
