### ISSUE TITLE
docs: Intro is missing

### ISSUE THREAD

**Issue by guettli** [jekyll/jekyll#7891]
## Motivation

On the homepage I see this:

![image](https://user-images.githubusercontent.com/414336/68398755-83aa5100-0175-11ea-9175-fae4b2ff2c5e.png)

Source: https://jekyllrb.com/

I click on "How Jekyll works" and I see ..... (small dramaturgical break) ...

"Command Line Usage".

Grrrr.

Please start with the big picture first.

Please start with "why?".

**Comment by DirtyF** [comment]
If you're wondering why you should a static site generator read https://dev.to/chrisrhymes/why-use-a-static-site-generator-2e53

Pick Jekyll if you're looking a SSG that is easy to learn, flexible to model your content in Markdown and data files.

**Comment by guettli** [comment]
Thank you for this hint.

There are two very different aspects now: 

- my curiosity. (one person)
- the homepage: Read by several people. After some month maybe several hundred people

I care for the later, not for my personal "missing info" issue.

Try to see my issue trough the eyes of a child.

Have you ever tried to teach a child (or new comer) something?

You need to start with a overview and a "why".

Thank you for the link. Now I know why static site generator is useful.

Now how to present the "why?" on the homepage?

**Comment by DirtyF** [comment]
I invite you to read Jekyll's creator original blog post: https://tom.preston-werner.com/2008/11/17/blogging-like-a-hacker.html

Since we track visits, Jekyll's homepage has been seen by 5 millions unique visitors. We don't expect _everyone_ to understand, some technical background is needed. Retrospectively, the project was aimed at hackers understanding the power and convenience of using a git backend. The homepage already states: simple, static, blog aware. It partly answer to why you should use Jekyll IMHO. Given it's still one of the most popular SSG out there, I hope we do a good job on introducing people to SSGs.

**Comment by guettli** [comment]
I repeat myself: If you click on the a link called "How Jyekll" works, and the next text you read is the command line reference, then I think to myself: Oh my god. These detail lovers. They are not able to wear the glasses of new comer. Consult a book about teaching or how to write documents. The first thing you need is an introduction, not a command line reference.

Since I see that you don't want to understand me I close this. Have a nice time.

**Comment by DirtyF** [comment]
Feel free to open a PR, if your think we can do better.

**Comment by guettli** [comment]
I am a user. I am here for reporting issues. It is not my job to maintain the docs.
