### ISSUE TITLE
Why are site variables in a remote_theme's _config file not accessible?

### ISSUE THREAD

**Issue by pavelkomarov** [jekyll/jekyll#7971]
[According to this](https://jekyllrb.com/docs/themes/#pre-configuring-theme-gems40) "Jekyll will read-in a `_config.yml` at the root of the theme-gem and merge its data into the site’s existing configuration data." But I've created a theme with a config that looks like this:
![image](https://user-images.githubusercontent.com/5639551/72230751-954d1200-3585-11ea-93e1-5e5f052f87ec.png)
And I'm referencing the variables like this in my theme's css: (Notice empty frontmatter and liquid tag on last line.)
![image](https://user-images.githubusercontent.com/5639551/72230773-b01f8680-3585-11ea-871f-fc86ae4b114f.png)
And the result comes out like this in the rendered site: (Notice the emptystring where my liquid tag used to be.)
![image](https://user-images.githubusercontent.com/5639551/72230791-d2190900-3585-11ea-9036-285911cc5ab3.png)

If I put the variables in the `_config` of my site rather than in the one for the theme, everything works as expected. But I want these variables tied to the theme.

To make matters more mysterious, I can find examples in the common `minimal-mistakes` theme where site variables are defined in the theme and then used, just as I've used these, in theme files with no issues.

What is going on?

**Comment by ashmaroli** [comment]
@pavelkomarov What version of Jekyll are you using? (Run `bundle info jekyll` to check for metadata). This feature was introduced only in Jekyll 4.0.

If you're indeed on Jekyll 4.0, ensure the following:
- That your theme's gemspec includes the config file. Remote themes are downloaded locally to a temp directory. Inspect the contents of the downloaded theme to confirm that the config file has been included in it.
- That there isn't another `site.color` defined in the config file at source-dir because that will override the config setting in the theme.

**Comment by pavelkomarov** [comment]
@ashmaroli I was using Jekyll 4.0.0. I actually downgraded to solve [another problem](https://github.com/benbalter/jekyll-remote-theme/issues/66) to 3.8.5 since I posted that.

Looking in the local directory for the `_config` is actually a brilliant idea, and now that I solved [the other problem](https://github.com/benbalter/jekyll-remote-theme/issues/66), I can look there. Yep, can confirm the theme's `_config.yml` survived transit.

I haven't been using a `.gemspec` file because honestly I hate having so many configurations all over the place. I find your design confusing, and `remote_theme` manages to work without the `.gemspec`.

There definitely isn't another `site.color` that would override my variables.

**Comment by pavelkomarov** [comment]
Oh, I know the problem, actually. *I* was using Jekyll 4.0.0, [but *github* is still on 3.8.6](https://github.com/jekyll/minima/issues/422#issuecomment-567089139), so it won't work when I deploy either way. Is there a workaround? I need these variables to be linked to the theme. And it's confusing as all hell that [the documentation](https://jekyllrb.com/docs/themes/#pre-configuring-theme-gems40) says it should work when 4.0.0 is too new for github.

**Comment by ashmaroli** [comment]
> purely as examples of what _could_ be done by defining the variables in the leveraging site?

Yes, you deduced correctly.
The demo sites are simply GitHub Pages (GHP) builds of the theme repository itself (similar to how GHP builds your `pavelkomarov.github.io` repo).
If you inspect the config file of *such demo sites*, you'll see that they all lack the `theme:` or `remote_theme:` keys &mdash; the styles are sourced from current location instead of pulling them from a gem / remote-repository.

**Comment by ashmaroli** [comment]
I'm closing this as it isn't a bug report.

**Comment by pavelkomarov** [comment]
Any ideas for how to keep variables stored with the theme in the mean time, then? I *can* just hardcode my colors and whatnot and wait until 4.0.0 to tease them all back out again, but I'd rather not have to do that.

**Comment by ashmaroli** [comment]
Since GitHub Pages is locked to a particular version of jekyll and whitelisted plugins, there is no way out there but to build locally with Jekyll 4.0 and commit the *contents of `_site` directory* to a `gh-pages` branch in the site's repository.

**Comment by ashmaroli** [comment]
Another solution would be to ditch GHP and opt for Netlify or CloudCannon to handle the build..
