### ISSUE TITLE
theme _config merging overwrites site.data

### ISSUE THREAD

**Issue by jonsage** [jekyll/jekyll#8153]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | MacOS |
| `jekyll` | 4.0.0 |
| `github-pages`  | No |

---

## Expected Behaviour

Understanding that Jekyll v4 will merge `<site>/_config.yml` with `<theme>/_config.yml`, but not merge any data files from `<theme>/_data` I attempted to put my data in the `<theme>/_config.yml` like so:

```yaml
data:
  items:
    - one
    - two
    - three
```

It is expected that any site using this theme will have it's `site.data` pre-populated with the `items`, and subsequently any `<site>/_data` files will also be added to the `site.data` hash as normal.

## Current Behavior

What actually happens is that the `data` key in `<theme>/_config.yml` overwrites all `<site>/_data` files preventing the site from using data files.

**Comment by ashmaroli** [comment]
This is expected. Every *top-level* key in the config file (whether from source or theme) is exposed as `{{ site.<key> }}`. Which is why having a config file with a top-level key named `data` is a bad idea irrespective of where it is located.

You will be able to reproduce this behavior on older versions of Jekyll as well if you put the same in the config file at source.

If you want to have `site.data` pre-populated you'll have to use a plugin (e.g. `jekyll-data`)
