### ISSUE TITLE
feat: Can jekyll-sass-converter be made an optional installation? (sassc install is slow)

### ISSUE THREAD

**Issue by thbar** [jekyll/jekyll#8184]
Thanks for your work on Jekyll!

Currently, `jekyll-sass-converter` is installed by default (hard dependency), and it brings `sassc` as a dependency. The installation of `sassc` can be very slow (ex [here](https://community.netlify.com/t/ruby-gems-cache-seems-to-be-ineffective/14821) more than 3 minutes on a given Netlify build.

Although the real fix would be to accelerate `sassc` installation (https://github.com/sass/sassc-ruby/issues/189), it will take time and effort.

Therefore I wonder if it could be done to make `jekyll-sass-converter` a soft requirement?

Thanks for taking this input into consideration ^_^

**Comment by ashmaroli** [comment]
Unfortunately, we cannot remove a hard dependency. Our next release will be v4.1.0 (minor-version bump) and removing a hard dependency in a minor version bump is against the principles of semver (Semantic Versioning).

Sorry, you'll have to depend on Netlify's caching (albeit apparent lack of one for preview-deploys).

**Comment by Robbie-Cook** [comment]
I hope you all see this as the absolute disaster that it is for Jekyll. Slow builds are a huge reason for jumping ship re: https://hacks.mozilla.org/2020/10/to-eleventy-and-beyond/

**Comment by fauno** [comment]
to add to this, there's an issue open in sassc about providing a binary
gem:

https://github.com/sass/sassc-ruby/issues/189

for our projects we've set up a gem repository hosting our own binary
gems using gem-compiler, for alpine/musl, which lead to finding some
quirks on how rubygems finds platform specific gems for linux+glibc:

https://github.com/rubygems/rubygems/issues/3174

i tried building binary gems for glibc but since we're using rbenv for
development, libraries end up hardcoding local directories and i haven't
had time to fix it.

maybe a first step would be helping sassc to provide a binary gem
officially, that would reduce build times for everyone :)

**Comment by ashmaroli** [comment]
@Robbie-Cook The *build time* referred to in the Mozilla blog post is the time Jekyll took during multiple build sessions (i.e., from running `jekyll build` or `jekyll serve` both of which comprises of reading the source files, converting and finally writing the HTML files to disk.)
That time has nothing to do with `sassc` gem or `jekyll-sass-converter` installation.
Gems are ideally installed once in a while, and not for every build session.

**Comment by typhoon2099** [comment]
Is this still not an option? We don't use sass in our project but still have to wait an extra 3 minutes on each Netlify build to include sassc, despite not needing it.
