### ISSUE TITLE
_site/ doesn't get ignored 

### ISSUE THREAD

**Issue by buditanrim** [jekyll/jekyll#8198]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Mac OS |     10.15.3       |
| `jekyll`         | Latest     |
| `github-pages`   | Latest     |

---

## Expected Behaviour
By putting `_site/` on the `.gitignore` the github should not merge the _site or even consider it as changes.

## Current Behavior
I have put `_site/` in the .gitignore file but Github desktop still recognizes the changes under _site folder

## Code Sample
![image](https://user-images.githubusercontent.com/1830184/82657577-c6ce9c00-9c4f-11ea-86df-a5dc446877a1.png)

**Comment by ashmaroli** [comment]
Technically, this isn't because of Jekyll. So closing.

**Comment by buditanrim** [comment]
so, because of what?

**Comment by ashmaroli** [comment]
It is probably because:
- you added `_site` to `.gitignore` after you built the site and committed.
- you did not commit the changes to `.gitignore`

What you can do now is temporarily remove `_site` from `.gitignore`. Then delete the folder `_site`. Then add `_site` back to `.gitignore`.
Run `git add . && git commit -m "Remove _site from repository"`
