### ISSUE TITLE
A possible problem with the find filter in v4.1

### ISSUE THREAD

**Issue by chmaynard** [jekyll/jekyll#8271]
According to the docs, the find filter "returns the first object in an array for which the queried attribute has the given value or return nil if no item in the array satisfies the given criteria." When I use this filter, I seem to get the opposite result. 

For example, this code produces the correct result if the test in line 2 is changed to ```post == nil```:

            {% assign post = posts | find: "ID", concert.ID %}
            {% if post != nil %}
                <td><a href="{{ concert.ID }}">{{ concert.Description }}</a></td>
            {% else %}
                <td>{{ concert.Description }}</td>
            {% endif %}

**Comment by ashmaroli** [comment]
The `find` filter is intended to behave along the same lines as chaining the `where` and `first` filters. Do you get the expected result when using `where` and `first`: ?
```html
{% assign post = posts | where: "ID", concert.ID | first %}
{% if post != nil %}
  <td><a href="{{ concert.ID }}">{{ concert.Description }}</a></td>
{% else %}
  <td>{{ concert.Description }}</td>
{% endif %}


```

**Comment by chmaynard** [comment]
Yes. I'm also observing that if the concert array is reversed using Liquid's reverse filter, the code seems to work fine as written.

**Comment by ashmaroli** [comment]
Since the returned result is the same irrespective of using `find` or the combo of `where` and `first`, I'd say that there is no bug at Jekyll's end.

For continued support, please open a ticket at our forum at https://talk.jekyllrb.com/
*Ensure that you either provide a link to the site's repository or enough context so that the visitors are able to verify the following:
- `posts` have been defined properly as a shorthand for `site.posts`.
- what the `concert` object is actually.
- what attributes have been defined for the `concert` object.

**Comment by chmaynard** [comment]
I hope you're right. Thanks.
