### ISSUE TITLE
Convert plugin does not get content from referenced layouts

### ISSUE THREAD

**Issue by TomFreudenberg** [jekyll/jekyll#8445]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |  MAC OSX / rbenv / ruby 2.7.1 |
| `jekyll`         | Latest     |
| `github-pages`   | No     |

---

## Expected Behaviour

My converter plugin should change the content of pages.

## Current Behavior

If I move some parts of my page to a layout - the converter method won't receive that part(s) anymore.

##### file: _layout/demo.html

```
---
---
<div>
  <h1>Demo</h1>
  {{ content }}
</div>
```

##### file: index.html

```
---
layout: demo
---

<p>This is a sample</p>
```

##### file: converter.rb

```ruby
module Jekyll
  class NobreakConverter < Converter

    safe true
    priority :low

    def matches(ext)
      ext =~ /^\.html$/i
    end

    def output_ext(ext)
      ".html"
    end

    def convert(content)
      puts "CONVERT:"
      # this will only show: <p>This is a sample</p>
      puts content.inspect
      content
  end
end
```

### Issue

The content from layout is not posted to `convert`

**Comment by TomFreudenberg** [comment]
In case of the issue - I rewrote my Convert to a Hook plugin

``` ruby
Jekyll::Hooks.register :pages, :post_render do |page, drop_payload|
  # code to call after Jekyll hat rendered a page
  page.output = Jekyll::NobreakConverter::convert(page.output) if Jekyll::NobreakConverter::matches(page.ext)
end
```

That does the trick for now

**Comment by ashmaroli** [comment]
Based on the source-code as of Jekyll 4.1:
https://github.com/jekyll/jekyll/blob/b3b9fae4bcf4c772ec201c3c06bc76d06c60272d/lib/jekyll/renderer.rb#L83-L92

Converters do not access layout contents.
This was probably designed as such because *layouts* were never intended to be *converted*, but to just act as an agency that receives *converted output* and use it to be rendered by Liquid.
In other words, layouts were only meant to be rendered by Liquid.

That said, the next version of Jekyll i.e. v4.2 will introduce a new hook, namely the `:post_convert` hook:
https://github.com/jekyll/jekyll/blob/1ae2a1dd04eed6061df508c5251a882d3e8ae000/lib/jekyll/renderer.rb#L83-L96
which will allow users to modify converted output before being rendered into a given layout.
If you're interested, do try it out by pointing your Gemfile to the `master` branch and let us know what you think about it:
```diff
# Gemfile

- gem "jekyll", "~> 4.0"
+ gem "jekyll", github: "jekyll/jekyll"
```

**Comment by TomFreudenberg** [comment]
Hi @ashmaroli , thanks for your fast and detailed answer!

Unfortunaly  that won't help because I need to do "convert" work on the -layouted- page output

So it would be great to have a convert be called AFTER `place_in_layouts' or at least to have a Hook after that.

For the moment I am quite happy with my above posted Hook - so I could reused my complete work on the converter without re-coding all that stuff.

**Comment by ashmaroli** [comment]
> I need to do "convert" work on the -layouted- page output

In this case, the `:post_render` hook is indeed the best point of entry.
For the moment, I don't see the benefit for having converters run on a *layouted* output. So closing.

Feel free to report back with a solid use-case and I'll reopen.
Thank you.
