### ISSUE TITLE
system-wide definition for relative and abosolute path not respected

### ISSUE THREAD

**Issue by Fenn-CS** [jekyll/jekyll#8517]
## Summary
The url, `/assets/css/style.css` translates to `/root/assets/style.css` and is in fact an absolute URL however this is considered a relative URL in Jekyll. The definitions for absolute and relative url in Jekyll does not seem to agree with what  the OS understands. Except I am missing something, compiled relative urls should look as such `assets/css/style.css`, this way the static files can be loaded easily without needing any configurations.

## Motivation

- Github pages fails to load assets compiled with via Github Actions (asset urls are wrong)
- `bundle exec jekyll serve` generates a `_site` folder locally containing files, clicking on `index.html` should load the site correctly without any changes. (That is without using `localhost:4000` for example)

**Comment by ashmaroli** [comment]
Jekyll generates pages as *ready-to-be-served* via a webserver instead of the `file://` protocol on the OS.
`relative_url` generates URLs *relative to server root*.
`absolute_url generates URLs complete with the URL scheme and domain.

**Comment by Fenn-CS** [comment]
Yeah I get that, I still wonder if it's appropriate to refer to `/dir`as
relative even on web servers. That's clearly an absolute path in the
context of the static files.


What's wrong with leaving relative urls without a starting forward slash?

**Comment by ashmaroli** [comment]
> What's wrong with leaving relative urls without a starting forward slash?

A URL without a *leading* forward slash implies that the resource is located *relative to current page* instead of *relative to webserver root*.

Say I have a site at URL `https://example.com/`. *All pages of the site* rely on the same external stylesheet at URL **`https://example.com/assets/styles.css`**.
I'm currently at URL `https://example.com/about/`.Semantically, that translates to the webserver serving the file at location `<server-root>/about/index.html`.

Now if the about page had *linked* to the stylesheet as `assets/styles.css` instead of `/assets/styles.css`, then the *served page* would not be able to *find* the stylesheet since it would be looking for `https://example.com/about/assets/styles.css` and return a `404 HTTP Error`.

**Comment by Fenn-CS** [comment]
@ashmaroli That's clear now. Thank you.
