### ISSUE TITLE
Jekyll auto date and time on post publish

### ISSUE THREAD

**Issue by hippomu-media** [jekyll/jekyll#8715]
title: "Your title"
layout: post
date: {{ auto.date }}

How auto date and time on post publish without write date and time

**Comment by munimation** [comment]
Iam remove date: "your date publish post" and i put this code {{ page.date }} only render 2021-06-22 00:00:00:00 +0000

Why time 00:00:00:00 +0000

**Comment by uberfuzzy** [comment]
Because the "date" object of a `page.date` (and also `site.date`) is actually a DateTime object.

Use the `date` filter:
https://jekyllrb.com/docs/liquid/filters/#standard-liquid-filters
https://jekyllrb.com/docs/liquid/filters/#:~:text=concat-,date,-default
https://shopify.github.io/liquid/filters/date/
https://shopify.dev/api/liquid/filters/additional-filters#date

`{{ page.date | date: "%Y-%m-%d" }}`

You can use this to easily build the format you want, then copy it, http://www.strfti.me/
