### ISSUE TITLE
Permalink /:tag not work how make it work?

### ISSUE THREAD

**Issue by hippomu-media** [jekyll/jekyll#8750]
In permalink collection _config.yml :

permalink: /:tag/:title

Or

permalink: /:tags/:title

Not work how make it work?

**Comment by fauno** [comment]
There's no :tags placeholder for URLs, but you could use :categories for
the same effect, or :slugified_categories if your categories have
spaces.

**Comment by hippomu-media** [comment]
What about jekyll_custom_permalink plugin? Can i use :tag if i install this plugin?

**Comment by fauno** [comment]
It looks like it could work for you if you have a single tag, for
several tags you'll end up with something like `/[\"tag1\",
\"tag2\"]/title/`

It's because the way this plugin lookups the value is by converting it
into a string with `to_s`.  Jekyll treats categories specially and joins
them with forward slashes (`/`)

https://github.com/NiklasEi/jekyll_custom_permalink/blob/master/lib/jekyll_custom_permalink/custom_permalink.rb#L20

If you are comfortable with a little Ruby, you could write your own
plugin by extending `Jekyll::Drops::UrlDrop` to have a `tags` method
that behaves like `categories`.

https://github.com/jekyll/jekyll/blob/master/lib/jekyll/drops/url_drop.rb#L30

(Alternatively you could request this feature to the custom_permalink author.)

**Comment by hippomu-media** [comment]
Thanks for answer my question, i can try it.
