### ISSUE TITLE
GitHub Actions not working. [Dependency error]

### ISSUE THREAD

**Issue by iamtheblackunicorn** [jekyll/jekyll#8769]
Hi, so I have this repository right [here](https://github.com/iamtheblackunicorn/iamtheblackunicorn.github.io) which contains my personal website and blog. A while back I made a custom theme which can be found [here](https://github.com/iamtheblackunicorn/elegant-simplicity). I've been trying to add some site CI to my personal website and the build keeps failing. I added my theme to my `Gemfile` and my `_config.yml`. Theoretically the build should succeed. Why isn't it?

Here are some links to the relevant files:

- [.github/workflows/jekyll.yml](https://github.com/iamtheblackunicorn/iamtheblackunicorn.github.io/blob/main/.github/workflows/jekyll.yml)
- [Gemfile](https://github.com/iamtheblackunicorn/iamtheblackunicorn.github.io/blob/main/Gemfile)
- [_config.yml](https://github.com/iamtheblackunicorn/iamtheblackunicorn.github.io/blob/main/_config.yml)

**Comment by ashmaroli** [comment]
Hello @iamtheblackunicorn 
The issues tracker in this repository is to report and track bugs in Jekyll, not investigate dependency errors of a third-party theme.
We have a dedicated community platform at https://talk.jekyllrb.com/

That said, since this is your first time here, I'll not close this ticket right away.

Couple of questions:
- Does everything work as expected on your local system?
- Why is the theme listed under `:jekyll_plugins` group in your Gemfile? Themes are not plugins.
- Have you tried using the `jekyll-remote-theme` plugin if your theme has not been published to Rubygems?

**Comment by iamtheblackunicorn** [comment]
@ashmaroli To answer your first question: Yes!
I read on the Jekyll forum somewhere that that fixed the same issue for someone else.
No, I haven't, I'll try that right now!!

**Comment by iamtheblackunicorn** [comment]
Turns out that adding `jekyll-remote-theme` to the `Gemfile` and the `_config.yml` solved the problem! Thanks so much!!
