### ISSUE TITLE
Jekyll fails mapping reference style links to local .md files to .html

### ISSUE THREAD

**Issue by mmichaelis** [jekyll/jekyll#8828]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |            |
| `jekyll`         | Latest     |
| `github-pages`   | Latest     |

---

## Expected Behaviour

```markdown
* [Lorem](./TEST.md)
* [Ipsum][Test]
* [Test][]

[Test]: <./TEST.md>
```

All alternatives should create the same link to `TEST.html` on GitHub Pages.

## Current Behavior

While _Lorem_ correctly links to `./TEST.html`, the reference style links are unmapped and link to `./TEST.md` which essentially displays the markdown as plain-text when opened.

If that matters: I am trying to do so for GitHub Pages from main-branch starting at root-folder (so just using the same README-structure as within the repository).

## Code Sample

See above.

**Comment by mattr-** [comment]
This is not an issue with Jekyll's core code. Relative links like this are handled by the [jekyll-relative-links] plugin that's bundled with GitHub Pages. Since I can't transfer this issue to that repository, please open an issue against that plugin so that it can be fixed there.

Thanks for taking the time to report the issue! 

[jekyll-relative-links]: https://github.com/benbalter/jekyll-relative-links
