### ISSUE TITLE
Hard code dependency on http_parser 0.6.1 

### ISSUE THREAD

**Issue by fulldecent** [jekyll/jekyll#8872]
As we all know, http_parser 0.6.0 is broken and you can't install Jekyll if there is a space in the directory name.

This is fixed in 0.6.1. But our dependency here is indirect so we inherit the problem until it is fixed at https://github.com/igrigorik/em-websocket/issues/158

---

Can we please here make a temporary, explicit dependency on version 0.6.1 which fixes the problem?

**Comment by ashmaroli** [comment]
@fulldecent Technically, the constraint isn't as hard as you think it is..
The following directive..
```ruby
s.add_dependency("http_parser.rb", '~> 0.6.0')
```
..means that you're **allowed to** use any version of the **`0.6.x`** series, including `0.6.1`.
You however will not be able to use **`0.7.0`**.

If you're using jekyll via a Gemfile, run **`bundle update http_parser`** or **`bundle update`** (to update all outdated deps).
Otherwise, simply run **`gem update http_parser`**

**Comment by ashmaroli** [comment]
**UPDATE:** Apparently, `http_parser.rb-0.6.1` has been [*yanked*](https://rubygems.org/gems/http_parser.rb/versions). So, you won't be able to upgrade to any of the recent versions until there's an upstream patch in `em-websocket`.

**Comment by fulldecent** [comment]
Thanks you. I have reported that upstream. 

So now this instant issue is no longer actionable here, we are simply waiting for upstream to fix and we can bump dep. 

But in all cases this does affect us. And it is a painful and undocumented issue here.

**Comment by fulldecent** [comment]
Upstream has bumped dependencies.

Because our dependency is to them is soft `~> 0.5` this means our problem is solved.  Closing.

**Comment by ashmaroli** [comment]
Thank you for spearheading the resolution, @fulldecent
