### ISSUE TITLE
[Bug]: With future: false it is still publishing future dated blogs

### ISSUE THREAD

**Issue by rupeshtiwari** [jekyll/jekyll#8929]
### Operating System

Windows

### Ruby Version

rupby 2.7

### Jekyll Version

jekyll 4.2.1

### Expected Behavior

I expected my site to not show the future blogs. I am using `future: false`. 
Here is my action link https://github.com/rupeshtiwari/rupeshtiwari.github.io/actions 
Check it is showing all of my future blogs https://www.rupeshtiwari.com/posts/ 

### Current Behavior

It is showing all of the future dated blogs check this blog 
https://www.rupeshtiwari.com/posts/
Here is my config file 
https://github.com/rupeshtiwari/rupeshtiwari.github.io/blob/main/_config.yml

**Comment by ashmaroli** [comment]
@rupeshtiwari The issue is with GitHub Pages:
https://github.com/actions/jekyll-build-pages/blob/4fc751033d200f65b97b3ecf09ada61cedcc59ab/action.yml#L14-L17

I suggest you file an issue at that repository. Provide them with a link to your workflow logs.

In the meantime, the only solution is to build the site outside their scope using either of:
- Build locally and push contents of `_site` to `gh-pages` branch on your repo, or
- Use GitHub Actions to build your source files and deploy to `gh-pages` branch on your repo.

Refer https://jekyllrb.com/docs/continuous-integration/github-actions/ for helpful tips.

**Comment by rupeshtiwari** [comment]
Thanks @ashmaroli for guidance, I will report to the jekyll build pages repo. Also I will try to follow the given links and try to fix it. It is very disappointing.
