### ISSUE TITLE
[Bug]: Images are displayed in p elemnts for no reason

### ISSUE THREAD

**Issue by godalming123** [jekyll/jekyll#9003]
### Operating System

Arch Linux (but I'm building with GH pages so thtat doesnt matter)

### Ruby Version

I'm not building it locally just with github pages ¯\_(ツ)_/¯

### Jekyll Version

I dont know assuming it the latest ¯\_(ツ)_/¯

### GitHub Pages Version

I dont know assuming it the latest ¯\_(ツ)_/¯

### Expected Behavior

When I place an image on my site it gets placed as an outstanding image with no paragraphs around it

### Current Behavior

When I place an image jekyll puts a paragraph around it even if their is no need to as their is no text in the paragraph (other then the image).

### Code Sample

```md
## Screenshots
These are some screenshots of my setup:

<img class="materialboxed" alt="1st image of my setup" src="/blog/imgs/my-linux-setup/1.png">
<img class="materialboxed" alt="2nd image of my setup" src="/blog/imgs/my-linux-setup/2.png">
```

**Comment by yboulkaid** [comment]
When running your code sample locally, I can see that both images get wrapped in a single `<p>` tag. 

AFAIK this is a behavior of markdown rather than jekyll, see [this discussion](https://stackoverflow.com/questions/24456010/in-markdown-is-there-a-way-to-stop-images-from-being-wrapped-with-p-tags/24526497) for example. Any block of markdown text separated by new lines will be wrapped in a `<p>` tag, which is expected behavior.

There are a couple workarounds in the discussion linked above if you really don't want to have the wrapping paragraphs maybe?

**Comment by godalming123** [comment]
Thanks for the response cannot find a solution I'm happy with so I will close this issue since it's not your fault
