### ISSUE TITLE
Excluding subdirectory from being generated

### ISSUE THREAD

**Issue by jcldavid** [jekyll/jekyll#906]
I wanted to exclude assets/sass from being included into the generated `_site`:

``` yaml
exclude:
  - assets/sass
  - README.md
  - config.rb
```

However it still includes `assets/sass`. I tried adding a trailing slash, putting it inside quotation marks but none works?

![Directioner forever](http://i.imgur.com/on9jTBX.png)

**Comment by RonJeffries** [comment]
Hello. I am from the future, specifically February 2015. This issue is still not resolved. It is possible to exclude a folder by putting its exact name in the exclude. If the folder's name is, say, xyzzy, you can put
xyzzy, or xyzzy/ and the folder will be excluded. 

If you say xyzzy/foo.bar, it appears that you cannot exclude just foo.bar.

If you say xyzzy, not xyzzy/, the folder will be excluded and so will any file (and folder?) containing the string 'xyzzy', such as article-about-xyzzy-magic-word.md

File watch does not interpret the things in exclude the same way that jekyll generation does. It is possible to set things up so that watch will not trigger but jekyll will generate the file if started manually. I believe it is possible to do the reverse. 

There are essentially zero working examples anywhere. I would wager that there are no working tests or checks as well, since if there were someone would surely have published them by now.

This is not the end of the world. I'll write to you about that later. But it is not particularly good nor impressive.

**Comment by aaronlademann-wf** [comment]
+1 to what @RonJeffries said... this issue seems to have re-appeared.

I have been using the following include configuration for the past 6 months to ensure that the entire contents of my `sass` directory are copied for purposes of source mapping...  It was working until a few days ago.

```yml
include:
  - "sass/_*"
```

The only way I can get the underscored files / directories in my `sass` directory to be copied during build - is by changing my include to:

```yml
include:
  - "_*"
```

This is sub-optimal, however, because it now copies the entirety of `_includes`, `_layouts`, `_data`, etc.

@parkr @mojombo should a new issue be opened - or is this issue still an appropriate place to investigate possible regressions?

Thanks for your time.

**Comment by nhoizey** [comment]
I am strugling with this as well, with Jekyll 2.5.3.

I have a `tags` folder in the root, and I want its content to be added to the `_site/tags/` folder that is generated by the [jekyll tagging](https://github.com/pattex/jekyll-tagging) plugin.

I tried several syntaxes, from the comments in this thread, with no result.
