### ISSUE TITLE
[Bug]: `name` attributes defined in front matter are rendered incorrectly with Jekyll 4.3.0

### ISSUE THREAD

**Issue by marcwrobel** [jekyll/jekyll#9164]
### Operating System

Debian 11

### Ruby Version

ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

### Jekyll Version

Jekyll 4.3.0

### GitHub Pages Version

Latest

### Expected Behavior

If a collection declare the `name` attribute its document front matter, the attribute value should be rendered in the templates that are referencing this attribute.

### Current Behavior

When referencing the `name` attribute, the markdown filename is rendered instead of the attribute value. Other attributes are rendered as expected.

### Code Sample

On `main` branch (Jekyll 4.2.2) everything works fine :
- clone https://github.com/lescastcodeurs/lescastcodeurs.com
- install dependencies (`bundle install`)
- serve the site `bundle exec jekyll serve --livereload --trace`
- go to http://127.0.0.1:4000/equipe/
- team members names are correctly rendered with the `name` specified in the metadata (such as `Antonio Goncalves`)

On `jekyll-4.3.0` branch (Jekyll 4.3.0) `name` attributes are not rendered as expected :
- clone https://github.com/lescastcodeurs/lescastcodeurs.com
- switch the the `jekyll-4.3.0` branch
- install dependencies (`bundle install`)
- serve the site `bundle exec jekyll serve --livereload --trace`
- go to http://127.0.0.1:4000/equipe/
- team members names are incorrectly rendered with the markdown filenames (such as `AntonioGoncalves.md`)

**Comment by marcwrobel** [comment]
I do not know if it's related, but there was this change in Jekyll 4.3.0 : _Expose basename from document.rb as name to Liquid templates (#8761)_.

**Comment by marcwrobel** [comment]
Other attributes are rendered as expected. A workaround is to use a different name for the attribute.

**Comment by ashmaroli** [comment]
Hello @marcwrobel 
You're right in stating that this issue is related to the mentioned change in v4.3.0.
It is unfortunate that your project is encountering this issue. I admit that I had overlooked the possibility of a conflict with front matter definition when accepting the change.
I will release a v4.3.1 some time in next week.

**Comment by JKarlavige** [comment]
Just opened an issue on this as well, #9165. Can confirm we are experiencing this as well and noticed issues with our site this morning. Reverting to Jekyll `v4.2.2` resolved it. 

I would like to leave #9165 open, as we are experiencing another issue where we are seeing a Jekyll hash rather than the object of data when using our `_data` collection.

**Comment by marcwrobel** [comment]
Thanks for the quick fix @ashmaroli.
