### ISSUE TITLE
I can't add post to github page blog

### ISSUE THREAD

**Issue by Pitxunet** [jekyll/jekyll#9172]
Hi,
Newbie here. I'm trying to create a portfolio webpage using github pages. I'm doing it directely on github instead of locally because I didn't manage to install jekyll (maybe because I have Windows?).
So I first created the site with minima theme and after some struggles first simple post was added. Then I changed the them and since then I can't see the post anymore. I tried various things but I can't tackle the issue.
Could anybody help, please? This is the website : https://pitxunet.github.io/Estitxu-Larralde/

Thank you,

**Comment by ashmaroli** [comment]
Hello @Pitxunet,
Could you tell us what issue you have faced when trying to install Jekyll on Windows?
What version of Windows are you using?
What version of Ruby did you install?

Regarding posts in your blog, I see you have added two Markdown documents with correct filenames under the `_posts` directory. So, Jekyll will process them as expected. If you add the following code to your `index.md`, you will see a summary of your posts with links to full articles:

```
{% for post in site.posts %}
## {{ post.title }}

{{ post.excerpt }}

[Full Article]({{ post.url | relative_url }})
{% endfor %}
```

**Comment by Pitxunet** [comment]
Thank you very much, the code at the end of index.md worked perfectly.

I got an error message twice while trying to download Ruby+Devkit 3.1.2-1 (x64). I've insisted now by resuming the downloading and it seems to work now.

Do you recommend to create the blog/page in a local repository and then to push it to Github? I'm really new in Github and I only had a Wordpress.org blog some years ago.

Thank you again for your help, much appreciated.

Estitxu

**Comment by ashmaroli** [comment]
Hello again @Pitxunet
Unlike WordPress, there is a steeper learning curve with Jekyll. My personal recommendation would be to get familiar with using the command-line interface to "develop" your Jekyll projects because there is very little limitations via that route (default GitHub Pages build system only allows a few plugins to be used):
- Freedom to use any text editor that you have already been using for other stuff.
- Freedom to use any plugin / theme available for consumption.
- Executing `bundle exec jekyll serve` will build and start a local webserver for you to preview the blog as you develop it.
- Do not have to commit a change, push it to GitHub and wait for GitHub to build and deploy those changes.

That said, using GitHub web interface does have it benefits:
- If you're comfortable using a graphical interface over the command-line interface..
- Push or stash changes when you're not in a position to access your development computer.
- If you were to work on a different Git branch than the default or base branch, you can *commit* multiple changes, view a collective / atomic "diff" of the changes with respect to the base branch, create a pull request and have those changes incorporated as individual commits or one single commit.

**Comment by Pitxunet** [comment]
Hi Ashwin,

Thank you very much for all this information. I installed Ruby and Jekyll
yesterday and I will clone the repository to local machine as soon as I can
(my biggest limitation is time at the moment).
My command-line knowledge is quite limited. I did a workshop in Udacity and
that's it. Is there any particular tutorial or ressource you would
recommend in order to get familiar with command-line to develop Jekyll
projects?  I haven't been through all the Jekyll and GitHub pages
documentation yet. Hopefully I will find some guidance in there, too.
Thank you again for taking the time to help me. I really appreciate it
Have a nice day

Ashwin Maroli ***@***.***> igorleak hau idatzi zuen (2022
urr. 31, al. 07:51):

**Comment by ashmaroli** [comment]
> I will clone the repository to local machine..

New users on Windows usually clone to their system dir / user dir / home dir. *Don't do that.* Create a separate directory far away from system and personal files. For example, `E:\GitHub`. Use that location to store all your clones from GitHub so that even if the cloned repository grows in size significantly (they tend to over time), your primary partition doesn't get affected with fragmentation issues.
Regarding familiarity with command-line, you just need to know that `cd` is executed to *change current directory* to desired location, `jekyll new [...]` to start a new project from scratch. Thereon, if the project contains a Gemfile, always prepend `bundle exec` to Ruby executables. For example, to get a list of commands Jekyll understands, one would either run `jekyll help` or its equivalent `bundle exec jekyll help` if there's a Gemfile mentioning `"jekyll"` in current location.
The docs about this is at https://jekyllrb.com/docs/usage/

**Comment by Pitxunet** [comment]
Thank you very much! I will then create a new directory to clone the
repository.

Sorry if this is a silly question, but should I install Jekyll in the same
separate directory?

Ashwin Maroli ***@***.***> igorleak hau idatzi zuen (2022
urr. 31, al. 16:08):
