### ISSUE TITLE
[Docs]: Jekyll on macOS - Step 2: "Install chruby and the latest Ruby with ruby-install" Fails Due to Outdated Ruby Version in Doc

### ISSUE THREAD

**Issue by masaki9** [jekyll/jekyll#9194]
## Motivation

I followed the [Jekyll on macOS](https://jekyllrb.com/docs/installation/macos/) guide to install and run Jekyll for the first time earlier today. I restarted Terminal per the guide at the end of step 2 in the guide and got an error message saying "chruby: unknown Ruby: ruby-3.1.2" as shown below:

![image](https://user-images.githubusercontent.com/40445257/204074852-939b54c3-66c5-4285-b178-b41417994ddb.png)

## Suggestion

To fix it, "echo "chruby ruby-**3.1.2**" >> ~/.zshrc" should be "echo "chruby ruby-**3.1.3**" >> ~/.zshrc" in step 2 in the [Jekyll on macOS](https://jekyllrb.com/docs/installation/macos/) guide.

When I updated the line in .zshrc, I was able to proceed and install Jekyll successfully.

![image](https://user-images.githubusercontent.com/40445257/204075072-cdc94ec1-855c-4018-98c7-0c3ef43c3f75.png)

**Comment by postmodern** [comment]
The problem is that the docs recommend running `ruby-install ruby` which will install the current stable version of ruby, which is currently 3.1.3 but soon will be 3.2.0. I recommend either `ruby-install ruby-3.1` or `ruby-install ruby-3.1.3`. Or you could change `~/.zshrc` to run `chruby ruby-3.1` which will match any 3.1 version of ruby.
