### ISSUE TITLE
_pages Directory, like _posts Directory?

### ISSUE THREAD

**Issue by jhauraw** [jekyll/jekyll#920]
Thank you @mojombo for an awesome project. I used to build sites like Jekyll produces years ago, but now with Jekyll we get automation and pre-processing, awesome-sauce.

I've got a project with quite a few pages and it would be great if there was a way to store them in a _pages directory, like we do with _posts. Having Pages clutter up the top-level Jekyll dir makes it a bit messy.

I created a _pages dir and added it to _config.yml with include = ['_pages'], so that Jekyll processes and copies them into _site.

Problem is, it also copies them nested in the _pages dir, no fault of Jekyll, that's how it works. Just not how we would like it to work in this case.

Is there a way, maybe with a plugin, to have Jekyll do everything it does but modifying the copy process to move the Pages out of the _pages dir to top-level _site when generating? Just like how it happens with Posts?

If you have a snippet or plugin known, please point me in the right direction. I'd rather not use a third-party process (such as Grunt or copy:). I'd like it to be with a Jekyll option or plugin.

BTW. I posted this to the Google Group, but it looks like that has died out and my message never went through.

**Comment by liaocs2008** [comment]
It would't work but I did exactly as you explained. I mean I can only access "new_page" by the permalink set in my markdown file. It didn't show up in the index page like "about" page did. May I ask why about.md in the root directory can be detected but "new_page.md" in root directory can't?

**Comment by joshuapowell** [comment]
The solution above describes how to use a `_pages` folder to organize/house all of your static pages. You said you put `new_page.md` in the root ... that kind of goes against everything the above code says. Note that the directory tree in step 2 doesn't show `about.md`? That's because all page files should be placed under the `_pages` folder

Like so:

![screen shot 2015-01-15 at 9 20 17 am](https://cloud.githubusercontent.com/assets/569351/5758932/be6deeac-9c97-11e4-9c47-5705949ff8e2.png)

If you have any other questions about it, just let me know.

**Comment by liaocs2008** [comment]
Well, I should say that I tried creating _pages directory and configuring it in _config.yml. But new_page.md in _pages directory didn't show up in the index page. So I tried moving it to the root directory. Maybe I should start it over. BTW, do you know how jekyll searches for post.md and page.md? Just by "include" variable in _config.yml?

**Comment by joshuapowell** [comment]
Yeah, try the above steps with a brand new Jekyll site, it definitely works.

Regarding the `.md` files, the default functionality is that it looks in `_posts` for posts and the `root` for pages See http://jekyllrb.com/docs/posts/ and http://jekyllrb.com/docs/pages/

When you're including the `include` variable in your `config.yml` your telling Jekyll "Hey Jekyll there's also stuff in here you should process"

**Comment by eberkund** [comment]
Is there a way to do that without specifying a permalink? ie. by using the filename instead?

**Comment by joshuapowell** [comment]
You might just be able to drop the permalink from the front matter, but I'm
not sure.

On Thursday, January 22, 2015, Erik Berkun-Drevnig <notifications@github.com>
wrote:

> Is there a way to do that without specifying a permalink? ie. by using the
> filename instead?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jekyll/jekyll/issues/920#issuecomment-71101172>.
>


-- 
Best,
Joshua Powell

Founder & Managing Director *of*
Viable Industries, L.L.C.
6101 Penn Ave, Suite 201
Pittsburgh, PA 15206

412-956-3358
www.viableindustries.com

**Comment by budparr** [comment]
To my knowledge, no. There's no way to use the method above (putting everything in a folder, like _pages) without specifying the permalink in front matter.

**Comment by stevemoser** [comment]
@joshuapowell I tried your technique and it works well except I can't get relative links to work.

This is my directory structure.
````
.
|-- _pages
    |-- example.md
    |-- test.md
|-- _config.yml
|-- _includes/
|-- _layouts/
|-- _posts/
|-- _site/
|-- index.html
````

example.md contents:
````
---
permalink: "/example/"
---
[test](test.md)
````

So far so good as this achieves my goal of using relative links with Github. 
https://github.com/blog/1395-relative-links-in-markup-files

However this doesn't work with the rendered page. Instead of linking to 
`http://www.example.com/test/`
it links to
`http://www.example.com/example/test.md`

What am I missing?

**Comment by stevemoser** [comment]
I found a solution but I don't like it because it feels like a hack and I don't know if it has SEO problems.

The solution is in this SO answer starting at the part that begins with "Relative linking to these documents works if you include the following jQuery function..."
http://stackoverflow.com/a/16389663/142358

Basically @coryg89's interesting solution runs some javascript when the page loads to change links from .md files to pretty URLs. So using my example above it changes 
`http://www.example.com/example/test.md`
to
`http://www.example.com/example/test/`

Anyone got anything better?

**Comment by siamakcomputerscience** [comment]
Thanks joshuapowell, worked for me.

**Comment by eberkund** [comment]
@stevemoser Just add to your `_config.xml` the line `include: ['_pages']` and then make sure to define the permalink in all your pages. It is the easiest solution and it works perfectly. You can look at my repo here for a demonstration of this: https://github.com/eberkund/seniorchairs

**Comment by joshuapowell** [comment]
@stevemoser I second @eberkund comment ... actually it's the first step you need to follow to get this to work right see https://github.com/jekyll/jekyll/issues/920#issuecomment-63093764 above

**Comment by stevemoser** [comment]
@eberkund @joshuapowell Thanks I relative links to work. See http://stevemoser.org/example and https://github.com/stevemoser/stevemoser.org.

My problem was more with relative links and permalinks than with publishing pages. But now with this generator script which removes the .md from links by Partly Cloudy http://stackoverflow.com/a/29234076/142358 and Jekyll 3 (using the --pre) option to use extensionless permalinks I can now get relative links to work on github.com as well as my site.

**Comment by CelticParser** [comment]
For SEO best practices, it's best to have "important pages" at the root level.

**_e.g._** `about.html`, `contact.html`, etc should be in the sites root (permalinked as such). Search engines give weight of importance to a page in relation to how deep the link is in the site as a ranking variable for indexing in the SERP's.

**_With that in mind:_**

Directory structure:
```
.
|-- _pages
    |-- about.md
    |-- contact.md
    |-- etc.md
|-- _config.yml
|-- _includes/
|-- _layouts/
|-- _posts/
|-- _site/
|-- index.html
```

```
# _config.yml
...
include: ['_pages']
...
```

In your `_pages/[FILE_NAME].md`:
```
---
permalink: "/[FILE_NAME].html"
---
```

**Comment by k-funk** [comment]
I'd still really like to see this solution done without explicitly defining a permalink. If I have lots of documentation under `/docs/<filename>` I don't want to put that path/directory-name in `n` files. Not very DRY, more room for human error, and if I move from `/docs/` to `/documentation/` I need to change `n` files.

An interesting solution could be to have the front matter specify

    ---
    ...
    permalink_pattern: '/:dir/:title/'`
    ...
    ---

or

    ---
    ...
    prepend_path_to_permalink: true
    ...
    ---

Since `include: ["_pages"]` is already defining the file import "root", the `/:dir` could traverse the directory structure upwards until that entry point. This would be really powerful because you could specify different entry-points to those directory structures that would also define the path/url/permalink. Example: `include: ["_pages/departments", "_pages/professors"]`

    |-- _pages
        |-- departments
            |-- biology.md
            |-- chemistry.md
        |-- professors
            |-- freddie-mercury.md
            |-- david-bowie.md
    |-- _site
        |-- biology.html
        |-- chemistry.html
        |-- freddie-mercury.md
        |-- david-bowie.md
    |-- _config.yml
    |-- _includes/
    |-- _layouts/
    |-- _posts/
    |-- index.html

**Comment by MattSturgeon** [comment]
As @parkr [suggested](https://github.com/jekyll/jekyll/issues/920#issuecomment-56077763), I worked around this by adding a `pages` collection to my config:

```yml
collections:
  pages:
    output: true
    permalink: /:path
```

Because the collection is named `pages`, `site.pages` **does** get populated, contrary to what @steinsag [implied](https://github.com/jekyll/jekyll/issues/920#issuecomment-57720824).

Jekyll will look in the directory `_pages` for a collection named `pages`, so this seems to work perfectly.

**Comment by Rarst** [comment]
FYI I've tried the last method posted and while it mostly worked:
- nested pages got generated without trailing slashes on GitHub Pages (_with_ them locally), which broke existing navigation;
- sitemap plugin picked up root as `example.com/index` so there might be hiccups with `site.pages` after all.

**Comment by philippemarlin** [comment]
> @MattSturgeon @parkr Have question. How we can do hierarchic pages permalink ?
> like a strucuture parents and childs pages (each /:path/ are reals pages not fake path)
> like in worpdress
> http://prntscr.com/l56mtr
> http://prntscr.com/l56n3r
> ex:
> site.tld/mypageparent1/
> site.tld/mypageparent2/
> ect..
> and
> site.tld/mypageparent1/child1ofparent1/
> site.tld/mypageparent1/child2ofparent1/
> site.tld/mypageparent2/childofparent2/
> ect...
> and
> site.tld/mypageparent1/childofparent1/chlid1ofchild1ofparent1/
> site.tld/mypageparent1/childofparent1/child2ofchild1ofparent1/

have found https://github.com/bbakersmith/jekyll-pages-directory

**Comment by jeradrutnam** [comment]
My requirement was to achieve something like below, with keeping my pages within a `_pages` folder.

[example.com/](#)
[example.com/about/](#)
[example.com/downloads/archived/ ](#)

And I was able to achieve it by below structure and configuration.

```
.
|-- _pages
|   |-- downloads/
|   |   |-- archived.md
|   |-- about.md
|-- _site
|   |-- about
|   |   |-- index.html
|   |-- downloads/
|   |   |-- archived
|   |   |   |-- index.html
|   |-- index.html
|-- _config.yml
|-- ...
|-- index.html
```

_config.yml

```yaml
...
collections:
  pages:
    output: true
    permalink: /:path/

permalink: pretty
...
```

And you can change the `permalink` according to your url style.  Hope this will help someone.

**Comment by jeradrutnam** [comment]
My requirement was to achieve something like below, with keeping my pages within a _pages folder.

[example.com/](#)
[example.com/about/](#)
[example.com/downloads/archived/](#)

And I was able to achieve it by below structure and configuration.

```
.
|-- _pages
|   |-- downloads/
|   |   |-- archived.md
|   |-- about.md
|-- _site
|   |-- about
|   |   |-- index.html
|   |-- downloads/
|   |   |-- archived
|   |   |   |-- index.html
|   |-- index.html
|-- _config.yml
|-- ...
|-- index.html
```

__config.yml_
```
...
collections:
  pages:
    output: true
    permalink: /:path/

permalink: pretty
...
```

And you can change the `permalink` according to your url style. Hope this will help someone.

**Comment by peter-jerry-ye** [comment]
> ```yaml
> ...
> collections:
>   pages:
>     output: true
>     permalink: /:path/
>...
> ```
I achieved the same effect but with ```/:path```. In my case, it won't work if there's a slash after the path.
