### ISSUE TITLE
[Bug]: Sass convertor is crashing with "Error: This file is already being loaded" and can not recognize front matter

### ISSUE THREAD

**Issue by yagarea** [jekyll/jekyll#9265]
### Operating System

6.1.7-arch1-1

### Ruby Version

ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [x86_64-linux]

### Jekyll Version

jekyll 4.3.2

### GitHub Pages Version

I do not use github pages

### Expected Behavior

not crashing

### Current Behavior

when I try to build my site it crashes and does not build the site.

### Relevant log output

```shell
...
     Generating...
       Jekyll Feed: Generating feed for posts
Warning on line 1, column 1 of /home/john/Projects/blackblog/assets/css/index.sass:
This selector doesn't have any properties and won't be rendered.
  ╷
1 │ ---
  │ ^^^
  ╵
Warning on line 2, column 1 of /home/john/Projects/blackblog/assets/css/index.sass:
This selector doesn't have any properties and won't be rendered.
  ╷
2 │ ---
  │ ^^^
  ╵
Error: This file is already being loaded.
  ┌──> /home/john/Projects/blackblog/assets/css/index.sass
4 │ @import index, font, basic, layout
  │         ^^^^^ new load
  ╵
  ┌──> /home/john/Projects/blackblog/assets/css/classes.sass
1 │ @import index, highlight
  │         ━━━━━ original load
  ╵
  /home/john/Projects/blackblog/assets/css/index.sass 4:9    @import
  /home/john/Projects/blackblog/assets/css/classes.sass 1:9  root stylesheet
  Conversion error: Jekyll::Converters::Sass encountered an error while converting 'assets/css/classes.sass':
                    This file is already being loaded.
...
```

### Code Sample

Whole source code of my site is here: [github.com/yagarea/blackblog](https://github.com/yagarea/blackblog)

**Comment by ashmaroli** [comment]
Hello @yagarea
The root cause of the problem is you have an `index.sass` *importing* `index.sass` partial. This is the new behavior from `jekyll-sass-converter-3.0.0` and will be so going forward.
You can either rename either the template name or the partial name for being future-compatibility,  OR downgrade the sass-converter to an older version via Gemfile:
```ruby
# Gemfile

gem "jekyll-sass-converter", "< 3.0"
```

**Comment by ashmaroli** [comment]
@ntkme I'd like to know why the sass-converter-3.0 issues warning regarding the front matter dashes only when there's a basename conflict.. The warnings disappear when the template and partial are of different basename inspite of the front matter dashes still being present. Is this a bug in Dart Sass or  the sass-converter?
Thanks.

**Comment by ntkme** [comment]
Not really a bug. This is how it happened:

1. `index.scss` has front matter. Jekyll read file as string, process and remove the front matter, then start to compile an input “string”.
2. `index.scss` imports `index.scss`, according to sass spec, the relative import of itself hits before load path, and now we are importing the same file which technically is a circular import. When sass read the same input directly from disk, it knows nothing about the Jekyll front matter and would give up with a syntax error.

One way to address it can be write a custom importer that checks for front matter in each imported partials, and compile it with Jekyll before read as sass partials. However, this has significant drawbacks that isn’t worth doing:
1. Jekyll’s sass implementation has never allowed partials to have front matters.
2. Allowing front matter in partials would lead to slower compilation performance as every partial need to be preprocessed by Jekyll, and then passed through protobuf via stdio as a string rather than dart-sass-embedded directly read file from disk.
3. Even if we allow front matter in partials, it would still be circular import, and user would just get a different error message.

**Comment by yagarea** [comment]
@ashmaroli Thank you for help. Yes front matter warnings disappeared when I renamed `_sass/indes.sass` to `_sass/main.sass`.

**Comment by ashmaroli** [comment]
> `index.scss` imports `index.scss`, according to sass spec, the relative import of itself hits before load path..

Thank you for the explanation @ntkme. It all makes sense now. :)
