### ISSUE TITLE
[Docs]: Document whether `exclude` in `_config.yml` replaces or appends to the default exclusions

### ISSUE THREAD

**Issue by TomasHubelbauer** [jekyll/jekyll#9372]
## Motivation

At the moment it is not clear whether by setting `exclude` to my own list, I am disabling the default exclusions.
If `exclude` replaces the default exclusions, it may be that I do not need some of the `include`s I added for file which were excluded by the default exclusions. Or if I need to repeat those default exclusions to not let undesired files into my build.
If `exclude` appends to the default excludes, the behavior is IMO more intuitive and desirable, but it should be commented so that a user can be sure that is the case.

## Suggestion

Expand the Exclude row in https://jekyllrb.com/docs/configuration/options.
For Exclude, either mention it is added to the default exclusions or replaces them.
Also mention the default exclusions. I know dotfiles are excluded (from the Include row), what else? Is there documentation for this elsewhere that I missed?

I am happy to PR this myself, but I am lacking the information. Can anyone help me determine which is the case with `exclude` and what are the default exclusions?

**Comment by TomasHubelbauer** [comment]
@ashmaroli Friendly reminder… Ignore if you're too busy, just wanna make sure my comment doesn't fall through the crack. PTAL at the proposed changes and where I plan to make the edits and give me a green light - I'll PR straight away.

**Comment by ashmaroli** [comment]
@TomasHubelbauer Yes, you seem to be on the right track.
The best environment to work in while making significant changes to the docs is always the local machine. Since the docs are a Jekyll site as well, one may simply clone the repository, run `bundle install` from the repo directory location and run `bundle exec jekyll serve -s docs -d docs/_site --livereload` to get a locally served version of the docs site to get an accurate idea about the changes being made.
