### ISSUE TITLE
Cannot create a new jekyll site because of error 'error occurred while installing wdm (0.1.1),'

### ISSUE THREAD

**Issue by axfreeman** [jekyll/jekyll#9615]
New to Ruby and Jekyll but generally tech savvy.
Trying to create a new Jekyll site.
Installed Ruby
Followed all the steps in the docs (some problems accessing Jekyll, resolved by editing Windows path and rebooting)

In VSCODE, ran

    gem install jekyll bundler

which ran with no faults.

Tried to create a new jekyll site with

    jekyll new mysite
In VSCODE also

This reported the error `error occurred while installing wdm (0.1.1), and Bundler cannot continue`
I've looked at various solutions to this - since I am new to Ruby I haven't gone into any of its internals.

Ran 

     bundle install
This reported `Gem::Ext::BuildError: ERROR: Failed to build gem native extension.` with quite extensive diagnostics 

Ran

    gem install wdm
This gave the same diagnostics. At the end it states

    Gem files will remain installed in C:/Users/afree/.local/share/gem/ruby/3.3.0/gems/wdm-0.1.1 for inspection.  
    Results logged to C:/Users/afree/.local/share/gem/ruby/3.3.0/extensions/x64-mingw-ucrt/3.3.0/wdm-0.1.1/gem_make.out
  
 I've gone through most of these steps also outside VScode, in both cmd and powershell
 
I am raising this in the Jekyll forum, but it seems to me that if this is the experience of a newbie following the documentation, it's serious enough to bring to the attention of the maintainers. Apologies (and let me know) if this is the wrong protocol.

**Comment by umarok** [comment]
I know this doesn't solve the problem but wdm is not necessary. It just keeps the file changes in sync with the server process. I just commented out the wdm part in the gem file to get it working. I also want a solution

**Comment by axfreeman** [comment]
Yes, I discovered this by trial and error eventually. The solution is to delete the reference to WDM.

Thus perhaps the issue is wrongly entitled. Actually, it is that WDM doesn't install properly

**Comment by adamburkegh** [comment]
I am seeing this after having a working build working for ages, then needing to rebuild on a new machine with newly installed versions of ruby and bundler. 

jekyll 4.1.0
Ruby 3.1.6p260
Bundler version 2.1.4

Initially tried with latest ruby and downgraded after incompatible with a gem in the jekyll project Gemfile.

**Comment by msarczar** [comment]
> I am seeing this after having a working build working for ages, then needing to rebuild on a new machine with newly installed versions of ruby and bundler.
> 
> jekyll 4.1.0 Ruby 3.1.6p260 Bundler version 2.1.4
> 
> Initially tried with latest ruby and downgraded after incompatible with a gem in the jekyll project Gemfile.
> 
> Removing wdm also fixed.

So is Ruby 3.1.6 fully compatible with Jekyll? I tried the latest 3.3.3.1 and I'm having issues. I can't get a solid answer on which version to get.

**Comment by monfresh** [comment]
@msarczar Typically, Jekyll supports the latest Ruby versions. In general, I recommend making sure to use the latest version of Jekyll. For example, I see Jekyll 4.1.0 mentioned earlier in this GitHub issue, but that version was released over 4 years ago. The latest Jekyll version is 4.3.3.

Also, without specifying exactly what issues you're having, and what OS and computer model you're using, it's hard to give you advice. If your issue is related to the "wdm" gem, then that implies that you're on a Windows machine. The solution, as others have mentioned, is to remove or comment out this line in the `Gemfile`:

```
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
```

Perhaps this used to work fine on Windows, but if it doesn't anymore, I would recommend to the Jekyll team to make that gem optional. In general, any gem that is not required should ideally be optional.

**Comment by szschaler** [comment]
The problem appears to be with WDM: it uses object tainting, which has apparently now been deprecated in Ruby. Unfortunately, the last commit to WDM appears to have been 9 years ago...

I'm not a Ruby expert, so not sure what solutions might be available. Are there other directory watching gems that could be plugged into Jekyll?

**Comment by monfresh** [comment]
IMO, the solution should be to either replace `wdm` with something that works with newer Ruby versions, or to stop automatically including the gem in the Gemfile that gets generated when you create a new Jekyll site. Based on the [Jekyll installation docs for Windows](https://github.com/jekyll/jekyll/blob/e44b52d9f9387e932cab79b539f34e54934b94fb/docs/_docs/installation/windows.md?plain=1#L133-L145) and the [comment describing the gem](https://github.com/jekyll/jekyll/blob/e44b52d9f9387e932cab79b539f34e54934b94fb/lib/jekyll/commands/new.rb#L99), it sounds like a "nice to have" that can improve performance and auto regeneration, and not a requirement for Windows users.

I recommend submitting a PR with one of these options: 

- remove [these 2 lines](https://github.com/jekyll/jekyll/blob/e44b52d9f9387e932cab79b539f34e54934b94fb/lib/jekyll/commands/new.rb#L99-L100)

- comment out line 100, with a note saying that this gem doesn't work with newer Ruby versions. I'm not sure what the last supported version of Ruby is for `wdm` because I don't use Windows.

**Comment by axfreeman** [comment]
It sounds sensible in the light of these comments to submit a PR. Since I'm not a contributor I won't do that, but thanks for the information

**Comment by monfresh** [comment]
If you don't feel comfortable submitting a PR, or if you don't have the time, that's one thing, but the right to submit a PR is open to anyone who is interested in improving the project.

**Comment by axfreeman** [comment]
Not sure how to do it. Would be glad to assist in improving. If you can point me to a guide I will have a shot

**Comment by ashmaroli** [comment]
Hello Everyone.

What is not clear to me from going through all of the comments in this thread is, _Was Ruby installed via the RubyInstaller for Windows program and if `ridk enable` was run in the terminal shell prior to running `gem install jekyll` or `gem install wdm`.._?

**Comment by axfreeman** [comment]
@ashmaroli yes, I installed Ruby from the Ruby site using rubyinstaller-devkit-3.3.2-1-x64.exe. Then enabled ridk as specified in the docs.

**Comment by jeffng50** [comment]
Hi @ashmaroli, appreciate the attempt of helping, however it still didn't work for me (at least)

> c:\workspace> ridk enable
This step wasn't mentioned in the [docs](https://jekyllrb.com/docs/installation/windows/)

However still having the same issue where it'll say:  `An error occurred while installing wdm (0.1.1), and Bundler cannot continue.` during `bundler install` : (
